= Building JME3 from Sources in Netbeans 8.x
:author:
:revnumber:
:revdate: 2016/03/17 20:48
:keywords: documentation, install
:relfileprefix: ../
:imagesdir: ..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


You are welcome to try out the new jME3, and contribute patches and features! This document shows how to download, set up, build, and run the latest development version from the sources. These instructions work in NetBeans IDE 8.x or better.

.Prerequisites
.  Have a link:https://github.com/[GitHub account].
.  Are a jMonkeyEngine project member.

If you are not a member, you fork the repository into your GitHub account and issue pull requests from there.

To fork the jMonkeyEngine repository into your GitHub Account:

.  Navigate to link:https://github.com/jMonkeyEngine/jmonkeyengine[https://github.com/jMonkeyEngine/jmonkeyengine].
.  In the menu at the top of the page, select the icon:code-fork[]*Fork* button.


NOTE: In the following, always replace kbd:[~] with the path to your home directory.


== Downloading the Sources

Clone the sources from the repository.

.  In NetBeans, go to `menu:Team[Git>Clone]`.
..  Repository +++<abbr title="Uniform Resource Locator">URL</abbr>+++: +
`link:https://github.com/jMonkeyEngine/jmonkeyengine[https://github.com/jMonkeyEngine/jmonkeyengine]`
+
IMPORTANT: Use the +++<abbr title="Uniform Resource Locator">URL</abbr>+++ to your repository fork and clone your fork if a non-member and you wish to contribute.

..  You can leave user/pw blank for anonymous access unless you are going to `push` a `commit`.
..  Specify Destination Folder. +
Local Folder: `~/NetBeansProjects]/jmonkeyengine`

.  Click btn:[Next].
..  Select: +
* [x] master*

.  Click btn:[Next].
..  Verify the auto-fill information in the `Destination Directory` dialog is correct.
..  Select: +
* [x] `Scan for NetBeans Projects after Clone`

.  Click Finish and wait.


After some time, the `Cloned Projects` dialog will open. Select `Open Project` followed by the `jmonkeyengine` node. The `jmonkeyengine` project opens in the Project window.


== Information on Pull/Pushing Commits


You now have a local copy of the `jmonkeyengine` repository. There are a few rules you need to follow in order to contribute.

.Members Pull
Update your local copy in NetBeans by using the NetBeans command `menu:Git[Remote>Pull From Upstream]`. Everything was properly configured while cloning from the jMonkeyEngine Repository directly.

.Non-Members Pull
Update your local copy in NetBeans by using the NetBeans command `menu:Git[Remote>Pull]`.

**  In the `Remote Repository` dialog you toggle:
* [x] Specify Git Repository Location
+
and use the jmonkeyengine repository +++<abbr title="Uniform Resource Locator">URL</abbr>+++: `link:https://github.com/jMonkeyEngine/jmonkeyengine[https://github.com/jMonkeyEngine/jmonkeyengine]`

.Members Push
Update jMonkeyEngine by using the NetBeans command `menu:Git[Remote>Push To Upstream]`. Everything was properly configured while cloning from the jMonkeyEngine Repository directly.

.Non-Members Push
. Update *your fork* by using the NetBeans command `menu:Git[Remote>Push]`.

**  In the `Remote Repository` dialog you toggle:
* [x] Select Configured Git Repository Location:
+
--
and use the forked +++<abbr title="Uniform Resource Locator">URL</abbr>+++: `https://username@github.com/username/jmonkeyengine` where username is your username.

NOTE: Note the distinction between `//github.com`: in the pull case and `//username@github.com`: in the push case.
--

.  To submit changes to the jMonkeyEngine repository after pushing them to *your fork*:
..  Go to your version of the repository on GitHub.
..  Click the btn:[New Pull Request] button at the top.
..  Note that the jMonkeyEngine repository will be on the left and your repository will be on the right.
..  Click the green button btn:[Create pull request]. Give a succinct and informative title, in the comment field give a short explanation of the changes and click the green button btn:[Create pull request] again.

.Everyone
NOTE: See  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md[How to contribute to jMonkeyEngine] before submitting a P/R.


== Verify Cloned Subprojects

Look into the `Subprojects` node and confirm that the subprojects cloned:

*  jme3-android
*  jme3-android-native
*  jme3-blender
*  jme3-bullet
*  jme3-bullet-native
*  jme3-bullet-native-android
*  jme3-core
*  jme3-desktop
*  jme3-effects
*  jme3-examples
*  jme3-ios
*  jme3-jbullet
*  jme3-jogg
*  jme3-jogl
*  jme3-lwjgl
*  jme3-lwjgl3
*  jme3-networking
*  jme3-niftygui
*  jme3-plugins
*  jme3-terrain
*  jme3-testdata
*  jme3-vr

For a detailed description of the separate jar files see <<jme3/jme3_source_structure#structure_of_jmonkeyengine3_jars,this list>>.


== Build the Project and Run a Sample App

.  btn:[RMB] select the `jmonkeyengine` project node and `Clean and Build` the project.
.  In the Projects window, btn:[RMB] select and then open the `jme-examples` node which contains the sample apps. You do this for any subproject you wish to make changes to.
.  Every file in the `Source Packages` folder with a Main class (for example `jme3test.model/TestHoverTank.java` or `jme3test.games/CubeField.java`) is an app.
.  Right-click a sample app and choose "`Run File`" (Shift-F6).
.  Generally in sample apps:
..  the mouse and the WASD keys control movement
..  the Esc key exits the application

TIP: You can btn:[RMB] select the `jme-examples` node and select `Run` to start the `Test Chooser` app whether or not you open the project node.

== Optional: Javadoc Popups and Source Navigation in NetBeans

If you are working on the jme3 sources:

.  Confirm in the Files window that the javadoc has been created in `~/NetBeansProjects/jmonkeyengine/dist/javadoc`
.  In the editor, place the caret in a jme class and press kbd:[ctrl]-kbd:[space] to view javadoc.

If you are working on a game project that depends on jme3, you will most likely have your dependencies spread around and linked to different subprojects and or folders:

.  In your game project, add the jme3 jar by btn:[RMB] selecting the Libraries node and selecting btn:[Add Far/Folder].
.  Navigate to the `~/NetBeansProjects/jmonkeyengine/` folder and select the library jar you're interested in.  Check "`as relative path`" and click btn:[Open] .
.  btn:[RMB] select the newly added jar and choose "`Edit`".
.  In the `Edit Jar Reference` dialog, `JavaDoc:` btn:[Browse] to the `~/NetBeansProjects/jmonkeyengine/dist/javadoc/` folder. Check "`as relative path`" and click btn:[Open] .
.  In the `Edit Jar Reference` dialog, `Sources:` btn:[Browse] to the `~/NetBeansProjects/jmonkeyengine/` folder that contains your sources. Usually in the subprojects `build/lib` folder (after running the "`build`" task) or `build/libDist/sources` folder (after running the "`libDist`" task). Check "`as relative path`" and click btn:[Open].
.  In the editor, place the caret in a jme class and press kbd:[ctrl]-kbd:[space] to view javadoc. Ctrl-click any jme3 method to jump to its definition in the sources.

This tip works for any third-party JAR library that you use. (You may have to download the javadoc/sources from their home page separately).

'''

Sources used: https://github.com/jMonkeyEngine/jmonkeyengine[https://github.com/jMonkeyEngine/jmonkeyengine]
