= hardware_compatibility_list
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


+

emoji: *Please expand this list!*
I've copied this page from the original jME2 hardware compatibility list and will work on getting this up to date for jME3 -Skye

+
This page lists the compatibility of various different graphic cards and the latest version of jME3

To fill in a new entry add the name of your graphics card in the first column (Card Name), which driver version the card is running on in the second column (Driver Version).  Then put a 'Y' for yes and a 'N' for no in the next three columns as to whether your card supports the given feature.

*  Basic Features should be considered things like rendering primitive shapes and models fully textured and lit. 
*  Advanced Features should be considered things like Render to Texture and Cloth effects.
*  Shader Features should be anything that uses shaders such as Bloom and Motion Blur.


== General System Requirements for Applications Built with jMonkeyEngine

Please see <<jme3/requirements#,requirements>>
+
For a detailed list of Graphic Card/Driver combinations and which OpenGL features they support see +++<strike>link:http://www.delphi3d.net/hardware/index.php[http://www.delphi3d.net/hardware/index.php]</strike>+++ link:http://www.opengl.org/wiki/Hardware_specifics[http://www.opengl.org/wiki/Hardware_specifics]


=== ATI/AMD
[cols="6", options="header"]
|===

a| Card Name 
a| Driver Version 
a| Basic Features? 
a| Advanced Features (No Shader)? 
a| Shader Features? 
a| Notes 

a| Radeon HD 4850 512MB 
a| 11.8 running on Linux Mint 12 x64+11.12 running on Windows 7 Professional x64
a|Y
a|Y
a|Y
a|All tests works fine.

a| Radeon HD 5850 1GB 
a| 11.12 running on Windows 7 Professional x64 
a|Y
a|Y
a|Y
a|All tests works fine.

a| Radeon HD 6900 2GB 
a| 11.5 running on Windows 7 x64 
a|Y
a|Y
a|Y
a|All tests works fine.

|===


=== Intel
[cols="6", options="header"]
|===

a| Card Name 
a| Driver Version 
a| Basic Features? 
a| Advanced Features (No Shader)? 
a| Shader Features? 
a| Notes 

a|Intel GMA 950 
a| Mac +++<abbr title="Operating System">OS</abbr>+++ X 10.5 
a|Y
a|Y
a|N
a|Works in OpenGL1 compatibility mode.

|===


=== NVidia
[cols="6", options="header"]
|===

a| Card Name 
a| Driver Version 
a| Basic Features? 
a| Advanced Features (No Shader)? 
a| Shader Features? 
a| Notes 

a|NVidia GeForce GT330M 512M 
a| Mac +++<abbr title="Operating System">OS</abbr>+++ X 10.7.2 
a|Y
a|Y
a|Y
a|All tests works fine.

a|NVidia GeForce GT540M 1024M 
a| Windows 7 280.26 
a|Y
a|Y
a|Y
a|All tests works fine.

a|NVidia GeForce GTX480 1536M 
a| Windows 7 285.62 
a|Y
a|Y
a|Y
a|All tests works fine.

|===


=== SiS
[cols="6", options="header"]
|===

a| Card Name 
a| Driver Version 
a| Basic Features? 
a| Advanced Features (No Shader)? 
a| Shader Features? 
a| Notes 

|===
