= JME3 Documentation: Materials
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Work in progress. :)
[cols="2", options="header"]
|===

<a| Default Definition                       
a| Usage 

a| `Common/MatDefs/Misc/SimpleTextured.j3md` 
a| Textured: Use with mat.setTexture() and TextureKey 

<a| `Common/MatDefs/Misc/SolidColor.j3md`     
a| Colored: Use with mat.setColor() and RGBAColor 

<a| `Common/MatDefs/Misc/Sky.j3md`            
a| A solid skyblue. Or use with custom texture. 

<a| `Common/MatDefs/Misc/WireColor.j3md`      
a| Transparent, show only outline 

<a| `Common/MatDefs/Misc/Particle.j3md`       
<a|  

<a| `Common/MatDefs/Misc/ShowNormals.j3md`    
a| Shows a color gradient calculated from surface normals. 

<a| `Common/MatDefs/Misc/VertexColor.j3md`    
a| 

<a| `Common/MatDefs/Gui/Gui.j3md`             
a| 

<a| `Common/MatDefs/Hdr/LogLum.j3md`          
a| 

<a| `Common/MatDefs/Hdr/ToneMap.j3md`         
a| 

<a| `Common/MatDefs/Light/Lighting.j3md`      
a| For texture lighting effects like Bump- and NormalMaps

<a| `Common/MatDefs/Light/Reflection.j3md`    
a| 

<a| `Common/MatDefs/Shadow/PostShadow.j3md`   
a| 

<a| `Common/MatDefs/Shadow/PreShadow.j3md`    
a| 

|===
