= Requerimentos jMonkeyEngine3
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Essa página mostra os requerimentos de hardware e software a partir de dois pontos de vista:

*  Para os desenvolvedores Java que criam jogos; e
*  Para os usuários (seus clientes) que jogam os jogos que você criou.


== Para Desenvolvedores

Esses são os requisitos mínimos para desenvolvedores que criam jogos utilizando a jMonkeyEngine SDK:
[cols="2", options="header"]
|===

a|Sistema Operacional
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris 

a|Memória (tamanho da JVM heap)
a| &gt; 40 +++<abbr title="Megabyte">MB</abbr>+++ ++ memória para assets 

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Placa gráfica
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, ou superior +com suporte à OpenGL 2.0 ou melhor (bibliotecas nativas estão incluídas no download)

a|Java Development Kit
a|JDK 6 ou superior +Seu time de desenvolvimento baixa o Java Development Kit gratuítamente em link:http://www.java.com[http://www.java.com]; para Mac +++<abbr title="Operating System">OS</abbr>+++, veja link:http://support.apple.com/kb/DL1421[apple.com]. +No mínimo experiência intermediária em Java é necessária.

|===

Nós recomendamos utilizar a <<sdk#,jMonkeyEngine SDK>> como ambiênte de desenvolvimento de jogos (IDE). No entanto, qualquer Java IDE de terceiro (e até um editor de texto em linha de comando) funcionará em conjunto com o jME3 se você for experiente com a ferramenta que você escolheu. Para os requisitos de outras IDEs, veja a documentação de terceiros.


== Para Usuários

Esses sãos os requisítos mínimos para seus clientes, usuários que jogarão os jogos que foram criados utilizando a jMonkeyEngine3:
[cols="2", options="header"]
|===

a|Sistema Operacional
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris 

a|Memória (tamanho da JVM heap)
a| &gt; 10 +++<abbr title="Megabyte">MB</abbr>+++ ++ memória para assets (modelos, texturas, sons, etc, do jogo em questão) 

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Placa Gráfica
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, or better +com suporte à OpenGL 2.0 ou melhor (bibliotecas nativas estão incluídas no download)

a|link:http://jmonkeyengine.org/groups/android/forum/topic/does-my-phone-meet-the-requirements-necessary-to-run-jmonkeyengine-3/[Dispoitivos Android]
a|(Para jogos mobile apenas) Android 2.2 +++<abbr title="Operating System">OS</abbr>+++, placa gráfica com suporte à OpenGL 2

a|Java Runtime
a|Java 5 ou superior +A Java Virtual Machine (JVM) é necessária para rodar jogos jME. +A JVM precisa já estar instalada, se não, seus usuários podem baixar de graça em link:http://www.java.com[http://www.java.com]; para Mac +++<abbr title="Operating System">OS</abbr>+++, veja link:http://support.apple.com/kb/DL1421[apple.com]. 

|===

Tenha certeza de informar os seus usuários sobre estes requisitos.
