

= jMonkeyEngine3 开发需求

本文分别从游戏开发者和用户的2种视角，分别介绍使用jMonkeyEngine3所需的软硬件需求。



== 开发者

使用jMonkeyEngine SDK来开发游戏的最低配置需求如下：

[cols="2", options="header"]
|===

a|操作系统
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris 

a|内存 (JVM heap size)
a| &gt; 40 +++<abbr title="Megabyte">MB</abbr>+++ +
+ memory for assets 

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|显卡
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, or better +
supporting OpenGL 2.0 or better (native libraries are included in download)

a|JDK
a|JDK 6 或更高 +
你的开发团队可以从 link:http://www.java.com[http://www.java.com] 免费下载JDK； 对于 Mac +++<abbr title="Operating System">OS</abbr>+++ 开发者, 请访问link:http://support.apple.com/kb/DL1421[apple.com]. +
使用jMonkeyEngine SDK开发游戏，要求至少具备Java中级开发水准。 

|===

We recommend using the <<sdk#,jMonkeyEngine SDK>> as game development environment (IDE). However, any third-party Java IDE (and even a text editor and the commandline) will work fine together with the jME framework if you are experienced with the tool of your choice. For requirements of other IDEs, please see the third party's documentation.



== 用户

These are the minimum requirements for your customers, users who play the games that were created using the jMonkeyEngine3 framework:

[cols="2", options="header"]
|===

a|Operating system
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris 

a|Memory (JVM heap size)
a| &gt; 10 +++<abbr title="Megabyte">MB</abbr>+++ +
+ memory for assets (models, textures, sounds, etc, of a particular game) 

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Graphic card
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, or better +
supporting OpenGL 2.0 or better (native libraries are included in download)

a|link:http://jmonkeyengine.org/groups/android/forum/topic/does-my-phone-meet-the-requirements-necessary-to-run-jmonkeyengine-3/[Android Devices]
a|(For mobile games only) Android 2.2 +++<abbr title="Operating System">OS</abbr>+++, graphics card supporting OpenGL 2

a|Java Runtime
a|Java 5 or higher +
The Java Virtual Machine (JVM) is required to run jME games. +
The JVM is often preinstalled, if not, your users get it for free from link:http://www.java.com[http://www.java.com]; for Mac +++<abbr title="Operating System">OS</abbr>+++, see link:http://support.apple.com/kb/DL1421[apple.com]. 

|===

Make sure to inform your users about these requirements.

