= Setting up JME3 in Eclipse
:author: 
:revnumber: 
:revdate: 2014/03/05 20:25
:keywords: documentation, install, eclipse
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


For development with the jMonkeyEngine 3, we recommend to use the jMonkeyEngine SDK.


Alternatively, you can use your favorite IDE: In this tutorial we show how to download and set up the latest nightly build of the jMonkeyEngine 3 for use with the Eclipse IDE. Instructions for <<jme3/setting_up_netbeans_and_jme3#,NetBeans IDE>> are also available.



== Downloading jME3

The currently available JAR binaries are the nightly builds. 


.  Download the most recent zipped build from link:http://updates.jmonkeyengine.org/stable/3.0/engine[http://updates.jmonkeyengine.org/stable/3.0/engine]
.  Unzip the file and save it as `jME3_2012-xx-xx` in your home directory ($HOME). You should see the following files and directories:
**  `lib/` – The jMonkeyEngine binaries, and libraries used by the jMonkeyEngine. (Don't remove)
**  `TestChooser.exe` – Run this file to see various feature demos. (optional)
**  `javadoc/` – jME3 +++<abbr title="Application Programming Interface">API</abbr>+++ documentation. (optional)



== Creating a New Game Project

*  In Eclipse, choose File &gt; New &gt; Java Project
*  Project Name: HelloJME3
*  Click Finish

The new project appears in the Explorer.



== Setting up Dependencies

Your project depends on the jMonkeyEngine libraries and needs to know where they are.


.  Right-click the project in the explorer and choose `Build Path &gt; Add External Archives`
.  In the “JAR selection dialog, browse to the `$HOME/jME3_2012-xx-xx` directory.
.  Select all JARs in the `lib` directory and click Open.

All necessary JAR libraries are now on the classpath and should appear in the Referenced Libraries list. For a detailed description of the separate jar files see <<jme3/jme3_source_structure#structure_of_jmonkeyengine3_jars,this list>>.



== Setting up Assets

The easiest way to make sure the asset manager can access the assets is by adding the assets folder to the classpath.


.  Go to Project Properties
.  Select Java Build Path
.  Under the Source tab click add folder 
.  Add your Assets folder


== Writing a Simple Application

.  From the menu call File &gt; New &gt; New Package. Name the src package for example `hello`.
.  From the menu call File &gt; New &gt; Class. 
**  Select package `hello`.
**  Name the class for example `MyGame`.
**  Superclass: `com.jme3.app.SimpleApplication`
**  Make sure that the checkbox to Create the `main()` Method is active
**  Make sure that the checkbox to Inheriting Abstract Methods is active
**  Click Finish.


You can now continue to write <<jme3/beginner/hello_simpleapplication#,your first jme3 application>>!

