= points
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../
:imagesdir: ../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== ES Design goals explained

This page revive and explain more about points of design goals and implementations for an ES and its usefulness (means features) to corporate with other Java and game software techs and layers.

Theoricaly an Java ES done right should be:

.  Pure data : very debatable
..  Mutable : as bean with setter and getter
..  Immutate : as bean with getter, should be replace if changed.

.  Multi-threading, concurency enable : very debatable
..  As my experience, pure data or not is not clear contract to multi-threading success. Consider other things happen outside of ES scope, so it not an solid waranty that those component will not be touched by any other thread.
..  Also if there is a contract that no other thread touching those data, in Java style via synchonization or other paradigm like actor… multi-threading also consider success but just more complicated!

.  Communication: very debatable
..  Event messaging enable
..  No event or messaging : update beat, no need of inter-com or events. How can we do network messaging?

.  Is database (and other kind of persistent) friendly
..  Save to XML (file, serialized)?
..  Send over network?
..  Change sets are resembling Databse concept, what about tranactions?

.  Is enterprise friendly (expanable/ extensible/ modulizable)
..  Spring, as lazy loaded, injected?

.  Script possibilities
..  Can be script, non trivial work in pure data!
..  Can be use with other JVM language than java like groovy, or scala, jython?

.  Restrictions and limitation
..  No dynamic Java object methods in Component ? What about Entities and Systems ( Processors)
..  An overal way to manage and config Systems, freely chose? How to hook to its routine?

.  Depedencies
..  The separation of components are clear, as no dependencies at all. Hard cored, scripted or injected will break the overal contract!
..  The separation of Entities. What about depedencies of entities? Ex: parent/ child relationship in JME spatial. How the framework handle that?
..  The separation of Systems. Ex: any contract about that?

