= jMonkeyEngine3 开发需求
:author: yanmaoyuan
:revnumber: 1.0
:revdate: 2018/01/15 16:29
:relfileprefix: ../
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

本文分别从游戏开发者和用户的2种视角，分别介绍使用jMonkeyEngine3所需的软硬件需求。

== 开发者

使用jMonkeyEngine SDK来开发游戏的最低配置需求如下：
[cols="2", options="header"]
|===

a|操作系统
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris 

a|内存 (JVM heap size)
a| &gt; 40 +++<abbr title="Megabyte">MB</abbr>+++ ++ 游戏资源所占用的内存 

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|显卡
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, 或者更高性能的显卡 +最好支持OpenGL 2.0(你下载jMonkeyEngine SDK中包含本地运行库)

a|JDK
a|JDK 7 或更高 +
你的开发团队可以从 link:http://www.java.com[http://www.java.com] 免费下载JDK； 对于 Mac +++<abbr title="Operating System">OS</abbr>+++ 开发者, 请访问link:http://support.apple.com/kb/DL1421[apple.com]. +
使用jMonkeyEngine SDK开发游戏，要求至少具备Java中级开发水准。 

|===

我们推荐开发者使用<<sdk/index#,jMonkeyEngine SDK>>作为游戏开发IDE。但是你也可以选择自己熟悉的第三方IDE来集成jMonkeyEngine框架进行开发，甚至可以使用记事本写代码然后在命令行下编译。对于第三方IDE的软硬件需求，请查看对应IDE的文档。


== 用户

下面是用户运行jMonkeyEngine框架开发的游戏所需的最低配置:
[cols="2", options="header"]
|===

a|操作系统
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris 

a|内存 (JVM heap size)
a| &gt; 10 +++<abbr title="Megabyte">MB</abbr>+++ ++ 游戏资源所占用的内存(一般包括模型、贴图、声音等) 

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|显卡
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, 或更高性能的显卡 +最好能够支持OpenGL 2.0

a|link:http://jmonkeyengine.org/groups/android/forum/topic/does-my-phone-meet-the-requirements-necessary-to-run-jmonkeyengine-3/[Android 设备]
a|(玩手游需要) Android 2.2 +++<abbr title="Operating System">OS</abbr>+++, 支持OpenGL 2的显卡

a|Java 运行环境
a|Java 5 及以上 +
你需要JVM来运行jME游戏. +
JVM通常需要提前安装。如果你的用户没有安装的话，可以通过 link:http://www.java.com[http://www.java.com] 免费下载； Mac +++<abbr title="Operating System">OS</abbr>+++ 用户请访问link:http://support.apple.com/kb/DL1421[apple.com]. 

|===

请确保你的用户了解上诉需求。