= jMonkeyEngine3 Supported File 類型s
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../
:圖片sdir: ../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== jMonkeyEngine3 檔案格式
[cols="10,65,25", options="header"]
|===

a|Suffix
a|使用方法
a|了解更多

l|.j3o
a|Binary 3D模型 or scene. At the latest from the Beta release of your game on, you should convert all models to .j3o format. +
During alpha and earlier development phases (when models still change a lot) you can alternatively load OgreXML/OBJ models directly.
a|<<sdk/model_loader_and_viewer#,Model Loader and Viewer>> 

l|.j3m
a|A custom Material. You can create a .j3m file to store a Material configuration for a Geometry (e.g. 3D model).
a|<<jme3/advanced/materials_overview#,Materials Overview>> +
<<sdk/material_editing#,Material Editing>> 

l|.j3md
a|A Material definition. These are pre-defined templates for shader-based Materials. +
Each custom .j3m Material is based on a material definition. Advanced users can create their own material definitions. 
a| <<jme3/advanced/materials_overview#,Materials Overview>> 

l|.j3f
a|A custom post-processor filter configuration. You can create a .j3f file to store a FilterPostProcessor with a set of preconfigured filters. 
a| <<sdk/filters#,Filters>> +
<<jme3/advanced/effects_overview#,Effects Overview>> 

|===


== 支援的外部檔案類型
[cols="3", options="header"]
|===

a|檔案支援
a|Type
a|描述

l|.mesh.xml, .meshxml
a|3D model
a|Ogre Mesh XML 

l|.scene
a|3D scene
a|Ogre DotScene 

l|.OBJ, .MTL
a|3D model
a|Wavefront

l|.blend
a|3D model
a|Blender version 2.49 onwards (tested up to 2.65)

a|COLLADA
a| 3D model
a|Imported via Blender bundled with the SDK

a|3DS
a|3D model
a|Imported via Blender bundled with the SDK

|===
[cols="3", options="header"]
|===

a|.JPG, .PNG, .GIF
a|image
a|Textures, icons

l|.DDS
a|image
a|Direct Draw Surface texture

l|.HDR
a|image
a|High Dynamic Range texture

l|.TGA
a|image
a|Targa Image File texture

l|.PFM
a|image
a|Portable Float Map texture

l|.fnt
a|bitmap font
a|AngelCode font for +++<abbr title="Graphical User Interface">GUI</abbr>+++ and HUD

l|.WAV
a|audio
a|Wave music and sounds

l|.OGG
a|audio
a|OGG Vorbis music and sounds

|===
