= Wiki页头分析
:author: mitm (翻译 jmecn)
:revnumber:
:revdate: 2018-01-16 13:02:21
:relfileprefix: ../../
:imagesdir: ../..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

所有Wiki文档均使用下列页头属性。“可选”属性的值可不填，在 kbd:[:] 符号后留空即可。

[source,subs="+macros"]
----
= 文档标题
:author:
:revnumber:
:revdate:
:relfileprefix: ../../
:imagesdir: ../..
:experimental:
ifdef++::++env-github,env-browser[:outfilesuffix: .adoc]
----

*pass:[=]* 必填，文档的标题。

*pass:[:]author:* 可选，文档的作者。

*pass:[:]revnumber:* 可选，文档的版本号。

*pass:[:]revdate:* 可选，文档更新日期。

*pass:[:]relfileprefix:* 必填，输入该文档到 "asciidoc" 目录的路径。

TIP: 在 link:https://atom.io/[Atom] 编辑器中，可以通过 `Tree View` (kbd:[ctrl]+kbd:[\ ] 或 `menu:View[Toggle Tree View]`) 来定位 "`asciidoc`" 目录。

在下面的例子中，"`asciidoc`" 目录位于该文件的两层目录之上。

`pass:[:]relfileprefix: ../../`

*pass:[:]imagesdir:* 必填，输入该文档到 "images" 目录的路径。

TIP: 在 link:https://atom.io/[Atom] 编辑器中，可以通过 `Tree View` (kbd:[ctrl]+kbd:[\ ] 或 `menu:View[Toggle Tree View]`) 来定位 "`images`" 目录。

在下面的例子中，"`images`" 目录位于该文件的两层目录之上。注意路径最后缺少的 kbd:[/] 符号。

`pass:[:]imagesdir: ../..`

[TIP]
====
在 Atom 编辑器中，你可以通过一个简单的方法来判断 "`images`" 和 "`asciidoc`" 目录的位置。

先把文件保存到某个目录下，然后在 `Tree View` (kbd:[ctrl]+kbd:[\ ] 或 `menu:View[Toggle Tree View]`) 中用鼠标右键点击该文件，并在弹出菜单中选择 btn:[Copy Project Path]。

把这个路径临时粘贴到文档中，看看 "`asciidoc`" 目录在哪儿。

例如： `src\docs\asciidoc\jme3\advanced\3d_models.adoc`

在这个例子中，"`asciidoc`" 与 "`3d_models.adoc`" 之间隔着两层目录。

你同样可以使用 link:https://github.com/jMonkeyEngine/wiki/blob/master/src/docs/asciidoc/jme3/advanced/3d_models.adoc[GitHub] 来查看文件路径。
====

由于 "`images`" 目录与 "`asciidoc`" 目录位于同一层次，除了比 "`asciidoc`" 的路径少一个 kbd:[/ ] 之外，它们的路径设置几乎完全相同。

*pass:[:]experimental:* 保留空白即可。此属性用于开启 link:http://asciidoctor.org/docs/user-manual/#user-interface-macros[User Interface Macros] 功能。你可以用这些宏来创建快捷键、显示按钮以及UI按钮。

*ifdef++::++env-github,env-browser[:outfilesuffix: .adoc]* 保留原内容即可。欲详细了解，请查阅 AsciiDoctor 用户手册中的 link:http://asciidoctor.org/docs/user-manual/#navigating-between-source-files[Navigating Between Source Files] 章节。
