= jMonkeyEngine3 Requirements
:revnumber: 3.0
:revdate: 2020/07/13


This page shows software and hardware requirements from two points of view:

*  For the Java developers who create games; and
*  For the users (your customers) who play the games that you created.


== For Developers

These are the minimum requirements for developers who create games using the jMonkeyEngine SDK:
[cols="20,80", options="header"]
|===

a|Operating system
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux

a|Memory (JVM heap size)
a| ++>++ 40 +++<abbr title="Megabyte">MB</abbr>+++ +++++ memory for assets.

a|CPU
a|++>++ 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Graphic card
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, or better supporting OpenGL 2.0 or better. (native libraries are included in download) +
Mac OS, only OpenGL 3.2 is available; You need to specify OpenGL 3.2 in AppSettings, you can’t use OpenGL 2.0.

All platforms: +
If you use the  LWJGL3 library (LWJGL2 is default), you need a specific launch argument (-XstartOnFirstThread), and thus can’t use any launchers not using the main thread. Because of this, calls to app.start() hang as it uses the current thread.

See the forum post link:https://hub.jmonkeyengine.org/t/lwjgl-v2-versus-v3/42125[LWJGL v2 versus v3] for additional details.


a|Java Development Kit
a|JDK 7 or higher +
Your development team gets the Java Development Kit for free from link:http://www.java.com[http://www.java.com]. +
Mac +++<abbr title="Operating System">OS</abbr>+++, see link:http://support.apple.com/kb/DL1421[apple.com]. +
At least intermediate Java experience is required.

|===

We recommend using the xref:sdk:sdk.adoc[SDK] as game development environment (IDE). However, any third-party Java IDE (and even a text editor and the commandline) will work fine together with the jME framework if you are experienced with the tool of your choice. For requirements of other IDEs, please see the third party's documentation.


== For Users

These are the minimum requirements for your customers, users who play the games that were created using the jMonkeyEngine3 framework:
[cols="20,80", options="header"]
|===

a|Operating system
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux

a|Memory (JVM heap size)
a| ++>++ 10 +++<abbr title="Megabyte">MB</abbr>+++ +++++ memory for assets. (models, textures, sounds, etc, of a particular game)

a|CPU
a|++>++ 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Graphic card
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, or better supporting OpenGL 2.0 or better. (native libraries are included in download) +
Mac OS requires OpenGL 3.2.

a|link:https://hub.jmonkeyengine.org/t/does-my-phone-meet-the-requirements-necessary-to-run-jmonkeyengine-3/17231[Android Devices]
a|(For mobile games only) Android 2.2 +++<abbr title="Operating System">OS</abbr>+++, graphics card supporting OpenGL 2

a|Java Runtime
a|Java 5 or higher. +
The Java Virtual Machine (JVM) is required to run jME games. +
The JVM is often preinstalled, if not, your users get it for free from link:http://www.java.com[http://www.java.com]. +
 Mac +++<abbr title="Operating System">OS</abbr>+++, see link:http://support.apple.com/kb/DL1421[apple.com].

|===

Make sure to inform your users about these requirements.
