

= jMonkeyEngine3 Требования

На этой странице показаны программные и аппаратные требования с двух точек зрения:


*  Для Java-разработчиков, которые создают игры; и
*  Для пользователей (клиентов), которые играют в игры, которые вы создали.


== Для Разработчиков

Это минимальные требования для разработчиков, которые создают игры с использованием jMonkeyEngine SDK:

[cols="2", options="header"]
|===

a|Операционная система
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris 

a|Память (JVM heap size)
a| &gt; 40 +++<abbr title="Megabyte">MB</abbr>+++ +
+ память для ресурсов 

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Видеокарта
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, или лучше +
supporting OpenGL 2.0 или лучше (родные библиотеки включены в download)

a|Java Development Kit
a|JDK 6 или выше +
Ваша команда разработчиков получает Java Development Kit бесплатно из link:http://www.java.com[http://www.java.com]; для Mac +++<abbr title="Operating System">OS</abbr>+++, см. также link:http://support.apple.com/kb/DL1421[apple.com]. +
По крайней мере, промежуточные Java опыт требуется. 

|===

Мы рекомендуем использовать <<sdk#,jMonkeyEngine SDK>> в качестве среды разработки игры(IDE). Однако, какие-либо сторонние Java IDE (и даже текстовый редактор и командная строка) будет прекрасно работать вместе с jME framework, если у вас есть опыт в работе с вашим инструментом. По требованиям других IDE, обратитесь к третьему лицу, документации.



== Для Пользователей

Это минимальные требования для ваших клиентов, пользователей, которые играют в игры, созданные с использованием jMonkeyEngine3:

[cols="2", options="header"]
|===

a|Операционная система
a|Mac +++<abbr title="Operating System">OS</abbr>+++ X, Windows, Linux, Solaris 

a|Память (JVM heap size)
a| &gt; 10 +++<abbr title="Megabyte">MB</abbr>+++ +
+ память для ресурсов (модели, текстуры, звуки и т.д.), конкретной игры 

a|CPU
a|&gt; 1 +++<abbr title="Gigahertz">GHz</abbr>+++

a|Видеокарта
a|AMD/ATI Radeon 9500, NVIDIA GeForce 5 FX, Intel GMA 4500, или лучше +
supporting OpenGL 2.0 или лучше (родные библиотеки включены в download)

a|link:http://jmonkeyengine.org/groups/android/forum/topic/does-my-phone-meet-the-requirements-necessary-to-run-jmonkeyengine-3/[Android Devices]
a|(Только для мобильных игр) Android 2.2 +++<abbr title="Operating System">OS</abbr>+++, Видеокарта, поддерживающая OpenGL 2

a|Java Runtime
a|Java 5 или выше +
Java Virtual Machine (JVM) требуется для запуска jME игры. +
JVM часто предварительно установлен, если нет, то ваши пользователи получить его бесплатно отсюда link:http://www.java.com[http://www.java.com]; для Mac +++<abbr title="Operating System">OS</abbr>+++, см. также link:http://support.apple.com/kb/DL1421[apple.com]. 

|===

Убедитесь в том, что вы проинформировали пользователей об этих требованиях.

