= Atom Snippets Page
:author: mitm
:revnumber: 2
:revdate: 2017-09-08T23:24:11.262Z
:relfileprefix: ../
:imagesdir: ..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Edit this file to add snippets to the snippets.cson file for the
link:https://atom.io/[Atom editor]. To use these snippets just copy and paste
the text below into your snippets.cson file.

[source]
----
# Your snippets
#
# Atom snippets allow you to enter a simple prefix in the editor and hit tab to
# expand the prefix into a larger code block with templated values.
#
# You can create a new snippet in this file by typing "snip" and then hitting
# tab.
#
# An example CoffeeScript snippet to expand log to console.log:
#
# '.source.coffee':
#   'Console log':
#     'prefix': 'log'
#     'body': 'console.log $1'
#
# Each scope (e.g. '.source.coffee' above) can only be declared once.
#
# This file uses CoffeeScript Object Notation (CSON).
# If you are unfamiliar with CSON, you can read more about it in the
# Atom Flight Manual:
# http://flight-manual.atom.io/using-atom/sections/basic-customization/#_cson
'.source.asciidoc':
  'Inter-Doc Cross Reference':
    'prefix': 'xref'
    'body': '<<${1:path/to/wiki/page}#,${2:custom label text}>>'
  'Admonition Block':
    'prefix': 'admonB'
    'body': """
    [${1:NOTE}${2:TIP}${3:IMPORTANT}${4:CAUTION}${5:WARNING}]
    ====
    $6
    ====
    $7
    """
  'Admonition Block with Title':
    'prefix': 'admonBwT'
    'body': """
    [${1:NOTE}${2:TIP}${3:IMPORTANT}${4:CAUTION}${5:WARNING}]
    .${6:Optional Title}
    ====
    $7
    ====
    $8
    """
  'Admonition Paragraph':
    'prefix': 'admonP'
    'body': """
    ${1:NOTE}${2:TIP}${3:IMPORTANT}${4:CAUTION}${5:WARNING}: $6
    """
  'Admonition Paragraph with Title':
    'prefix': 'admonPwT'
    'body': """
    .${1:Optional Title}
    ${2:NOTE}${3:TIP}${4:IMPORTANT}${5:CAUTION}${6:WARNING}: $7
    """
----

== Snippets Explained

[cols="10, 45,45"*,options="header"]
|===

| Prefix
| Inserted Syntax
| Description

| xref
|`+<<path/to/wiki/page#,custom label text>>+`
| Inserts an `Inter-Document Cross Reference`.

| admonB
| [NOTETIPIMPORTANTCAUTIONWARNING] +
 ==== +
 ====
| Inserts an `Admonition Block` with the #NOTE# style highlighted. Use the kbd:[Tab] key to cycle to the next style
and kbd:[Backspace] off any unwanted style as you go. The final kbd:[Tab] will take you into the block.

| admonBwT
| [NOTETIPIMPORTANTCAUTIONWARNING] +
.Optional Title +
 ==== +
 ====
| Inserts an `Admonition Block` with title.


| admonP
| NOTETIPIMPORTANTCAUTIONWARNING:
| Inserts an `Admonition Paragraph` with the #NOTE# style highlighted. Use the kbd:[Tab] key to cycle to the next style
and kbd:[Backspace] off any unwanted style as you go. The final kbd:[Tab] will take you to the beginning of the paragraph.

| admonPwT
| .Optional Title +
NOTETIPIMPORTANTCAUTIONWARNING:
| Inserts an `Admonition Paragraph` with title.

|===
