= Emoji Cheat Sheet
:author: mitm
:revnumber:
:revdate: 2019-12-18T23:24:11.262Z
:stylesheet: twemoji-awesome.css
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== How to use emoji in the wiki

Using emoji in wiki docs currently requires the setting of the `:stylesheet:` attribute in the header of the wiki document.

```
:stylesheet: twemoji-awesome.css
```
The <<wiki/wiki_header.adoc#,Anatomy of a Wiki Header>> document exlains setting of this and other header attributes.

Once the header attribute is set, you can add the emoji using the following syntax.

```
emoji:heart[2x] // the "[2x]" is a size modifier
emoji:rage[]
```

[NOTE]
====
You can change the icon size with the size modifier `[2x]`.

`+emoji:heart[]+` emoji:heart[] `+emoji:heart[2x]+` emoji:heart[2x]
====

== Full list of emoji and their syntax.

[.stripes-none,cols=3*, frame=none, grid=none]
|===
a| emoji:smile[] [.small]`+emoji:smile[]+`
a| emoji:laughing[] [.small]`+emoji:laughing[]+`
a| emoji:blush[] [.small]`+emoji:blush[]+`

a| emoji:smiley[] [.small]`+emoji:smiley[]+`
a| emoji:relaxed[] [.small]`+emoji:relaxed[]+`
a| emoji:smirk[] [.small]`+emoji:smirk[]+`

a| emoji:heart-eyes[] [.small]`+emoji:heart-eyes[]+`
a| emoji:kissing-heart[] [.small]`+emoji:kissing-heart[]+`
a| emoji:kissing-closed-eyes[] [.small]`+emoji:kissing-closed-eyes[]+`

a| emoji:flushed[] [.small]`+emoji:flushed[]+`
a| emoji:relieved[] [.small]`+emoji:relieved[]+`
a| emoji:satisfied[] [.small]`+emoji:satisfied[]+`

a| emoji:grin[] [.small]`+emoji:grin[]+`
a| emoji:wink[] [.small]`+emoji:wink[]+`
a| emoji:stuck-out-tongue-winking-eye[] [.small]`+emoji:stuck-out-tongue-winking-eye[]+`

a| emoji:stuck-out-tongue-closed-eyes[] [.small]`+emoji:stuck-out-tongue-closed-eyes[]+`
a| emoji:grinning[] [.small]`+emoji:grinning[]+`
a| emoji:kissing[] [.small]`+emoji:kissing[]+`

a| emoji:kissing-smiling-eyes[] [.small]`+emoji:kissing-smiling-eyes[]+`
a| emoji:stuck-out-tongue[] [.small]`+emoji:stuck-out-tongue[]+`
a| emoji:sleeping[] [.small]`+emoji:sleeping[]+`

a| emoji:worried[] [.small]`+emoji:worried[]+`
a| emoji:frowning[] [.small]`+emoji:frowning[]+`
a| emoji:anguished[] [.small]`+emoji:anguished[]+`

a| emoji:open-mouth[] [.small]`+emoji:open-mouth[]+`
a| emoji:grimacing[] [.small]`+emoji:grimacing[]+`
a| emoji:confused[] [.small]`+emoji:confused[]+`

a| emoji:hushed[] [.small]`+emoji:hushed[]+`
a| emoji:expressionless[] [.small]`+emoji:expressionless[]+`
a| emoji:unamused[] [.small]`+emoji:unamused[]+`

a| emoji:sweat-smile[] [.small]`+emoji:sweat-smile[]+`
a| emoji:sweat[] [.small]`+emoji:sweat[]+`
a| emoji:weary[] [.small]`+emoji:weary[]+`

a| emoji:pensive[] [.small]`+emoji:pensive[]+`
a| emoji:disappointed[] [.small]`+emoji:disappointed[]+`
a| emoji:confounded[] [.small]`+emoji:confounded[]+`

a| emoji:fearful[] [.small]`+emoji:fearful[]+`
a| emoji:cold-sweat[] [.small]`+emoji:cold-sweat[]+`
a| emoji:persevere[] [.small]`+emoji:persevere[]+`

a| emoji:cry[] [.small]`+emoji:cry[]+`
a| emoji:sob[] [.small]`+emoji:sob[]+`
a| emoji:joy[] [.small]`+emoji:joy[]+`

a| emoji:astonished[] [.small]`+emoji:astonished[]+`
a| emoji:scream[] [.small]`+emoji:scream[]+`
a| emoji:tired-face[] [.small]`+emoji:tired-face[]+`

a| emoji:angry[] [.small]`+emoji:angry[]+`
a| emoji:rage[] [.small]`+emoji:rage[]+`
a| emoji:triumph[] [.small]`+emoji:triumph[]+`

a| emoji:sleepy[] [.small]`+emoji:sleepy[]+`
a| emoji:yum[] [.small]`+emoji:yum[]+`
a| emoji:mask[] [.small]`+emoji:mask[]+`

a| emoji:sunglasses[] [.small]`+emoji:sunglasses[]+`
a| emoji:dizzy-face[] [.small]`+emoji:dizzy-face[]+`
a| emoji:imp[] [.small]`+emoji:imp[]+`

a| emoji:smiling-imp[] [.small]`+emoji:smiling-imp[]+`
a| emoji:neutral-face[] [.small]`+emoji:neutral-face[]+`
a| emoji:no-mouth[] [.small]`+emoji:no-mouth[]+`

a| emoji:innocent[] [.small]`+emoji:innocent[]+`
a| emoji:alien[] [.small]`+emoji:alien[]+`
a| emoji:yellow-heart[] [.small]`+emoji:yellow-heart[]+`

a| emoji:blue-heart[] [.small]`+emoji:blue-heart[]+`
a| emoji:purple-heart[] [.small]`+emoji:purple-heart[]+`
a| emoji:heart[] [.small]`+emoji:heart[]+`

a| emoji:green-heart[] [.small]`+emoji:green-heart[]+`
a| emoji:broken-heart[] [.small]`+emoji:broken-heart[]+`
a| emoji:heartbeat[] [.small]`+emoji:heartbeat[]+`

a| emoji:heartpulse[] [.small]`+emoji:heartpulse[]+`
a| emoji:two-hearts[] [.small]`+emoji:two-hearts[]+`
a| emoji:revolving-hearts[] [.small]`+emoji:revolving-hearts[]+`

a| emoji:cupid[] [.small]`+emoji:cupid[]+`
a| emoji:sparkling-heart[] [.small]`+emoji:sparkling-heart[]+`
a| emoji:sparkles[] [.small]`+emoji:sparkles[]+`

a| emoji:star[] [.small]`+emoji:star[]+`
a| emoji:star2[] [.small]`+emoji:star2[]+`
a| emoji:dizzy[] [.small]`+emoji:dizzy[]+`

a| emoji:boom[] [.small]`+emoji:boom[]+`
a| emoji:anger[] [.small]`+emoji:anger[]+`
a| emoji:exclamation[] [.small]`+emoji:exclamation[]+`

a| emoji:question[] [.small]`+emoji:question[]+`
a| emoji:grey-exclamation[] [.small]`+emoji:grey-exclamation[]+`
a| emoji:grey-question[] [.small]`+emoji:grey-question[]+`

a| emoji:zzz[] [.small]`+emoji:zzz[]+`
a| emoji:dash[] [.small]`+emoji:dash[]+`
a| emoji:sweat-drops[] [.small]`+emoji:sweat-drops[]+`

a| emoji:notes[] [.small]`+emoji:notes[]+`
a| emoji:musical-note[] [.small]`+emoji:musical-note[]+`
a| emoji:fire[] [.small]`+emoji:fire[]+`

a| emoji:poop[] [.small]`+emoji:poop[]+`
a| emoji:thumbsup[] [.small]`+emoji:thumbsup[]+`
a| emoji:thumbsdown[] [.small]`+emoji:thumbsdown[]+`

a| emoji:ok-hand[] [.small]`+emoji:ok-hand[]+`
a| emoji:punch[] [.small]`+emoji:punch[]+`
a| emoji:fist[] [.small]`+emoji:fist[]+`

a| emoji:v[] [.small]`+emoji:v[]+`
a| emoji:wave[] [.small]`+emoji:wave[]+`
a| emoji:hand[] [.small]`+emoji:hand[]+`

a| emoji:point-up[] emoji:open-hands[] [.small]`+emoji:open-hands[]+`
a| emoji:point-up[] [.small]`+emoji:point-up[]+`
a| emoji:point-down[] [.small]`+emoji:point-down[]+`

a| emoji:point-left[] [.small]`+emoji:point-left[]+`
a| emoji:point-right[] [.small]`+emoji:point-right[]+`
a| emoji:raised-hands[] [.small]`+emoji:raised-hands[]+`

a| emoji:pray[] [.small]`+emoji:pray[]+`
a| emoji:point-up-2[] [.small]`+emoji:point-up-2[]+`
a| emoji:clap[] [.small]`+emoji:clap[]+`

a| emoji:muscle[] [.small]`+emoji:muscle[]+`
a| emoji:walking[] [.small]`+emoji:walking[]+`
a| emoji:runner[] [.small]`+emoji:runner[]+`

a| emoji:couple[] [.small]`+emoji:couple[]+`
a| emoji:family[] [.small]`+emoji:family[]+`
a| emoji:two-men-holding-hands[] [.small]`+emoji:two-men-holding-hands[]+`

a| emoji:two-women-holding-hands[] [.small]`+emoji:two-women-holding-hands[]+`
a| emoji:dancer[] [.small]`+emoji:dancer[]+`
a| emoji:dancers[] [.small]`+emoji:dancers[]+`

a| emoji:ok-woman[] [.small]`+emoji:ok-woman[]+`
a| emoji:no-good[] [.small]`+emoji:no-good[]+`
a| emoji:information-desk-person[] [.small]`+emoji:information-desk-person[]+`

a| emoji:raised-hand[] [.small]`+emoji:raised-hand[]+`
a| emoji:bride-with-veil[] [.small]`+emoji:bride-with-veil[]+`
a| emoji:person-with-pouting-face[] [.small]`+emoji:person-with-pouting-face[]+`

a| emoji:person-frowning[] [.small]`+emoji:person-frowning[]+`
a| emoji:bow[] [.small]`+emoji:bow[]+`
a| emoji:couplekiss[][.small]`+emoji:couplekiss[]+`

a| emoji:couple-with-heart[] [.small]`+emoji:couple-with-heart[]+`
a| emoji:massage[] [.small]`+emoji:massage[]+`
a| emoji:haircut[] [.small]`+emoji:haircut[]+`

a| emoji:nail-care[] [.small]`+emoji:nail-care[]+`
a| emoji:boy[] [.small]`+emoji:boy[]+`
a| emoji:girl[] [.small]`+emoji:girl[]+`

a| emoji:woman[] [.small]`+emoji:woman[]+`
a| emoji:man[] [.small]`+emoji:man[]+`
a| emoji:baby[] [.small]`+emoji:baby[]+`

a| emoji:older-woman[] [.small]`+emoji:older-woman[]+`
a| emoji:older-man[] [.small]`+emoji:older-man[]+`
a| emoji:person-with-blond-hair[] [.small]`+emoji:person-with-blond-hair[]+`

a| emoji:man-with-gua-pi-mao[] [.small]`+emoji:man-with-gua-pi-mao[]+`
a| emoji:man-with-turban[] [.small]`+emoji:man-with-turban[]+`
a| emoji:construction-worker[] [.small]`+emoji:construction-worker[]+`

a| emoji:cop[] [.small]`+emoji:cop[]+`
a| emoji:angel[] [.small]`+emoji:angel[]+`
a| emoji:princess[] [.small]`+emoji:princess[]+`

a| emoji:smiley-cat[] [.small]`+emoji:smiley-cat[]+`
a| emoji:smile-cat[] [.small]`+emoji:smile-cat[]+`
a| emoji:heart-eyes-cat[] [.small]`+emoji:heart-eyes-cat[]+`

a| emoji:kissing-cat[] [.small]`+emoji:kissing-cat[]+`
a| emoji:smirk-cat[] [.small]`+emoji:smirk-cat[]+`
a| emoji:scream-cat[] [.small]`+emoji:scream-cat[]+`

a| emoji:crying-cat-face[] [.small]`+emoji:crying-cat-face[]+`
a| emoji:joy-cat[] [.small]`+emoji:joy-cat[]+`
a| emoji:pouting-cat[] [.small]`+emoji:pouting-cat[]+`

a| emoji:japanese-ogre[] [.small]`+emoji:japanese-ogre[]+`
a| emoji:japanese-goblin[] [.small]`+emoji:japanese-goblin[]+`
a| emoji:see-no-evil[] [.small]`+emoji:see-no-evil[]+`

a| emoji:hear-no-evil[] [.small]`+emoji:hear-no-evil[]+`
a| emoji:speak-no-evil[] [.small]`+emoji:speak-no-evil[]+`
a| emoji:guardsman[] [.small]`+emoji:guardsman[]+`

a| emoji:skull[] [.small]`+emoji:skull[]+`
a| emoji:feet[] [.small]`+emoji:feet[]+`
a| emoji:lips[] [.small]`+emoji:lips[]+`

a| emoji:kiss[] [.small]`+emoji:kiss[]+`
a| emoji:droplet[] [.small]`+emoji:droplet[]+`
a| emoji:ear[] [.small]`+emoji:ear[]+`

a| emoji:eyes[] [.small]`+emoji:eyes[]+`
a| emoji:nose[] [.small]`+emoji:nose[]+`
a| emoji:tongue[] [.small]`+emoji:tongue[]+`

a| emoji:love-letter[] [.small]`+emoji:love-letter[]+`
a| emoji:bust-in-silhouette[] [.small]`+emoji:bust-in-silhouette[]+`
a| emoji:busts-in-silhouette[] [.small]`+emoji:busts-in-silhouette[]+`

a| emoji:speech-balloon[] [.small]`+emoji:speech-balloon[]+`
a| emoji:thought-balloon[] [.small]`+emoji:thought-balloon[]+`
a| emoji:sunny[] [.small]`+emoji:sunny[]+`

a| emoji:umbrella[] [.small]`+emoji:umbrella[]+`
a| emoji:cloud[] [.small]`+emoji:cloud[]+`
a| emoji:snowflake[] [.small]`+emoji:snowflake[]+`

a| emoji:snowman[] [.small]`+emoji:snowman[]+`
a| emoji:zap[] [.small]`+emoji:zap[]+`
a| emoji:cyclone[] [.small]`+emoji:cyclone[]+`

a| emoji:foggy[] [.small]`+emoji:foggy[]+`
a| emoji:ocean[] [.small]`+emoji:ocean[]+`
a| emoji:cat[] [.small]`+emoji:cat[]+`

a| emoji:dog[] [.small]`+emoji:dog[]+`
a| emoji:mouse[] [.small]`+emoji:mouse[]+`
a| emoji:hamster[] [.small]`+emoji:hamster[]+`

a| emoji:rabbit[] [.small]`+emoji:rabbit[]+`
a| emoji:wolf[] [.small]`+emoji:wolf[]+`
a| emoji:frog[] [.small]`+emoji:frog[]+`

a| emoji:tiger[] [.small]`+emoji:tiger[]+`
a| emoji:koala[] [.small]`+emoji:koala[]+`
a| emoji:bear[] [.small]`+emoji:bear[]+`

a| emoji:pig[] [.small]`+emoji:pig[]+`
a| emoji:pig-nose[] [.small]`+emoji:pig-nose[]+`
a| emoji:cow[] [.small]`+emoji:cow[]+`

a| emoji:boar[] [.small]`+emoji:boar[]+`
a| emoji:monkey-face[] [.small]`+emoji:monkey-face[]+`
a| emoji:monkey[] [.small]`+emoji:monkey[]+`

a| emoji:horse[] [.small]`+emoji:horse[]+`
a| emoji:racehorse[] [.small]`+emoji:racehorse[]+`
a| emoji:camel[] [.small]`+emoji:camel[]+`

a| emoji:sheep[] [.small]`+emoji:sheep[]+`
a| emoji:elephant[] [.small]`+emoji:elephant[]+`
a| emoji:panda-face[] [.small]`+emoji:panda-face[]+`

a| emoji:snake[] [.small]`+emoji:snake[]+`
a| emoji:bird[] [.small]`+emoji:bird[]+`
a| emoji:baby-chick[] [.small]`+emoji:baby-chick[]+`

a| emoji:hatched-chick[] [.small]`+emoji:hatched-chick[]+`
a| emoji:hatching-chick[] [.small]`+emoji:hatching-chick[]+`
a| emoji:chicken[] [.small]`+emoji:chicken[]+`

a| emoji:penguin[] [.small]`+emoji:penguin[]+`
a| emoji:turtle[] [.small]`+emoji:turtle[]+`
a| emoji:bug[] [.small]`+emoji:bug[]+`

a| emoji:honeybee[] [.small]`+emoji:honeybee[]+`
a| emoji:ant[] [.small]`+emoji:ant[]+`
a| emoji:beetle[] [.small]`+emoji:beetle[]+`

a| emoji:snail[] [.small]`+emoji:snail[]+`
a| emoji:octopus[] [.small]`+emoji:octopus[]+`
a| emoji:tropical-fish[] [.small]`+emoji:tropical-fish[]+`

a| emoji:fish[] [.small]`+emoji:fish[]+`
a| emoji:whale[] [.small]`+emoji:whale[]+`
a| emoji:whale2[] [.small]`+emoji:whale2[]+`

a| emoji:dolphin[] [.small]`+emoji:dolphin[]+`
a| emoji:cow2[] [.small]`+emoji:cow2[]+`
a| emoji:ram[] [.small]`+emoji:ram[]+`

a| emoji:rat[] [.small]`+emoji:rat[]+`
a| emoji:water-buffalo[] [.small]`+emoji:water-buffalo[]+`
a| emoji:tiger2[] [.small]`+emoji:tiger2[]+`

a| emoji:rabbit2[] [.small]`+emoji:rabbit2[]+`
a| emoji:dragon[] [.small]`+emoji:dragon[]+`
a| emoji:goat[] [.small]`+emoji:goat[]+`

a| emoji:rooster[] [.small]`+emoji:rooster[]+`
a| emoji:dog2[] [.small]`+emoji:dog2[]+`
a| emoji:pig2[] [.small]`+emoji:pig2[]+`

a| emoji:mouse2[] [.small]`+emoji:mouse2[]+`
a| emoji:ox[] [.small]`+emoji:ox[]+`
a| emoji:dragon-face[] [.small]`+emoji:dragon-face[]+`

a| emoji:blowfish[] [.small]`+emoji:blowfish[]+`
a| emoji:crocodile[] [.small]`+emoji:crocodile[]+`
a| emoji:dromedary-camel[] [.small]`+emoji:dromedary-camel[]+`

a| emoji:leopard[] [.small]`+emoji:leopard[]+`
a| emoji:cat2[] [.small]`+emoji:cat2[]+`
a| emoji:poodle[] [.small]`+emoji:poodle[]+`

a| emoji:paw-prints[] [.small]`+emoji:paw-prints[]+`
a| emoji:bouquet[] [.small]`+emoji:bouquet[]+`
a| emoji:cherry-blossom[] [.small]`+emoji:cherry-blossom[]+`

a| emoji:tulip[] [.small]`+emoji:tulip[]+`
a| emoji:four-leaf-clover[] [.small]`+emoji:four-leaf-clover[]+`
a| emoji:rose[] [.small]`+emoji:rose[]+`

a| emoji:sunflower[] [.small]`+emoji:sunflower[]+`
a| emoji:hibiscus[] [.small]`+emoji:hibiscus[]+`
a| emoji:maple-leaf[] [.small]`+emoji:maple-leaf[]+`

a| emoji:leaves[] [.small]`+emoji:leaves[]+`
a| emoji:fallen-leaf[] [.small]`+emoji:fallen-leaf[]+`
a| emoji:herb[] [.small]`+emoji:herb[]+`

a| emoji:mushroom[] [.small]`+emoji:mushroom[]+`
a| emoji:cactus[] [.small]`+emoji:cactus[]+`
a| emoji:palm-tree[] [.small]`+emoji:palm-tree[]+`

a| emoji:evergreen-tree[] [.small]`+emoji:evergreen-tree[]+`
a| emoji:deciduous-tree[] [.small]`+emoji:deciduous-tree[]+`
a| emoji:chestnut[] [.small]`+emoji:chestnut[]+`

a| emoji:seedling[] [.small]`+emoji:seedling[]+`
a| emoji:blossom[] [.small]`+emoji:blossom[]+`
a| emoji:ear-of-rice[] [.small]`+emoji:ear-of-rice[]+`

a| emoji:shell[] [.small]`+emoji:shell[]+`
a| emoji:globe-with-meridians[] [.small]`+emoji:globe-with-meridians[]+`
a| emoji:sun-with-face[] [.small]`+emoji:sun-with-face[]+`

a| emoji:full-moon-with-face[] [.small]`+emoji:full-moon-with-face[]+`
a| emoji:new-moon-with-face[] [.small]`+emoji:new-moon-with-face[]+`
a| emoji:new-moon[] [.small]`+emoji:new-moon[]+`

a| emoji:waxing-crescent-moon[] [.small]`+emoji:waxing-crescent-moon[]+`
a| emoji:first-quarter-moon[] [.small]`+emoji:first-quarter-moon[]+`
a| emoji:waxing-gibbous-moon[] [.small]`+emoji:waxing-gibbous-moon[]+`

a| emoji:full-moon[] [.small]`+emoji:full-moon[]+`
a| emoji:waning-gibbous-moon[] [.small]`+emoji:waning-gibbous-moon[]+`
a| emoji:last-quarter-moon[] [.small]`+emoji:last-quarter-moon[]+`

a| emoji:waning-crescent-moon[] [.small]`+emoji:waning-crescent-moon[]+`
a| emoji:last-quarter-moon-with-face[] [.small]`+emoji:last-quarter-moon-with-face[]+`
a| emoji:first-quarter-moon-with-face[] [.small]`+emoji:first-quarter-moon-with-face[]+`

a| emoji:moon[] [.small]`+emoji:moon[]+`
a| emoji:earth-africa[] [.small]`+emoji:earth-africa[]+`
a| emoji:earth-americas[] [.small]`+emoji:earth-americas[]+`

a| emoji:earth-asia[] [.small]`+emoji:earth-asia[]+`
a| emoji:volcano[] [.small]`+emoji:volcano[]+`
a| emoji:milky-way[] [.small]`+emoji:milky-way[]+`

a| emoji:partly-sunny[] [.small]`+emoji:partly-sunny[]+`
a| emoji:bamboo[] [.small]`+emoji:bamboo[]+`
a| emoji:gift-heart[] [.small]`+emoji:gift-heart[]+`

a| emoji:dolls[] [.small]`+emoji:dolls[]+`
a| emoji:school-satchel[] [.small]`+emoji:school-satchel[]+`
a| emoji:mortar-board[] [.small]`+emoji:mortar-board[]+`

a| emoji:flags[] [.small]`+emoji:flags[]+`
a| emoji:fireworks[] [.small]`+emoji:fireworks[]+`
a| emoji:sparkler[] [.small]`+emoji:sparkler[]+`

a| emoji:wind-chime[] [.small]`+emoji:wind-chime[]+`
a| emoji:rice-scene[] [.small]`+emoji:rice-scene[]+`
a| emoji:jack-o-lantern[] [.small]`+emoji:jack-o-lantern[]+`

a| emoji:ghost[] [.small]`+emoji:ghost[]+`
a| emoji:santa[] [.small]`+emoji:santa[]+`
a| emoji:8ball[] [.small]`+emoji:8ball[]+`

a| emoji:alarm-clock[] [.small]`+emoji:alarm-clock[]+`
a| emoji:apple[] [.small]`+emoji:apple[]+`
a| emoji:art[] [.small]`+emoji:art[]+`

a| emoji:baby-bottle[] [.small]`+emoji:baby-bottle[]+`
a| emoji:balloon[] [.small]`+emoji:balloon[]+`
a| emoji:banana[] [.small]`+emoji:banana[]+`

a| emoji:bar-chart[] [.small]`+emoji:bar-chart[]+`
a| emoji:baseball[] [.small]`+emoji:baseball[]+`
a| emoji:basketball[] [.small]`+emoji:basketball[]+`

a| emoji:bath[] [.small]`+emoji:bath[]+`
a| emoji:bathtub[] [.small]`+emoji:bathtub[]+`
a| emoji:battery[] [.small]`+emoji:battery[]+`

a| emoji:beer[] [.small]`+emoji:beer[]+`
a| emoji:beers[] [.small]`+emoji:beers[]+`
a| emoji:bell[] [.small]`+emoji:bell[]+`

a| emoji:bento[] [.small]`+emoji:bento[]+`
a| emoji:bicyclist[] [.small]`+emoji:bicyclist[]+`
a| emoji:bikini[] [.small]`+emoji:bikini[]+`

a| emoji:birthday[] [.small]`+emoji:birthday[]+`
a| emoji:black-joker[] [.small]`+emoji:black-joker[]+`
a| emoji:black-nib[] [.small]`+emoji:black-nib[]+`

a| emoji:blue-book[] [.small]`+emoji:blue-book[]+`
a| emoji:bomb[] [.small]`+emoji:bomb[]+`
a| emoji:bookmark[] [.small]`+emoji:bookmark[]+`

a| emoji:bookmark-tabs[] [.small]`+emoji:bookmark-tabs[]+`
a| emoji:books[] [.small]`+emoji:books[]+`
a| emoji:boot[] [.small]`+emoji:boot[]+`

a| emoji:bowling[] [.small]`+emoji:bowling[]+`
a| emoji:bread[] [.small]`+emoji:bread[]+`
a| emoji:briefcase[] [.small]`+emoji:briefcase[]+`

a| emoji:bulb[] [.small]`+emoji:bulb[]+`
a| emoji:cake[] [.small]`+emoji:cake[]+`
a| emoji:calendar[] [.small]`+emoji:calendar[]+`

a| emoji:calling[] [.small]`+emoji:calling[]+`
a| emoji:camera[] [.small]`+emoji:camera[]+`
a| emoji:candy[] [.small]`+emoji:candy[]+`

a| emoji:card-index[] [.small]`+emoji:card-index[]+`
a| emoji:cd[] [.small]`+emoji:cd[]+`
a| emoji:chart-with-downwards-trend[] [.small]`+emoji:chart-with-downwards-trend[]+`

a| emoji:chart-with-upwards-trend[] [.small]`+emoji:chart-with-upwards-trend[]+`
a| emoji:cherries[] [.small]`+emoji:cherries[]+`
a| emoji:chocolate-bar[] [.small]`+emoji:chocolate-bar[]+`

a| emoji:christmas-tree[] [.small]`+emoji:christmas-tree[]+`
a| emoji:clapper[] [.small]`+emoji:clapper[]+`
a| emoji:clipboard[] [.small]`+emoji:clipboard[]+`

a| emoji:closed-book[] [.small]`+emoji:closed-book[]+`
a| emoji:closed-lock-with-key[] [.small]`+emoji:closed-lock-with-key[]+`
a| emoji:closed-umbrella[] [.small]`+emoji:closed-umbrella[]+`

a| emoji:clubs[] [.small]`+emoji:clubs[]+`
a| emoji:cocktail[] [.small]`+emoji:cocktail[]+`
a| emoji:coffee[] [.small]`+emoji:coffee[]+`

a| emoji:computer[] [.small]`+emoji:computer[]+`
a| emoji:confetti-ball[] [.small]`+emoji:confetti-ball[]+`
a| emoji:cookie[] [.small]`+emoji:cookie[]+`

a| emoji:corn[] [.small]`+emoji:corn[]+`
a| emoji:credit-card[] [.small]`+emoji:credit-card[]+`
a| emoji:crown[] [.small]`+emoji:crown[]+`

a| emoji:crystal-ball[] [.small]`+emoji:crystal-ball[]+`
a| emoji:curry[] [.small]`+emoji:curry[]+`
a| emoji:custard[] [.small]`+emoji:custard[]+`

a| emoji:dango[] [.small]`+emoji:dango[]+`
a| emoji:dart[] [.small]`+emoji:dart[]+`
a| emoji:date[] [.small]`+emoji:date[]+`

a| emoji:diamonds[] [.small]`+emoji:diamonds[]+`
a| emoji:dollar[] [.small]`+emoji:dollar[]+`
a| emoji:door[] [.small]`+emoji:door[]+`

a| emoji:doughnut[] [.small]`+emoji:doughnut[]+`
a| emoji:dress[] [.small]`+emoji:dress[]+`
a| emoji:dvd[] [.small]`+emoji:dvd[]+`

a| emoji:e-mail[] [.small]`+emoji:e-mail[]+`
a| emoji:egg[] [.small]`+emoji:egg[]+`
a| emoji:eggplant[] [.small]`+emoji:eggplant[]+`

a| emoji:electric-plug[] [.small]`+emoji:electric-plug[]+`
a| emoji:email[] [.small]`+emoji:email[]+`
a| emoji:euro[] [.small]`+emoji:euro[]+`

a| emoji:eyeglasses[] [.small]`+emoji:eyeglasses[]+`
a| emoji:fax[] [.small]`+emoji:fax[]+`
a| emoji:file-folder[] [.small]`+emoji:file-folder[]+`

a| emoji:fish-cake[] [.small]`+emoji:fish-cake[]+`
a| emoji:fishing-pole-and-fish[] [.small]`+emoji:fishing-pole-and-fish[]+`
a| emoji:flashlight[] [.small]`+emoji:flashlight[]+`

a| emoji:floppy-disk[] [.small]`+emoji:floppy-disk[]+`
a| emoji:flower-playing-cards[] [.small]`+emoji:flower-playing-cards[]+`
a| emoji:football[] [.small]`+emoji:football[]+`

a| emoji:fork-and-knife[] [.small]`+emoji:fork-and-knife[]+`
a| emoji:fried-shrimp[] [.small]`+emoji:fried-shrimp[]+`
a| emoji:fries[] [.small]`+emoji:fries[]+`

a| emoji:game-die[] [.small]`+emoji:game-die[]+`
a| emoji:gem[] [.small]`+emoji:gem[]+`
a| emoji:gift[] [.small]`+emoji:gift[]+`

a| emoji:golf[] [.small]`+emoji:golf[]+`
a| emoji:grapes[] [.small]`+emoji:grapes[]+`
a| emoji:green-apple[] [.small]`+emoji:green-apple[]+`

a| emoji:green-book[] [.small]`+emoji:green-book[]+`
a| emoji:guitar[] [.small]`+emoji:guitar[]+`
a| emoji:gun[] [.small]`+emoji:gun[]+`

a| emoji:hamburger[] [.small]`+emoji:hamburger[]+`
a| emoji:hammer[] [.small]`+emoji:hammer[]+`
a| emoji:handbag[] [.small]`+emoji:handbag[]+`

a| emoji:headphones[] [.small]`+emoji:headphones[]+`
a| emoji:hearts[] [.small]`+emoji:hearts[]+`
a| emoji:high-brightness[] [.small]`+emoji:high-brightness[]+`

a| emoji:high-heel[] [.small]`+emoji:high-heel[]+`
a| emoji:hocho[] [.small]`+emoji:hocho[]+`
a| emoji:honey-pot[] [.small]`+emoji:honey-pot[]+`

a| emoji:horse-racing[] [.small]`+emoji:horse-racing[]+`
a| emoji:hourglass[] [.small]`+emoji:hourglass[]+`
a| emoji:hourglass-flowing-sand[] [.small]`+emoji:hourglass-flowing-sand[]+`

a| emoji:ice-cream[] [.small]`+emoji:ice-cream[]+`
a| emoji:icecream[] [.small]`+emoji:icecream[]+`
a| inbox-tray[] [.small]`+emoji:inbox-tray[]+`

a| emoji:incoming-envelope[] [.small]`+emoji:incoming-envelope[]+`
a| emoji:iphone[] [.small]`+emoji:iphone[]+`
a| emoji:jeans[] [.small]`+emoji:jeans[]+`

a| emoji:key[] [.small]`+emoji:key[]+`
a| emoji:kimono[] [.small]`+emoji:kimono[]+`
a| emoji:ledger[] [.small]`+emoji:ledger[]+`

a| emoji:lemon[] [.small]`+emoji:lemon[]+`
a| emoji:lipstick[] [.small]`+emoji:lipstick[]+`
a| emoji:lock[] [.small]`+emoji:lock[]+`

a| emoji:lock-with-ink-pen[] [.small]`+emoji:lock-with-ink-pen[]+`
a| emoji:lollipop[] [.small]`+emoji:lollipop[]+`
a| emoji:loop[] [.small]`+emoji:loop[]+`

a| emoji:loudspeaker[] [.small]`+emoji:loudspeaker[]+`
a| emoji:low-brightness[] [.small]`+emoji:low-brightness[]+`
a| emoji:mag[] [.small]`+emoji:mag[]+`

a| emoji:mag-right[] [.small]`+emoji:mag-right[]+`
a| emoji:mahjong[] [.small]`+emoji:mahjong[]+`
a| emoji:mailbox[] [.small]`+emoji:mailbox[]+`

a| emoji:mailbox-closed[] [.small]`+emoji:mailbox-closed[]+`
a| emoji:mailbox-with-mail[] [.small]`+emoji:mailbox-with-mail[]+`
a| emoji:mailbox-with-no-mail[] [.small]`+emoji:mailbox-with-no-mail[]+`

a| emoji:mans-shoe[] [.small]`+emoji:mans-shoe[]+`
a| emoji:meat-on-bone[] [.small]`+emoji:meat-on-bone[]+`
a| emoji:mega[] [.small]`+emoji:mega[]+`

a| emoji:melon[] [.small]`+emoji:melon[]+`
a| +emoji:memo[] [.small]`+emoji:memo[]+`
a| emoji:microphone[] [.small]`+emoji:microphone[]+`

a| emoji:microscope[] [.small]`+emoji:microscope[]+`
a| emoji:minidisc[] [.small]`+emoji:minidisc[]+`
a| emoji:money-with-wings[] [.small]`+emoji:money-with-wings[]+`

a| emoji:moneybag[] [.small]`+emoji:moneybag[]+`
a| emoji:mountain-bicyclist[] [.small]`+emoji:mountain-bicyclist[]+`
a| emoji:movie-camera[] [.small]`+emoji:movie-camera[]+`

a| emoji:musical-keyboard[] [.small]`+emoji:musical-keyboard[]+`
a| emoji:musical-score[] [.small]`+emoji:musical-score[]+`
a| emoji:mute[] [.small]`+emoji:mute[]+`

a| emoji:name-badge[] [.small]`+emoji:name-badge[]+`
a| emoji:necktie[] [.small]`+emoji:necktie[]+`
a| emoji:newspaper[] [.small]`+emoji:newspaper[]+`

a| emoji:no-bell[] [.small]`+emoji:no-bell[]+`
a| emoji:notebook[] [.small]`+emoji:notebook[]+`
a| emoji:notebook-with-decorative-cover[] [.small]`+emoji:notebook-with-decorative-cover[]+`

a| emoji:nut-and-bolt[] [.small]`+emoji:nut-and-bolt[]+`
a| emoji:oden[] [.small]`+emoji:oden[]+`
a| emoji:open-file-folder[] [.small]`+emoji:open-file-folder[]+`

a| emoji:orange-book[] [.small]`+emoji:orange-book[]+`
a| emoji:outbox-tray[] [.small]`+emoji:outbox-tray[]+`
a| emoji:page-facing-up[] [.small]`+emoji:page-facing-up[]+`

a| emoji:page-with-curl[] [.small]`+emoji:page-with-curl[]+`
a| emoji:pager[] [.small]`+emoji:pager[]+`
a| emoji:paperclip[] [.small]`+emoji:paperclip[]+`

a| emoji:peach[] [.small]`+emoji:peach[]+`
a| emoji:pear[] [.small]`+emoji:pear[]+`
a| emoji:pencil2[] [.small]`+emoji:pencil2[]+`

a| emoji:phone[] [.small]`+emoji:phone[]+`
a| emoji:pill[] [.small]`+emoji:pill[]+`
a| emoji:pineapple[] [.small]`+emoji:pineapple[]+`

a| emoji:pizza[] [.small]`+emoji:pizza[]+`
a| emoji:postal-horn[] [.small]`+emoji:postal-horn[]+`
a| emoji:postbox[] [.small]`+emoji:postbox[]+`

a| emoji:pouch[] [.small]`+emoji:pouch[]+`
a| emoji:poultry-leg[] [.small]`+emoji:poultry-leg[]+`
a| emoji:pound[] [.small]`+emoji:pound[]+`

a| emoji:purse[] [.small]`+emoji:purse[]+`
a| emoji:pushpin[] [.small]`+emoji:pushpin[]+`
a| emoji:radio[] [.small]`+emoji:radio[]+`

a| emoji:ramen[] [.small]`+emoji:ramen[]+`
a| emoji:ribbon[] [.small]`+emoji:ribbon[]+`
a| emoji:rice[] [.small]`+emoji:rice[]+`

a| emoji:rice-ball[] [.small]`+emoji:rice-ball[]+`
a| emoji:rice-cracker[] [.small]`+emoji:rice-cracker[]+`
a| emoji:ring[] [.small]`+emoji:ring[]+`

a| emoji:rugby-football[] [.small]`+emoji:rugby-football[]+`
a| emoji:running-shirt-with-sash[] [.small]`+emoji:running-shirt-with-sash[]+`
a| emoji:sake[] [.small]`+emoji:sake[]+`

a| emoji:sandal[] [.small]`+emoji:sandal[]+`
a| emoji:satellite[] [.small]`+emoji:satellite[]+`
a| emoji:saxophone[] [.small]`+emoji:saxophone[]+`

a| emoji:scissors[] [.small]`+emoji:scissors[]+`
a| emoji:scroll[] [.small]`+emoji:scroll[]+`
a| emoji:seat[] [.small]`+emoji:seat[]+`

a| emoji:shaved-ice[] [.small]`+emoji:shaved-ice[]+`
a| emoji:shirt[] [.small]`+emoji:shirt[]+`
a| emoji:shower[] [.small]`+emoji:shower[]+`

a| emoji:ski[] [.small]`+emoji:ski[]+`
a| emoji:smoking[] [.small]`+emoji:smoking[]+`
a| emoji:snowboarder[] [.small]`+emoji:snowboarder[]+`

a| emoji:soccer[] [.small]`+emoji:soccer[]+`
a| emoji:sound[] [.small]`+emoji:sound[]+`
a| emoji:space-invader[] [.small]`+emoji:space-invader[]+`

a| emoji:spades[] [.small]`+emoji:spades[]+`
a| emoji:spaghetti[] [.small]`+emoji:spaghetti[]+`
a| emoji:speaker[] [.small]`+emoji:speaker[]+`

a| emoji:stew[] [.small]`+emoji:stew[]+`
a| emoji:straight-ruler[] [.small]`+emoji:straight-ruler[]+`
a| emoji:strawberry[] [.small]`+emoji:strawberry[]+`

a| emoji:surfer[] [.small]`+emoji:surfer[]+`
a| emoji:sushi[] [.small]`+emoji:sushi[]+`
a| emoji:sweet-potato[] [.small]`+emoji:sweet-potato[]+`

a| emoji:swimmer[] [.small]`+emoji:swimmer[]+`
a| emoji:syringe[] [.small]`+emoji:syringe[]+`
a| emoji:tada[] [.small]`+emoji:tada[]+`

a| emoji:tanabata-tree[] [.small]`+emoji:tanabata-tree[]+`
a| emoji:tangerine [.small]`+emoji:tangerine[]+`
a| emoji:tea[] [.small]`+emoji:tea[]+`

a| emoji:telephone-receiver[] [.small]`+emoji:telephone-receiver[]+`
a| emoji:telescope[] [.small]`+emoji:telescope[]+`
a| emoji:tennis[] [.small]`+emoji:tennis[]+`

a| emoji:toilet[] [.small]`+emoji:toilet[]+`
a| emoji:tomato[] [.small]`+emoji:tomato[]+`
a| emoji:tophat[] [.small]`+emoji:tophat[]+`

a| emoji:triangular-ruler[] [.small]`+emoji:triangular-ruler[]+`
a| emoji:trophy[] [.small]`+emoji:trophy[]+`
a| emoji:tropical-drink[] [.small]`+emoji:tropical-drink[]+`

a| emoji:trumpet[] [.small]`+emoji:trumpet[]+`
a| emoji:tv[] [.small]`+emoji:tv[]+`
a| emoji:unlock[] [.small]`+emoji:unlock[]+`

a| emoji:vhs[] [.small]`+emoji:vhs[]+`
a| emoji:video-camera[] [.small]`+emoji:video-camera[]+`
a| emoji:video-game[] [.small]`+emoji:video-game[]+`

a| emoji:violin[] [.small]`+emoji:violin[]+`
a| emoji:watch[] [.small]`+emoji:watch[]+`
a| emoji:watermelon[] [.small]`+emoji:watermelon[]+`

a| emoji:wine-glass[] [.small]`+emoji:wine-glass[]+`
a| emoji:womans-clothes[] [.small]`+emoji:womans-clothes[]+`
a| emoji:womans-hat[] [.small]`+emoji:womans-hat[]+`

a| emoji:wrench[] [.small]`+emoji:wrench[]+`
a| emoji:yen[] [.small]`+emoji:yen[]+`
a| emoji:aerial-tramway[] [.small]`+emoji:aerial-tramway[]+`

a| emoji:airplane[] [.small]`+emoji:airplane[]+`
a| emoji:ambulance[] [.small]`+emoji:ambulance[]+`
a| emoji:anchor[] [.small]`+emoji:anchor[]+`

a| emoji:articulated-lorry[] [.small]`+emoji:articulated-lorry[]+`
a| emoji:atm[] [.small]`+emoji:atm[]+`
a| emoji:bank[] [.small]`+emoji:bank[]+`

a| emoji:barber[] [.small]`+emoji:barber[]+`
a| emoji:beginner[] [.small]`+emoji:beginner[]+`
a| emoji:bike[] [.small]`+emoji:bike[]+`

a| emoji:blue-car[] [.small]`+emoji:blue-car[]+`
a| emoji:boat[] [.small]`+emoji:boat[]+`
a| emoji:bridge-at-night[] [.small]`+emoji:bridge-at-night[]+`

a| emoji:bullettrain-front[] [.small]`+emoji:bullettrain-front[]+`
a| emoji:bullettrain-side[] [.small]`+emoji:bullettrain-side[]+`
a| emoji:bus[] [.small]`+emoji:bus[]+`

a| emoji:busstop[] [.small]`+emoji:busstop[]+`
a| emoji:car[] [.small]`+emoji:car[]+`
a| emoji:carousel-horse[] [.small]`+emoji:carousel-horse[]+`

a| emoji:checkered-flag[] [.small]`+emoji:checkered-flag[]+`
a| emoji:church[] [.small]`+emoji:church[]+`
a| emoji:circus-tent[] [.small]`+emoji:circus-tent[]+`

a| emoji:city-sunrise[] [.small]`+emoji:city-sunrise[]+`
a| emoji:city-sunset[] [.small]`+emoji:city-sunset[]+`
a| emoji:construction[] [.small]`+emoji:construction[]+`

a| emoji:convenience-store[] [.small]`+emoji:convenience-store[]+`
a| emoji:crossed-flags[] [.small]`+emoji:crossed-flags[]+`
a| emoji:department-store[] [.small]`+emoji:department-store[]+`

a| emoji:european-castle[] [.small]`+emoji:european-castle[]+`
a| emoji:european-post-office[] [.small]`+emoji:european-post-office[]+`
a| emoji:factory[] [.small]`+emoji:factory[]+`

a| emoji:ferris-wheel[] [.small]`+emoji:ferris-wheel[]+`
a| emoji:fire-engine[] [.small]`+emoji:fire-engine[]+`
a| emoji:fountain[] [.small]`+emoji:fountain[]+`

a| emoji:fuelpump[] [.small]`+emoji:fuelpump[]+`
a| emoji:helicopter[] [.small]`+emoji:helicopter[]+`
a| emoji:hospital[] [.small]`+emoji:hospital[]+`

a| emoji:hotel[] [.small]`+emoji:hotel[]+`
a| emoji:hotsprings[] [.small]`+emoji:hotsprings[]+`
a| emoji:house[] [.small]`+emoji:house[]+`

a| emoji:house-with-garden[] [.small]`+emoji:house-with-garden[]+`
a| emoji:japan[] [.small]`+emoji:japan[]+`
a| emoji:japanese-castle[] [.small]`+emoji:japanese-castle[]+`

a| emoji:light-rail[] [.small]`+emoji:light-rail[]+`
a| emoji:love-hotel[] [.small]`+emoji:love-hotel[]+`
a| emoji:minibus[] [.small]`+emoji:minibus[]+`

a| emoji:monorail[] [.small]`+emoji:monorail[]+`
a| emoji:mount-fuji[] [.small]`+emoji:mount-fuji[]+`
a| emoji:mountain-cableway[] [.small]`+emoji:mountain-cableway[]+`

a| emoji:mountain-railway[] [.small]`+emoji:mountain-railway[]+`
a| emoji:moyai[] [.small]`+emoji:moyai[]+`
a| emoji:office[] [.small]`+emoji:office[]+`

a| emoji:oncoming-automobile[] [.small]`+emoji:oncoming-automobile[]+`
a| emoji:oncoming-bus[] [.small]`+emoji:oncoming-bus[]+`
a| emoji:oncoming-police-car[] [.small]`+emoji:oncoming-police-car[]+`

a| emoji:oncoming-taxi[] [.small]`+emoji:oncoming-taxi[]+`
a| emoji:performing-arts[] [.small]`+emoji:performing-arts[]+`
a| emoji:police-car[] [.small]`+emoji:police-car[]+`

a| emoji:post-office[] [.small]`+emoji:post-office[]+`
a| emoji:railway-car[] [.small]`+emoji:railway-car[]+`
a| emoji:rainbow[] [.small]`+emoji:rainbow[]+`

a| emoji:rocket[] [.small]`+emoji:rocket[]+`
a| emoji:roller-coaster[] [.small]`+emoji:roller-coaster[]+`
a| emoji:rotating-light[] [.small]`+emoji:rotating-light[]+`

a| emoji:round-pushpin[] [.small]`+emoji:round-pushpin[]+`
a| emoji:rowboat[] [.small]`+emoji:rowboat[]+`
a| emoji:school[] [.small]`+emoji:school[]+`

a| emoji:ship[] [.small]`+emoji:ship[]+`
a| emoji:slot-machine[] [.small]`+emoji:slot-machine[]+`
a| emoji:speedboat[] [.small]`+emoji:speedboat[]+`

a| emoji:stars[] [.small]`+emoji:stars[]+`
a| emoji:station[] [.small]`+emoji:station[]+`
a| emoji:statue-of-liberty[] [.small]`+emoji:statue-of-liberty[]+`

a| emoji:steam-locomotive[] [.small]`+emoji:steam-locomotive[]+`
a| emoji:sunrise[] [.small]`+emoji:sunrise[]+`
a| emoji:sunrise-over-mountains[] [.small]`+emoji:sunrise-over-mountains[]+`

a| emoji:suspension-railway[] [.small]`+emoji:suspension-railway[]+`
a| emoji:taxi[] [.small]`+emoji:taxi[]+`
a| emoji:tent[] [.small]`+emoji:tent[]+`

a| emoji:ticket[] [.small]`+emoji:ticket[]+`
a| emoji:tokyo-tower[] [.small]`+emoji:tokyo-tower[]+`
a| emoji:tractor[] [.small]`+emoji:tractor[]+`

a| emoji:traffic-light[] [.small]`+emoji:traffic-light[]+`
a| emoji:train2[] [.small]`+emoji:train2[]+`
a| emoji:tram[] [.small]`+emoji:tram[]+`

a| emoji:triangular-flag-on-post[] [.small]`+emoji:triangular-flag-on-post[]+`
a| emoji:trolleybus[] [.small]`+emoji:trolleybus[]+`
a| emoji:truck[] [.small]`+emoji:truck[]+`

a| emoji:vertical-traffic-light[] [.small]`+emoji:vertical-traffic-light[]+`
a| emoji:warning[] [.small]`+emoji:warning[]+`
a| emoji:wedding[] [.small]`+emoji:wedding[]+`

a| emoji:jp[] [.small]`+emoji:jp[]+`
a| emoji:kr[] [.small]`+emoji:kr[]+`
a| emoji:cn[] [.small]`+emoji:cn[]+`

a| emoji:us[] [.small]`+emoji:us[]+`
a| emoji:fr[] [.small]`+emoji:fr[]+`
a| emoji:es[] [.small]`+emoji:es[]+`

a| emoji:it[] [.small]`+emoji:it[]+`
a| emoji:ru[] [.small]`+emoji:ru[]+`
a| emoji:gb[] [.small]`+emoji:gb[]+`

a| emoji:de[] [.small]`+emoji:de[]+`
a| emoji:100[] [.small]`+emoji:100[]+`
a| emoji:1234[] [.small]`+emoji:1234[]+`

a| emoji:a[] [.small]`+emoji:a[]+`
a| emoji:ab[] [.small]`+emoji:ab[]+`
a| emoji:abc[] [.small]`+emoji:abc[]+`

a| emoji:abcd[] [.small]`+emoji:abcd[]+`
a| emoji:accept[] [.small]`+emoji:accept[]+`
a| emoji:aquarius[] [.small]`+emoji:aquarius[]+`

a| emoji:aries[] [.small]`+emoji:aries[]+`
a| emoji:arrow-backward[] [.small]`+emoji:arrow-backward[]+`
a| emoji:arrow-double-down[] [.small]`+emoji:arrow-double-down[]+`

a| emoji:arrow-double-up[] [.small]`+emoji:arrow-double-up[]+`
a| emoji:arrow-down[] [.small]`+emoji:arrow-down[]+`
a| emoji:arrow-down-small[] [.small]`+emoji:arrow-down-small[]+`

a| emoji:arrow-forward[] [.small]`+emoji:arrow-forward[]+`
a| emoji:arrow-heading-down[] [.small]`+emoji:arrow-heading-down[]+`
a| emoji:arrow-heading-up[] [.small]`+emoji:arrow-heading-up[]+`

a| emoji:arrow-left[] [.small]`+emoji:arrow-left[]+`
a| emoji:arrow-lower-left[] [.small]`+emoji:arrow-lower-left[]+`
a| emoji:arrow-lower-right[] [.small]`+emoji:arrow-lower-right[]+`

a| emoji:arrow-right[] [.small]`+emoji:arrow-right[]+`
a| emoji:arrow-right-hook[] [.small]`+emoji:arrow-right-hook[]+`
a| emoji:arrow-up[] [.small]`+emoji:arrow-up[]+`

a| emoji:arrow-up-down[] [.small]`+emoji:arrow-up-down[]+`
a| emoji:arrow-up-small[] [.small]`+emoji:arrow-up-small[]+`
a| emoji:arrow-upper-left[] [.small]`+emoji:arrow-upper-left[]+`

a| emoji:arrow-upper-right[] [.small]`+emoji:arrow-upper-right[]+`
a| emoji:arrows-clockwise[] [.small]`+emoji:arrows-clockwise[]+`
a| emoji:arrows-counterclockwise[] [.small]`+emoji:arrows-counterclockwise[]+`

a| emoji:b[] [.small]`+emoji:b[]+`
a| emoji:baby-symbol[] [.small]`+emoji:baby-symbol[]+`
a| emoji:baggage-claim[] [.small]`+emoji:baggage-claim[]+`

a| emoji:ballot-box-with-check[] [.small]`+emoji:ballot-box-with-check[]+`
a| emoji:bangbang[] [.small]`+emoji:bangbang[]+`
a| emoji:black-circle[] [.small]`+emoji:black-circle[]+`

a| emoji:black-square-button[] [.small]`+emoji:black-square-button[]+`
a| emoji:cancer[] [.small]`+emoji:cancer[]+`
a| emoji:capital-abcd[] [.small]`+emoji:capital-abcd[]+`

a| emoji:capricorn[] [.small]`+emoji:capricorn[]+`
a| emoji:chart[] [.small]`+emoji:chart[]+`
a| emoji:children-crossing[] [.small]`+emoji:children-crossing[]+`

a| emoji:cinema[] [.small]`+emoji:cinema[]+`
a| emoji:cl[] [.small]`+emoji:cl[]+`
a| emoji:clock1[] [.small]`+emoji:clock1[]+`

a| emoji:clock10[] [.small]`+emoji:clock10[]+`
a| emoji:clock1030[] [.small]`+emoji:clock1030[]+`
a| emoji:clock11[] [.small]`+emoji:clock11[]+`

a| emoji:clock1130[] [.small]`+emoji:clock1130[]+`
a| emoji:clock12[] [.small]`+emoji:clock12[]+`
a| emoji:clock1230[] [.small]`+emoji:clock1230[]+`

a| emoji:clock130[] [.small]`+emoji:clock130[]+`
a| emoji:clock2[] [.small]`+emoji:clock2[]+`
a| emoji:clock230[] [.small]`+emoji:clock230[]+`

a| emoji:clock3[] [.small]`+emoji:clock3[]+`
a| emoji:clock330[] [.small]`+emoji:clock330[]+`
a| emoji:clock4[] [.small]`+emoji:clock4[]+`

a| emoji:clock430[] [.small]`+emoji:clock430[]+`
a| emoji:clock5[] [.small]`+emoji:clock5[]+`
a| emoji:clock530[] [.small]`+emoji:clock530[]+`

a| emoji:clock6[] [.small]`+emoji:clock6[]+`
a| emoji:clock630[] [.small]`+emoji:clock630[]+`
a| emoji:clock7[] [.small]`+emoji:clock7[]+`

a| emoji:clock730[] [.small]`+emoji:clock730[]+`
a| emoji:clock8[] [.small]`+emoji:clock8[]+`
a| emoji:clock830[] [.small]`+emoji:clock830[]+`

a| emoji:clock9[] [.small]`+emoji:clock9[]+`
a| emoji:clock930[] [.small]`+emoji:clock930[]+`
a| emoji:congratulations[] [.small]`+emoji:congratulations[]+`

a| emoji:cool[] [.small]`+emoji:cool[]+`
a| emoji:copyright[] [.small]`+emoji:copyright[]+`
a| emoji:curly-loop[] [.small]`+emoji:curly-loop[]+`

a| emoji:currency-exchange[] [.small]`+emoji:currency-exchange[]+`
a| emoji:customs[] [.small]`+emoji:customs[]+`
a| emoji:diamond-shape-with-a-dot-inside[] [.small]`+emoji:diamond-shape-with-a-dot-inside[]+`

a| emoji:do-not-litter[] [.small]`+emoji:do-not-litter[]+`
a| emoji:eight[] [.small]`+emoji:eight[]+`
a| emoji:eight-pointed-black-star[] [.small]`+emoji:eight-pointed-black-star[]+`

a| emoji:eight-spoked-asterisk[] [.small]`+emoji:eight-spoked-asterisk[]+`
a| emoji:end[] [.small]`+emoji:end[]+`
a| emoji:fast-forward[] [.small]`+emoji:fast-forward[]+`

a| emoji:five[] [.small]`+emoji:five[]+`
a| emoji:four[] [.small]`+emoji:four[]+`
a| emoji:free[] [.small]`+emoji:free[]+`

a| emoji:gemini[] [.small]`+emoji:gemini[]+`
a| emoji:hash[] [.small]`+emoji:hash[]+`
a| emoji:heart-decoration[] [.small]`+emoji:heart-decoration[]+`

a| emoji:heavy-check-mark[] [.small]`+emoji:heavy-check-mark[]+`
a| emoji:heavy-division-sign[] [.small]`+emoji:heavy-division-sign[]+`
a| emoji:heavy-dollar-sign[] [.small]`+emoji:heavy-dollar-sign[]+`

a| emoji:heavy-minus-sign[] [.small]`+emoji:heavy-minus-sign[]+`
a| emoji:heavy-multiplication-x[] [.small]`+emoji:heavy-multiplication-x[]+`
a| emoji:heavy-plus-sign[] [.small]`+emoji:heavy-plus-sign[]+`

a| emoji:id[] [.small]`+emoji:id[]+`
a| emoji:ideograph-advantage[] [.small]`+emoji:ideograph-advantage[]+`
a| emoji:information-source[] [.small]`+emoji:information-source[]+`

a| emoji:interrobang[] [.small]`+emoji:interrobang[]+`
a| emoji:keycap-ten[] [.small]`+emoji:keycap-ten[]+`
a| emoji:koko[] [.small]`+emoji:koko[]+`

a| [.small]`+emoji:large-blue-circle[]+`
a| [.small]`+emoji:large-blue-diamond[]+`
a| [.small]`+emoji:large-orange-diamond[]+`

a| [.small]`+emoji:left-luggage[]+`
a| [.small]`+emoji:left-right-arrow[]+`
a| [.small]`+emoji:leftwards-arrow-with-hook[]+`

a| [.small]`+emoji:leo[]+`
a| [.small]`+emoji:libra[]+`
a| [.small]`+emoji:link[]+`

a| [.small]`+emoji:m[]+`
a| [.small]`+emoji:mens[]+`
a| [.small]`+emoji:metro[]+`

a| [.small]`+emoji:mobile-phone-off[]+`
a| [.small]`+emoji:negative-squared-cross-mark[]+`
a| [.small]`+emoji:new[]+`

a| [.small]`+emoji:ng[]+`
a| [.small]`+emoji:nine[]+`
a| [.small]`+emoji:no-bicycles[]+`

a| [.small]`+emoji:no-entry[]+`
a| [.small]`+emoji:no-entry-sign[]+`
a| [.small]`+emoji:no-mobile-phones[]+`

a| [.small]`+emoji:no-pedestrians[]+`
a| [.small]`+emoji:no-smoking[]+`
a| [.small]`+emoji:non-potable-water[]+`

a| [.small]`+emoji:o[]+`
a| [.small]`+emoji:o2[]+`
a| [.small]`+emoji:ok[]+`

a| [.small]`+emoji:on[]+`
a| [.small]`+emoji:one[]+`
a| [.small]`+emoji:ophiuchus[]+`

a| [.small]`+emoji:parking[]+`
a| [.small]`+emoji:part-alternation-mark[]+`
a| [.small]`+emoji:passport-control[]+`

a| [.small]`+emoji:pisces[]+`
a| [.small]`+emoji:potable-water[]+`
a| [.small]`+emoji:put-litter-in-its-place[]+`

a| [.small]`+emoji:radio-button[]+`
a| [.small]`+emoji:recycle[]+`
a| [.small]`+emoji:red-circle[]+`

a| [.small]`+emoji:registered[]+`
a| [.small]`+emoji:repeat[]+`
a| [.small]`+emoji:repeat-one[]+`

a| [.small]`+emoji:restroom[]+`
a| [.small]`+emoji:rewind[]+`
a| [.small]`+emoji:sa[]+`

a| [.small]`+emoji:sagittarius[]+`
a| [.small]`+emoji:scorpius[]+`
a| [.small]`+emoji:secret[]+`

a| [.small]`+emoji:seven[]+`
a| [.small]`+emoji:signal-strength[]+`
a| [.small]`+emoji:six[]+`

a| [.small]`+emoji:six-pointed-star[]+`
a| [.small]`+emoji:small-blue-diamond[]+`
a| [.small]`+emoji:small-orange-diamond[]+`

a| [.small]`+emoji:small-red-triangle[]+`
a| [.small]`+emoji:small-red-triangle-down[]+`
a| [.small]`+emoji:soon[]+`

a| [.small]`+emoji:sos[]+`
a| [.small]`+emoji:symbols[]+`
a| [.small]`+emoji:taurus[]+`

a| [.small]`+emoji:three[]+`
a| [.small]`+emoji:tm[]+`
a| [.small]`+emoji:top[]+`

a| [.small]`+emoji:trident[]+`
a| [.small]`+emoji:twisted-rightwards-arrows[]+`
a| [.small]`+emoji:two[]+`

a| [.small]`+emoji:u5272[]+`
a| [.small]`+emoji:u5408[]+`
a| [.small]`+emoji:u55b6[]+`

a| [.small]`+emoji:u6307[]+`
a| [.small]`+emoji:u6708[]+`
a| [.small]`+emoji:u6709[]+`

a| [.small]`+emoji:u6e80[]+`
a| [.small]`+emoji:u7121[]+`
a| [.small]`+emoji:u7533[]+`

a| [.small]`+emoji:u7981[]+`
a| [.small]`+emoji:u7a7a[]+`
a| [.small]`+emoji:underage[]+`

a| [.small]`+emoji:up[]+`
a| [.small]`+emoji:vibration-mode[]+`
a| [.small]`+emoji:virgo[]+`

a| [.small]`+emoji:vs[]+`
a| [.small]`+emoji:wavy-dash[]+`
a| [.small]`+emoji:wc[]+`

a| [.small]`+emoji:wheelchair[]+`
a| [.small]`+emoji:white-check-mark[]+`
a| [.small]`+emoji:white-circle[]+`

a| [.small]`+emoji:white-flower[]+`
a| [.small]`+emoji:white-square-button[]+`
a| [.small]`+emoji:womens[]+`

a| [.small]`+emoji:x[]+`
a| [.small]`+emoji:zero[]+`
a|
|===
