= Emoji Cheat Sheet
:author: mitm
:revnumber:
:revdate: 2019-12-18T23:24:11.262Z
:stylesheet: twemoji-awesome.css
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== How to use emoji in the wiki

Using emoji in wiki docs currently requires the setting of the `:stylesheet:` attribute in the header of the wiki document.

```
:stylesheet: twemoji-awesome.css
```
The <<wiki/wiki_header.adoc#,Anatomy of a Wiki Header>> document exlains setting of this and other header attributes.

Once the header attribute is set, you can add the emoji using the following syntax.

```
emoji:heart[2x] // the "[2x]" is a size modifier
emoji:rage[]
```

[NOTE]
====
you can change the icon size with the syntax `emoji:heart[2x]`.
====

Full list of emoji and their syntax.

[cols=4, frame=none, grid=none]
|===
a| emoji:smile[] `+emoji:smile[]+`
a| emoji:laughing[] `+emoji:laughing[]+`
a| emoji:blush[] `+emoji:blush[]+`
a| emoji:smiley[] `+emoji:smiley[]+`

a| emoji:relaxed[] `+emoji:relaxed[]+`
a| emoji:smirk[] `+emoji:smirk[]+`
a| `+emoji:heart-eyes[]+`
a| `+emoji:kissing-heart[]+`

a| `+emoji:kissing-closed-eyes[]+`
a| `+emoji:flushed[]+`
a| `+emoji:relieved[]+`
a| `+emoji:satisfied[]+`

a| `+emoji:grin[]+`
a| `+emoji:wink[]+`
a| `+emoji:stuck-out-tongue-winking-eye[]+`
a| `+emoji:stuck-out-tongue-closed-eyes[]+`

a| `+emoji:grinning[]+`
a| `+emoji:kissing[]+`
a| `+emoji:kissing-smiling-eyes[]+`
a| `+emoji:stuck-out-tongue[]+`

a| `+emoji:sleeping[]+`
a| `+emoji:worried[]+`
a| `+emoji:frowning[]+`
a| `+emoji:anguished[]+`

a| `+emoji:open-mouth[]+`
a| `+emoji:grimacing[]+`
a| `+emoji:confused[]+`
a| `+emoji:hushed[]+`

a| `+emoji:expressionless[]+`
a| `+emoji:unamused[]+`
a| `+emoji:sweat-smile[]+`
a| `+emoji:sweat[]+`

a| `+emoji:weary[]+`
a| `+emoji:pensive[]+`
a| `+emoji:disappointed[]+`
a| `+emoji:confounded[]+`

a| `+emoji:fearful[]+`
a| `+emoji:cold-sweat[]+`
a| `+emoji:persevere[]+`
a| `+emoji:cry[]+`

a| `+emoji:sob[]+`
a| `+emoji:joy[]+`
a| `+emoji:astonished[]+`
a| `+emoji:scream[]+`

a| `+emoji:tired-face[]+`
a| `+emoji:angry[]+`
a| `+emoji:rage[]+`
a| `+emoji:triumph[]+`

a| `+emoji:sleepy[]+`
a| `+emoji:yum[]+`
a| `+emoji:mask[]+`
a| `+emoji:sunglasses[]+`

a| `+emoji:dizzy-face[]+`
a| `+emoji:imp[]+`
a| `+emoji:smiling-imp[]+`
a| `+emoji:neutral-face[]+`

a| `+emoji:no-mouth[]+`
a| `+emoji:innocent[]+`
a| `+emoji:alien[]+`
a| `+emoji:yellow-heart[]+`

a| `+emoji:blue-heart[]+`
a| `+emoji:purple-heart[]+`
a| `+emoji:heart[]+`
a| `+emoji:green-heart[]+`

a| `+emoji:broken-heart[]+`
a| `+emoji:heartbeat[]+`
a| `+emoji:heartpulse[]+`
a| `+emoji:two-hearts[]+`

a| `+emoji:revolving-hearts[]+`
a| `+emoji:cupid[]+`
a| `+emoji:sparkling-heart[]+`
a| `+emoji:sparkles[]+`

a| `+emoji:star[]+`
a| `+emoji:star2[]+`
a| `+emoji:dizzy[]+`
a| `+emoji:boom[]+`

a| `+emoji:anger[]+`
a| `+emoji:exclamation[]+`
a| `+emoji:question[]+`
a| `+emoji:grey-exclamation[]+`

a| `+emoji:grey-question[]+`
a| `+emoji:zzz[]+`
a| `+emoji:dash[]+`
a| `+emoji:sweat-drops[]+`

a| `+emoji:notes[]+`
a| `+emoji:musical-note[]+`
a| `+emoji:fire[]+`
a| `+emoji:poop[]+`

a| `+emoji:thumbsup[]+`
a| `+emoji:thumbsdown[]+`
a| `+emoji:ok-hand[]+`
a| `+emoji:punch[]+`

a| `+emoji:fist[]+`
a| `+emoji:v[]+`
a| `+emoji:wave[]+`
a| `+emoji:hand[]+`

a| `+emoji:open-hands[]+`
a| `+emoji:point-up[]+`
a| `+emoji:point-down[]+`
a| `+emoji:point-left[]+`

a| `+emoji:point-right[]+`
a| `+emoji:raised-hands[]+`
a| `+emoji:pray[]+`
a| `+emoji:point-up-2[]+`

a| `+emoji:clap[]+`
a| `+emoji:muscle[]+`
a| `+emoji:walking[]+`
a| `+emoji:runner[]+`

a| `+emoji:couple[]+`
a| `+emoji:family[]+`
a| `+emoji:two-men-holding-hands[]+`
a| `+emoji:two-women-holding-hands[]+`

a| `+emoji:dancer[]+`
a| `+emoji:dancers[]+`
a| `+emoji:ok-woman[]+`
a| `+emoji:no-good[]+`

a| `+emoji:information-desk-person[]+`
a| `+emoji:raised-hand[]+`
a| `+emoji:bride-with-veil[]+`
a| `+emoji:person-with-pouting-face[]+`

a| `+emoji:person-frowning[]+`
a| `+emoji:bow[]+`
a| `+emoji:couplekiss[]+`
a| `+emoji:couple-with-heart[]+`

a| `+emoji:massage[]+`
a| `+emoji:haircut[]+`
a| `+emoji:nail-care[]+`
a| `+emoji:boy[]+`

a| `+emoji:girl[]+`
a| `+emoji:woman[]+`
a| `+emoji:man[]+`
a| `+emoji:baby[]+`

a| `+emoji:older-woman[]+`
a| `+emoji:older-man[]+`
a| `+emoji:person-with-blond-hair[]+`
a| `+emoji:man-with-gua-pi-mao[]+`

a| `+emoji:man-with-turban[]+`
a| `+emoji:construction-worker[]+`
a| `+emoji:cop[]+`
a| `+emoji:angel[]+`

a| `+emoji:princess[]+`
a| `+emoji:smiley-cat[]+`
a| `+emoji:smile-cat[]+`
a| `+emoji:heart-eyes-cat[]+`

a| `+emoji:kissing-cat[]+`
a| `+emoji:smirk-cat[]+`
a| `+emoji:scream-cat[]+`
a| `+emoji:crying-cat-face[]+`

a| `+emoji:joy-cat[]+`
a| `+emoji:pouting-cat[]+`
a| `+emoji:japanese-ogre[]+`
a| `+emoji:japanese-goblin[]+`

a| `+emoji:see-no-evil[]+`
a| `+emoji:hear-no-evil[]+`
a| `+emoji:speak-no-evil[]+`
a| `+emoji:guardsman[]+`

a| `+emoji:skull[]+`
a| `+emoji:feet[]+`
a| `+emoji:lips[]+`
a| `+emoji:kiss[]+`

a| `+emoji:droplet[]+`
a| `+emoji:ear[]+`
a| `+emoji:eyes[]+`
a| `+emoji:nose[]+`

a| `+emoji:tongue[]+`
a| `+emoji:love-letter[]+`
a| `+emoji:bust-in-silhouette[]+`
a| `+emoji:busts-in-silhouette[]+`

a| `+emoji:speech-balloon[]+`
a| `+emoji:thought-balloon[]+`
a| `+emoji:sunny[]+`
a| `+emoji:umbrella[]+`

a| `+emoji:cloud[]+`
a| `+emoji:snowflake[]+`
a| `+emoji:snowman[]+`
a| `+emoji:zap[]+`

a| `+emoji:cyclone[]+`
a| `+emoji:foggy[]+`
a| `+emoji:ocean[]+`
a| `+emoji:cat[]+`

a| `+emoji:dog[]+`
a| `+emoji:mouse[]+`
a| `+emoji:hamster[]+`
a| `+emoji:rabbit[]+`

a| `+emoji:wolf[]+`
a| `+emoji:frog[]+`
a| `+emoji:tiger[]+`
a| `+emoji:koala[]+`

a| `+emoji:bear[]+`
a| `+emoji:pig[]+`
a| `+emoji:pig-nose[]+`
a| `+emoji:cow[]+`

a| `+emoji:boar[]+`
a| `+emoji:monkey-face[]+`
a| `+emoji:monkey[]+`
a| `+emoji:horse[]+`

a| `+emoji:racehorse[]+`
a| `+emoji:camel[]+`
a| `+emoji:sheep[]+`
a| `+emoji:elephant[]+`

a| `+emoji:panda-face[]+`
a| `+emoji:snake[]+`
a| `+emoji:bird[]+`
a| `+emoji:baby-chick[]+`

a| `+emoji:hatched-chick[]+`
a| `+emoji:hatching-chick[]+`
a| `+emoji:chicken[]+`
a| `+emoji:penguin[]+`

a| `+emoji:turtle[]+`
a| `+emoji:bug[]+`
a| `+emoji:honeybee[]+`
a| `+emoji:ant[]+`

a| `+emoji:beetle[]+`
a| `+emoji:snail[]+`
a| `+emoji:octopus[]+`
a| `+emoji:tropical-fish[]+`

a| `+emoji:fish[]+`
a| `+emoji:whale[]+`
a| `+emoji:whale2[]+`
a| `+emoji:dolphin[]+`

a| `+emoji:cow2[]+`
a| `+emoji:ram[]+`
a| `+emoji:rat[]+`
a| `+emoji:water-buffalo[]+`

a| `+emoji:tiger2[]+`
a| `+emoji:rabbit2[]+`
a| `+emoji:dragon[]+`
a| `+emoji:goat[]+`

a| `+emoji:rooster[]+`
a| `+emoji:dog2[]+`
a| `+emoji:pig2[]+`
a| `+emoji:mouse2[]+`

a| `+emoji:ox[]+`
a| `+emoji:dragon-face[]+`
a| `+emoji:blowfish[]+`
a| `+emoji:crocodile[]+`

a| `+emoji:dromedary-camel[]+`
a| `+emoji:leopard[]+`
a| `+emoji:cat2[]+`
a| `+emoji:poodle[]+`

a| `+emoji:paw-prints[]+`
a| `+emoji:bouquet[]+`
a| `+emoji:cherry-blossom[]+`
a| `+emoji:tulip[]+`

a| `+emoji:four-leaf-clover[]+`
a| `+emoji:rose[]+`
a| `+emoji:sunflower[]+`
a| `+emoji:hibiscus[]+`

a| `+emoji:maple-leaf[]+`
a| `+emoji:leaves[]+`
a| `+emoji:fallen-leaf[]+`
a| `+emoji:herb[]+`

a| `+emoji:mushroom[]+`
a| `+emoji:cactus[]+`
a| `+emoji:palm-tree[]+`
a| `+emoji:evergreen-tree[]+`

a| `+emoji:deciduous-tree[]+`
a| `+emoji:chestnut[]+`
a| `+emoji:seedling[]+`
a| `+emoji:blossom[]+`

a| `+emoji:ear-of-rice[]+`
a| `+emoji:shell[]+`
a| `+emoji:globe-with-meridians[]+`
a| `+emoji:sun-with-face[]+`

a| `+emoji:full-moon-with-face[]+`
a| `+emoji:new-moon-with-face[]+`
a| `+emoji:new-moon[]+`
a| `+emoji:waxing-crescent-moon[]+`

a| `+emoji:first-quarter-moon[]+`
a| `+emoji:waxing-gibbous-moon[]+`
a| `+emoji:full-moon[]+`
a| `+emoji:waning-gibbous-moon[]+`

a| `+emoji:last-quarter-moon[]+`
a| `+emoji:waning-crescent-moon[]+`
a| `+emoji:last-quarter-moon-with-face[]+`
a| `+emoji:first-quarter-moon-with-face[]+`

a| `+emoji:moon[]+`
a| `+emoji:earth-africa[]+`
a| `+emoji:earth-americas[]+`
a| `+emoji:earth-asia[]+`

a| `+emoji:volcano[]+`
a| `+emoji:milky-way[]+`
a| `+emoji:partly-sunny[]+`
a| `+emoji:bamboo[]+`

a| `+emoji:gift-heart[]+`
a| `+emoji:dolls[]+`
a| `+emoji:school-satchel[]+`
a| `+emoji:mortar-board[]+`

a| `+emoji:flags[]+`
a| `+emoji:fireworks[]+`
a| `+emoji:sparkler[]+`
a| `+emoji:wind-chime[]+`

a| `+emoji:rice-scene[]+`
a| `+emoji:jack-o-lantern[]+`
a| `+emoji:ghost[]+`
a| `+emoji:santa[]+`

a| `+emoji:8ball[]+`
a| `+emoji:alarm-clock[]+`
a| `+emoji:apple[]+`
a| `+emoji:art[]+`

a| `+emoji:baby-bottle[]+`
a| `+emoji:balloon[]+`
a| `+emoji:banana[]+`
a| `+emoji:bar-chart[]+`

a| `+emoji:baseball[]+`
a| `+emoji:basketball[]+`
a| `+emoji:bath[]+`
a| `+emoji:bathtub[]+`

a| `+emoji:battery[]+`
a| `+emoji:beer[]+`
a| `+emoji:beers[]+`
a| `+emoji:bell[]+`

a| `+emoji:bento[]+`
a| `+emoji:bicyclist[]+`
a| `+emoji:bikini[]+`
a| `+emoji:birthday[]+`

a| `+emoji:black-joker[]+`
a| `+emoji:black-nib[]+`
a| `+emoji:blue-book[]+`
a| `+emoji:bomb[]+`

a| `+emoji:bookmark[]+`
a| `+emoji:bookmark-tabs[]+`
a| `+emoji:books[]+`
a| `+emoji:boot[]+`

a| `+emoji:bowling[]+`
a| `+emoji:bread[]+`
a| `+emoji:briefcase[]+`
a| `+emoji:bulb[]+`

a| `+emoji:cake[]+`
a| `+emoji:calendar[]+`
a| `+emoji:calling[]+`
a| `+emoji:camera[]+`

a| `+emoji:candy[]+`
a| `+emoji:card-index[]+`
a| `+emoji:cd[]+`
a| `+emoji:chart-with-downwards-trend[]+`

a| `+emoji:chart-with-upwards-trend[]+`
a| `+emoji:cherries[]+`
a| `+emoji:chocolate-bar[]+`
a| `+emoji:christmas-tree[]+`

a| `+emoji:clapper[]+`
a| `+emoji:clipboard[]+`
a| `+emoji:closed-book[]+`
a| `+emoji:closed-lock-with-key[]+`

a| `+emoji:closed-umbrella[]+`
a| `+emoji:clubs[]+`
a| `+emoji:cocktail[]+`
a| `+emoji:coffee[]+`

a| `+emoji:computer[]+`
a| `+emoji:confetti-ball[]+`
a| `+emoji:cookie[]+`
a| `+emoji:corn[]+`

a| `+emoji:credit-card[]+`
a| `+emoji:crown[]+`
a| `+emoji:crystal-ball[]+`
a| `+emoji:curry[]+`

a| `+emoji:custard[]+`
a| `+emoji:dango[]+`
a| `+emoji:dart[]+`
a| `+emoji:date[]+`

a| `+emoji:diamonds[]+`
a| `+emoji:dollar[]+`
a| `+emoji:door[]+`
a| `+emoji:doughnut[]+`

a| `+emoji:dress[]+`
a| `+emoji:dvd[]+`
a| `+emoji:e-mail[]+`
a| `+emoji:egg[]+`

a| `+emoji:eggplant[]+`
a| `+emoji:electric-plug[]+`
a| `+emoji:email[]+`
a| `+emoji:euro[]+`

a| `+emoji:eyeglasses[]+`
a| `+emoji:fax[]+`
a| `+emoji:file-folder[]+`
a| `+emoji:fish-cake[]+`

a| `+emoji:fishing-pole-and-fish[]+`
a| `+emoji:flashlight[]+`
a| `+emoji:floppy-disk[]+`
a| `+emoji:flower-playing-cards[]+`

a| `+emoji:football[]+`
a| `+emoji:fork-and-knife[]+`
a| `+emoji:fried-shrimp[]+`
a| `+emoji:fries[]+`

a| `+emoji:game-die[]+`
a| `+emoji:gem[]+`
a| `+emoji:gift[]+`
a| `+emoji:golf[]+`

a| `+emoji:grapes[]+`
a| `+emoji:green-apple[]+`
a| `+emoji:green-book[]+`
a| `+emoji:guitar[]+`

a| `+emoji:gun[]+`
a| `+emoji:hamburger[]+`
a| `+emoji:hammer[]+`
a| `+emoji:handbag[]+`

a| `+emoji:headphones[]+`
a| `+emoji:hearts[]+`
a| `+emoji:high-brightness[]+`
a| `+emoji:high-heel[]+`

a| `+emoji:hocho[]+`
a| `+emoji:honey-pot[]+`
a| `+emoji:horse-racing[]+`
a| `+emoji:hourglass[]+`

a| `+emoji:hourglass-flowing-sand[]+`
a| `+emoji:ice-cream[]+`
a| `+emoji:icecream[]+`
a| `+emoji:inbox-tray[]+`

a| `+emoji:incoming-envelope[]+`
a| `+emoji:iphone[]+`
a| `+emoji:jeans[]+`
a| `+emoji:key[]+`

a| `+emoji:kimono[]+`
a| `+emoji:ledger[]+`
a| `+emoji:lemon[]+`
a| `+emoji:lipstick[]+`

a| `+emoji:lock[]+`
a| `+emoji:lock-with-ink-pen[]+`
a| `+emoji:lollipop[]+`
a| `+emoji:loop[]+`

a| `+emoji:loudspeaker[]+`
a| `+emoji:low-brightness[]+`
a| `+emoji:mag[]+`
a| `+emoji:mag-right[]+`

a| `+emoji:mahjong[]+`
a| `+emoji:mailbox[]+`
a| `+emoji:mailbox-closed[]+`
a| `+emoji:mailbox-with-mail[]+`

a| `+emoji:mailbox-with-no-mail[]+`
a| `+emoji:mans-shoe[]+`
a| `+emoji:meat-on-bone[]+`
a| `+emoji:mega[]+`

a| `+emoji:melon[]+`
a| `+emoji:memo[]+`
a| `+emoji:microphone[]+`
a| `+emoji:microscope[]+`

a| `+emoji:minidisc[]+`
a| `+emoji:money-with-wings[]+`
a| `+emoji:moneybag[]+`
a| `+emoji:mountain-bicyclist[]+`

a| `+emoji:movie-camera[]+`
a| `+emoji:musical-keyboard[]+`
a| `+emoji:musical-score[]+`
a| `+emoji:mute[]+`

a| `+emoji:name-badge[]+`
a| `+emoji:necktie[]+`
a| `+emoji:newspaper[]+`
a| `+emoji:no-bell[]+`

a| `+emoji:notebook[]+`
a| `+emoji:notebook-with-decorative-cover[]+`
a| `+emoji:nut-and-bolt[]+`
a| `+emoji:oden[]+`

a| `+emoji:open-file-folder[]+`
a| `+emoji:orange-book[]+`
a| `+emoji:outbox-tray[]+`
a| `+emoji:page-facing-up[]+`

a| `+emoji:page-with-curl[]+`
a| `+emoji:pager[]+`
a| `+emoji:paperclip[]+`
a| `+emoji:peach[]+`

a| `+emoji:pear[]+`
a| `+emoji:pencil2[]+`
a| `+emoji:phone[]+`
a| `+emoji:pill[]+`

a| `+emoji:pineapple[]+`
a| `+emoji:pizza[]+`
a| `+emoji:postal-horn[]+`
a| `+emoji:postbox[]+`

a| `+emoji:pouch[]+`
a| `+emoji:poultry-leg[]+`
a| `+emoji:pound[]+`
a| `+emoji:purse[]+`

a| `+emoji:pushpin[]+`
a| `+emoji:radio[]+`
a| `+emoji:ramen[]+`
a| `+emoji:ribbon[]+`

a| `+emoji:rice[]+`
a| `+emoji:rice-ball[]+`
a| `+emoji:rice-cracker[]+`
a| `+emoji:ring[]+`

a| `+emoji:rugby-football[]+`
a| `+emoji:running-shirt-with-sash[]+`
a| `+emoji:sake[]+`
a| `+emoji:sandal[]+`

a| `+emoji:satellite[]+`
a| `+emoji:saxophone[]+`
a| `+emoji:scissors[]+`
a| `+emoji:scroll[]+`

a| `+emoji:seat[]+`
a| `+emoji:shaved-ice[]+`
a| `+emoji:shirt[]+`
a| `+emoji:shower[]+`

a| `+emoji:ski[]+`
a| `+emoji:smoking[]+`
a| `+emoji:snowboarder[]+`
a| `+emoji:soccer[]+`

a| `+emoji:sound[]+`
a| `+emoji:space-invader[]+`
a| `+emoji:spades[]+`
a| `+emoji:spaghetti[]+`

a| `+emoji:speaker[]+`
a| `+emoji:stew[]+`
a| `+emoji:straight-ruler[]+`
a| `+emoji:strawberry[]+`

a| `+emoji:surfer[]+`
a| `+emoji:sushi[]+`
a| `+emoji:sweet-potato[]+`
a| `+emoji:swimmer[]+`

a| `+emoji:syringe[]+`
a| `+emoji:tada[]+`
a| `+emoji:tanabata-tree[]+`
a| `+emoji:tangerine[]+`

a| `+emoji:tea[]+`
a| `+emoji:telephone-receiver[]+`
a| `+emoji:telescope[]+`
a| `+emoji:tennis[]+`

a| `+emoji:toilet[]+`
a| `+emoji:tomato[]+`
a| `+emoji:tophat[]+`
a| `+emoji:triangular-ruler[]+`

a| `+emoji:trophy[]+`
a| `+emoji:tropical-drink[]+`
a| `+emoji:trumpet[]+`
a| `+emoji:tv[]+`

a| `+emoji:unlock[]+`
a| `+emoji:vhs[]+`
a| `+emoji:video-camera[]+`
a| `+emoji:video-game[]+`

a| `+emoji:violin[]+`
a| `+emoji:watch[]+`
a| `+emoji:watermelon[]+`
a| `+emoji:wine-glass[]+`

a| `+emoji:womans-clothes[]+`
a| `+emoji:womans-hat[]+`
a| `+emoji:wrench[]+`
a| `+emoji:yen[]+`

a| `+emoji:aerial-tramway[]+`
a| `+emoji:airplane[]+`
a| `+emoji:ambulance[]+`
a| `+emoji:anchor[]+`

a| `+emoji:articulated-lorry[]+`
a| `+emoji:atm[]+`
a| `+emoji:bank[]+`
a| `+emoji:barber[]+`

a| `+emoji:beginner[]+`
a| `+emoji:bike[]+`
a| `+emoji:blue-car[]+`
a| `+emoji:boat[]+`

a| `+emoji:bridge-at-night[]+`
a| `+emoji:bullettrain-front[]+`
a| `+emoji:bullettrain-side[]+`
a| `+emoji:bus[]+`

a| `+emoji:busstop[]+`
a| `+emoji:car[]+`
a| `+emoji:carousel-horse[]+`
a| `+emoji:checkered-flag[]+`

a| `+emoji:church[]+`
a| `+emoji:circus-tent[]+`
a| `+emoji:city-sunrise[]+`
a| `+emoji:city-sunset[]+`

a| `+emoji:construction[]+`
a| `+emoji:convenience-store[]+`
a| `+emoji:crossed-flags[]+`
a| `+emoji:department-store[]+`

a| `+emoji:european-castle[]+`
a| `+emoji:european-post-office[]+`
a| `+emoji:factory[]+`
a| `+emoji:ferris-wheel[]+`

a| `+emoji:fire-engine[]+`
a| `+emoji:fountain[]+`
a| `+emoji:fuelpump[]+`
a| `+emoji:helicopter[]+`

a| `+emoji:hospital[]+`
a| `+emoji:hotel[]+`
a| `+emoji:hotsprings[]+`
a| `+emoji:house[]+`

a| `+emoji:house-with-garden[]+`
a| `+emoji:japan[]+`
a| `+emoji:japanese-castle[]+`
a| `+emoji:light-rail[]+`

a| `+emoji:love-hotel[]+`
a| `+emoji:minibus[]+`
a| `+emoji:monorail[]+`
a| `+emoji:mount-fuji[]+`

a| `+emoji:mountain-cableway[]+`
a| `+emoji:mountain-railway[]+`
a| `+emoji:moyai[]+`
a| `+emoji:office[]+`

a| `+emoji:oncoming-automobile[]+`
a| `+emoji:oncoming-bus[]+`
a| `+emoji:oncoming-police-car[]+`
a| `+emoji:oncoming-taxi[]+`

a| `+emoji:performing-arts[]+`
a| `+emoji:police-car[]+`
a| `+emoji:post-office[]+`
a| `+emoji:railway-car[]+`

a| `+emoji:rainbow[]+`
a| `+emoji:rocket[]+`
a| `+emoji:roller-coaster[]+`
a| `+emoji:rotating-light[]+`

a| `+emoji:round-pushpin[]+`
a| `+emoji:rowboat[]+`
a| `+emoji:school[]+`
a| `+emoji:ship[]+`

a| `+emoji:slot-machine[]+`
a| `+emoji:speedboat[]+`
a| `+emoji:stars[]+`
a| `+emoji:station[]+`

a| `+emoji:statue-of-liberty[]+`
a| `+emoji:steam-locomotive[]+`
a| `+emoji:sunrise[]+`
a| `+emoji:sunrise-over-mountains[]+`

a| `+emoji:suspension-railway[]+`
a| `+emoji:taxi[]+`
a| `+emoji:tent[]+`
a| `+emoji:ticket[]+`

a| `+emoji:tokyo-tower[]+`
a| `+emoji:tractor[]+`
a| `+emoji:traffic-light[]+`
a| `+emoji:train2[]+`

a| `+emoji:tram[]+`
a| `+emoji:triangular-flag-on-post[]+`
a| `+emoji:trolleybus[]+`
a| `+emoji:truck[]+`

a| `+emoji:vertical-traffic-light[]+`
a| `+emoji:warning[]+`
a| `+emoji:wedding[]+`
a| `+emoji:jp[]+`

a| `+emoji:kr[]+`
a| `+emoji:cn[]+`
a| `+emoji:us[]+`
a| `+emoji:fr[]+`

a| `+emoji:es[]+`
a| `+emoji:it[]+`
a| `+emoji:ru[]+`
a| `+emoji:gb[]+`

a| `+emoji:de[]+`
a| `+emoji:100[]+`
a| `+emoji:1234[]+`
a| `+emoji:a[]+`

a| `+emoji:ab[]+`
a| `+emoji:abc[]+`
a| `+emoji:abcd[]+`
a| `+emoji:accept[]+`

a| `+emoji:aquarius[]+`
a| `+emoji:aries[]+`
a| `+emoji:arrow-backward[]+`
a| `+emoji:arrow-double-down[]+`

a| `+emoji:arrow-double-up[]+`
a| `+emoji:arrow-down[]+`
a| `+emoji:arrow-down-small[]+`
a| `+emoji:arrow-forward[]+`

a| `+emoji:arrow-heading-down[]+`
a| `+emoji:arrow-heading-up[]+`
a| `+emoji:arrow-left[]+`
a| `+emoji:arrow-lower-left[]+`

a| `+emoji:arrow-lower-right[]+`
a| `+emoji:arrow-right[]+`
a| `+emoji:arrow-right-hook[]+`
a| `+emoji:arrow-up[]+`

a| `+emoji:arrow-up-down[]+`
a| `+emoji:arrow-up-small[]+`
a| `+emoji:arrow-upper-left[]+`
a| `+emoji:arrow-upper-right[]+`

a| `+emoji:arrows-clockwise[]+`
a| `+emoji:arrows-counterclockwise[]+`
a| `+emoji:b[]+`
a| `+emoji:baby-symbol[]+`

a| `+emoji:baggage-claim[]+`
a| `+emoji:ballot-box-with-check[]+`
a| `+emoji:bangbang[]+`
a| `+emoji:black-circle[]+`

a| `+emoji:black-square-button[]+`
a| `+emoji:cancer[]+`
a| `+emoji:capital-abcd[]+`
a| `+emoji:capricorn[]+`

a| `+emoji:chart[]+`
a| `+emoji:children-crossing[]+`
a| `+emoji:cinema[]+`
a| `+emoji:cl[]+`

a| `+emoji:clock1[]+`
a| `+emoji:clock10[]+`
a| `+emoji:clock1030[]+`
a| `+emoji:clock11[]+`

a| `+emoji:clock1130[]+`
a| `+emoji:clock12[]+`
a| `+emoji:clock1230[]+`
a| `+emoji:clock130[]+`

a| `+emoji:clock2[]+`
a| `+emoji:clock230[]+`
a| `+emoji:clock3[]+`
a| `+emoji:clock330[]+`

a| `+emoji:clock4[]+`
a| `+emoji:clock430[]+`
a| `+emoji:clock5[]+`
a| `+emoji:clock530[]+`

a| `+emoji:clock6[]+`
a| `+emoji:clock630[]+`
a| `+emoji:clock7[]+`
a| `+emoji:clock730[]+`

a| `+emoji:clock8[]+`
a| `+emoji:clock830[]+`
a| `+emoji:clock9[]+`
a| `+emoji:clock930[]+`

a| `+emoji:congratulations[]+`
a| `+emoji:cool[]+`
a| `+emoji:copyright[]+`
a| `+emoji:curly-loop[]+`

a| `+emoji:currency-exchange[]+`
a| `+emoji:customs[]+`
a| `+emoji:diamond-shape-with-a-dot-inside[]+`
a| `+emoji:do-not-litter[]+`

a| `+emoji:eight[]+`
a| `+emoji:eight-pointed-black-star[]+`
a| `+emoji:eight-spoked-asterisk[]+`
a| `+emoji:end[]+`

a| `+emoji:fast-forward[]+`
a| `+emoji:five[]+`
a| `+emoji:four[]+`
a| `+emoji:free[]+`

a| `+emoji:gemini[]+`
a| `+emoji:hash[]+`
a| `+emoji:heart-decoration[]+`
a| `+emoji:heavy-check-mark[]+`

a| `+emoji:heavy-division-sign[]+`
a| `+emoji:heavy-dollar-sign[]+`
a| `+emoji:heavy-minus-sign[]+`
a| `+emoji:heavy-multiplication-x[]+`

a| `+emoji:heavy-plus-sign[]+`
a| `+emoji:id[]+`
a| `+emoji:ideograph-advantage[]+`
a| `+emoji:information-source[]+`

a| `+emoji:interrobang[]+`
a| `+emoji:keycap-ten[]+`
a| `+emoji:koko[]+`
a| `+emoji:large-blue-circle[]+`

a| `+emoji:large-blue-diamond[]+`
a| `+emoji:large-orange-diamond[]+`
a| `+emoji:left-luggage[]+`
a| `+emoji:left-right-arrow[]+`

a| `+emoji:leftwards-arrow-with-hook[]+`
a| `+emoji:leo[]+`
a| `+emoji:libra[]+`
a| `+emoji:link[]+`

a| `+emoji:m[]+`
a| `+emoji:mens[]+`
a| `+emoji:metro[]+`
a| `+emoji:mobile-phone-off[]+`

a| `+emoji:negative-squared-cross-mark[]+`
a| `+emoji:new[]+`
a| `+emoji:ng[]+`
a| `+emoji:nine[]+`

a| `+emoji:no-bicycles[]+`
a| `+emoji:no-entry[]+`
a| `+emoji:no-entry-sign[]+`
a| `+emoji:no-mobile-phones[]+`

a| `+emoji:no-pedestrians[]+`
a| `+emoji:no-smoking[]+`
a| `+emoji:non-potable-water[]+`
a| `+emoji:o[]+`

a| `+emoji:o2[]+`
a| `+emoji:ok[]+`
a| `+emoji:on[]+`
a| `+emoji:one[]+`

a| `+emoji:ophiuchus[]+`
a| `+emoji:parking[]+`
a| `+emoji:part-alternation-mark[]+`
a| `+emoji:passport-control[]+`

a| `+emoji:pisces[]+`
a| `+emoji:potable-water[]+`
a| `+emoji:put-litter-in-its-place[]+`
a| `+emoji:radio-button[]+`

a| `+emoji:recycle[]+`
a| `+emoji:red-circle[]+`
a| `+emoji:registered[]+`
a| `+emoji:repeat[]+`

a| `+emoji:repeat-one[]+`
a| `+emoji:restroom[]+`
a| `+emoji:rewind[]+`
a| `+emoji:sa[]+`

a| `+emoji:sagittarius[]+`
a| `+emoji:scorpius[]+`
a| `+emoji:secret[]+`
a| `+emoji:seven[]+`

a| `+emoji:signal-strength[]+`
a| `+emoji:six[]+`
a| `+emoji:six-pointed-star[]+`
a| `+emoji:small-blue-diamond[]+`

a| `+emoji:small-orange-diamond[]+`
a| `+emoji:small-red-triangle[]+`
a| `+emoji:small-red-triangle-down[]+`
a| `+emoji:soon[]+`

a| `+emoji:sos[]+`
a| `+emoji:symbols[]+`
a| `+emoji:taurus[]+`
a| `+emoji:three[]+`

a| `+emoji:tm[]+`
a| `+emoji:top[]+`
a| `+emoji:trident[]+`
a| `+emoji:twisted-rightwards-arrows[]+`

a| `+emoji:two[]+`
a| `+emoji:u5272[]+`
a| `+emoji:u5408[]+`
a| `+emoji:u55b6[]+`

a| `+emoji:u6307[]+`
a| `+emoji:u6708[]+`
a| `+emoji:u6709[]+`
a| `+emoji:u6e80[]+`

a| `+emoji:u7121[]+`
a| `+emoji:u7533[]+`
a| `+emoji:u7981[]+`
a| `+emoji:u7a7a[]+`

a| `+emoji:underage[]+`
a| `+emoji:up[]+`
a| `+emoji:vibration-mode[]+`
a| `+emoji:virgo[]+`

a| `+emoji:vs[]+`
a| `+emoji:wavy-dash[]+`
a| `+emoji:wc[]+`
a| `+emoji:wheelchair[]+`

a| `+emoji:white-check-mark[]+`
a| `+emoji:white-circle[]+`
a| `+emoji:white-flower[]+`
a| `+emoji:white-square-button[]+`

a| `+emoji:womens[]+`
a| `+emoji:x[]+`
a| `+emoji:zero[]+`
a|
|===
