= Emoji Cheat Sheet
:author: mitm
:revnumber:
:revdate: 2019-12-18T23:24:11.262Z
:stylesheet: twemoji-awesome.css
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== How to use emoji in the wiki

Using emoji in wiki docs currently requires the setting of the `:stylesheet:` attribute in the header of the wiki document.

```
:stylesheet: twemoji-awesome.css
```
The <<wiki/wiki_header.adoc#,Anatomy of a Wiki Header>> document exlains setting of this and other header attributes.

Once the header attribute is set, you can add the emoji using the following syntax.

```
emoji:heart[2x] // the "[2x]" is a size modifier
emoji:rage[]
```

[NOTE]
====
You can change the icon size with the size modifier `[2x]`.

`+emoji:heart[]+` emoji:heart[] `+emoji:heart[2x]+` emoji:heart[2x]
====

== Full list of emoji and their syntax.

[cols=4, frame=none, grid=none, stripes=none]
|===
a| emoji:smile[] `+emoji:smile[]+`
a| emoji:laughing[] [.small]`+emoji:laughing[]+`
a| emoji:blush[] [.small]`+emoji:blush[]+`

a| emoji:smiley[] [.small]`+emoji:smiley[]+`
a| emoji:relaxed[] [.small]`+emoji:relaxed[]+`
a| emoji:smirk[] [.small]`+emoji:smirk[]+`

a| [.small]`+emoji:heart-eyes[]+`
a| [.small]`+emoji:kissing-heart[]+`
a| [.small]`+emoji:kissing-closed-eyes[]+`

a| [.small]`+emoji:flushed[]+`
a| [.small]`+emoji:relieved[]+`
a| [.small]`+emoji:satisfied[]+`

a| [.small]`+emoji:grin[]+`
a| [.small]`+emoji:wink[]+`
a| [.small]`+emoji:stuck-out-tongue-winking-eye[]+`

a| [.small]`+emoji:stuck-out-tongue-closed-eyes[]+`
a| [.small]`+emoji:grinning[]+`
a| [.small]`+emoji:kissing[]+`

a| [.small]`+emoji:kissing-smiling-eyes[]+`
a| [.small]`+emoji:stuck-out-tongue[]+`
a| [.small]`+emoji:sleeping[]+`

a| [.small]`+emoji:worried[]+`
a| [.small]`+emoji:frowning[]+`
a| [.small]`+emoji:anguished[]+`

a| [.small]`+emoji:open-mouth[]+`
a| [.small]`+emoji:grimacing[]+`
a| [.small]`+emoji:confused[]+`

a| [.small]`+emoji:hushed[]+`
a| [.small]`+emoji:expressionless[]+`
a| [.small]`+emoji:unamused[]+`

a| [.small]`+emoji:sweat-smile[]+`
a| [.small]`+emoji:sweat[]+`
a| [.small]`+emoji:weary[]+`

a| [.small]`+emoji:pensive[]+`
a| [.small]`+emoji:disappointed[]+`
a| [.small]`+emoji:confounded[]+`

a| [.small]`+emoji:fearful[]+`
a| [.small]`+emoji:cold-sweat[]+`
a| [.small]`+emoji:persevere[]+`

a| [.small]`+emoji:cry[]+`
a| [.small]`+emoji:sob[]+`
a| [.small]`+emoji:joy[]+`

a| [.small]`+emoji:astonished[]+`
a| [.small]`+emoji:scream[]+`
a| [.small]`+emoji:tired-face[]+`

a| [.small]`+emoji:angry[]+`
a| [.small]`+emoji:rage[]+`
a| [.small]`+emoji:triumph[]+`

a| [.small]`+emoji:sleepy[]+`
a| [.small]`+emoji:yum[]+`
a| [.small]`+emoji:mask[]+`

a| [.small]`+emoji:sunglasses[]+`
a| [.small]`+emoji:dizzy-face[]+`
a| [.small]`+emoji:imp[]+`

a| [.small]`+emoji:smiling-imp[]+`
a| [.small]`+emoji:neutral-face[]+`
a| [.small]`+emoji:no-mouth[]+`

a| [.small]`+emoji:innocent[]+`
a| [.small]`+emoji:alien[]+`
a| [.small]`+emoji:yellow-heart[]+`

a| [.small]`+emoji:blue-heart[]+`
a| [.small]`+emoji:purple-heart[]+`
a| [.small]`+emoji:heart[]+`

a| [.small]`+emoji:green-heart[]+`
a| [.small]`+emoji:broken-heart[]+`
a| [.small]`+emoji:heartbeat[]+`

a| [.small]`+emoji:heartpulse[]+`
a| [.small]`+emoji:two-hearts[]+`
a| [.small]`+emoji:revolving-hearts[]+`

a| [.small]`+emoji:cupid[]+`
a| [.small]`+emoji:sparkling-heart[]+`
a| [.small]`+emoji:sparkles[]+`

a| [.small]`+emoji:star[]+`
a| [.small]`+emoji:star2[]+`
a| [.small]`+emoji:dizzy[]+`

a| [.small]`+emoji:boom[]+`
a| [.small]`+emoji:anger[]+`
a| [.small]`+emoji:exclamation[]+`

a| [.small]`+emoji:question[]+`
a| [.small]`+emoji:grey-exclamation[]+`
a| [.small]`+emoji:grey-question[]+`

a| [.small]`+emoji:zzz[]+`
a| [.small]`+emoji:dash[]+`
a| [.small]`+emoji:sweat-drops[]+`

a| [.small]`+emoji:notes[]+`
a| [.small]`+emoji:musical-note[]+`
a| [.small]`+emoji:fire[]+`

a| [.small]`+emoji:poop[]+`
a| [.small]`+emoji:thumbsup[]+`
a| [.small]`+emoji:thumbsdown[]+`

a| [.small]`+emoji:ok-hand[]+`
a| [.small]`+emoji:punch[]+`
a| [.small]`+emoji:fist[]+`

a| [.small]`+emoji:v[]+`
a| [.small]`+emoji:wave[]+`
a| [.small]`+emoji:hand[]+`

a| [.small]`+emoji:open-hands[]+`
a| [.small]`+emoji:point-up[]+`
a| [.small]`+emoji:point-down[]+`

a| [.small]`+emoji:point-left[]+`
a| [.small]`+emoji:point-right[]+`
a| [.small]`+emoji:raised-hands[]+`

a| [.small]`+emoji:pray[]+`
a| [.small]`+emoji:point-up-2[]+`
a| [.small]`+emoji:clap[]+`

a| [.small]`+emoji:muscle[]+`
a| [.small]`+emoji:walking[]+`
a| [.small]`+emoji:runner[]+`

a| [.small]`+emoji:couple[]+`
a| [.small]`+emoji:family[]+`
a| [.small]`+emoji:two-men-holding-hands[]+`

a| [.small]`+emoji:two-women-holding-hands[]+`
a| [.small]`+emoji:dancer[]+`
a| [.small]`+emoji:dancers[]+`

a| [.small]`+emoji:ok-woman[]+`
a| [.small]`+emoji:no-good[]+`
a| [.small]`+emoji:information-desk-person[]+`

a| [.small]`+emoji:raised-hand[]+`
a| [.small]`+emoji:bride-with-veil[]+`
a| [.small]`+emoji:person-with-pouting-face[]+`

a| [.small]`+emoji:person-frowning[]+`
a| [.small]`+emoji:bow[]+`
a| [.small]`+emoji:couplekiss[]+`

a| [.small]`+emoji:couple-with-heart[]+`
a| [.small]`+emoji:massage[]+`
a| [.small]`+emoji:haircut[]+`

a| [.small]`+emoji:nail-care[]+`
a| [.small]`+emoji:boy[]+`
a| [.small]`+emoji:girl[]+`

a| [.small]`+emoji:woman[]+`
a| [.small]`+emoji:man[]+`
a| [.small]`+emoji:baby[]+`

a| [.small]`+emoji:older-woman[]+`
a| [.small]`+emoji:older-man[]+`
a| [.small]`+emoji:person-with-blond-hair[]+`

a| [.small]`+emoji:man-with-gua-pi-mao[]+`
a| [.small]`+emoji:man-with-turban[]+`
a| [.small]`+emoji:construction-worker[]+`

a| [.small]`+emoji:cop[]+`
a| [.small]`+emoji:angel[]+`
a| [.small]`+emoji:princess[]+`

a| [.small]`+emoji:smiley-cat[]+`
a| [.small]`+emoji:smile-cat[]+`
a| [.small]`+emoji:heart-eyes-cat[]+`

a| [.small]`+emoji:kissing-cat[]+`
a| [.small]`+emoji:smirk-cat[]+`
a| [.small]`+emoji:scream-cat[]+`

a| [.small]`+emoji:crying-cat-face[]+`
a| [.small]`+emoji:joy-cat[]+`
a| [.small]`+emoji:pouting-cat[]+`

a| [.small]`+emoji:japanese-ogre[]+`
a| [.small]`+emoji:japanese-goblin[]+`
a| [.small]`+emoji:see-no-evil[]+`

a| [.small]`+emoji:hear-no-evil[]+`
a| [.small]`+emoji:speak-no-evil[]+`
a| [.small]`+emoji:guardsman[]+`

a| [.small]`+emoji:skull[]+`
a| [.small]`+emoji:feet[]+`
a| [.small]`+emoji:lips[]+`

a| [.small]`+emoji:kiss[]+`

a| [.small]`+emoji:droplet[]+`
a| [.small]`+emoji:ear[]+`
a| [.small]`+emoji:eyes[]+`
a| [.small]`+emoji:nose[]+`

a| [.small]`+emoji:tongue[]+`
a| [.small]`+emoji:love-letter[]+`
a| [.small]`+emoji:bust-in-silhouette[]+`
a| [.small]`+emoji:busts-in-silhouette[]+`

a| [.small]`+emoji:speech-balloon[]+`
a| [.small]`+emoji:thought-balloon[]+`
a| [.small]`+emoji:sunny[]+`
a| [.small]`+emoji:umbrella[]+`

a| [.small]`+emoji:cloud[]+`
a| [.small]`+emoji:snowflake[]+`
a| [.small]`+emoji:snowman[]+`
a| [.small]`+emoji:zap[]+`

a| [.small]`+emoji:cyclone[]+`
a| [.small]`+emoji:foggy[]+`
a| [.small]`+emoji:ocean[]+`
a| [.small]`+emoji:cat[]+`

a| [.small]`+emoji:dog[]+`
a| [.small]`+emoji:mouse[]+`
a| [.small]`+emoji:hamster[]+`
a| [.small]`+emoji:rabbit[]+`

a| [.small]`+emoji:wolf[]+`
a| [.small]`+emoji:frog[]+`
a| [.small]`+emoji:tiger[]+`
a| [.small]`+emoji:koala[]+`

a| [.small]`+emoji:bear[]+`
a| [.small]`+emoji:pig[]+`
a| [.small]`+emoji:pig-nose[]+`
a| [.small]`+emoji:cow[]+`

a| [.small]`+emoji:boar[]+`
a| [.small]`+emoji:monkey-face[]+`
a| [.small]`+emoji:monkey[]+`
a| [.small]`+emoji:horse[]+`

a| [.small]`+emoji:racehorse[]+`
a| [.small]`+emoji:camel[]+`
a| [.small]`+emoji:sheep[]+`
a| [.small]`+emoji:elephant[]+`

a| [.small]`+emoji:panda-face[]+`
a| [.small]`+emoji:snake[]+`
a| [.small]`+emoji:bird[]+`
a| [.small]`+emoji:baby-chick[]+`

a| [.small]`+emoji:hatched-chick[]+`
a| [.small]`+emoji:hatching-chick[]+`
a| [.small]`+emoji:chicken[]+`
a| [.small]`+emoji:penguin[]+`

a| [.small]`+emoji:turtle[]+`
a| [.small]`+emoji:bug[]+`
a| [.small]`+emoji:honeybee[]+`
a| [.small]`+emoji:ant[]+`

a| [.small]`+emoji:beetle[]+`
a| [.small]`+emoji:snail[]+`
a| [.small]`+emoji:octopus[]+`
a| [.small]`+emoji:tropical-fish[]+`

a| [.small]`+emoji:fish[]+`
a| [.small]`+emoji:whale[]+`
a| [.small]`+emoji:whale2[]+`
a| [.small]`+emoji:dolphin[]+`

a| [.small]`+emoji:cow2[]+`
a| [.small]`+emoji:ram[]+`
a| [.small]`+emoji:rat[]+`
a| [.small]`+emoji:water-buffalo[]+`

a| [.small]`+emoji:tiger2[]+`
a| [.small]`+emoji:rabbit2[]+`
a| [.small]`+emoji:dragon[]+`
a| [.small]`+emoji:goat[]+`

a| [.small]`+emoji:rooster[]+`
a| [.small]`+emoji:dog2[]+`
a| [.small]`+emoji:pig2[]+`
a| [.small]`+emoji:mouse2[]+`

a| [.small]`+emoji:ox[]+`
a| [.small]`+emoji:dragon-face[]+`
a| [.small]`+emoji:blowfish[]+`
a| [.small]`+emoji:crocodile[]+`

a| [.small]`+emoji:dromedary-camel[]+`
a| [.small]`+emoji:leopard[]+`
a| [.small]`+emoji:cat2[]+`
a| [.small]`+emoji:poodle[]+`

a| [.small]`+emoji:paw-prints[]+`
a| [.small]`+emoji:bouquet[]+`
a| [.small]`+emoji:cherry-blossom[]+`
a| [.small]`+emoji:tulip[]+`

a| [.small]`+emoji:four-leaf-clover[]+`
a| [.small]`+emoji:rose[]+`
a| [.small]`+emoji:sunflower[]+`
a| [.small]`+emoji:hibiscus[]+`

a| [.small]`+emoji:maple-leaf[]+`
a| [.small]`+emoji:leaves[]+`
a| [.small]`+emoji:fallen-leaf[]+`
a| [.small]`+emoji:herb[]+`

a| [.small]`+emoji:mushroom[]+`
a| [.small]`+emoji:cactus[]+`
a| [.small]`+emoji:palm-tree[]+`
a| [.small]`+emoji:evergreen-tree[]+`

a| [.small]`+emoji:deciduous-tree[]+`
a| [.small]`+emoji:chestnut[]+`
a| [.small]`+emoji:seedling[]+`
a| [.small]`+emoji:blossom[]+`

a| [.small]`+emoji:ear-of-rice[]+`
a| [.small]`+emoji:shell[]+`
a| [.small]`+emoji:globe-with-meridians[]+`
a| [.small]`+emoji:sun-with-face[]+`

a| [.small]`+emoji:full-moon-with-face[]+`
a| [.small]`+emoji:new-moon-with-face[]+`
a| [.small]`+emoji:new-moon[]+`
a| [.small]`+emoji:waxing-crescent-moon[]+`

a| [.small]`+emoji:first-quarter-moon[]+`
a| [.small]`+emoji:waxing-gibbous-moon[]+`
a| [.small]`+emoji:full-moon[]+`
a| [.small]`+emoji:waning-gibbous-moon[]+`

a| [.small]`+emoji:last-quarter-moon[]+`
a| [.small]`+emoji:waning-crescent-moon[]+`
a| [.small]`+emoji:last-quarter-moon-with-face[]+`
a| [.small]`+emoji:first-quarter-moon-with-face[]+`

a| [.small]`+emoji:moon[]+`
a| [.small]`+emoji:earth-africa[]+`
a| [.small]`+emoji:earth-americas[]+`
a| [.small]`+emoji:earth-asia[]+`

a| [.small]`+emoji:volcano[]+`
a| [.small]`+emoji:milky-way[]+`
a| [.small]`+emoji:partly-sunny[]+`
a| [.small]`+emoji:bamboo[]+`

a| [.small]`+emoji:gift-heart[]+`
a| [.small]`+emoji:dolls[]+`
a| [.small]`+emoji:school-satchel[]+`
a| [.small]`+emoji:mortar-board[]+`

a| [.small]`+emoji:flags[]+`
a| [.small]`+emoji:fireworks[]+`
a| [.small]`+emoji:sparkler[]+`
a| [.small]`+emoji:wind-chime[]+`

a| [.small]`+emoji:rice-scene[]+`
a| [.small]`+emoji:jack-o-lantern[]+`
a| [.small]`+emoji:ghost[]+`
a| [.small]`+emoji:santa[]+`

a| [.small]`+emoji:8ball[]+`
a| [.small]`+emoji:alarm-clock[]+`
a| [.small]`+emoji:apple[]+`
a| [.small]`+emoji:art[]+`

a| [.small]`+emoji:baby-bottle[]+`
a| [.small]`+emoji:balloon[]+`
a| [.small]`+emoji:banana[]+`
a| [.small]`+emoji:bar-chart[]+`

a| [.small]`+emoji:baseball[]+`
a| [.small]`+emoji:basketball[]+`
a| [.small]`+emoji:bath[]+`
a| [.small]`+emoji:bathtub[]+`

a| [.small]`+emoji:battery[]+`
a| [.small]`+emoji:beer[]+`
a| [.small]`+emoji:beers[]+`
a| [.small]`+emoji:bell[]+`

a| [.small]`+emoji:bento[]+`
a| [.small]`+emoji:bicyclist[]+`
a| [.small]`+emoji:bikini[]+`
a| [.small]`+emoji:birthday[]+`

a| [.small]`+emoji:black-joker[]+`
a| [.small]`+emoji:black-nib[]+`
a| [.small]`+emoji:blue-book[]+`
a| [.small]`+emoji:bomb[]+`

a| [.small]`+emoji:bookmark[]+`
a| [.small]`+emoji:bookmark-tabs[]+`
a| [.small]`+emoji:books[]+`
a| [.small]`+emoji:boot[]+`

a| [.small]`+emoji:bowling[]+`
a| [.small]`+emoji:bread[]+`
a| [.small]`+emoji:briefcase[]+`
a| [.small]`+emoji:bulb[]+`

a| [.small]`+emoji:cake[]+`
a| [.small]`+emoji:calendar[]+`
a| [.small]`+emoji:calling[]+`
a| [.small]`+emoji:camera[]+`

a| [.small]`+emoji:candy[]+`
a| [.small]`+emoji:card-index[]+`
a| [.small]`+emoji:cd[]+`
a| [.small]`+emoji:chart-with-downwards-trend[]+`

a| [.small]`+emoji:chart-with-upwards-trend[]+`
a| [.small]`+emoji:cherries[]+`
a| [.small]`+emoji:chocolate-bar[]+`
a| [.small]`+emoji:christmas-tree[]+`

a| [.small]`+emoji:clapper[]+`
a| [.small]`+emoji:clipboard[]+`
a| [.small]`+emoji:closed-book[]+`
a| [.small]`+emoji:closed-lock-with-key[]+`

a| [.small]`+emoji:closed-umbrella[]+`
a| [.small]`+emoji:clubs[]+`
a| [.small]`+emoji:cocktail[]+`
a| [.small]`+emoji:coffee[]+`

a| [.small]`+emoji:computer[]+`
a| [.small]`+emoji:confetti-ball[]+`
a| [.small]`+emoji:cookie[]+`
a| [.small]`+emoji:corn[]+`

a| [.small]`+emoji:credit-card[]+`
a| [.small]`+emoji:crown[]+`
a| [.small]`+emoji:crystal-ball[]+`
a| [.small]`+emoji:curry[]+`

a| [.small]`+emoji:custard[]+`
a| [.small]`+emoji:dango[]+`
a| [.small]`+emoji:dart[]+`
a| [.small]`+emoji:date[]+`

a| [.small]`+emoji:diamonds[]+`
a| [.small]`+emoji:dollar[]+`
a| [.small]`+emoji:door[]+`
a| [.small]`+emoji:doughnut[]+`

a| [.small]`+emoji:dress[]+`
a| [.small]`+emoji:dvd[]+`
a| [.small]`+emoji:e-mail[]+`
a| [.small]`+emoji:egg[]+`

a| [.small]`+emoji:eggplant[]+`
a| [.small]`+emoji:electric-plug[]+`
a| [.small]`+emoji:email[]+`
a| [.small]`+emoji:euro[]+`

a| [.small]`+emoji:eyeglasses[]+`
a| [.small]`+emoji:fax[]+`
a| [.small]`+emoji:file-folder[]+`
a| [.small]`+emoji:fish-cake[]+`

a| [.small]`+emoji:fishing-pole-and-fish[]+`
a| [.small]`+emoji:flashlight[]+`
a| [.small]`+emoji:floppy-disk[]+`
a| [.small]`+emoji:flower-playing-cards[]+`

a| [.small]`+emoji:football[]+`
a| [.small]`+emoji:fork-and-knife[]+`
a| [.small]`+emoji:fried-shrimp[]+`
a| [.small]`+emoji:fries[]+`

a| [.small]`+emoji:game-die[]+`
a| [.small]`+emoji:gem[]+`
a| [.small]`+emoji:gift[]+`
a| [.small]`+emoji:golf[]+`

a| [.small]`+emoji:grapes[]+`
a| [.small]`+emoji:green-apple[]+`
a| [.small]`+emoji:green-book[]+`
a| [.small]`+emoji:guitar[]+`

a| [.small]`+emoji:gun[]+`
a| [.small]`+emoji:hamburger[]+`
a| [.small]`+emoji:hammer[]+`
a| [.small]`+emoji:handbag[]+`

a| [.small]`+emoji:headphones[]+`
a| [.small]`+emoji:hearts[]+`
a| [.small]`+emoji:high-brightness[]+`
a| [.small]`+emoji:high-heel[]+`

a| [.small]`+emoji:hocho[]+`
a| [.small]`+emoji:honey-pot[]+`
a| [.small]`+emoji:horse-racing[]+`
a| [.small]`+emoji:hourglass[]+`

a| [.small]`+emoji:hourglass-flowing-sand[]+`
a| [.small]`+emoji:ice-cream[]+`
a| [.small]`+emoji:icecream[]+`
a| [.small]`+emoji:inbox-tray[]+`

a| [.small]`+emoji:incoming-envelope[]+`
a| [.small]`+emoji:iphone[]+`
a| [.small]`+emoji:jeans[]+`
a| [.small]`+emoji:key[]+`

a| [.small]`+emoji:kimono[]+`
a| [.small]`+emoji:ledger[]+`
a| [.small]`+emoji:lemon[]+`
a| [.small]`+emoji:lipstick[]+`

a| [.small]`+emoji:lock[]+`
a| [.small]`+emoji:lock-with-ink-pen[]+`
a| [.small]`+emoji:lollipop[]+`
a| [.small]`+emoji:loop[]+`

a| [.small]`+emoji:loudspeaker[]+`
a| [.small]`+emoji:low-brightness[]+`
a| [.small]`+emoji:mag[]+`
a| [.small]`+emoji:mag-right[]+`

a| [.small]`+emoji:mahjong[]+`
a| [.small]`+emoji:mailbox[]+`
a| [.small]`+emoji:mailbox-closed[]+`
a| [.small]`+emoji:mailbox-with-mail[]+`

a| [.small]`+emoji:mailbox-with-no-mail[]+`
a| [.small]`+emoji:mans-shoe[]+`
a| [.small]`+emoji:meat-on-bone[]+`
a| [.small]`+emoji:mega[]+`

a| [.small]`+emoji:melon[]+`
a| [.small]`+emoji:memo[]+`
a| [.small]`+emoji:microphone[]+`
a| [.small]`+emoji:microscope[]+`

a| [.small]`+emoji:minidisc[]+`
a| [.small]`+emoji:money-with-wings[]+`
a| [.small]`+emoji:moneybag[]+`
a| [.small]`+emoji:mountain-bicyclist[]+`

a| [.small]`+emoji:movie-camera[]+`
a| [.small]`+emoji:musical-keyboard[]+`
a| [.small]`+emoji:musical-score[]+`
a| [.small]`+emoji:mute[]+`

a| [.small]`+emoji:name-badge[]+`
a| [.small]`+emoji:necktie[]+`
a| [.small]`+emoji:newspaper[]+`
a| [.small]`+emoji:no-bell[]+`

a| [.small]`+emoji:notebook[]+`
a| [.small]`+emoji:notebook-with-decorative-cover[]+`
a| [.small]`+emoji:nut-and-bolt[]+`
a| [.small]`+emoji:oden[]+`

a| [.small]`+emoji:open-file-folder[]+`
a| [.small]`+emoji:orange-book[]+`
a| [.small]`+emoji:outbox-tray[]+`
a| [.small]`+emoji:page-facing-up[]+`

a| [.small]`+emoji:page-with-curl[]+`
a| [.small]`+emoji:pager[]+`
a| [.small]`+emoji:paperclip[]+`
a| [.small]`+emoji:peach[]+`

a| [.small]`+emoji:pear[]+`
a| [.small]`+emoji:pencil2[]+`
a| [.small]`+emoji:phone[]+`
a| [.small]`+emoji:pill[]+`

a| [.small]`+emoji:pineapple[]+`
a| [.small]`+emoji:pizza[]+`
a| [.small]`+emoji:postal-horn[]+`
a| [.small]`+emoji:postbox[]+`

a| [.small]`+emoji:pouch[]+`
a| [.small]`+emoji:poultry-leg[]+`
a| [.small]`+emoji:pound[]+`
a| [.small]`+emoji:purse[]+`

a| [.small]`+emoji:pushpin[]+`
a| [.small]`+emoji:radio[]+`
a| [.small]`+emoji:ramen[]+`
a| [.small]`+emoji:ribbon[]+`

a| [.small]`+emoji:rice[]+`
a| [.small]`+emoji:rice-ball[]+`
a| [.small]`+emoji:rice-cracker[]+`
a| [.small]`+emoji:ring[]+`

a| [.small]`+emoji:rugby-football[]+`
a| [.small]`+emoji:running-shirt-with-sash[]+`
a| [.small]`+emoji:sake[]+`
a| [.small]`+emoji:sandal[]+`

a| [.small]`+emoji:satellite[]+`
a| [.small]`+emoji:saxophone[]+`
a| [.small]`+emoji:scissors[]+`
a| [.small]`+emoji:scroll[]+`

a| [.small]`+emoji:seat[]+`
a| [.small]`+emoji:shaved-ice[]+`
a| [.small]`+emoji:shirt[]+`
a| [.small]`+emoji:shower[]+`

a| [.small]`+emoji:ski[]+`
a| [.small]`+emoji:smoking[]+`
a| [.small]`+emoji:snowboarder[]+`
a| [.small]`+emoji:soccer[]+`

a| [.small]`+emoji:sound[]+`
a| [.small]`+emoji:space-invader[]+`
a| [.small]`+emoji:spades[]+`
a| [.small]`+emoji:spaghetti[]+`

a| [.small]`+emoji:speaker[]+`
a| [.small]`+emoji:stew[]+`
a| [.small]`+emoji:straight-ruler[]+`
a| [.small]`+emoji:strawberry[]+`

a| [.small]`+emoji:surfer[]+`
a| [.small]`+emoji:sushi[]+`
a| [.small]`+emoji:sweet-potato[]+`
a| [.small]`+emoji:swimmer[]+`

a| [.small]`+emoji:syringe[]+`
a| [.small]`+emoji:tada[]+`
a| [.small]`+emoji:tanabata-tree[]+`
a| [.small]`+emoji:tangerine[]+`

a| [.small]`+emoji:tea[]+`
a| [.small]`+emoji:telephone-receiver[]+`
a| [.small]`+emoji:telescope[]+`
a| [.small]`+emoji:tennis[]+`

a| [.small]`+emoji:toilet[]+`
a| [.small]`+emoji:tomato[]+`
a| [.small]`+emoji:tophat[]+`
a| [.small]`+emoji:triangular-ruler[]+`

a| [.small]`+emoji:trophy[]+`
a| [.small]`+emoji:tropical-drink[]+`
a| [.small]`+emoji:trumpet[]+`
a| [.small]`+emoji:tv[]+`

a| [.small]`+emoji:unlock[]+`
a| [.small]`+emoji:vhs[]+`
a| [.small]`+emoji:video-camera[]+`
a| [.small]`+emoji:video-game[]+`

a| [.small]`+emoji:violin[]+`
a| [.small]`+emoji:watch[]+`
a| [.small]`+emoji:watermelon[]+`
a| [.small]`+emoji:wine-glass[]+`

a| [.small]`+emoji:womans-clothes[]+`
a| [.small]`+emoji:womans-hat[]+`
a| [.small]`+emoji:wrench[]+`
a| [.small]`+emoji:yen[]+`

a| [.small]`+emoji:aerial-tramway[]+`
a| [.small]`+emoji:airplane[]+`
a| [.small]`+emoji:ambulance[]+`
a| [.small]`+emoji:anchor[]+`

a| [.small]`+emoji:articulated-lorry[]+`
a| [.small]`+emoji:atm[]+`
a| [.small]`+emoji:bank[]+`
a| [.small]`+emoji:barber[]+`

a| [.small]`+emoji:beginner[]+`
a| [.small]`+emoji:bike[]+`
a| [.small]`+emoji:blue-car[]+`
a| [.small]`+emoji:boat[]+`

a| [.small]`+emoji:bridge-at-night[]+`
a| [.small]`+emoji:bullettrain-front[]+`
a| [.small]`+emoji:bullettrain-side[]+`
a| [.small]`+emoji:bus[]+`

a| [.small]`+emoji:busstop[]+`
a| [.small]`+emoji:car[]+`
a| [.small]`+emoji:carousel-horse[]+`
a| [.small]`+emoji:checkered-flag[]+`

a| [.small]`+emoji:church[]+`
a| [.small]`+emoji:circus-tent[]+`
a| [.small]`+emoji:city-sunrise[]+`
a| [.small]`+emoji:city-sunset[]+`

a| [.small]`+emoji:construction[]+`
a| [.small]`+emoji:convenience-store[]+`
a| [.small]`+emoji:crossed-flags[]+`
a| [.small]`+emoji:department-store[]+`

a| [.small]`+emoji:european-castle[]+`
a| [.small]`+emoji:european-post-office[]+`
a| [.small]`+emoji:factory[]+`
a| [.small]`+emoji:ferris-wheel[]+`

a| [.small]`+emoji:fire-engine[]+`
a| [.small]`+emoji:fountain[]+`
a| [.small]`+emoji:fuelpump[]+`
a| [.small]`+emoji:helicopter[]+`

a| [.small]`+emoji:hospital[]+`
a| [.small]`+emoji:hotel[]+`
a| [.small]`+emoji:hotsprings[]+`
a| [.small]`+emoji:house[]+`

a| [.small]`+emoji:house-with-garden[]+`
a| [.small]`+emoji:japan[]+`
a| [.small]`+emoji:japanese-castle[]+`
a| [.small]`+emoji:light-rail[]+`

a| [.small]`+emoji:love-hotel[]+`
a| [.small]`+emoji:minibus[]+`
a| [.small]`+emoji:monorail[]+`
a| [.small]`+emoji:mount-fuji[]+`

a| [.small]`+emoji:mountain-cableway[]+`
a| [.small]`+emoji:mountain-railway[]+`
a| [.small]`+emoji:moyai[]+`
a| [.small]`+emoji:office[]+`

a| [.small]`+emoji:oncoming-automobile[]+`
a| [.small]`+emoji:oncoming-bus[]+`
a| [.small]`+emoji:oncoming-police-car[]+`
a| [.small]`+emoji:oncoming-taxi[]+`

a| [.small]`+emoji:performing-arts[]+`
a| [.small]`+emoji:police-car[]+`
a| [.small]`+emoji:post-office[]+`
a| [.small]`+emoji:railway-car[]+`

a| [.small]`+emoji:rainbow[]+`
a| [.small]`+emoji:rocket[]+`
a| [.small]`+emoji:roller-coaster[]+`
a| [.small]`+emoji:rotating-light[]+`

a| [.small]`+emoji:round-pushpin[]+`
a| [.small]`+emoji:rowboat[]+`
a| [.small]`+emoji:school[]+`
a| [.small]`+emoji:ship[]+`

a| [.small]`+emoji:slot-machine[]+`
a| [.small]`+emoji:speedboat[]+`
a| [.small]`+emoji:stars[]+`
a| [.small]`+emoji:station[]+`

a| [.small]`+emoji:statue-of-liberty[]+`
a| [.small]`+emoji:steam-locomotive[]+`
a| [.small]`+emoji:sunrise[]+`
a| [.small]`+emoji:sunrise-over-mountains[]+`

a| [.small]`+emoji:suspension-railway[]+`
a| [.small]`+emoji:taxi[]+`
a| [.small]`+emoji:tent[]+`
a| [.small]`+emoji:ticket[]+`

a| [.small]`+emoji:tokyo-tower[]+`
a| [.small]`+emoji:tractor[]+`
a| [.small]`+emoji:traffic-light[]+`
a| [.small]`+emoji:train2[]+`

a| [.small]`+emoji:tram[]+`
a| [.small]`+emoji:triangular-flag-on-post[]+`
a| [.small]`+emoji:trolleybus[]+`
a| [.small]`+emoji:truck[]+`

a| [.small]`+emoji:vertical-traffic-light[]+`
a| [.small]`+emoji:warning[]+`
a| [.small]`+emoji:wedding[]+`
a| [.small]`+emoji:jp[]+`

a| [.small]`+emoji:kr[]+`
a| [.small]`+emoji:cn[]+`
a| [.small]`+emoji:us[]+`
a| [.small]`+emoji:fr[]+`

a| [.small]`+emoji:es[]+`
a| [.small]`+emoji:it[]+`
a| [.small]`+emoji:ru[]+`
a| [.small]`+emoji:gb[]+`

a| [.small]`+emoji:de[]+`
a| [.small]`+emoji:100[]+`
a| [.small]`+emoji:1234[]+`
a| [.small]`+emoji:a[]+`

a| [.small]`+emoji:ab[]+`
a| [.small]`+emoji:abc[]+`
a| [.small]`+emoji:abcd[]+`
a| [.small]`+emoji:accept[]+`

a| [.small]`+emoji:aquarius[]+`
a| [.small]`+emoji:aries[]+`
a| [.small]`+emoji:arrow-backward[]+`
a| [.small]`+emoji:arrow-double-down[]+`

a| [.small]`+emoji:arrow-double-up[]+`
a| [.small]`+emoji:arrow-down[]+`
a| [.small]`+emoji:arrow-down-small[]+`
a| [.small]`+emoji:arrow-forward[]+`

a| [.small]`+emoji:arrow-heading-down[]+`
a| [.small]`+emoji:arrow-heading-up[]+`
a| [.small]`+emoji:arrow-left[]+`
a| [.small]`+emoji:arrow-lower-left[]+`

a| [.small]`+emoji:arrow-lower-right[]+`
a| [.small]`+emoji:arrow-right[]+`
a| [.small]`+emoji:arrow-right-hook[]+`
a| [.small]`+emoji:arrow-up[]+`

a| [.small]`+emoji:arrow-up-down[]+`
a| [.small]`+emoji:arrow-up-small[]+`
a| [.small]`+emoji:arrow-upper-left[]+`
a| [.small]`+emoji:arrow-upper-right[]+`

a| [.small]`+emoji:arrows-clockwise[]+`
a| [.small]`+emoji:arrows-counterclockwise[]+`
a| [.small]`+emoji:b[]+`
a| [.small]`+emoji:baby-symbol[]+`

a| [.small]`+emoji:baggage-claim[]+`
a| [.small]`+emoji:ballot-box-with-check[]+`
a| [.small]`+emoji:bangbang[]+`
a| [.small]`+emoji:black-circle[]+`

a| [.small]`+emoji:black-square-button[]+`
a| [.small]`+emoji:cancer[]+`
a| [.small]`+emoji:capital-abcd[]+`
a| [.small]`+emoji:capricorn[]+`

a| [.small]`+emoji:chart[]+`
a| [.small]`+emoji:children-crossing[]+`
a| [.small]`+emoji:cinema[]+`
a| [.small]`+emoji:cl[]+`

a| [.small]`+emoji:clock1[]+`
a| [.small]`+emoji:clock10[]+`
a| [.small]`+emoji:clock1030[]+`
a| [.small]`+emoji:clock11[]+`

a| [.small]`+emoji:clock1130[]+`
a| [.small]`+emoji:clock12[]+`
a| [.small]`+emoji:clock1230[]+`
a| [.small]`+emoji:clock130[]+`

a| [.small]`+emoji:clock2[]+`
a| [.small]`+emoji:clock230[]+`
a| [.small]`+emoji:clock3[]+`
a| [.small]`+emoji:clock330[]+`

a| [.small]`+emoji:clock4[]+`
a| [.small]`+emoji:clock430[]+`
a| [.small]`+emoji:clock5[]+`
a| [.small]`+emoji:clock530[]+`

a| [.small]`+emoji:clock6[]+`
a| [.small]`+emoji:clock630[]+`
a| [.small]`+emoji:clock7[]+`
a| [.small]`+emoji:clock730[]+`

a| [.small]`+emoji:clock8[]+`
a| [.small]`+emoji:clock830[]+`
a| [.small]`+emoji:clock9[]+`
a| [.small]`+emoji:clock930[]+`

a| [.small]`+emoji:congratulations[]+`
a| [.small]`+emoji:cool[]+`
a| [.small]`+emoji:copyright[]+`
a| [.small]`+emoji:curly-loop[]+`

a| [.small]`+emoji:currency-exchange[]+`
a| [.small]`+emoji:customs[]+`
a| [.small]`+emoji:diamond-shape-with-a-dot-inside[]+`
a| [.small]`+emoji:do-not-litter[]+`

a| [.small]`+emoji:eight[]+`
a| [.small]`+emoji:eight-pointed-black-star[]+`
a| [.small]`+emoji:eight-spoked-asterisk[]+`
a| [.small]`+emoji:end[]+`

a| [.small]`+emoji:fast-forward[]+`
a| [.small]`+emoji:five[]+`
a| [.small]`+emoji:four[]+`
a| [.small]`+emoji:free[]+`

a| [.small]`+emoji:gemini[]+`
a| [.small]`+emoji:hash[]+`
a| [.small]`+emoji:heart-decoration[]+`
a| [.small]`+emoji:heavy-check-mark[]+`

a| [.small]`+emoji:heavy-division-sign[]+`
a| [.small]`+emoji:heavy-dollar-sign[]+`
a| [.small]`+emoji:heavy-minus-sign[]+`
a| [.small]`+emoji:heavy-multiplication-x[]+`

a| [.small]`+emoji:heavy-plus-sign[]+`
a| [.small]`+emoji:id[]+`
a| [.small]`+emoji:ideograph-advantage[]+`
a| [.small]`+emoji:information-source[]+`

a| [.small]`+emoji:interrobang[]+`
a| [.small]`+emoji:keycap-ten[]+`
a| [.small]`+emoji:koko[]+`
a| [.small]`+emoji:large-blue-circle[]+`

a| [.small]`+emoji:large-blue-diamond[]+`
a| [.small]`+emoji:large-orange-diamond[]+`
a| [.small]`+emoji:left-luggage[]+`
a| [.small]`+emoji:left-right-arrow[]+`

a| [.small]`+emoji:leftwards-arrow-with-hook[]+`
a| [.small]`+emoji:leo[]+`
a| [.small]`+emoji:libra[]+`
a| [.small]`+emoji:link[]+`

a| [.small]`+emoji:m[]+`
a| [.small]`+emoji:mens[]+`
a| [.small]`+emoji:metro[]+`
a| [.small]`+emoji:mobile-phone-off[]+`

a| [.small]`+emoji:negative-squared-cross-mark[]+`
a| [.small]`+emoji:new[]+`
a| [.small]`+emoji:ng[]+`
a| [.small]`+emoji:nine[]+`

a| [.small]`+emoji:no-bicycles[]+`
a| [.small]`+emoji:no-entry[]+`
a| [.small]`+emoji:no-entry-sign[]+`
a| [.small]`+emoji:no-mobile-phones[]+`

a| [.small]`+emoji:no-pedestrians[]+`
a| [.small]`+emoji:no-smoking[]+`
a| [.small]`+emoji:non-potable-water[]+`
a| [.small]`+emoji:o[]+`

a| [.small]`+emoji:o2[]+`
a| [.small]`+emoji:ok[]+`
a| [.small]`+emoji:on[]+`
a| [.small]`+emoji:one[]+`

a| [.small]`+emoji:ophiuchus[]+`
a| [.small]`+emoji:parking[]+`
a| [.small]`+emoji:part-alternation-mark[]+`
a| [.small]`+emoji:passport-control[]+`

a| [.small]`+emoji:pisces[]+`
a| [.small]`+emoji:potable-water[]+`
a| [.small]`+emoji:put-litter-in-its-place[]+`
a| [.small]`+emoji:radio-button[]+`

a| [.small]`+emoji:recycle[]+`
a| [.small]`+emoji:red-circle[]+`
a| [.small]`+emoji:registered[]+`
a| [.small]`+emoji:repeat[]+`

a| [.small]`+emoji:repeat-one[]+`
a| [.small]`+emoji:restroom[]+`
a| [.small]`+emoji:rewind[]+`
a| [.small]`+emoji:sa[]+`

a| [.small]`+emoji:sagittarius[]+`
a| [.small]`+emoji:scorpius[]+`
a| [.small]`+emoji:secret[]+`
a| [.small]`+emoji:seven[]+`

a| [.small]`+emoji:signal-strength[]+`
a| [.small]`+emoji:six[]+`
a| [.small]`+emoji:six-pointed-star[]+`
a| [.small]`+emoji:small-blue-diamond[]+`

a| [.small]`+emoji:small-orange-diamond[]+`
a| [.small]`+emoji:small-red-triangle[]+`
a| [.small]`+emoji:small-red-triangle-down[]+`
a| [.small]`+emoji:soon[]+`

a| [.small]`+emoji:sos[]+`
a| [.small]`+emoji:symbols[]+`
a| [.small]`+emoji:taurus[]+`
a| [.small]`+emoji:three[]+`

a| [.small]`+emoji:tm[]+`
a| [.small]`+emoji:top[]+`
a| [.small]`+emoji:trident[]+`
a| [.small]`+emoji:twisted-rightwards-arrows[]+`

a| [.small]`+emoji:two[]+`
a| [.small]`+emoji:u5272[]+`
a| [.small]`+emoji:u5408[]+`
a| [.small]`+emoji:u55b6[]+`

a| [.small]`+emoji:u6307[]+`
a| [.small]`+emoji:u6708[]+`
a| [.small]`+emoji:u6709[]+`
a| [.small]`+emoji:u6e80[]+`

a| [.small]`+emoji:u7121[]+`
a| [.small]`+emoji:u7533[]+`
a| [.small]`+emoji:u7981[]+`
a| [.small]`+emoji:u7a7a[]+`

a| [.small]`+emoji:underage[]+`
a| [.small]`+emoji:up[]+`
a| [.small]`+emoji:vibration-mode[]+`
a| [.small]`+emoji:virgo[]+`

a| [.small]`+emoji:vs[]+`
a| [.small]`+emoji:wavy-dash[]+`
a| [.small]`+emoji:wc[]+`
a| [.small]`+emoji:wheelchair[]+`

a| [.small]`+emoji:white-check-mark[]+`
a| [.small]`+emoji:white-circle[]+`
a| [.small]`+emoji:white-flower[]+`
a| [.small]`+emoji:white-square-button[]+`

a| [.small]`+emoji:womens[]+`
a| [.small]`+emoji:x[]+`
a| [.small]`+emoji:zero[]+`
a|
|===
