= Emoji Cheat Sheet
:author: mitm
:revnumber:
:revdate: 2019-12-18T23:24:11.262Z
:stylesheet: twemoji-awesome.css
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

== How to use emoji in the wiki

Using emoji in wiki docs currently requires the setting of the `:stylesheet:` attribute in the header of the wiki document.

```
:stylesheet: twemoji-awesome.css
```
The <<wiki/wiki_header.adoc#,Anatomy of a Wiki Header>> document exlains setting of this and other header attributes.

Once the header attribute is set, you can add the emoji using the following syntax.

```
emoji:heart[2x] // the "[2x]" is a size modifier
emoji:rage[]
```

[NOTE]
====
You can change the icon size with the size modifier `[2x]`.

`+emoji:heart[]+` emoji:heart[] `+emoji:heart[2x]+` emoji:heart[2x]
====

== Emoji and Names

=== People

[cols=3*, frame=none, grid=none]
|===
a| emoji:smile[2x] [.small]`smile` +
emoji:smiley[2x] [.small]`smiley` +
emoji:heart-eyes[2x] [.small]`heart-eyes` +
emoji:flushed[2x] [.small]`flushed` +
emoji:grin[2x] [.small]`grin` +
emoji:stuck-out-tongue-closed-eyes[2x] [.small]`stuck-out-tongue-closed-eyes` +
emoji:kissing-smiling-eyes[2x] [.small]`kissing-smiling-eyes` +
emoji:worried[2x] [.small]`worried` +
emoji:open-mouth[2x] [.small]`open-mouth` +
emoji:hushed[2x] [.small]`hushed` +
emoji:sweat-smile[2x] [.small]`sweat-smile` +
emoji:pensive[2x] [.small]`pensive` +
emoji:fearful[2x] [.small]`fearful` +
emoji:cry[2x] [.small]`cry` +
emoji:astonished[2x] [.small]`astonished` +
emoji:angry[2x] [.small]`angry` +
emoji:sleepy[2x] [.small]`sleepy` +
emoji:sunglasses[2x] [.small]`sunglasses` +
emoji:smiling-imp[2x] [.small]`smiling-imp` +
emoji:innocent[2x] [.small]`innocent` +
emoji:blue-heart[2x] [.small]`blue-heart` +
emoji:green-heart[2x] [.small]`green-heart` +
emoji:heartpulse[2x] [.small]`heartpulse` +
emoji:cupid[2x] [.small]`cupid` +
emoji:star[2x] [.small]`star` +
emoji:boom[2x] [.small]`boom` +
emoji:question[2x] [.small]`question` +
emoji:zzz[2x] [.small]`zzz` +
emoji:notes[2x] [.small]`notes` +
emoji:poop[2x] [.small]`poop` +
emoji:ok-hand[2x] [.small]`ok-hand` +
emoji:v[2x] [.small]`v` +
emoji:open-hands[2x] [.small]`open-hands` +
emoji:point-left[2x] [.small]`point-left` +
emoji:pray[2x] [.small]`pray` +
emoji:muscle[2x] [.small]`muscle` +
emoji:couple[2x] [.small]`couple` +
emoji:dancers[2x] [.small]`dancers` +
emoji:information-desk-person[2x] [.small]`information-desk-person` +
emoji:person-with-pouting-face[2x] [.small]`person-with-pouting-face` +
emoji:couplekiss[2x] [.small]`couplekiss` +
emoji:haircut[2x] [.small]`haircut` +
emoji:girl[2x] [.small]`girl` +
emoji:baby[2x] [.small]`baby` +
emoji:person-with-blond-hair[2x] [.small]`person-with-blond-hair` +
emoji:construction-worker[2x] [.small]`construction-worker` +
emoji:princess[2x] [.small]`princess` +
emoji:heart-eyes-cat[2x] [.small]`heart-eyes-cat` +
emoji:scream-cat[2x] [.small]`scream-cat` +
emoji:pouting-cat[2x] [.small]`pouting-cat` +
emoji:see-no-evil[2x] [.small]`see-no-evil` +
emoji:guardsman[2x] [.small]`guardsman` +
emoji:lips[2x] [.small]`lips` +
emoji:ear[2x] [.small]`ear` +
emoji:tongue[2x] [.small]`tongue` +
emoji:busts-in-silhouette[2x] [.small]`busts-in-silhouette` +

a| emoji:laughing[2x] [.small]`laughing` +
emoji:relaxed[2x] [.small]`relaxed` +
emoji:kissing-heart[2x] [.small]`kissing-heart` +
emoji:relieved[2x] [.small]`relieved` +
emoji:wink[2x] [.small]`wink` +
emoji:grinning[2x] [.small]`grinning` +
emoji:stuck-out-tongue[2x] [.small]`stuck-out-tongue` +
emoji:frowning[2x] [.small]`frowning` +
emoji:grimacing[2x] [.small]`grimacing` +
emoji:expressionless[2x] [.small]`expressionless` +
emoji:sweat[2x] [.small]`sweat` +
emoji:disappointed[2x] [.small]`disappointed` +
emoji:cold-sweat[2x] [.small]`cold-sweat` +
emoji:sob[2x] [.small]`sob` +
emoji:scream[2x] [.small]`scream` +
emoji:rage[2x] [.small]`rage` +
emoji:yum[2x] [.small]`yum` +
emoji:dizzy-face[2x] [.small]`dizzy-face` +
emoji:neutral-face[2x] [.small]`neutral-face` +
emoji:alien[2x] [.small]`alien` +
emoji:purple-heart[2x] [.small]`purple-heart` +
emoji:broken-heart[2x] [.small]`broken-heart` +
emoji:two-hearts[2x] [.small]`two-hearts` +
emoji:sparkling-heart[2x] [.small]`sparkling-heart` +
emoji:star2[2x] [.small]`star2` +
emoji:anger[2x] [.small]`anger` +
emoji:grey-exclamation[2x] [.small]`grey-exclamation` +
emoji:dash[2x] [.small]`dash` +
emoji:musical-note[2x] [.small]`musical-note` +
emoji:thumbsup[2x] [.small]`thumbsup` +
emoji:punch[2x] [.small]`punch` +
emoji:wave[2x] [.small]`wave` +
emoji:point-up[2x] [.small]`point-up` +
emoji:point-right[2x] [.small]`point-right` +
emoji:point-up-2[2x] [.small]`point-up-2` +
emoji:walking[2x] [.small]`walking` +
emoji:family[2x] [.small]`family` +
emoji:ok-woman[2x] [.small]`ok-woman` +
emoji:raised-hand[2x] [.small]`raised-hand` +
emoji:person-frowning[2x] [.small]`person-frowning` +
emoji:couple-with-heart[2x] [.small]`couple-with-heart` +
emoji:nail-care[2x] [.small]`nail-care` +
emoji:woman[2x] [.small]`woman` +
emoji:older-woman[2x] [.small]`older-woman` +
emoji:man-with-gua-pi-mao[2x] [.small]`man-with-gua-pi-mao` +
emoji:cop[2x] [.small]`cop` +
emoji:smiley-cat[2x] [.small]`smiley-cat` +
emoji:kissing-cat[2x] [.small]`kissing-cat` +
emoji:crying-cat-face[2x] [.small]`crying-cat-face` +
emoji:japanese-ogre[2x] [.small]`japanese-ogre` +
emoji:hear-no-evil[2x] [.small]`hear-no-evil` +
emoji:skull[2x] [.small]`skull` +
emoji:kiss[2x] [.small]`kiss` +
emoji:eyes[2x] [.small]`eyes` +
emoji:love-letter[2x] [.small]`love-letter` +
emoji:speech-balloon[2x] [.small]`speech-balloon` +

a| emoji:blush[2x] [.small]`blush` +
emoji:smirk[2x] [.small]`smirk` +
emoji:kissing-closed-eyes[2x] [.small]`kissing-closed-eyes` +
emoji:satisfied[2x] [.small]`satisfied` +
emoji:stuck-out-tongue-winking-eye[2x] [.small]`stuck-out-tongue-winking-eye` +
emoji:kissing[2x] [.small]`kissing` +
emoji:sleeping[2x] [.small]`sleeping` +
emoji:anguished[2x] [.small]`anguished` +
emoji:confused[2x] [.small]`confused` +
emoji:unamused[2x] [.small]`unamused` +
emoji:weary[2x] [.small]`weary` +
emoji:confounded[2x] [.small]`confounded` +
emoji:persevere[2x] [.small]`persevere` +
emoji:joy[2x] [.small]`joy` +
emoji:tired-face[2x] [.small]`tired-face` +
emoji:triumph[2x] [.small]`triumph` +
emoji:mask[2x] [.small]`mask` +
emoji:imp[2x] [.small]`imp` +
emoji:no-mouth[2x] [.small]`no-mouth` +
emoji:yellow-heart[2x] [.small]`yellow-heart` +
emoji:heart[2x] [.small]`heart` +
emoji:heartbeat[2x] [.small]`heartbeat` +
emoji:revolving-hearts[2x] [.small]`revolving-hearts` +
emoji:sparkles[2x] [.small]`sparkles` +
emoji:dizzy[2x] [.small]`dizzy` +
emoji:exclamation[2x] [.small]`exclamation` +
emoji:grey-question[2x] [.small]`grey-question` +
emoji:sweat-drops[2x] [.small]`sweat-drops` +
emoji:fire[2x] [.small]`fire` +
emoji:thumbsdown[2x] [.small]`thumbsdown` +
emoji:fist[2x] [.small]`fist` +
emoji:hand[2x] [.small]`hand` +
emoji:point-down[2x] [.small]`point-down` +
emoji:raised-hands[2x] [.small]`raised-hands` +
emoji:clap[2x] [.small]`clap` +
emoji:runner[2x] [.small]`runner` +
emoji:dancer[2x] [.small]`dancer` +
emoji:no-good[2x] [.small]`no-good` +
emoji:bride-with-veil[2x] [.small]`bride-with-veil` +
emoji:bow[2x] [.small]`bow` +
emoji:massage[2x] [.small]`massage` +
emoji:boy[2x] [.small]`boy` +
emoji:man[2x] [.small]`man` +
emoji:older-man[2x] [.small]`older-man` +
emoji:man-with-turban[2x] [.small]`man-with-turban` +
emoji:angel[2x] [.small]`angel` +
emoji:smile-cat[2x] [.small]`smile-cat` +
emoji:smirk-cat[2x] [.small]`smirk-cat` +
emoji:joy-cat[2x] [.small]`joy-cat` +
emoji:japanese-goblin[2x] [.small]`japanese-goblin` +
emoji:speak-no-evil[2x] [.small]`speak-no-evil` +
emoji:feet[2x] [.small]`feet` +
emoji:droplet[2x] [.small]`droplet` +
emoji:nose[2x] [.small]`nose` +
emoji:bust-in-silhouette[2x] [.small]`bust-in-silhouette` +
emoji:thought-balloon[2x] [.small]`thought-balloon` +
|===

=== Nature

[cols=3*, frame=none, grid=none]
|===
a| emoji:sunny[] [.small]`+emoji:sunny[]+`
a| emoji:umbrella[] [.small]`+emoji:umbrella[]+`
a| emoji:cloud[] [.small]`+emoji:cloud[]+`

a| emoji:snowflake[] [.small]`+emoji:snowflake[]+`
a| emoji:snowman[] [.small]`+emoji:snowman[]+`
a| emoji:zap[] [.small]`+emoji:zap[]+`

a| emoji:cyclone[] [.small]`+emoji:cyclone[]+`
a| emoji:foggy[] [.small]`+emoji:foggy[]+`
a| emoji:ocean[] [.small]`+emoji:ocean[]+`

a| emoji:cat[] [.small]`+emoji:cat[]+`
a| emoji:dog[] [.small]`+emoji:dog[]+`
a| emoji:mouse[] [.small]`+emoji:mouse[]+`

a| emoji:hamster[] [.small]`+emoji:hamster[]+`
a| emoji:rabbit[] [.small]`+emoji:rabbit[]+`
a| emoji:wolf[] [.small]`+emoji:wolf[]+`

a| emoji:frog[] [.small]`+emoji:frog[]+`
a| emoji:tiger[] [.small]`+emoji:tiger[]+`
a| emoji:koala[] [.small]`+emoji:koala[]+`

a| emoji:bear[] [.small]`+emoji:bear[]+`
a| emoji:pig[] [.small]`+emoji:pig[]+`
a| emoji:pig-nose[] [.small]`+emoji:pig-nose[]+`

a| emoji:cow[] [.small]`+emoji:cow[]+`
a| emoji:boar[] [.small]`+emoji:boar[]+`
a| emoji:monkey-face[] [.small]`+emoji:monkey-face[]+`

a| emoji:monkey[] [.small]`+emoji:monkey[]+`
a| emoji:horse[] [.small]`+emoji:horse[]+`
a| emoji:racehorse[] [.small]`+emoji:racehorse[]+`

a| emoji:camel[] [.small]`+emoji:camel[]+`
a| emoji:sheep[] [.small]`+emoji:sheep[]+`
a| emoji:elephant[] [.small]`+emoji:elephant[]+`

a| emoji:panda-face[] [.small]`+emoji:panda-face[]+`
a| emoji:snake[] [.small]`+emoji:snake[]+`
a| emoji:bird[] [.small]`+emoji:bird[]+`

a| emoji:baby-chick[] [.small]`+emoji:baby-chick[]+`
a| emoji:hatched-chick[] [.small]`+emoji:hatched-chick[]+`
a| emoji:hatching-chick[] [.small]`+emoji:hatching-chick[]+`

a| emoji:chicken[] [.small]`+emoji:chicken[]+`
a| emoji:penguin[] [.small]`+emoji:penguin[]+`
a| emoji:turtle[] [.small]`+emoji:turtle[]+`

a| emoji:bug[] [.small]`+emoji:bug[]+`
a| emoji:honeybee[] [.small]`+emoji:honeybee[]+`
a| emoji:ant[] [.small]`+emoji:ant[]+`

a| emoji:beetle[] [.small]`+emoji:beetle[]+`
a| emoji:snail[] [.small]`+emoji:snail[]+`
a| emoji:octopus[] [.small]`+emoji:octopus[]+`

a| emoji:tropical-fish[] [.small]`+emoji:tropical-fish[]+`
a| emoji:fish[] [.small]`+emoji:fish[]+`
a| emoji:whale[] [.small]`+emoji:whale[]+`

a| emoji:whale2[] [.small]`+emoji:whale2[]+`
a| emoji:dolphin[] [.small]`+emoji:dolphin[]+`
a| emoji:cow2[] [.small]`+emoji:cow2[]+`

a| emoji:ram[] [.small]`+emoji:ram[]+`
a| emoji:rat[] [.small]`+emoji:rat[]+`
a| emoji:water-buffalo[] [.small]`+emoji:water-buffalo[]+`

a| emoji:tiger2[] [.small]`+emoji:tiger2[]+`
a| emoji:rabbit2[] [.small]`+emoji:rabbit2[]+`
a| emoji:dragon[] [.small]`+emoji:dragon[]+`

a| emoji:goat[] [.small]`+emoji:goat[]+`
a| emoji:rooster[] [.small]`+emoji:rooster[]+`
a| emoji:dog2[] [.small]`+emoji:dog2[]+`

a| emoji:pig2[] [.small]`+emoji:pig2[]+`
a| emoji:mouse2[] [.small]`+emoji:mouse2[]+`
a| emoji:ox[] [.small]`+emoji:ox[]+`

a| emoji:dragon-face[] [.small]`+emoji:dragon-face[]+`
a| emoji:blowfish[] [.small]`+emoji:blowfish[]+`
a| emoji:crocodile[] [.small]`+emoji:crocodile[]+`

a| emoji:dromedary-camel[] [.small]`+emoji:dromedary-camel[]+`
a| emoji:leopard[] [.small]`+emoji:leopard[]+`
a| emoji:cat2[] [.small]`+emoji:cat2[]+`

a| emoji:poodle[] [.small]`+emoji:poodle[]+`
a| emoji:paw-prints[] [.small]`+emoji:paw-prints[]+`
a| emoji:bouquet[] [.small]`+emoji:bouquet[]+`

a| emoji:cherry-blossom[] [.small]`+emoji:cherry-blossom[]+`
a| emoji:tulip[] [.small]`+emoji:tulip[]+`
a| emoji:four-leaf-clover[] [.small]`+emoji:four-leaf-clover[]+`

a| emoji:rose[] [.small]`+emoji:rose[]+`
a| emoji:sunflower[] [.small]`+emoji:sunflower[]+`
a| emoji:hibiscus[] [.small]`+emoji:hibiscus[]+`

a| emoji:maple-leaf[] [.small]`+emoji:maple-leaf[]+`
a| emoji:leaves[] [.small]`+emoji:leaves[]+`
a| emoji:fallen-leaf[] [.small]`+emoji:fallen-leaf[]+`

a| emoji:herb[] [.small]`+emoji:herb[]+`
a| emoji:mushroom[] [.small]`+emoji:mushroom[]+`
a| emoji:cactus[] [.small]`+emoji:cactus[]+`

a| emoji:palm-tree[] [.small]`+emoji:palm-tree[]+`
a| emoji:evergreen-tree[] [.small]`+emoji:evergreen-tree[]+`
a| emoji:deciduous-tree[] [.small]`+emoji:deciduous-tree[]+`

a| emoji:chestnut[] [.small]`+emoji:chestnut[]+`
a| emoji:seedling[] [.small]`+emoji:seedling[]+`
a| emoji:blossom[] [.small]`+emoji:blossom[]+`

a| emoji:ear-of-rice[] [.small]`+emoji:ear-of-rice[]+`
a| emoji:shell[] [.small]`+emoji:shell[]+`
a| emoji:globe-with-meridians[] [.small]`+emoji:globe-with-meridians[]+`

a| emoji:sun-with-face[] [.small]`+emoji:sun-with-face[]+`
a| emoji:full-moon-with-face[] [.small]`+emoji:full-moon-with-face[]+`
a| emoji:new-moon-with-face[] [.small]`+emoji:new-moon-with-face[]+`

a| emoji:new-moon[] [.small]`+emoji:new-moon[]+`
a| emoji:waxing-crescent-moon[] [.small]`+emoji:waxing-crescent-moon[]+`
a| emoji:first-quarter-moon[] [.small]`+emoji:first-quarter-moon[]+`

a| emoji:waxing-gibbous-moon[] [.small]`+emoji:waxing-gibbous-moon[]+`
a| emoji:full-moon[] [.small]`+emoji:full-moon[]+`
a| emoji:waning-gibbous-moon[] [.small]`+emoji:waning-gibbous-moon[]+`

a| emoji:last-quarter-moon[] [.small]`+emoji:last-quarter-moon[]+`
a| emoji:waning-crescent-moon[] [.small]`+emoji:waning-crescent-moon[]+`
a| emoji:last-quarter-moon-with-face[] [.small]`+emoji:last-quarter-moon-with-face[]+`

a| emoji:first-quarter-moon-with-face[] [.small]`+emoji:first-quarter-moon-with-face[]+`
a| emoji:moon[] [.small]`+emoji:moon[]+`
a| emoji:earth-africa[] [.small]`+emoji:earth-africa[]+`

a| emoji:earth-americas[] [.small]`+emoji:earth-americas[]+`
a| emoji:earth-asia[] [.small]`+emoji:earth-asia[]+`
a| emoji:volcano[] [.small]`+emoji:volcano[]+`

a| emoji:milky-way[] [.small]`+emoji:milky-way[]+`
a| emoji:partly-sunny[] [.small]`+emoji:partly-sunny[]+`
a| emoji:bamboo[] [.small]`+emoji:bamboo[]+`

a| emoji:gift-heart[] [.small]`+emoji:gift-heart[]+`
a| emoji:dolls[] [.small]`+emoji:dolls[]+`
a| emoji:school-satchel[] [.small]`+emoji:school-satchel[]+`

a| emoji:mortar-board[] [.small]`+emoji:mortar-board[]+`
a| emoji:flags[] [.small]`+emoji:flags[]+`
a| emoji:fireworks[] [.small]`+emoji:fireworks[]+`

a| emoji:sparkler[] [.small]`+emoji:sparkler[]+`
a| emoji:wind-chime[] [.small]`+emoji:wind-chime[]+`
a| emoji:rice-scene[] [.small]`+emoji:rice-scene[]+`

a| emoji:jack-o-lantern[] [.small]`+emoji:jack-o-lantern[]+`
a| emoji:ghost[] [.small]`+emoji:ghost[]+`
a| emoji:santa[] [.small]`+emoji:santa[]+`

a| emoji:8ball[] [.small]`+emoji:8ball[]+`
a| emoji:alarm-clock[] [.small]`+emoji:alarm-clock[]+`
a| emoji:apple[] [.small]`+emoji:apple[]+`

a| emoji:art[] [.small]`+emoji:art[]+`
a| emoji:baby-bottle[] [.small]`+emoji:baby-bottle[]+`
a| emoji:balloon[] [.small]`+emoji:balloon[]+`

a| emoji:banana[] [.small]`+emoji:banana[]+`
a| emoji:bar-chart[] [.small]`+emoji:bar-chart[]+`
a| emoji:baseball[] [.small]`+emoji:baseball[]+`

a| emoji:basketball[] [.small]`+emoji:basketball[]+`
a| emoji:bath[] [.small]`+emoji:bath[]+`
a| emoji:bathtub[] [.small]`+emoji:bathtub[]+`

a| emoji:battery[] [.small]`+emoji:battery[]+`
a| emoji:beer[] [.small]`+emoji:beer[]+`
a| emoji:beers[] [.small]`+emoji:beers[]+`

a| emoji:bell[] [.small]`+emoji:bell[]+`
a| emoji:bento[] [.small]`+emoji:bento[]+`
a| emoji:bicyclist[] [.small]`+emoji:bicyclist[]+`

a| emoji:bikini[] [.small]`+emoji:bikini[]+`
a| emoji:birthday[] [.small]`+emoji:birthday[]+`
a| emoji:black-joker[] [.small]`+emoji:black-joker[]+`

a| emoji:black-nib[] [.small]`+emoji:black-nib[]+`
a| emoji:blue-book[] [.small]`+emoji:blue-book[]+`
a| emoji:bomb[] [.small]`+emoji:bomb[]+`

a| emoji:bookmark[] [.small]`+emoji:bookmark[]+`
a| emoji:bookmark-tabs[] [.small]`+emoji:bookmark-tabs[]+`
a| emoji:books[] [.small]`+emoji:books[]+`

a| emoji:boot[] [.small]`+emoji:boot[]+`
a| emoji:bowling[] [.small]`+emoji:bowling[]+`
a| emoji:bread[] [.small]`+emoji:bread[]+`

a| emoji:briefcase[] [.small]`+emoji:briefcase[]+`
a| emoji:bulb[] [.small]`+emoji:bulb[]+`
a| emoji:cake[] [.small]`+emoji:cake[]+`

a| emoji:calendar[] [.small]`+emoji:calendar[]+`
a| emoji:calling[] [.small]`+emoji:calling[]+`
a| emoji:camera[] [.small]`+emoji:camera[]+`

a| emoji:candy[] [.small]`+emoji:candy[]+`
a| emoji:card-index[] [.small]`+emoji:card-index[]+`
a| emoji:cd[] [.small]`+emoji:cd[]+`

a| emoji:chart-with-downwards-trend[] [.small]`+emoji:chart-with-downwards-trend[]+`
a| emoji:chart-with-upwards-trend[] [.small]`+emoji:chart-with-upwards-trend[]+`
a| emoji:cherries[] [.small]`+emoji:cherries[]+`

a| emoji:chocolate-bar[] [.small]`+emoji:chocolate-bar[]+`
a| emoji:christmas-tree[] [.small]`+emoji:christmas-tree[]+`
a| emoji:clapper[] [.small]`+emoji:clapper[]+`

a| emoji:clipboard[] [.small]`+emoji:clipboard[]+`
a| emoji:closed-book[] [.small]`+emoji:closed-book[]+`
a| emoji:closed-lock-with-key[] [.small]`+emoji:closed-lock-with-key[]+`

a| emoji:closed-umbrella[] [.small]`+emoji:closed-umbrella[]+`
a| emoji:clubs[] [.small]`+emoji:clubs[]+`
a| emoji:cocktail[] [.small]`+emoji:cocktail[]+`

a| emoji:coffee[] [.small]`+emoji:coffee[]+`
a| emoji:computer[] [.small]`+emoji:computer[]+`
a| emoji:confetti-ball[] [.small]`+emoji:confetti-ball[]+`

a| emoji:cookie[] [.small]`+emoji:cookie[]+`
a| emoji:corn[] [.small]`+emoji:corn[]+`
a| emoji:credit-card[] [.small]`+emoji:credit-card[]+`

a| emoji:crown[] [.small]`+emoji:crown[]+`
a| emoji:crystal-ball[] [.small]`+emoji:crystal-ball[]+`
a| emoji:curry[] [.small]`+emoji:curry[]+`

a| emoji:custard[] [.small]`+emoji:custard[]+`
a| emoji:dango[] [.small]`+emoji:dango[]+`
a| emoji:dart[] [.small]`+emoji:dart[]+`

a| emoji:date[] [.small]`+emoji:date[]+`
a| emoji:diamonds[] [.small]`+emoji:diamonds[]+`
a| emoji:dollar[] [.small]`+emoji:dollar[]+`

a| emoji:door[] [.small]`+emoji:door[]+`
a| emoji:doughnut[] [.small]`+emoji:doughnut[]+`
a| emoji:dress[] [.small]`+emoji:dress[]+`

a| emoji:dvd[] [.small]`+emoji:dvd[]+`
a| emoji:e-mail[] [.small]`+emoji:e-mail[]+`
a| emoji:egg[] [.small]`+emoji:egg[]+`

a| emoji:eggplant[] [.small]`+emoji:eggplant[]+`
a| emoji:electric-plug[] [.small]`+emoji:electric-plug[]+`
a| emoji:email[] [.small]`+emoji:email[]+`

a| emoji:euro[] [.small]`+emoji:euro[]+`
a| emoji:eyeglasses[] [.small]`+emoji:eyeglasses[]+`
a| emoji:fax[] [.small]`+emoji:fax[]+`

a| emoji:file-folder[] [.small]`+emoji:file-folder[]+`
a| emoji:fish-cake[] [.small]`+emoji:fish-cake[]+`
a| emoji:fishing-pole-and-fish[] [.small]`+emoji:fishing-pole-and-fish[]+`

a| emoji:flashlight[] [.small]`+emoji:flashlight[]+`
a| emoji:floppy-disk[] [.small]`+emoji:floppy-disk[]+`
a| emoji:flower-playing-cards[] [.small]`+emoji:flower-playing-cards[]+`

a| emoji:football[] [.small]`+emoji:football[]+`
a| emoji:fork-and-knife[] [.small]`+emoji:fork-and-knife[]+`
a| emoji:fried-shrimp[] [.small]`+emoji:fried-shrimp[]+`

a| emoji:fries[] [.small]`+emoji:fries[]+`
a| emoji:game-die[] [.small]`+emoji:game-die[]+`
a| emoji:gem[] [.small]`+emoji:gem[]+`

a| emoji:gift[] [.small]`+emoji:gift[]+`
a| emoji:golf[] [.small]`+emoji:golf[]+`
a| emoji:grapes[] [.small]`+emoji:grapes[]+`

a| emoji:green-apple[] [.small]`+emoji:green-apple[]+`
a| emoji:green-book[] [.small]`+emoji:green-book[]+`
a| emoji:guitar[] [.small]`+emoji:guitar[]+`

a| emoji:gun[] [.small]`+emoji:gun[]+`
a| emoji:hamburger[] [.small]`+emoji:hamburger[]+`
a| emoji:hammer[] [.small]`+emoji:hammer[]+`

a| emoji:handbag[] [.small]`+emoji:handbag[]+`
a| emoji:headphones[] [.small]`+emoji:headphones[]+`
a| emoji:hearts[] [.small]`+emoji:hearts[]+`

a| emoji:high-brightness[] [.small]`+emoji:high-brightness[]+`
a| emoji:high-heel[] [.small]`+emoji:high-heel[]+`
a| emoji:hocho[] [.small]`+emoji:hocho[]+`

a| emoji:honey-pot[] [.small]`+emoji:honey-pot[]+`
a| emoji:horse-racing[] [.small]`+emoji:horse-racing[]+`
a| emoji:hourglass[] [.small]`+emoji:hourglass[]+`

a| emoji:hourglass-flowing-sand[] [.small]`+emoji:hourglass-flowing-sand[]+`
a| emoji:ice-cream[] [.small]`+emoji:ice-cream[]+`
a| emoji:icecream[] [.small]`+emoji:icecream[]+`

a| inbox-tray[] [.small]`+emoji:inbox-tray[]+`
a| emoji:incoming-envelope[] [.small]`+emoji:incoming-envelope[]+`
a| emoji:iphone[] [.small]`+emoji:iphone[]+`

a| emoji:jeans[] [.small]`+emoji:jeans[]+`
a| emoji:key[] [.small]`+emoji:key[]+`
a| emoji:kimono[] [.small]`+emoji:kimono[]+`

a| emoji:ledger[] [.small]`+emoji:ledger[]+`
a| emoji:lemon[] [.small]`+emoji:lemon[]+`
a| emoji:lipstick[] [.small]`+emoji:lipstick[]+`

a| emoji:lock[] [.small]`+emoji:lock[]+`
a| emoji:lock-with-ink-pen[] [.small]`+emoji:lock-with-ink-pen[]+`
a| emoji:lollipop[] [.small]`+emoji:lollipop[]+`

a| emoji:loop[] [.small]`+emoji:loop[]+`
a| emoji:loudspeaker[] [.small]`+emoji:loudspeaker[]+`
a| emoji:low-brightness[] [.small]`+emoji:low-brightness[]+`

a| emoji:mag[] [.small]`+emoji:mag[]+`
a| emoji:mag-right[] [.small]`+emoji:mag-right[]+`
a| emoji:mahjong[] [.small]`+emoji:mahjong[]+`

a| emoji:mailbox[] [.small]`+emoji:mailbox[]+`
a| emoji:mailbox-closed[] [.small]`+emoji:mailbox-closed[]+`
a| emoji:mailbox-with-mail[] [.small]`+emoji:mailbox-with-mail[]+`

a| emoji:mailbox-with-no-mail[] [.small]`+emoji:mailbox-with-no-mail[]+`
a| emoji:mans-shoe[] [.small]`+emoji:mans-shoe[]+`
a| emoji:meat-on-bone[] [.small]`+emoji:meat-on-bone[]+`

a| emoji:mega[] [.small]`+emoji:mega[]+`
a| emoji:melon[] [.small]`+emoji:melon[]+`
a| +emoji:memo[] [.small]`+emoji:memo[]+`

a| emoji:microphone[] [.small]`+emoji:microphone[]+`
a| emoji:microscope[] [.small]`+emoji:microscope[]+`
a| emoji:minidisc[] [.small]`+emoji:minidisc[]+`

a| emoji:money-with-wings[] [.small]`+emoji:money-with-wings[]+`
a| emoji:moneybag[] [.small]`+emoji:moneybag[]+`
a| emoji:mountain-bicyclist[] [.small]`+emoji:mountain-bicyclist[]+`

a| emoji:movie-camera[] [.small]`+emoji:movie-camera[]+`
a| emoji:musical-keyboard[] [.small]`+emoji:musical-keyboard[]+`
a| emoji:musical-score[] [.small]`+emoji:musical-score[]+`

a| emoji:mute[] [.small]`+emoji:mute[]+`
a| emoji:name-badge[] [.small]`+emoji:name-badge[]+`
a| emoji:necktie[] [.small]`+emoji:necktie[]+`

a| emoji:newspaper[] [.small]`+emoji:newspaper[]+`
a| emoji:no-bell[] [.small]`+emoji:no-bell[]+`
a| emoji:notebook[] [.small]`+emoji:notebook[]+`

a| emoji:notebook-with-decorative-cover[] [.small]`+emoji:notebook-with-decorative-cover[]+`
a| emoji:nut-and-bolt[] [.small]`+emoji:nut-and-bolt[]+`
a| emoji:oden[] [.small]`+emoji:oden[]+`

a| emoji:open-file-folder[] [.small]`+emoji:open-file-folder[]+`
a| emoji:orange-book[] [.small]`+emoji:orange-book[]+`
a| emoji:outbox-tray[] [.small]`+emoji:outbox-tray[]+`

a| emoji:page-facing-up[] [.small]`+emoji:page-facing-up[]+`
a| emoji:page-with-curl[] [.small]`+emoji:page-with-curl[]+`
a| emoji:pager[] [.small]`+emoji:pager[]+`

a| emoji:paperclip[] [.small]`+emoji:paperclip[]+`
a| emoji:peach[] [.small]`+emoji:peach[]+`
a| emoji:pear[] [.small]`+emoji:pear[]+`

a| emoji:pencil2[] [.small]`+emoji:pencil2[]+`
a| emoji:phone[] [.small]`+emoji:phone[]+`
a| emoji:pill[] [.small]`+emoji:pill[]+`

a| emoji:pineapple[] [.small]`+emoji:pineapple[]+`
a| emoji:pizza[] [.small]`+emoji:pizza[]+`
a| emoji:postal-horn[] [.small]`+emoji:postal-horn[]+`

a| emoji:postbox[] [.small]`+emoji:postbox[]+`
a| emoji:pouch[] [.small]`+emoji:pouch[]+`
a| emoji:poultry-leg[] [.small]`+emoji:poultry-leg[]+`

a| emoji:pound[] [.small]`+emoji:pound[]+`
a| emoji:purse[] [.small]`+emoji:purse[]+`
a| emoji:pushpin[] [.small]`+emoji:pushpin[]+`

a| emoji:radio[] [.small]`+emoji:radio[]+`
a| emoji:ramen[] [.small]`+emoji:ramen[]+`
a| emoji:ribbon[] [.small]`+emoji:ribbon[]+`

a| emoji:rice[] [.small]`+emoji:rice[]+`
a| emoji:rice-ball[] [.small]`+emoji:rice-ball[]+`
a| emoji:rice-cracker[] [.small]`+emoji:rice-cracker[]+`

a| emoji:ring[] [.small]`+emoji:ring[]+`
a| emoji:rugby-football[] [.small]`+emoji:rugby-football[]+`
a| emoji:running-shirt-with-sash[] [.small]`+emoji:running-shirt-with-sash[]+`

a| emoji:sake[] [.small]`+emoji:sake[]+`
a| emoji:sandal[] [.small]`+emoji:sandal[]+`
a| emoji:satellite[] [.small]`+emoji:satellite[]+`

a| emoji:saxophone[] [.small]`+emoji:saxophone[]+`
a| emoji:scissors[] [.small]`+emoji:scissors[]+`
a| emoji:scroll[] [.small]`+emoji:scroll[]+`

a| emoji:seat[] [.small]`+emoji:seat[]+`
a| emoji:shaved-ice[] [.small]`+emoji:shaved-ice[]+`
a| emoji:shirt[] [.small]`+emoji:shirt[]+`

a| emoji:shower[] [.small]`+emoji:shower[]+`
a| emoji:ski[] [.small]`+emoji:ski[]+`
a| emoji:smoking[] [.small]`+emoji:smoking[]+`

a| emoji:snowboarder[] [.small]`+emoji:snowboarder[]+`
a| emoji:soccer[] [.small]`+emoji:soccer[]+`
a| emoji:sound[] [.small]`+emoji:sound[]+`

a| emoji:space-invader[] [.small]`+emoji:space-invader[]+`
a| emoji:spades[] [.small]`+emoji:spades[]+`
a| emoji:spaghetti[] [.small]`+emoji:spaghetti[]+`

a| emoji:speaker[] [.small]`+emoji:speaker[]+`
a| emoji:stew[] [.small]`+emoji:stew[]+`
a| emoji:straight-ruler[] [.small]`+emoji:straight-ruler[]+`

a| emoji:strawberry[] [.small]`+emoji:strawberry[]+`
a| emoji:surfer[] [.small]`+emoji:surfer[]+`
a| emoji:sushi[] [.small]`+emoji:sushi[]+`

a| emoji:sweet-potato[] [.small]`+emoji:sweet-potato[]+`
a| emoji:swimmer[] [.small]`+emoji:swimmer[]+`
a| emoji:syringe[] [.small]`+emoji:syringe[]+`

a| emoji:tada[] [.small]`+emoji:tada[]+`
a| emoji:tanabata-tree[] [.small]`+emoji:tanabata-tree[]+`
a| emoji:tangerine[] [.small]`+emoji:tangerine[]+`

a| emoji:tea[] [.small]`+emoji:tea[]+`
a| emoji:telephone-receiver[] [.small]`+emoji:telephone-receiver[]+`
a| emoji:telescope[] [.small]`+emoji:telescope[]+`

a| emoji:tennis[] [.small]`+emoji:tennis[]+`
a| emoji:toilet[] [.small]`+emoji:toilet[]+`
a| emoji:tomato[] [.small]`+emoji:tomato[]+`

a| emoji:tophat[] [.small]`+emoji:tophat[]+`
a| emoji:triangular-ruler[] [.small]`+emoji:triangular-ruler[]+`
a| emoji:trophy[] [.small]`+emoji:trophy[]+`

a| emoji:tropical-drink[] [.small]`+emoji:tropical-drink[]+`
a| emoji:trumpet[] [.small]`+emoji:trumpet[]+`
a| emoji:tv[] [.small]`+emoji:tv[]+`

a| emoji:unlock[] [.small]`+emoji:unlock[]+`
a| emoji:vhs[] [.small]`+emoji:vhs[]+`
a| emoji:video-camera[] [.small]`+emoji:video-camera[]+`

a| emoji:video-game[] [.small]`+emoji:video-game[]+`
a| emoji:violin[] [.small]`+emoji:violin[]+`
a| emoji:watch[] [.small]`+emoji:watch[]+`

a| emoji:watermelon[] [.small]`+emoji:watermelon[]+`
a| emoji:wine-glass[] [.small]`+emoji:wine-glass[]+`
a| emoji:womans-clothes[] [.small]`+emoji:womans-clothes[]+`

a| emoji:womans-hat[] [.small]`+emoji:womans-hat[]+`
a| emoji:wrench[] [.small]`+emoji:wrench[]+`
a| emoji:yen[] [.small]`+emoji:yen[]+`

a| emoji:aerial-tramway[] [.small]`+emoji:aerial-tramway[]+`
a| emoji:airplane[] [.small]`+emoji:airplane[]+`
a| emoji:ambulance[] [.small]`+emoji:ambulance[]+`

a| emoji:anchor[] [.small]`+emoji:anchor[]+`
a| emoji:articulated-lorry[] [.small]`+emoji:articulated-lorry[]+`
a| emoji:atm[] [.small]`+emoji:atm[]+`

a| emoji:bank[] [.small]`+emoji:bank[]+`
a| emoji:barber[] [.small]`+emoji:barber[]+`
a| emoji:beginner[] [.small]`+emoji:beginner[]+`

a| emoji:bike[] [.small]`+emoji:bike[]+`
a| emoji:blue-car[] [.small]`+emoji:blue-car[]+`
a| emoji:boat[] [.small]`+emoji:boat[]+`

a| emoji:bridge-at-night[] [.small]`+emoji:bridge-at-night[]+`
a| emoji:bullettrain-front[] [.small]`+emoji:bullettrain-front[]+`
a| emoji:bullettrain-side[] [.small]`+emoji:bullettrain-side[]+`

a| emoji:bus[] [.small]`+emoji:bus[]+`
a| emoji:busstop[] [.small]`+emoji:busstop[]+`
a| emoji:car[] [.small]`+emoji:car[]+`

a| emoji:carousel-horse[] [.small]`+emoji:carousel-horse[]+`
a| emoji:checkered-flag[] [.small]`+emoji:checkered-flag[]+`
a| emoji:church[] [.small]`+emoji:church[]+`

a| emoji:circus-tent[] [.small]`+emoji:circus-tent[]+`
a| emoji:city-sunrise[] [.small]`+emoji:city-sunrise[]+`
a| emoji:city-sunset[] [.small]`+emoji:city-sunset[]+`

a| emoji:construction[] [.small]`+emoji:construction[]+`
a| emoji:convenience-store[] [.small]`+emoji:convenience-store[]+`
a| emoji:crossed-flags[] [.small]`+emoji:crossed-flags[]+`

a| emoji:department-store[] [.small]`+emoji:department-store[]+`
a| emoji:european-castle[] [.small]`+emoji:european-castle[]+`
a| emoji:european-post-office[] [.small]`+emoji:european-post-office[]+`

a| emoji:factory[] [.small]`+emoji:factory[]+`
a| emoji:ferris-wheel[] [.small]`+emoji:ferris-wheel[]+`
a| emoji:fire-engine[] [.small]`+emoji:fire-engine[]+`

a| emoji:fountain[] [.small]`+emoji:fountain[]+`
a| emoji:fuelpump[] [.small]`+emoji:fuelpump[]+`
a| emoji:helicopter[] [.small]`+emoji:helicopter[]+`

a| emoji:hospital[] [.small]`+emoji:hospital[]+`
a| emoji:hotel[] [.small]`+emoji:hotel[]+`
a| emoji:hotsprings[] [.small]`+emoji:hotsprings[]+`

a| emoji:house[] [.small]`+emoji:house[]+`
a| emoji:house-with-garden[] [.small]`+emoji:house-with-garden[]+`
a| emoji:japan[] [.small]`+emoji:japan[]+`

a| emoji:japanese-castle[] [.small]`+emoji:japanese-castle[]+`
a| emoji:light-rail[] [.small]`+emoji:light-rail[]+`
a| emoji:love-hotel[] [.small]`+emoji:love-hotel[]+`

a| emoji:minibus[] [.small]`+emoji:minibus[]+`
a| emoji:monorail[] [.small]`+emoji:monorail[]+`
a| emoji:mount-fuji[] [.small]`+emoji:mount-fuji[]+`

a| emoji:mountain-cableway[] [.small]`+emoji:mountain-cableway[]+`
a| emoji:mountain-railway[] [.small]`+emoji:mountain-railway[]+`
a| emoji:moyai[] [.small]`+emoji:moyai[]+`

a| emoji:office[] [.small]`+emoji:office[]+`
a| emoji:oncoming-automobile[] [.small]`+emoji:oncoming-automobile[]+`
a| emoji:oncoming-bus[] [.small]`+emoji:oncoming-bus[]+`

a| emoji:oncoming-police-car[] [.small]`+emoji:oncoming-police-car[]+`
a| emoji:oncoming-taxi[] [.small]`+emoji:oncoming-taxi[]+`
a| emoji:performing-arts[] [.small]`+emoji:performing-arts[]+`

a| emoji:police-car[] [.small]`+emoji:police-car[]+`
a| emoji:post-office[] [.small]`+emoji:post-office[]+`
a| emoji:railway-car[] [.small]`+emoji:railway-car[]+`

a| emoji:rainbow[] [.small]`+emoji:rainbow[]+`
a| emoji:rocket[] [.small]`+emoji:rocket[]+`
a| emoji:roller-coaster[] [.small]`+emoji:roller-coaster[]+`

a| emoji:rotating-light[] [.small]`+emoji:rotating-light[]+`
a| emoji:round-pushpin[] [.small]`+emoji:round-pushpin[]+`
a| emoji:rowboat[] [.small]`+emoji:rowboat[]+`

a| emoji:school[] [.small]`+emoji:school[]+`
a| emoji:ship[] [.small]`+emoji:ship[]+`
a| emoji:slot-machine[] [.small]`+emoji:slot-machine[]+`

a| emoji:speedboat[] [.small]`+emoji:speedboat[]+`
a| emoji:stars[] [.small]`+emoji:stars[]+`
a| emoji:station[] [.small]`+emoji:station[]+`

a| emoji:statue-of-liberty[] [.small]`+emoji:statue-of-liberty[]+`
a| emoji:steam-locomotive[] [.small]`+emoji:steam-locomotive[]+`
a| emoji:sunrise[] [.small]`+emoji:sunrise[]+`

a| emoji:sunrise-over-mountains[] [.small]`+emoji:sunrise-over-mountains[]+`
a| emoji:suspension-railway[] [.small]`+emoji:suspension-railway[]+`
a| emoji:taxi[] [.small]`+emoji:taxi[]+`

a| emoji:tent[] [.small]`+emoji:tent[]+`
a| emoji:ticket[] [.small]`+emoji:ticket[]+`
a| emoji:tokyo-tower[] [.small]`+emoji:tokyo-tower[]+`

a| emoji:tractor[] [.small]`+emoji:tractor[]+`
a| emoji:traffic-light[] [.small]`+emoji:traffic-light[]+`
a| emoji:train2[] [.small]`+emoji:train2[]+`

a| emoji:tram[] [.small]`+emoji:tram[]+`
a| emoji:triangular-flag-on-post[] [.small]`+emoji:triangular-flag-on-post[]+`
a| emoji:trolleybus[] [.small]`+emoji:trolleybus[]+`

a| emoji:truck[] [.small]`+emoji:truck[]+`
a| emoji:vertical-traffic-light[] [.small]`+emoji:vertical-traffic-light[]+`
a| emoji:warning[] [.small]`+emoji:warning[]+`

a| emoji:wedding[] [.small]`+emoji:wedding[]+`
a| emoji:jp[] [.small]`+emoji:jp[]+`
a| emoji:kr[] [.small]`+emoji:kr[]+`

a| emoji:cn[] [.small]`+emoji:cn[]+`
a| emoji:us[] [.small]`+emoji:us[]+`
a| emoji:fr[] [.small]`+emoji:fr[]+`

a| emoji:es[] [.small]`+emoji:es[]+`
a| emoji:it[] [.small]`+emoji:it[]+`
a| emoji:ru[] [.small]`+emoji:ru[]+`

a| emoji:gb[] [.small]`+emoji:gb[]+`
a| emoji:de[] [.small]`+emoji:de[]+`
a| emoji:100[] [.small]`+emoji:100[]+`

a| emoji:1234[] [.small]`+emoji:1234[]+`
a| emoji:a[] [.small]`+emoji:a[]+`
a| emoji:ab[] [.small]`+emoji:ab[]+`

a| emoji:abc[] [.small]`+emoji:abc[]+`
a| emoji:abcd[] [.small]`+emoji:abcd[]+`
a| emoji:accept[] [.small]`+emoji:accept[]+`

a| emoji:aquarius[] [.small]`+emoji:aquarius[]+`
a| emoji:aries[] [.small]`+emoji:aries[]+`
a| emoji:arrow-backward[] [.small]`+emoji:arrow-backward[]+`

a| emoji:arrow-double-down[] [.small]`+emoji:arrow-double-down[]+`
a| emoji:arrow-double-up[] [.small]`+emoji:arrow-double-up[]+`
a| emoji:arrow-down[] [.small]`+emoji:arrow-down[]+`

a| emoji:arrow-down-small[] [.small]`+emoji:arrow-down-small[]+`
a| emoji:arrow-forward[] [.small]`+emoji:arrow-forward[]+`
a| emoji:arrow-heading-down[] [.small]`+emoji:arrow-heading-down[]+`

a| emoji:arrow-heading-up[] [.small]`+emoji:arrow-heading-up[]+`
a| emoji:arrow-left[] [.small]`+emoji:arrow-left[]+`
a| emoji:arrow-lower-left[] [.small]`+emoji:arrow-lower-left[]+`

a| emoji:arrow-lower-right[] [.small]`+emoji:arrow-lower-right[]+`
a| emoji:arrow-right[] [.small]`+emoji:arrow-right[]+`
a| emoji:arrow-right-hook[] [.small]`+emoji:arrow-right-hook[]+`

a| emoji:arrow-up[] [.small]`+emoji:arrow-up[]+`
a| emoji:arrow-up-down[] [.small]`+emoji:arrow-up-down[]+`
a| emoji:arrow-up-small[] [.small]`+emoji:arrow-up-small[]+`

a| emoji:arrow-upper-left[] [.small]`+emoji:arrow-upper-left[]+`
a| emoji:arrow-upper-right[] [.small]`+emoji:arrow-upper-right[]+`
a| emoji:arrows-clockwise[] [.small]`+emoji:arrows-clockwise[]+`

a| emoji:arrows-counterclockwise[] [.small]`+emoji:arrows-counterclockwise[]+`
a| emoji:b[] [.small]`+emoji:b[]+`
a| emoji:baby-symbol[] [.small]`+emoji:baby-symbol[]+`

a| emoji:baggage-claim[] [.small]`+emoji:baggage-claim[]+`
a| emoji:ballot-box-with-check[] [.small]`+emoji:ballot-box-with-check[]+`
a| emoji:bangbang[] [.small]`+emoji:bangbang[]+`

a| emoji:black-circle[] [.small]`+emoji:black-circle[]+`
a| emoji:black-square-button[] [.small]`+emoji:black-square-button[]+`
a| emoji:cancer[] [.small]`+emoji:cancer[]+`

a| emoji:capital-abcd[] [.small]`+emoji:capital-abcd[]+`
a| emoji:capricorn[] [.small]`+emoji:capricorn[]+`
a| emoji:chart[] [.small]`+emoji:chart[]+`

a| emoji:children-crossing[] [.small]`+emoji:children-crossing[]+`
a| emoji:cinema[] [.small]`+emoji:cinema[]+`
a| emoji:cl[] [.small]`+emoji:cl[]+`

a| emoji:clock1[] [.small]`+emoji:clock1[]+`
a| emoji:clock10[] [.small]`+emoji:clock10[]+`
a| emoji:clock1030[] [.small]`+emoji:clock1030[]+`

a| emoji:clock11[] [.small]`+emoji:clock11[]+`
a| emoji:clock1130[] [.small]`+emoji:clock1130[]+`
a| emoji:clock12[] [.small]`+emoji:clock12[]+`

a| emoji:clock1230[] [.small]`+emoji:clock1230[]+`
a| emoji:clock130[] [.small]`+emoji:clock130[]+`
a| emoji:clock2[] [.small]`+emoji:clock2[]+`

a| emoji:clock230[] [.small]`+emoji:clock230[]+`
a| emoji:clock3[] [.small]`+emoji:clock3[]+`
a| emoji:clock330[] [.small]`+emoji:clock330[]+`

a| emoji:clock4[] [.small]`+emoji:clock4[]+`
a| emoji:clock430[] [.small]`+emoji:clock430[]+`
a| emoji:clock5[] [.small]`+emoji:clock5[]+`

a| emoji:clock530[] [.small]`+emoji:clock530[]+`
a| emoji:clock6[] [.small]`+emoji:clock6[]+`
a| emoji:clock630[] [.small]`+emoji:clock630[]+`

a| emoji:clock7[] [.small]`+emoji:clock7[]+`
a| emoji:clock730[] [.small]`+emoji:clock730[]+`
a| emoji:clock8[] [.small]`+emoji:clock8[]+`

a| emoji:clock830[] [.small]`+emoji:clock830[]+`
a| emoji:clock9[] [.small]`+emoji:clock9[]+`
a| emoji:clock930[] [.small]`+emoji:clock930[]+`

a| emoji:congratulations[] [.small]`+emoji:congratulations[]+`
a| emoji:cool[] [.small]`+emoji:cool[]+`
a| emoji:copyright[] [.small]`+emoji:copyright[]+`

a| emoji:curly-loop[] [.small]`+emoji:curly-loop[]+`
a| emoji:currency-exchange[] [.small]`+emoji:currency-exchange[]+`
a| emoji:customs[] [.small]`+emoji:customs[]+`

a| emoji:diamond-shape-with-a-dot-inside[] [.small]`+emoji:diamond-shape-with-a-dot-inside[]+`
a| emoji:do-not-litter[] [.small]`+emoji:do-not-litter[]+`
a| emoji:eight[] [.small]`+emoji:eight[]+`

a| emoji:eight-pointed-black-star[] [.small]`+emoji:eight-pointed-black-star[]+`
a| emoji:eight-spoked-asterisk[] [.small]`+emoji:eight-spoked-asterisk[]+`
a| emoji:end[] [.small]`+emoji:end[]+`

a| emoji:fast-forward[] [.small]`+emoji:fast-forward[]+`
a| emoji:five[] [.small]`+emoji:five[]+`
a| emoji:four[] [.small]`+emoji:four[]+`

a| emoji:free[] [.small]`+emoji:free[]+`
a| emoji:gemini[] [.small]`+emoji:gemini[]+`
a| emoji:hash[] [.small]`+emoji:hash[]+`

a| emoji:heart-decoration[] [.small]`+emoji:heart-decoration[]+`
a| emoji:heavy-check-mark[] [.small]`+emoji:heavy-check-mark[]+`
a| emoji:heavy-division-sign[] [.small]`+emoji:heavy-division-sign[]+`

a| emoji:heavy-dollar-sign[] [.small]`+emoji:heavy-dollar-sign[]+`
a| emoji:heavy-minus-sign[] [.small]`+emoji:heavy-minus-sign[]+`
a| emoji:heavy-multiplication-x[] [.small]`+emoji:heavy-multiplication-x[]+`

a| emoji:heavy-plus-sign[] [.small]`+emoji:heavy-plus-sign[]+`
a| emoji:id[] [.small]`+emoji:id[]+`
a| emoji:ideograph-advantage[] [.small]`+emoji:ideograph-advantage[]+`

a| emoji:information-source[] [.small]`+emoji:information-source[]+`
a| emoji:interrobang[] [.small]`+emoji:interrobang[]+`
a| emoji:keycap-ten[] [.small]`+emoji:keycap-ten[]+`

a| emoji:koko[] [.small]`+emoji:koko[]+`
a| emoji:large-blue-circle[] [.small]`+emoji:large-blue-circle[]+`
a| emoji:large-blue-diamond[] [.small]`+emoji:large-blue-diamond[]+`

a| emoji:large-orange-diamond[] [.small]`+emoji:large-orange-diamond[]+`
a| emoji:left-luggage[] [.small]`+emoji:left-luggage[]+`
a| emoji:left-right-arrow[] [.small]`+emoji:left-right-arrow[]+`

a| emoji:leftwards-arrow-with-hook[] [.small]`+emoji:leftwards-arrow-with-hook[]+`
a| emoji:leo[] [.small]`+emoji:leo[]+`
a| emoji:libra[] [.small]`+emoji:libra[]+`

a| emoji:link[] [.small]`+emoji:link[]+`
a| emoji:m[] [.small]`+emoji:m[]+`
a| emoji:mens[] [.small]`+emoji:mens[]+`

a| emoji:metro[] [.small]`+emoji:metro[]+`
a| emoji:mobile-phone-off[] [.small]`+emoji:mobile-phone-off[]+`
a| emoji:negative-squared-cross-mark[] [.small]`+emoji:negative-squared-cross-mark[]+`

a| emoji:new[] [.small]`+emoji:new[]+`
a| emoji:ng[] [.small]`+emoji:ng[]+`
a| emoji:nine[] [.small]`+emoji:nine[]+`

a| emoji:no-bicycles[] [.small]`+emoji:no-bicycles[]+`
a| emoji:no-entry[] [.small]`+emoji:no-entry[]+`
a| emoji:no-entry-sign[] [.small]`+emoji:no-entry-sign[]+`

a| emoji:no-mobile-phones[] [.small]`+emoji:no-mobile-phones[]+`
a| emoji:no-pedestrians[] [.small]`+emoji:no-pedestrians[]+`
a| emoji:no-smoking[] [.small]`+emoji:no-smoking[]+`

a| emoji:non-potable-water[] [.small]`+emoji:non-potable-water[]+`
a| emoji:o[] [.small]`+emoji:o[]+`
a| emoji:o2[] [.small]`+emoji:o2[]+`

a| emoji:ok[] [.small]`+emoji:ok[]+`
a| emoji:on[] [.small]`+emoji:on[]+`
a| emoji:one[] [.small]`+emoji:one[]+`

a| emoji:ophiuchus[] [.small]`+emoji:ophiuchus[]+`
a| emoji:parking[] [.small]`+emoji:parking[]+`
a| emoji:part-alternation-mark[] [.small]`+emoji:part-alternation-mark[]+`

a| emoji:passport-control[] [.small]`+emoji:passport-control[]+`
a| emoji:pisces[] [.small]`+emoji:pisces[]+`
a| emoji:potable-water[] [.small]`+emoji:potable-water[]+`

a| emoji:put-litter-in-its-place[] [.small]`+emoji:put-litter-in-its-place[]+`
a| emoji:radio-button[] [.small]`+emoji:radio-button[]+`
a| emoji:recycle[] [.small]`+emoji:recycle[]+`

a| emoji:red-circle[] [.small]`+emoji:red-circle[]+`
a| emoji:registered[] [.small]`+emoji:registered[]+`
a| emoji:repeat[] [.small]`+emoji:repeat[]+`

a| emoji:repeat-one[] [.small]`+emoji:repeat-one[]+`
a| emoji:restroom[] [.small]`+emoji:restroom[]+`
a| emoji:rewind[] [.small]`+emoji:rewind[]+`

a| emoji:sa[] [.small]`+emoji:sa[]+`
a| emoji:sagittarius[] [.small]`+emoji:sagittarius[]+`
a| emoji:scorpius[] [.small]`+emoji:scorpius[]+`

a| emoji:secret[] [.small]`+emoji:secret[]+`
a| emoji:seven[] [.small]`+emoji:seven[]+`
a| emoji:signal-strength[] [.small]`+emoji:signal-strength[]+`

a| emoji:six[] [.small]`+emoji:six[]+`
a| emoji:six-pointed-star[] [.small]`+emoji:six-pointed-star[]+`
a| emoji:small-blue-diamond[] [.small]`+emoji:small-blue-diamond[]+`

a| emoji:small-orange-diamond[] [.small]`+emoji:small-orange-diamond[]+`
a| emoji:small-red-triangle[] [.small]`+emoji:small-red-triangle[]+`
a| emoji:small-red-triangle-down[] [.small]`+emoji:small-red-triangle-down[]+`

a| emoji:soon[] [.small]`+emoji:soon[]+`
a| emoji:sos[] [.small]`+emoji:sos[]+`
a| emoji:symbols[] [.small]`+emoji:symbols[]+`

a| emoji:taurus[] [.small]`+emoji:taurus[]+`
a| emoji:three[] [.small]`+emoji:three[]+`
a| emoji:tm[] [.small]`+emoji:tm[]+`

a| emoji:top[] [.small]`+emoji:top[]+`
a| emoji:trident[] [.small]`+emoji:trident[]+`
a| emoji:twisted-rightwards-arrows[] [.small]`+emoji:twisted-rightwards-arrows[]+`

a| emoji:two[] [.small]`+emoji:two[]+`
a| emoji:u5272[] [.small]`+emoji:u5272[]+`
a| emoji:u5408[] [.small]`+emoji:u5408[]+`

a| emoji:u55b6[] [.small]`+emoji:u55b6[]+`
a| emoji:u6307[] [.small]`+emoji:u6307[]+`
a| emoji:u6708[] [.small]`+emoji:u6708[]+`

a| emoji:u6709[] [.small]`+emoji:u6709[]+`
a| emoji:u6e80[] [.small]`+emoji:u6e80[]+`
a| emoji:u7121[] [.small]`+emoji:u7121[]+`

a| emoji:u7533[] [.small]`+emoji:u7533[]+`
a| emoji:u7981[] [.small]`+emoji:u7981[]+`
a| emoji:u7a7a[] [.small]`+emoji:u7a7a[]+`

a| emoji:underage[] [.small]`+emoji:underage[]+`
a| emoji:up[] [.small]`+emoji:up[]+`
a| emoji:vibration-mode[] [.small]`+emoji:vibration-mode[]+`

a| emoji:virgo[] [.small]`+emoji:virgo[]+`
a| emoji:vs[] [.small]`+emoji:vs[]+`
a| emoji:wavy-dash[] [.small]`+emoji:wavy-dash[]+`

a| emoji:wc[] [.small]`+emoji:wc[]+`
a| emoji:wheelchair[] [.small]`+emoji:wheelchair[]+`
a| emoji:white-check-mark[] [.small]`+emoji:white-check-mark[]+`

a| emoji:white-circle[] [.small]`+emoji:white-circle[]+`
a| emoji:white-flower[] [.small]`+emoji:white-flower[]+`
a| emoji:white-square-button[] [.small]`+emoji:white-square-button[]+`

a| emoji:womens[] [.small]`+emoji:womens[]+`
a| emoji:x[] [.small]`+emoji:x[]+`
a| emoji:zero[] [.small]`+emoji:zero[]+`
|===
