= Emoji and Icons
:author: mitm
:revnumber: 1.0
:stylesheet: twemoji-awesome.css
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


== How to use icons in the wiki

You can use any font awesome icon listed at link:https://fontawesome.com/v4.7.0/icons/[https://fontawesome.com/v4.7.0/icons/] in your wiki documents by use of the icon macro.

.Syntax for inserting icons
```
icon:thumbs-up []
icon:database[role=green] // change color by use of the role syntax
icon:heart[2x] // icons can be sized
icon:shield[rotate=90, flip=vertical] // rotate and flip
```

[TIP]
====
When setting the icons name, you do not have to preface it with `fa-`, asciidoctor will accept the font name.
====

The icon macro has three attributes you can set, they are size, rotate, and flip.

* size +
  ** The first positional attribute found, scales the icon; values are: `1x` (default), `2x`, `3x`, `4x`, `5x`, `lg`, `fw`
  ** You can fix the width of the icon by use of the `fw` attribute. This helps when trying to align with other elements by giving the icon a fixed width.
* rotate
  ** Rotates the icon; values are: `90`, `180`, `270`
* flip
  ** Flips the icon; values are: `horizontal`, `vertical`

The first unnamed attribute is assumed to be the size. For instance, to make the icon twice the size as the default, simply add 2x inside the square brackets.

```
icon:heart[2x]
```
Results:

icon:heart[] 2x icon:heart[2x]

To rotate and flip the icon:
```
icon:shield[rotate=270, flip=vertical]
```
Results:

icon:shield[] rotated 90, and flipped vertical icon:shield[rotate=90, flip=vertical]

You can also link to icons.
```
icon:download[link="https://rubygems.org/downloads/asciidoctor-1.5.2.gem"]
```
Results:

icon:download[link="https://rubygems.org/downloads/asciidoctor-1.5.2.gem"]

Lastly, you can color your icons using the role syntax.
```
icon:database[role=green]
```
Results:

icon:database[] colored green icon:database[role=green]

== How to use emoji in the wiki

Using emoji in wiki docs currently requires the setting of the `:stylesheet:` attribute in the header of the wiki document.

```
:stylesheet: twemoji-awesome.css
```
The <<wiki/wiki_header.adoc#,Anatomy of a Wiki Header>> document explains setting of this and other header attributes.

Once the header attribute is set, you can add the emoji using the following syntax.

```
emoji:heart[2x] // the "[2x]" is a size modifier
emoji:rage[]
```

[NOTE]
====
You can change the icon size with the size modifier `[2x]`.

`+emoji:heart[]+` emoji:heart[] `+emoji:heart[2x]+` emoji:heart[2x]
====

== Emoji and Name Cheet Sheet

=== People

[cols=3*, frame=none, grid=none]
|===
a| emoji:smile[2x] [.small]`smile` +
emoji:smiley[2x] [.small]`smiley` +
emoji:heart-eyes[2x] [.small]`heart-eyes` +
emoji:flushed[2x] [.small]`flushed` +
emoji:grin[2x] [.small]`grin` +
emoji:stuck-out-tongue-closed-eyes[2x] [.small]`stuck-out-tongue-closed-eyes` +
emoji:kissing-smiling-eyes[2x] [.small]`kissing-smiling-eyes` +
emoji:worried[2x] [.small]`worried` +
emoji:open-mouth[2x] [.small]`open-mouth` +
emoji:hushed[2x] [.small]`hushed` +
emoji:sweat-smile[2x] [.small]`sweat-smile` +
emoji:pensive[2x] [.small]`pensive` +
emoji:fearful[2x] [.small]`fearful` +
emoji:cry[2x] [.small]`cry` +
emoji:astonished[2x] [.small]`astonished` +
emoji:angry[2x] [.small]`angry` +
emoji:sleepy[2x] [.small]`sleepy` +
emoji:sunglasses[2x] [.small]`sunglasses` +
emoji:smiling-imp[2x] [.small]`smiling-imp` +
emoji:innocent[2x] [.small]`innocent` +
emoji:blue-heart[2x] [.small]`blue-heart` +
emoji:green-heart[2x] [.small]`green-heart` +
emoji:heartpulse[2x] [.small]`heartpulse` +
emoji:cupid[2x] [.small]`cupid` +
emoji:star[2x] [.small]`star` +
emoji:boom[2x] [.small]`boom` +
emoji:question[2x] [.small]`question` +
emoji:zzz[2x] [.small]`zzz` +
emoji:notes[2x] [.small]`notes` +
emoji:poop[2x] [.small]`poop` +
emoji:ok-hand[2x] [.small]`ok-hand` +
emoji:v[2x] [.small]`v` +
emoji:open-hands[2x] [.small]`open-hands` +
emoji:point-left[2x] [.small]`point-left` +
emoji:pray[2x] [.small]`pray` +
emoji:muscle[2x] [.small]`muscle` +
emoji:couple[2x] [.small]`couple` +
emoji:dancers[2x] [.small]`dancers` +
emoji:information-desk-person[2x] [.small]`information-desk-person` +
emoji:person-with-pouting-face[2x] [.small]`person-with-pouting-face` +
emoji:couplekiss[2x] [.small]`couplekiss` +
emoji:haircut[2x] [.small]`haircut` +
emoji:girl[2x] [.small]`girl` +
emoji:baby[2x] [.small]`baby` +
emoji:person-with-blond-hair[2x] [.small]`person-with-blond-hair` +
emoji:construction-worker[2x] [.small]`construction-worker` +
emoji:princess[2x] [.small]`princess` +
emoji:heart-eyes-cat[2x] [.small]`heart-eyes-cat` +
emoji:scream-cat[2x] [.small]`scream-cat` +
emoji:pouting-cat[2x] [.small]`pouting-cat` +
emoji:see-no-evil[2x] [.small]`see-no-evil` +
emoji:guardsman[2x] [.small]`guardsman` +
emoji:lips[2x] [.small]`lips` +
emoji:ear[2x] [.small]`ear` +
emoji:tongue[2x] [.small]`tongue` +
emoji:busts-in-silhouette[2x] [.small]`busts-in-silhouette` +

a| emoji:laughing[2x] [.small]`laughing` +
emoji:relaxed[2x] [.small]`relaxed` +
emoji:kissing-heart[2x] [.small]`kissing-heart` +
emoji:relieved[2x] [.small]`relieved` +
emoji:wink[2x] [.small]`wink` +
emoji:grinning[2x] [.small]`grinning` +
emoji:stuck-out-tongue[2x] [.small]`stuck-out-tongue` +
emoji:frowning[2x] [.small]`frowning` +
emoji:grimacing[2x] [.small]`grimacing` +
emoji:expressionless[2x] [.small]`expressionless` +
emoji:sweat[2x] [.small]`sweat` +
emoji:disappointed[2x] [.small]`disappointed` +
emoji:cold-sweat[2x] [.small]`cold-sweat` +
emoji:sob[2x] [.small]`sob` +
emoji:scream[2x] [.small]`scream` +
emoji:rage[2x] [.small]`rage` +
emoji:yum[2x] [.small]`yum` +
emoji:dizzy-face[2x] [.small]`dizzy-face` +
emoji:neutral-face[2x] [.small]`neutral-face` +
emoji:alien[2x] [.small]`alien` +
emoji:purple-heart[2x] [.small]`purple-heart` +
emoji:broken-heart[2x] [.small]`broken-heart` +
emoji:two-hearts[2x] [.small]`two-hearts` +
emoji:sparkling-heart[2x] [.small]`sparkling-heart` +
emoji:star2[2x] [.small]`star2` +
emoji:anger[2x] [.small]`anger` +
emoji:grey-exclamation[2x] [.small]`grey-exclamation` +
emoji:dash[2x] [.small]`dash` +
emoji:musical-note[2x] [.small]`musical-note` +
emoji:thumbsup[2x] [.small]`thumbsup` +
emoji:punch[2x] [.small]`punch` +
emoji:wave[2x] [.small]`wave` +
emoji:point-up[2x] [.small]`point-up` +
emoji:point-right[2x] [.small]`point-right` +
emoji:point-up-2[2x] [.small]`point-up-2` +
emoji:walking[2x] [.small]`walking` +
emoji:family[2x] [.small]`family` +
emoji:ok-woman[2x] [.small]`ok-woman` +
emoji:raised-hand[2x] [.small]`raised-hand` +
emoji:person-frowning[2x] [.small]`person-frowning` +
emoji:couple-with-heart[2x] [.small]`couple-with-heart` +
emoji:nail-care[2x] [.small]`nail-care` +
emoji:woman[2x] [.small]`woman` +
emoji:older-woman[2x] [.small]`older-woman` +
emoji:man-with-gua-pi-mao[2x] [.small]`man-with-gua-pi-mao` +
emoji:cop[2x] [.small]`cop` +
emoji:smiley-cat[2x] [.small]`smiley-cat` +
emoji:kissing-cat[2x] [.small]`kissing-cat` +
emoji:crying-cat-face[2x] [.small]`crying-cat-face` +
emoji:japanese-ogre[2x] [.small]`japanese-ogre` +
emoji:hear-no-evil[2x] [.small]`hear-no-evil` +
emoji:skull[2x] [.small]`skull` +
emoji:kiss[2x] [.small]`kiss` +
emoji:eyes[2x] [.small]`eyes` +
emoji:love-letter[2x] [.small]`love-letter` +
emoji:speech-balloon[2x] [.small]`speech-balloon` +

a| emoji:blush[2x] [.small]`blush` +
emoji:smirk[2x] [.small]`smirk` +
emoji:kissing-closed-eyes[2x] [.small]`kissing-closed-eyes` +
emoji:satisfied[2x] [.small]`satisfied` +
emoji:stuck-out-tongue-winking-eye[2x] [.small]`stuck-out-tongue-winking-eye` +
emoji:kissing[2x] [.small]`kissing` +
emoji:sleeping[2x] [.small]`sleeping` +
emoji:anguished[2x] [.small]`anguished` +
emoji:confused[2x] [.small]`confused` +
emoji:unamused[2x] [.small]`unamused` +
emoji:weary[2x] [.small]`weary` +
emoji:confounded[2x] [.small]`confounded` +
emoji:persevere[2x] [.small]`persevere` +
emoji:joy[2x] [.small]`joy` +
emoji:tired-face[2x] [.small]`tired-face` +
emoji:triumph[2x] [.small]`triumph` +
emoji:mask[2x] [.small]`mask` +
emoji:imp[2x] [.small]`imp` +
emoji:no-mouth[2x] [.small]`no-mouth` +
emoji:yellow-heart[2x] [.small]`yellow-heart` +
emoji:heart[2x] [.small]`heart` +
emoji:heartbeat[2x] [.small]`heartbeat` +
emoji:revolving-hearts[2x] [.small]`revolving-hearts` +
emoji:sparkles[2x] [.small]`sparkles` +
emoji:dizzy[2x] [.small]`dizzy` +
emoji:exclamation[2x] [.small]`exclamation` +
emoji:grey-question[2x] [.small]`grey-question` +
emoji:sweat-drops[2x] [.small]`sweat-drops` +
emoji:fire[2x] [.small]`fire` +
emoji:thumbsdown[2x] [.small]`thumbsdown` +
emoji:fist[2x] [.small]`fist` +
emoji:hand[2x] [.small]`hand` +
emoji:point-down[2x] [.small]`point-down` +
emoji:raised-hands[2x] [.small]`raised-hands` +
emoji:clap[2x] [.small]`clap` +
emoji:runner[2x] [.small]`runner` +
emoji:dancer[2x] [.small]`dancer` +
emoji:no-good[2x] [.small]`no-good` +
emoji:bride-with-veil[2x] [.small]`bride-with-veil` +
emoji:bow[2x] [.small]`bow` +
emoji:massage[2x] [.small]`massage` +
emoji:boy[2x] [.small]`boy` +
emoji:man[2x] [.small]`man` +
emoji:older-man[2x] [.small]`older-man` +
emoji:man-with-turban[2x] [.small]`man-with-turban` +
emoji:angel[2x] [.small]`angel` +
emoji:smile-cat[2x] [.small]`smile-cat` +
emoji:smirk-cat[2x] [.small]`smirk-cat` +
emoji:joy-cat[2x] [.small]`joy-cat` +
emoji:japanese-goblin[2x] [.small]`japanese-goblin` +
emoji:speak-no-evil[2x] [.small]`speak-no-evil` +
emoji:feet[2x] [.small]`feet` +
emoji:droplet[2x] [.small]`droplet` +
emoji:nose[2x] [.small]`nose` +
emoji:bust-in-silhouette[2x] [.small]`bust-in-silhouette` +
emoji:thought-balloon[2x] [.small]`thought-balloon` +
|===

=== Nature

[cols=3*, frame=none, grid=none]
|===
a| emoji:sunny[2x] [.small]`sunny` +
emoji:snowflake[2x] [.small]`snowflake` +
emoji:cyclone[2x] [.small]`cyclone` +
emoji:cat[2x] [.small]`cat` +
emoji:hamster[2x] [.small]`hamster` +
emoji:frog[2x] [.small]`frog` +
emoji:bear[2x] [.small]`bear` +
emoji:cow[2x] [.small]`cow` +
emoji:monkey[2x] [.small]`monkey` +
emoji:camel[2x] [.small]`camel` +
emoji:panda-face[2x] [.small]`panda-face` +
emoji:baby-chick[2x] [.small]`baby-chick` +
emoji:chicken[2x] [.small]`chicken` +
emoji:bug[2x] [.small]`bug` +
emoji:beetle[2x] [.small]`beetle` +
emoji:tropical-fish[2x] [.small]`tropical-fish` +
emoji:whale2[2x] [.small]`whale2` +
emoji:ram[2x] [.small]`ram` +
emoji:tiger2[2x] [.small]`tiger2` +
emoji:goat[2x] [.small]`goat` +
emoji:pig2[2x] [.small]`pig2` +
emoji:dragon-face[2x] [.small]`dragon-face` +
emoji:dromedary-camel[2x] [.small]`dromedary-camel` +
emoji:poodle[2x] [.small]`poodle` +
emoji:cherry-blossom[2x] [.small]`cherry-blossom` +
emoji:rose[2x] [.small]`rose` +
emoji:maple-leaf[2x] [.small]`maple-leaf` +
emoji:herb[2x] [.small]`herb` +
emoji:palm-tree[2x] [.small]`palm-tree` +
emoji:chestnut[2x] [.small]`chestnut` +
emoji:ear-of-rice[2x] [.small]`ear-of-rice` +
emoji:sun-with-face[2x] [.small]`sun-with-face` +
emoji:new-moon[2x] [.small]`new-moon` +
emoji:waxing-gibbous-moon[2x] [.small]`waxing-gibbous-moon` +
emoji:last-quarter-moon[2x] [.small]`last-quarter-moon` +
emoji:first-quarter-moon-with-face[2x] [.small]`first-quarter-moon-with-face` +
emoji:earth-americas[2x] [.small]`earth-americas` +
emoji:milky-way[2x] [.small]`milky-way` +

a| emoji:umbrella[2x] [.small]`umbrella` +
emoji:snowman[2x] [.small]`snowman` +
emoji:foggy[2x] [.small]`foggy` +
emoji:dog[2x] [.small]`dog` +
emoji:rabbit[2x] [.small]`rabbit` +
emoji:tiger[2x] [.small]`tiger` +
emoji:pig[2x] [.small]`pig` +
emoji:boar[2x] [.small]`boar` +
emoji:horse[2x] [.small]`horse` +
emoji:sheep[2x] [.small]`sheep` +
emoji:snake[2x] [.small]`snake` +
emoji:hatched-chick[2x] [.small]`hatched-chick` +
emoji:penguin[2x] [.small]`penguin` +
emoji:honeybee[2x] [.small]`honeybee` +
emoji:snail[2x] [.small]`snail` +
emoji:fish[2x] [.small]`fish` +
emoji:dolphin[2x] [.small]`dolphin` +
emoji:rat[2x] [.small]`rat` +
emoji:rabbit2[2x] [.small]`rabbit2` +
emoji:rooster[2x] [.small]`rooster` +
emoji:mouse2[2x] [.small]`mouse2` +
emoji:blowfish[2x] [.small]`blowfish` +
emoji:leopard[2x] [.small]`leopard` +
emoji:paw-prints[2x] [.small]`paw-prints` +
emoji:tulip[2x] [.small]`tulip` +
emoji:sunflower[2x] [.small]`sunflower` +
emoji:leaves[2x] [.small]`leaves` +
emoji:mushroom[2x] [.small]`mushroom` +
emoji:evergreen-tree[2x] [.small]`evergreen-tree` +
emoji:seedling[2x] [.small]`seedling` +
emoji:shell[2x] [.small]`shell` +
emoji:full-moon-with-face[2x] [.small]`full-moon-with-face` +
emoji:waxing-crescent-moon[2x] [.small]`waxing-crescent-moon` +
emoji:full-moon[2x] [.small]`full-moon` +
emoji:waning-crescent-moon[2x] [.small]`waning-crescent-moon` +
emoji:moon[2x] [.small]`moon` +
emoji:earth-asia[2x] [.small]`earth-asia` +
emoji:partly-sunny[2x] [.small]`partly-sunny` +

a| emoji:cloud[2x] [.small]`cloud` +
emoji:zap[2x] [.small]`zap` +
emoji:ocean[2x] [.small]`ocean` +
emoji:mouse[2x] [.small]`mouse` +
emoji:wolf[2x] [.small]`wolf` +
emoji:koala[2x] [.small]`koala` +
emoji:pig-nose[2x] [.small]`pig-nose` +
emoji:monkey-face[2x] [.small]`monkey-face` +
emoji:racehorse[2x] [.small]`racehorse` +
emoji:elephant[2x] [.small]`elephant` +
emoji:bird[2x] [.small]`bird` +
emoji:hatching-chick[2x] [.small]`hatching-chick` +
emoji:turtle[2x] [.small]`turtle` +
emoji:ant[2x] [.small]`ant` +
emoji:octopus[2x] [.small]`octopus` +
emoji:whale[2x] [.small]`whale` +
emoji:cow2[2x] [.small]`cow2` +
emoji:water-buffalo[2x] [.small]`water-buffalo` +
emoji:dragon[2x] [.small]`dragon` +
emoji:dog2[2x] [.small]`dog2` +
emoji:ox[2x] [.small]`ox` +
emoji:crocodile[2x] [.small]`crocodile` +
emoji:cat2[2x] [.small]`cat2` +
emoji:bouquet[2x] [.small]`bouquet` +
emoji:four-leaf-clover[2x] [.small]`four-leaf-clover` +
emoji:hibiscus[2x] [.small]`hibiscus` +
emoji:fallen-leaf[2x] [.small]`fallen-leaf` +
emoji:cactus[2x] [.small]`cactus` +
emoji:deciduous-tree[2x] [.small]`deciduous-tree` +
emoji:blossom[2x] [.small]`blossom` +
emoji:globe-with-meridians[2x] [.small]`globe-with-meridians` +
emoji:new-moon-with-face[2x] [.small]`new-moon-with-face` +
emoji:first-quarter-moon[2x] [.small]`first-quarter-moon` +
emoji:waning-gibbous-moon[2x] [.small]`waning-gibbous-moon` +
emoji:last-quarter-moon-with-face[2x] [.small]`last-quarter-moon-with-face` +
emoji:earth-africa[2x] [.small]`earth-africa` +
emoji:volcano[2x] [.small]`volcano` +
|===

=== Objects

[cols=3*, frame=none, grid=none]
|===
a| emoji:bamboo[2x] [.small]`bamboo` +
emoji:school-satchel[2x] [.small]`school-satchel` +
emoji:fireworks[2x] [.small]`fireworks` +
emoji:rice-scene[2x] [.small]`rice-scene` +
emoji:santa[2x] [.small]`santa` +
emoji:apple[2x] [.small]`apple` +
emoji:balloon[2x] [.small]`balloon` +
emoji:baseball[2x] [.small]`baseball` +
emoji:bathtub[2x] [.small]`bathtub` +
emoji:beers[2x] [.small]`beers` +
emoji:bicyclist[2x] [.small]`bicyclist` +
emoji:black-joker[2x] [.small]`black-joker` +
emoji:bomb[2x] [.small]`bomb` +
emoji:books[2x] [.small]`books` +
emoji:bread[2x] [.small]`bread` +
emoji:cake[2x] [.small]`cake` +
emoji:camera[2x] [.small]`camera` +
emoji:cd[2x] [.small]`cd` +
emoji:cherries[2x] [.small]`cherries` +
emoji:clapper[2x] [.small]`clapper` +
emoji:closed-lock-with-key[2x] [.small]`closed-lock-with-key` +
emoji:cocktail[2x] [.small]`cocktail` +
emoji:confetti-ball[2x] [.small]`confetti-ball` +
emoji:credit-card[2x] [.small]`credit-card` +
emoji:curry[2x] [.small]`curry` +
emoji:dart[2x] [.small]`dart` +
emoji:dollar[2x] [.small]`dollar` +
emoji:dress[2x] [.small]`dress` +
emoji:egg[2x] [.small]`egg` +
emoji:email[2x] [.small]`email` +
emoji:fax[2x] [.small]`fax` +
emoji:fishing-pole-and-fish[2x] [.small]`fishing-pole-and-fish` +
emoji:flower-playing-cards[2x] [.small]`flower-playing-cards` +
emoji:fried-shrimp[2x] [.small]`fried-shrimp` +
emoji:gem[2x] [.small]`gem` +
emoji:grapes[2x] [.small]`grapes` +
emoji:guitar[2x] [.small]`guitar` +
emoji:hammer[2x] [.small]`hammer` +
emoji:hearts[2x] [.small]`hearts` +
emoji:hocho[2x] [.small]`hocho` +
emoji:hourglass[2x] [.small]`hourglass` +
emoji:icecream[2x] [.small]`icecream` +
emoji:iphone[2x] [.small]`iphone` +
emoji:kimono[2x] [.small]`kimono` +
emoji:lipstick[2x] [.small]`lipstick` +
emoji:lollipop[2x] [.small]`lollipop` +
emoji:low-brightness[2x] [.small]`low-brightness` +
emoji:mahjong[2x] [.small]`mahjong` +
emoji:mailbox-with-mail[2x] [.small]`mailbox-with-mail` +
emoji:meat-on-bone[2x] [.small]`meat-on-bone` +
emoji:memo[2x] [.small]`memo` +
emoji:minidisc[2x] [.small]`minidisc` +
emoji:mountain-bicyclist[2x] [.small]`mountain-bicyclist` +
emoji:musical-score[2x] [.small]`musical-score` +
emoji:necktie[2x] [.small]`necktie` +
emoji:notebook[2x] [.small]`notebook` +
emoji:oden[2x] [.small]`oden` +
emoji:outbox-tray[2x] [.small]`outbox-tray` +
emoji:pager[2x] [.small]`pager` +
emoji:pear[2x] [.small]`pear` +
emoji:pill[2x] [.small]`pill` +
emoji:postal-horn[2x] [.small]`postal-horn` +
emoji:poultry-leg[2x] [.small]`poultry-leg` +
emoji:pushpin[2x] [.small]`pushpin` +
emoji:ribbon[2x] [.small]`ribbon` +
emoji:rice-cracker[2x] [.small]`rice-cracker` +
emoji:running-shirt-with-sash[2x] [.small]`running-shirt-with-sash` +
emoji:satellite[2x] [.small]`satellite` +
emoji:scroll[2x] [.small]`scroll` +
emoji:shirt[2x] [.small]`shirt` +
emoji:smoking[2x] [.small]`smoking` +
emoji:sound[2x] [.small]`sound` +
emoji:spaghetti[2x] [.small]`spaghetti` +
emoji:straight-ruler[2x] [.small]`straight-ruler` +
emoji:sushi[2x] [.small]`sushi` +
emoji:syringe[2x] [.small]`syringe` +
emoji:tangerine[2x] [.small]`tangerine` +
emoji:telescope[2x] [.small]`telescope` +
emoji:tomato[2x] [.small]`tomato` +
emoji:trophy[2x] [.small]`trophy` +
emoji:tv[2x] [.small]`tv` +
emoji:video-camera[2x] [.small]`video-camera` +
emoji:watch[2x] [.small]`watch` +
emoji:womans-clothes[2x] [.small]`womans-clothes` +
emoji:yen[2x] [.small]`yen` +

a| emoji:gift-heart[2x] [.small]`gift-heart` +
emoji:mortar-board[2x] [.small]`mortar-board` +
emoji:sparkler[2x] [.small]`sparkler` +
emoji:jack-o-lantern[2x] [.small]`jack-o-lantern` +
emoji:8ball[2x] [.small]`8ball` +
emoji:art[2x] [.small]`art` +
emoji:banana[2x] [.small]`banana` +
emoji:basketball[2x] [.small]`basketball` +
emoji:battery[2x] [.small]`battery` +
emoji:bell[2x] [.small]`bell` +
emoji:bikini[2x] [.small]`bikini` +
emoji:black-nib[2x] [.small]`black-nib` +
emoji:bookmark[2x] [.small]`bookmark` +
emoji:boot[2x] [.small]`boot` +
emoji:briefcase[2x] [.small]`briefcase` +
emoji:calendar[2x] [.small]`calendar` +
emoji:candy[2x] [.small]`candy` +
emoji:chart-with-downwards-trend[2x] [.small]`chart-with-downwards-trend` +
emoji:chocolate-bar[2x] [.small]`chocolate-bar` +
emoji:clipboard[2x] [.small]`clipboard` +
emoji:closed-umbrella[2x] [.small]`closed-umbrella` +
emoji:coffee[2x] [.small]`coffee` +
emoji:cookie[2x] [.small]`cookie` +
emoji:crown[2x] [.small]`crown` +
emoji:custard[2x] [.small]`custard` +
emoji:date[2x] [.small]`date` +
emoji:door[2x] [.small]`door` +
emoji:dvd[2x] [.small]`dvd` +
emoji:eggplant[2x] [.small]`eggplant` +
emoji:euro[2x] [.small]`euro` +
emoji:file-folder[2x] [.small]`file-folder` +
emoji:flashlight[2x] [.small]`flashlight` +
emoji:football[2x] [.small]`football` +
emoji:fries[2x] [.small]`fries` +
emoji:gift[2x] [.small]`gift` +
emoji:green-apple[2x] [.small]`green-apple` +
emoji:gun[2x] [.small]`gun` +
emoji:handbag[2x] [.small]`handbag` +
emoji:high-brightness[2x] [.small]`high-brightness` +
emoji:honey-pot[2x] [.small]`honey-pot` +
emoji:hourglass-flowing-sand[2x] [.small]`hourglass-flowing-sand` +
emoji:inbox-tray[2x] [.small]`inbox-tray` +
emoji:jeans[2x] [.small]`jeans` +
emoji:ledger[2x] [.small]`ledger` +
emoji:lock[2x] [.small]`lock` +
emoji:loop[2x] [.small]`loop` +
emoji:mag[2x] [.small]`mag` +
emoji:mailbox[2x] [.small]`mailbox` +
emoji:mailbox-with-no-mail[2x] [.small]`mailbox-with-no-mail` +
emoji:mega[2x] [.small]`mega` +
emoji:microphone[2x] [.small]`microphone` +
emoji:money-with-wings[2x] [.small]`money-with-wings` +
emoji:movie-camera[2x] [.small]`movie-camera` +
emoji:mute[2x] [.small]`mute` +
emoji:newspaper[2x] [.small]`newspaper` +
emoji:notebook-with-decorative-cover[2x] [.small]`notebook-with-decorative-cover` +
emoji:open-file-folder[2x] [.small]`open-file-folder` +
emoji:page-facing-up[2x] [.small]`page-facing-up` +
emoji:paperclip[2x] [.small]`paperclip` +
emoji:pencil2[2x] [.small]`pencil2` +
emoji:pineapple[2x] [.small]`pineapple` +
emoji:postbox[2x] [.small]`postbox` +
emoji:pound[2x] [.small]`pound` +
emoji:radio[2x] [.small]`radio` +
emoji:rice[2x] [.small]`rice` +
emoji:ring[2x] [.small]`ring` +
emoji:sake[2x] [.small]`sake` +
emoji:saxophone[2x] [.small]`saxophone` +
emoji:seat[2x] [.small]`seat` +
emoji:shower[2x] [.small]`shower` +
emoji:snowboarder[2x] [.small]`snowboarder` +
emoji:space-invader[2x] [.small]`space-invader` +
emoji:speaker[2x] [.small]`speaker` +
emoji:strawberry[2x] [.small]`strawberry` +
emoji:sweet-potato[2x] [.small]`sweet-potato` +
emoji:tada[2x] [.small]`tada` +
emoji:tea[2x] [.small]`tea` +
emoji:tennis[2x] [.small]`tennis` +
emoji:tophat[2x] [.small]`tophat` +
emoji:tropical-drink[2x] [.small]`tropical-drink` +
emoji:unlock[2x] [.small]`unlock` +
emoji:video-game[2x] [.small]`video-game` +
emoji:watermelon[2x] [.small]`watermelon` +
emoji:womans-hat[2x] [.small]`womans-hat` +

a| emoji:dolls[2x] [.small]`dolls` +
emoji:flags[2x] [.small]`flags` +
emoji:wind-chime[2x] [.small]`wind-chime` +
emoji:ghost[2x] [.small]`ghost` +
emoji:alarm-clock[2x] [.small]`alarm-clock` +
emoji:baby-bottle[2x] [.small]`baby-bottle` +
emoji:bar-chart[2x] [.small]`bar-chart` +
emoji:bath[2x] [.small]`bath` +
emoji:beer[2x] [.small]`beer` +
emoji:bento[2x] [.small]`bento` +
emoji:birthday[2x] [.small]`birthday` +
emoji:blue-book[2x] [.small]`blue-book` +
emoji:bookmark-tabs[2x] [.small]`bookmark-tabs` +
emoji:bowling[2x] [.small]`bowling` +
emoji:bulb[2x] [.small]`bulb` +
emoji:calling[2x] [.small]`calling` +
emoji:card-index[2x] [.small]`card-index` +
emoji:chart-with-upwards-trend[2x] [.small]`chart-with-upwards-trend` +
emoji:christmas-tree[2x] [.small]`christmas-tree` +
emoji:closed-book[2x] [.small]`closed-book` +
emoji:clubs[2x] [.small]`clubs` +
emoji:computer[2x] [.small]`computer` +
emoji:corn[2x] [.small]`corn` +
emoji:crystal-ball[2x] [.small]`crystal-ball` +
emoji:dango[2x] [.small]`dango` +
emoji:diamonds[2x] [.small]`diamonds` +
emoji:doughnut[2x] [.small]`doughnut` +
emoji:e-mail[2x] [.small]`e-mail` +
emoji:electric-plug[2x] [.small]`electric-plug` +
emoji:eyeglasses[2x] [.small]`eyeglasses` +
emoji:fish-cake[2x] [.small]`fish-cake` +
emoji:floppy-disk[2x] [.small]`floppy-disk` +
emoji:fork-and-knife[2x] [.small]`fork-and-knife` +
emoji:game-die[2x] [.small]`game-die` +
emoji:golf[2x] [.small]`golf` +
emoji:green-book[2x] [.small]`green-book` +
emoji:hamburger[2x] [.small]`hamburger` +
emoji:headphones[2x] [.small]`headphones` +
emoji:high-heel[2x] [.small]`high-heel` +
emoji:horse-racing[2x] [.small]`horse-racing` +
emoji:ice-cream[2x] [.small]`ice-cream` +
emoji:incoming-envelope[2x] [.small]`incoming-envelope` +
emoji:key[2x] [.small]`key` +
emoji:lemon[2x] [.small]`lemon` +
emoji:lock-with-ink-pen[2x] [.small]`lock-with-ink-pen` +
emoji:loudspeaker[2x] [.small]`loudspeaker` +
emoji:mag-right[2x] [.small]`mag-right` +
emoji:mailbox-closed[2x] [.small]`mailbox-closed` +
emoji:mans-shoe[2x] [.small]`mans-shoe` +
emoji:melon[2x] [.small]`melon` +
emoji:microscope[2x] [.small]`microscope` +
emoji:moneybag[2x] [.small]`moneybag` +
emoji:musical-keyboard[2x] [.small]`musical-keyboard` +
emoji:name-badge[2x] [.small]`name-badge` +
emoji:no-bell[2x] [.small]`no-bell` +
emoji:nut-and-bolt[2x] [.small]`nut-and-bolt` +
emoji:orange-book[2x] [.small]`orange-book` +
emoji:page-with-curl[2x] [.small]`page-with-curl` +
emoji:peach[2x] [.small]`peach` +
emoji:phone[2x] [.small]`phone` +
emoji:pizza[2x] [.small]`pizza` +
emoji:pouch[2x] [.small]`pouch` +
emoji:purse[2x] [.small]`purse` +
emoji:ramen[2x] [.small]`ramen` +
emoji:rice-ball[2x] [.small]`rice-ball` +
emoji:rugby-football[2x] [.small]`rugby-football` +
emoji:sandal[2x] [.small]`sandal` +
emoji:scissors[2x] [.small]`scissors` +
emoji:shaved-ice[2x] [.small]`shaved-ice` +
emoji:ski[2x] [.small]`ski` +
emoji:soccer[2x] [.small]`soccer` +
emoji:spades[2x] [.small]`spades` +
emoji:stew[2x] [.small]`stew` +
emoji:surfer[2x] [.small]`surfer` +
emoji:swimmer[2x] [.small]`swimmer` +
emoji:tanabata-tree[2x] [.small]`tanabata-tree` +
emoji:telephone-receiver[2x] [.small]`telephone-receiver` +
emoji:toilet[2x] [.small]`toilet` +
emoji:triangular-ruler[2x] [.small]`triangular-ruler` +
emoji:trumpet[2x] [.small]`trumpet` +
emoji:vhs[2x] [.small]`vhs` +
emoji:violin[2x] [.small]`violin` +
emoji:wine-glass[2x] [.small]`wine-glass` +
emoji:wrench[2x] [.small]`wrench` +
|===

=== Places

[cols=3*, frame=none, grid=none]
|===
a| emoji:aerial-tramway[2x] [.small]`aerial-tramway` +
emoji:anchor[2x] [.small]`anchor` +
emoji:bank[2x] [.small]`bank` +
emoji:bike[2x] [.small]`bike` +
emoji:bridge-at-night[2x] [.small]`bridge-at-night` +
emoji:bus[2x] [.small]`bus` +
emoji:carousel-horse[2x] [.small]`carousel-horse` +
emoji:circus-tent[2x] [.small]`circus-tent` +
emoji:construction[2x] [.small]`construction` +
emoji:department-store[2x] [.small]`department-store` +
emoji:factory[2x] [.small]`factory` +
emoji:fountain[2x] [.small]`fountain` +
emoji:hospital[2x] [.small]`hospital` +
emoji:house[2x] [.small]`house` +
emoji:japanese-castle[2x] [.small]`japanese-castle` +
emoji:minibus[2x] [.small]`minibus` +
emoji:mountain-cableway[2x] [.small]`mountain-cableway` +
emoji:office[2x] [.small]`office` +
emoji:oncoming-police-car[2x] [.small]`oncoming-police-car` +
emoji:police-car[2x] [.small]`police-car` +
emoji:rainbow[2x] [.small]`rainbow` +
emoji:rotating-light[2x] [.small]`rotating-light` +
emoji:school[2x] [.small]`school` +
emoji:speedboat[2x] [.small]`speedboat` +
emoji:statue-of-liberty[2x] [.small]`statue-of-liberty` +
emoji:sunrise-over-mountains[2x] [.small]`sunrise-over-mountains` +
emoji:tent[2x] [.small]`tent` +
emoji:tractor[2x] [.small]`tractor` +
emoji:tram[2x] [.small]`tram` +
emoji:truck[2x] [.small]`truck` +
emoji:wedding[2x] [.small]`wedding` +
emoji:cn[2x] [.small]`cn` +
emoji:es[2x] [.small]`es` +
emoji:gb[2x] [.small]`gb` +

a| emoji:airplane[2x] [.small]`airplane` +
emoji:articulated-lorry[2x] [.small]`articulated-lorry` +
emoji:barber[2x] [.small]`barber` +
emoji:blue-car[2x] [.small]`blue-car` +
emoji:bullettrain-front[2x] [.small]`bullettrain-front` +
emoji:busstop[2x] [.small]`busstop` +
emoji:checkered-flag[2x] [.small]`checkered-flag` +
emoji:city-sunrise[2x] [.small]`city-sunrise` +
emoji:convenience-store[2x] [.small]`convenience-store` +
emoji:european-castle[2x] [.small]`european-castle` +
emoji:ferris-wheel[2x] [.small]`ferris-wheel` +
emoji:fuelpump[2x] [.small]`fuelpump` +
emoji:hotel[2x] [.small]`hotel` +
emoji:house-with-garden[2x] [.small]`house-with-garden` +
emoji:light-rail[2x] [.small]`light-rail` +
emoji:monorail[2x] [.small]`monorail` +
emoji:mountain-railway[2x] [.small]`mountain-railway` +
emoji:oncoming-automobile[2x] [.small]`oncoming-automobile` +
emoji:oncoming-taxi[2x] [.small]`oncoming-taxi` +
emoji:post-office[2x] [.small]`post-office` +
emoji:rocket[2x] [.small]`rocket` +
emoji:round-pushpin[2x] [.small]`round-pushpin` +
emoji:ship[2x] [.small]`ship` +
emoji:stars[2x] [.small]`stars` +
emoji:steam-locomotive[2x] [.small]`steam-locomotive` +
emoji:suspension-railway[2x] [.small]`suspension-railway` +
emoji:ticket[2x] [.small]`ticket` +
emoji:traffic-light[2x] [.small]`traffic-light` +
emoji:triangular-flag-on-post[2x] [.small]`triangular-flag-on-post` +
emoji:vertical-traffic-light[2x] [.small]`vertical-traffic-light` +
emoji:jp[2x] [.small]`jp` +
emoji:us[2x] [.small]`us` +
emoji:it[2x] [.small]`it` +
emoji:de[2x] [.small]`de` +

a| emoji:ambulance[2x] [.small]`ambulance` +
emoji:atm[2x] [.small]`atm` +
emoji:beginner[2x] [.small]`beginner` +
emoji:boat[2x] [.small]`boat` +
emoji:bullettrain-side[2x] [.small]`bullettrain-side` +
emoji:car[2x] [.small]`car` +
emoji:church[2x] [.small]`church` +
emoji:city-sunset[2x] [.small]`city-sunset` +
emoji:crossed-flags[2x] [.small]`crossed-flags` +
emoji:european-post-office[2x] [.small]`european-post-office` +
emoji:fire-engine[2x] [.small]`fire-engine` +
emoji:helicopter[2x] [.small]`helicopter` +
emoji:hotsprings[2x] [.small]`hotsprings` +
emoji:japan[2x] [.small]`japan` +
emoji:love-hotel[2x] [.small]`love-hotel` +
emoji:mount-fuji[2x] [.small]`mount-fuji` +
emoji:moyai[2x] [.small]`moyai` +
emoji:oncoming-bus[2x] [.small]`oncoming-bus` +
emoji:performing-arts[2x] [.small]`performing-arts` +
emoji:railway-car[2x] [.small]`railway-car` +
emoji:roller-coaster[2x] [.small]`roller-coaster` +
emoji:rowboat[2x] [.small]`rowboat` +
emoji:slot-machine[2x] [.small]`slot-machine` +
emoji:station[2x] [.small]`station` +
emoji:sunrise[2x] [.small]`sunrise` +
emoji:taxi[2x] [.small]`taxi` +
emoji:tokyo-tower[2x] [.small]`tokyo-tower` +
emoji:train2[2x] [.small]`train2` +
emoji:trolleybus[2x] [.small]`trolleybus` +
emoji:warning[2x] [.small]`warning` +
emoji:kr[2x] [.small]`kr` +
emoji:fr[2x] [.small]`fr` +
emoji:ru[2x] [.small]`ru` +
|===

=== Symbols

[cols=3*, frame=none, grid=none]
|===
a| emoji:100[2x] [.small]`100` +
emoji:ab[2x] [.small]`ab` +
emoji:accept[2x] [.small]`accept` +
emoji:arrow-backward[2x] [.small]`arrow-backward` +
emoji:arrow-down[2x] [.small]`arrow-down` +
emoji:arrow-heading-down[2x] [.small]`arrow-heading-down` +
emoji:arrow-lower-left[2x] [.small]`arrow-lower-left` +
emoji:arrow-right-hook[2x] [.small]`arrow-right-hook` +
emoji:arrow-up-small[2x] [.small]`arrow-up-small` +
emoji:arrows-clockwise[2x] [.small]`arrows-clockwise` +
emoji:baby-symbol[2x] [.small]`baby-symbol` +
emoji:bangbang[2x] [.small]`bangbang` +
emoji:cancer[2x] [.small]`cancer` +
emoji:chart[2x] [.small]`chart` +
emoji:cl[2x] [.small]`cl` +
emoji:clock1030[2x] [.small]`clock1030` +
emoji:clock12[2x] [.small]`clock12` +
emoji:clock2[2x] [.small]`clock2` +
emoji:clock330[2x] [.small]`clock330` +
emoji:clock5[2x] [.small]`clock5` +
emoji:clock630[2x] [.small]`clock630` +
emoji:clock8[2x] [.small]`clock8` +
emoji:clock930[2x] [.small]`clock930` +
emoji:copyright[2x] [.small]`copyright` +
emoji:customs[2x] [.small]`customs` +
emoji:eight[2x] [.small]`eight` +
emoji:end[2x] [.small]`end` +
emoji:four[2x] [.small]`four` +
emoji:hash[2x] [.small]`hash` +
emoji:heavy-division-sign[2x] [.small]`heavy-division-sign` +
emoji:heavy-multiplication-x[2x] [.small]`heavy-multiplication-x` +
emoji:ideograph-advantage[2x] [.small]`ideograph-advantage` +
emoji:keycap-ten[2x] [.small]`keycap-ten` +
emoji:large-blue-diamond[2x] [.small]`large-blue-diamond` +
emoji:left-right-arrow[2x] [.small]`left-right-arrow` +
emoji:libra[2x] [.small]`libra` +
emoji:mens[2x] [.small]`mens` +
emoji:negative-squared-cross-mark[2x] [.small]`negative-squared-cross-mark` +
emoji:nine[2x] [.small]`nine` +
emoji:no-entry-sign[2x] [.small]`no-entry-sign` +
emoji:no-smoking[2x] [.small]`no-smoking` +
emoji:o2[2x] [.small]`o2` +
emoji:one[2x] [.small]`one` +
emoji:part-alternation-mark[2x] [.small]`part-alternation-mark` +
emoji:potable-water[2x] [.small]`potable-water` +
emoji:recycle[2x] [.small]`recycle` +
emoji:repeat[2x] [.small]`repeat` +
emoji:rewind[2x] [.small]`rewind` +
emoji:scorpius[2x] [.small]`scorpius` +
emoji:signal-strength[2x] [.small]`signal-strength` +
emoji:small-blue-diamond[2x] [.small]`small-blue-diamond` +
emoji:small-red-triangle-down[2x] [.small]`small-red-triangle-down` +
emoji:symbols[2x] [.small]`symbols` +
emoji:tm[2x] [.small]`tm` +
emoji:twisted-rightwards-arrows[2x] [.small]`twisted-rightwards-arrows` +
emoji:u5408[2x] [.small]`u5408` +
emoji:u6708[2x] [.small]`u6708` +
emoji:u7121[2x] [.small]`u7121` +
emoji:u7a7a[2x] [.small]`u7a7a` +
emoji:vibration-mode[2x] [.small]`vibration-mode` +
emoji:wavy-dash[2x] [.small]`wavy-dash` +
emoji:white-check-mark[2x] [.small]`white-check-mark` +
emoji:white-square-button[2x] [.small]`white-square-button` +
emoji:zero[2x] [.small]`zero` +

a| emoji:1234[2x] [.small]`1234` +
emoji:abc[2x] [.small]`abc` +
emoji:aquarius[2x] [.small]`aquarius` +
emoji:arrow-double-down[2x] [.small]`arrow-double-down` +
emoji:arrow-down-small[2x] [.small]`arrow-down-small` +
emoji:arrow-heading-up[2x] [.small]`arrow-heading-up` +
emoji:arrow-lower-right[2x] [.small]`arrow-lower-right` +
emoji:arrow-up[2x] [.small]`arrow-up` +
emoji:arrow-upper-left[2x] [.small]`arrow-upper-left` +
emoji:arrows-counterclockwise[2x] [.small]`arrows-counterclockwise` +
emoji:baggage-claim[2x] [.small]`baggage-claim` +
emoji:black-circle[2x] [.small]`black-circle` +
emoji:capital-abcd[2x] [.small]`capital-abcd` +
emoji:children-crossing[2x] [.small]`children-crossing` +
emoji:clock1[2x] [.small]`clock1` +
emoji:clock11[2x] [.small]`clock11` +
emoji:clock1230[2x] [.small]`clock1230` +
emoji:clock230[2x] [.small]`clock230` +
emoji:clock4[2x] [.small]`clock4` +
emoji:clock530[2x] [.small]`clock530` +
emoji:clock7[2x] [.small]`clock7` +
emoji:clock830[2x] [.small]`clock830` +
emoji:congratulations[2x] [.small]`congratulations` +
emoji:curly-loop[2x] [.small]`curly-loop` +
emoji:diamond-shape-with-a-dot-inside[2x] [.small]`diamond-shape-with-a-dot-inside` +
emoji:eight-pointed-black-star[2x] [.small]`eight-pointed-black-star` +
emoji:fast-forward[2x] [.small]`fast-forward` +
emoji:free[2x] [.small]`free` +
emoji:heart-decoration[2x] [.small]`heart-decoration` +
emoji:heavy-dollar-sign[2x] [.small]`heavy-dollar-sign` +
emoji:heavy-plus-sign[2x] [.small]`heavy-plus-sign` +
emoji:information-source[2x] [.small]`information-source` +
emoji:koko[2x] [.small]`koko` +
emoji:large-orange-diamond[2x] [.small]`large-orange-diamond` +
emoji:leftwards-arrow-with-hook[2x] [.small]`leftwards-arrow-with-hook` +
emoji:link[2x] [.small]`link` +
emoji:metro[2x] [.small]`metro` +
emoji:new[2x] [.small]`new` +
emoji:no-bicycles[2x] [.small]`no-bicycles` +
emoji:no-mobile-phones[2x] [.small]`no-mobile-phones` +
emoji:non-potable-water[2x] [.small]`non-potable-water` +
emoji:ok[2x] [.small]`ok` +
emoji:ophiuchus[2x] [.small]`ophiuchus` +
emoji:passport-control[2x] [.small]`passport-control` +
emoji:put-litter-in-its-place[2x] [.small]`put-litter-in-its-place` +
emoji:red-circle[2x] [.small]`red-circle` +
emoji:repeat-one[2x] [.small]`repeat-one` +
emoji:sa[2x] [.small]`sa` +
emoji:secret[2x] [.small]`secret` +
emoji:six[2x] [.small]`six` +
emoji:small-orange-diamond[2x] [.small]`small-orange-diamond` +
emoji:soon[2x] [.small]`soon` +
emoji:taurus[2x] [.small]`taurus` +
emoji:top[2x] [.small]`top` +
emoji:two[2x] [.small]`two` +
emoji:u55b6[2x] [.small]`u55b6` +
emoji:u6709[2x] [.small]`u6709` +
emoji:u7533[2x] [.small]`u7533` +
emoji:underage[2x] [.small]`underage` +
emoji:virgo[2x] [.small]`virgo` +
emoji:wc[2x] [.small]`wc` +
emoji:white-circle[2x] [.small]`white-circle` +
emoji:womens[2x] [.small]`womens` +

a| emoji:a[2x] [.small]`a` +
emoji:abcd[2x] [.small]`abcd` +
emoji:aries[2x] [.small]`aries` +
emoji:arrow-double-up[2x] [.small]`arrow-double-up` +
emoji:arrow-forward[2x] [.small]`arrow-forward` +
emoji:arrow-left[2x] [.small]`arrow-left` +
emoji:arrow-right[2x] [.small]`arrow-right` +
emoji:arrow-up-down[2x] [.small]`arrow-up-down` +
emoji:arrow-upper-right[2x] [.small]`arrow-upper-right` +
emoji:b[2x] [.small]`b` +
emoji:ballot-box-with-check[2x] [.small]`ballot-box-with-check` +
emoji:black-square-button[2x] [.small]`black-square-button` +
emoji:capricorn[2x] [.small]`capricorn` +
emoji:cinema[2x] [.small]`cinema` +
emoji:clock10[2x] [.small]`clock10` +
emoji:clock1130[2x] [.small]`clock1130` +
emoji:clock130[2x] [.small]`clock130` +
emoji:clock3[2x] [.small]`clock3` +
emoji:clock430[2x] [.small]`clock430` +
emoji:clock6[2x] [.small]`clock6` +
emoji:clock730[2x] [.small]`clock730` +
emoji:clock9[2x] [.small]`clock9` +
emoji:cool[2x] [.small]`cool` +
emoji:currency-exchange[2x] [.small]`currency-exchange` +
emoji:do-not-litter[2x] [.small]`do-not-litter` +
emoji:eight-spoked-asterisk[2x] [.small]`eight-spoked-asterisk` +
emoji:five[2x] [.small]`five` +
emoji:gemini[2x] [.small]`gemini` +
emoji:heavy-check-mark[2x] [.small]`heavy-check-mark` +
emoji:heavy-minus-sign[2x] [.small]`heavy-minus-sign` +
emoji:id[2x] [.small]`id` +
emoji:interrobang[2x] [.small]`interrobang` +
emoji:large-blue-circle[2x] [.small]`large-blue-circle` +
emoji:left-luggage[2x] [.small]`left-luggage` +
emoji:leo[2x] [.small]`leo` +
emoji:m[2x] [.small]`m` +
emoji:mobile-phone-off[2x] [.small]`mobile-phone-off` +
emoji:ng[2x] [.small]`ng` +
emoji:no-entry[2x] [.small]`no-entry` +
emoji:no-pedestrians[2x] [.small]`no-pedestrians` +
emoji:o[2x] [.small]`o` +
emoji:on[2x] [.small]`on` +
emoji:parking[2x] [.small]`parking` +
emoji:pisces[2x] [.small]`pisces` +
emoji:radio-button[2x] [.small]`radio-button` +
emoji:registered[2x] [.small]`registered` +
emoji:restroom[2x] [.small]`restroom` +
emoji:sagittarius[2x] [.small]`sagittarius` +
emoji:seven[2x] [.small]`seven` +
emoji:six-pointed-star[2x] [.small]`six-pointed-star` +
emoji:small-red-triangle[2x] [.small]`small-red-triangle` +
emoji:sos[2x] [.small]`sos` +
emoji:three[2x] [.small]`three` +
emoji:trident[2x] [.small]`trident` +
emoji:u5272[2x] [.small]`u5272` +
emoji:u6307[2x] [.small]`u6307` +
emoji:u6e80[2x] [.small]`u6e80` +
emoji:u7981[2x] [.small]`u7981` +
emoji:up[2x] [.small]`up` +
emoji:vs[2x] [.small]`vs` +
emoji:wheelchair[2x] [.small]`wheelchair` +
emoji:white-flower[2x] [.small]`white-flower` +
emoji:x[2x] [.small]`x` +
|===
