= Welcome to your new DokuWiki
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Congratulations, your wiki is now up and running. Here are a few more tips to get you started.

Enjoy your work with DokuWiki,+
– the developers


== Create your first pages

Your wiki needs to have a start page. As long as it doesn't exist, this link will be red: <<start#,start>>.

Go on, follow that link and create the page. If you need help with using the syntax you can always refer to the <<wiki/syntax#,syntax page>>.

You might also want to use a sidebar. To create it, just edit the <<sidebar#,sidebar>> page. Everything in that page will be shown in a margin column on the side. Read our link:http://www.dokuwiki.org/faq%3Asidebar[FAQ on sidebars] to learn more.

Please be aware that not all templates support sidebars.


== Customize your Wiki

Once you're comfortable with creating and editing pages you might want to have a look at the doku.php?do=admin&page=config[configuration settings] (be sure to login as superuser first).

You may also want to see what link:http://www.dokuwiki.org/plugins[plugins] and link:http://www.dokuwiki.org/templates[templates] are available at DokuWiki.org to extend the functionality and looks of your DokuWiki installation.


== Join the Community

DokuWiki is an Open Source project that thrives through user contributions. A good way to stay informed on what's going on and to get useful tips in using DokuWiki is subscribing to the link:http://www.dokuwiki.org/newsletter[newsletter].

The link:http://forum.dokuwiki.org[DokuWiki User Forum] is an excellent way to get in contact with other DokuWiki users and is just one of the many ways to get link:http://www.dokuwiki.org/faq%3Asupport[support].

Of course we'd be more than happy to have you link:http://www.dokuwiki.org/teams%3Agetting_involved[getting involved] with DokuWiki.
