= Anatomy of a Wiki Header
:author: mitm
:revnumber:
:revdate: 2017-09-08T23:24:11.262Z
:relfileprefix: ../
:imagesdir: ..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

All wiki documents use these header attributes. Optional attributes can be left blank following the kbd:[:] colon symbol.

[source,subs="+macros"]
----
= Enter Document Title Here
:author:
:revnumber:
:revdate:
:relfileprefix: ../../
:imagesdir: ../..
:experimental:
ifdef++::++env-github,env-browser[:outfilesuffix: .adoc]
----

*pass:[=]* Mandatory. Title of your document.

*pass:[:]author:* Optional. Document author.

*pass:[:]revnumber:* Optional. Revision number.

*pass:[:]revdate:* Optional. Revision Date

*pass:[:]relfileprefix:* Mandatory. Enter a path to the "`asciidoc`" folder.

TIP: Use `Tree View` (kbd:[ctrl]+kbd:[\ ] or `menu:View[Toggle Tree View]`) to locate the "`asciidoc`" folder if using the link:https://atom.io/[Atom editor].

In the example below, "`asciidoc`" is two folders above the folder this file is located in.

`pass:[:]relfileprefix: ../../`

*pass:[:]imagesdir:* Mandatory. Enter a path to the "images" folder.

TIP: Use `Tree View` (kbd:[ctrl]+kbd:[\ ] or `menu:View[Toggle Tree View]`) to locate the "`images`" folder if using the link:https://atom.io/[Atom editor].

In the example below, "`images`" is two folders above the folder this file is located in. Note the missing kbd:[/] forward slash.

`pass:[:]imagesdir: ../..`

[TIP]
====
A simple way to determine the location of the "asciidoc" and "images" folder in the Atom editor is first save the file to its new location, then in `Tree View` (kbd:[ctrl]+kbd:[\ ] or `menu:View[Toggle Tree View]`), btn:[RMB] select the saved file and select btn:[Copy Project Path].

Temporarily paste this into your document to see where the "`asciidoc`" folder is located.

For example: `src\docs\asciidoc\jme3\advanced\3d_models.adoc`

In this example, "asciidoc" is located two folders above the "advanced" folder `3d_models.adoc` resides in.

You can find this same folder information using link:https://github.com/jMonkeyEngine/wiki/blob/master/src/docs/asciidoc/jme3/advanced/3d_models.adoc[GitHub].
====

The "`images`" folder resides in the same folder as the "`asciidoc`" folder so it has the same setting minus the kbd:[/ ] forward slash.

*pass:[:]experimental:* Leave this blank. This is the experimental attribute that allows the use of link:http://asciidoctor.org/docs/user-manual/#user-interface-macros[User Interface Macros]. You use these macros for creating keyboard shortcuts, displaying menu selections and UI buttons.

*ifdef++::++env-github,env-browser[:outfilesuffix: .adoc]* See link:http://asciidoctor.org/docs/user-manual/#navigating-between-source-files[Navigating Between Source Files] in the AsciiDoctor user manual. Leave this as written.
