= phase1
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../
:imagesdir: ../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== PHASE 1

*HI, WELCOME AGAIN !*

Glad that we made it through a month already. In fact I don't have much time to work on this project but it's still under control. 

Most important, we've had the base working with a three layers architecture of Server Client and Common which are know minimum amount of each other, beside of achieved other design goals… It's also good enough to be a Proof of concept at this point.. In conclusion, what we achieved in Phase Zero is a stable software design, gameplay and some WIP assets, and last but not least the Taste of an MMO. :p Nice!

Now we're going to move to the Phase 1. 

*Duration:* August 1st - Oct 1st . 2013

*Tasks:*

*Features:*

*Bugs:*


== Detail


== Concepts

Pictures

Videos


== Assets


=== 3D


=== Textures


=== Animations


== Programming


== Use of tools


=== Something to try
