= researches
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../
:imagesdir: ../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== Frameworks

Can be valuable in other field than MMO.

That said the contents here are not just about *Game developing* but also can be *Large-scale simulation* which can required *Distributed computing* model.


[TIP]
====
Collections of revelant articles and papers. 
GOTO <<jme3/atomixtuts/mmorpg/articlelinks#,articleLinks>>


====



=== Event/ Network/ Protocol Frameworks


==== Mina


==== Netty


==== ZeroMQ


==== FidMQ


==== KryoNet


==== Thrif


==== Protocol Buffers

More Goto <<jme3/atomixtuts/mmorpg/researches/network/probuf#,probuf>>


==== ICE

The Internet Communications Engine (Ice) is a modern object-oriented toolkit that enables you to build distributed applications with minimal effort. Ice allows you to focus your efforts on your application logic, and it takes care of all interactions with low-level network programming interfaces. With Ice, there is no need to worry about details such as opening network connections, serializing and deserializing data for network transmission, or retrying failed connection attempts (to name but a few of dozens of such low-level details). 

More Goto <<jme3/atomixtuts/mmorpg/researches/network/ice#,ice>>


=== Database Frameworks


==== ORM


===== Apache Cayenne


===== Hibernate


==== NoSQL


===== Neo4J

GOTO [jme3:atomixtuts:mmorpg:neo4j]


=== Distributed Computing Frameworks

In the order of scale and related to gaming from author's POV


==== Hadoop and folks


==== Storm


==== Akka


==== Frameworks Comperations

Some articles focus in comparation of Distributed Computing frameworks


===== Storm VS Akka

link:http://www.warski.org/blog/2013/06/akka-vs-storm/[http://www.warski.org/blog/2013/06/akka-vs-storm/]

<<jme3/atomixtuts/mmorpg/scala#,scala>>

==Storm VS Hadoop =


=== Distributed Software/Deploying Frameworks (Cloud)

In the order of scale and related to gaming from author's POV


==== GoogleAppEngine


=== Benchmarking test


=== Full scale MMORPG frameworks


==== ThreeRings - OOO Core Libraries

*  Narya, Nenya, Vilya, and Clyde: a collection of Java tools and frameworks useful for making games, 2D and 3D, networked and otherwise.
*  Getdown: a system for deploying Java-based applications and updating them over the network following installation.
*  Depot: a declarative Java object-relational mapping library that uses EJB3 annotations but is not managed like Hibernate and friends.
*  GWT Utils: a collection of utility and user interface routines that make developing games and applications in GWT more pleasant.
*  Honeybird: a library that makes interacting with the Google Analytics +++<abbr title="Application Programming Interface">API</abbr>+++ more pleasant.
*  


=== Evaluation


== Toolset

Read the full article in researches about the open-source and commercial tool for MMORPG we have currently (well, the most popular) 

[TIP]
====

Article about Toolset for MMORPG 
GOTO <<jme3/atomixtuts/mmorpg/tooset#,tooset>>

====

