= Models and Scenes
:author:
:revnumber:
:revdate: 2020/07/15


Like xref:jme3/advanced/shape.adoc[Shape]s, 3D models are also made up of xref:jme3/advanced/mesh.adoc[Mesh]es, but models are more complex than Shapes. While Shapes are built into jME3, you typically create models in external 3D Mesh Editors.


== Using Models and Scenes with jME3

To use 3D models in a jME3 application:

.  Export the 3D model using a xref:jme3/features.adoc#supported-external-file-types.adoc[Supported External File Type].
.  Save the files into a sub-directory of your jME3 `Assets` directory.
.  In your code, you use the xref:jme3/advanced/asset_manager.adoc[Asset Manager] to load models as xref:jme3/advanced/spatial.adoc[Spatial]s into a jME application.
+
[source,java]
----
Spatial model = assetManager.loadModel(
    "Models/MonkeyHead/MonkeyHead.mesh.xml" );
----

[NOTE]
====
(For the release build:) Use one of methods recommended for your 3D model xref:jme3/features.adoc#supported-external-file-types.adoc[Supported External File Type] to convert the model to .j3o format. You don't need this step until you deploy your application if you are making frequent changes to your models, however, you should get into the habit of always converting your models.
====


== Creating Models and Scenes

To create 3D models and scenes, you need a 3D Mesh Editor such as link:http://www.blender.org/[Blender].

[TIP]
====
Learn how to create link:http://en.wikibooks.org/wiki/Blender_3D:_Noob_to_Pro/UV_Map_Basics[UV textures] for more complex models, it looks more professional.
====

3D model editors are third-party products, so please consult their documentation for instructions how to use them. Here is an example workflow for Blender users:

*  xref:jme3/external/blender.adoc[Creating assets in Blender3D]
