= Blender Buffer Clearing
:author: mitm
:revnumber: 1.0
:relfileprefix: ../../../
:imagesdir: ../../..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Before exporting your Blender models, its is recommended that you clean the buffers of any unneeded `Action`, `Material`, `Texture` or `UV Image`. This is a straight forward process that only takes a few minutes. Failure to do so can lead you into a morass of problems, like having more than one AnimControl, duplicate materials and textures, wasted space from worthless images, just to mention a few potential troubles.


== Material, Texture, UV Image Buffers


.  Open the `UV Image Editor`, `Material Tab` or `Texture Tab`.
.  Select the btn:[Browse] button located next to the material, texture or UV Image name to load the item to be cleared.
.  While holding kbd:[Shift] down, click the btn:[X] button, also known as the btn:[Unlink datablock] button, located next to the loaded item. An item that is unlinked will show a `0` before it when viewed by selecting the btn:[Browse] button and will not be saved if you exit Blender.
.  Save your file.
.  From the `Info` header select `menu:File[Open Recent > Your Saved File]`, to close and re-open your file.

The exception to this rule is the `Linked Action` buffer, for animations, located in the `Dope Sheet Editor`.


== The Linked Action Buffer


. In the `Dope Sheet Editor`, change the context to `Action Editor`.
. Click the `Action to be linked` button and select the action you want cleared.
. Deselect the btn:[F] button to prevent it from saving.
. Change the editor type from `Dope Sheet` to `NLA Editor`. You will see the action listed.
. Click the icon:angle-double-down[]  button next to the action to push it into the stack.
. Click the small start next to the track name.
. With the mouse inside the `NLA Track List`,  press kbd:[X] to delete both the track and strip.
. Save your file.
. From the `Info` header, select `menu:File[Open Recent > Your Saved File]`.
. Save your file again.
. From the `Info` header, select `menu:File[Open Recent > Your Saved File]` again.
. Change back to the `Dope Sheet Editor`.
. Click the btn:[Browse Action to be linked] button and you will see only the baked action remains and the buffer is now clear of unwanted actions. Select your action.
. Save your file.
