= Wiki Contributions
:author: mitm
:revnumber: 1.0
:revdate: 2020/07/25

.Prerequisites
.  Have a link:https://github.com/[GitHub account].
.  Optional: Are a Wiki project member.

If you are not a member, you can fork the repository into your GitHub account and issue pull requests via github.

To fork the Wiki repository into your GitHub Account:

*  In the menu at the top of the docs.jmonkeyengine.org page, select the *Fork* button.

The syntax is asciidoctor:

*  link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[Asciidoc Syntax Quick Reference]
*  link:http://asciidoctor.org/docs/user-manual/[Asciidoctor User Manual]

An easy to use primer for GitHub commands can be found here:

*  link:http://rogerdudler.github.io/git-guide/[git - the simple guide]


== Contribute

The wiki is an Antora documentation site. There are a few simple rules to follow when contributing.

. It's not required but it's a good idea to give a heads up you made a P/R on the link:https://hub.jmonkeyengine.org/[jMonkeyEngine Forum] under the `Documentation` topic.
. When adding documents, make sure to always complete the link:https://docs.antora.org/antora/2.2/asciidoc/page-header/[header] of your document first.
. The docs are modular so you can create your own Antora site playbook and module and it can be included in the wiki and maintained by you. +
See: link:https://docs.antora.org/antora/2.3/[Antora Docs]. +
You can create modules and submit them here also.

It is recommended that you read at least these paragraphs to inform yourself on how to build pages and submit them for review to the wiki.

* <<atom_editor.adoc#updating-local-wiki-copies,Updating Local Wiki Copies>>
* <<atom_editor.adoc#pushing-changes,Pushing Changes>>
* <<atom_editor.adoc#creating-pages,Creating Pages>>
