= atomex
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../
:imagesdir: ../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== Atom Ex framework Introduction

*Hi Monkeys,*
*Atom Ex* framework helps you biggest steps to make your applications scale to web and distributed computing!


[TIP]
====

It's one of my long-term research, result of more than 6 years of research and 2 years of studying and coding
====



=== Idea & Buzz

*Bigger, more powerful with ease*
[quote]
____
From Data Central and Web's battle field, end up in game developing, I've dreamt about games and applications that scale its self in a snap. At first, something like a render-farm to accelerate 3D rendering pipeline or baking lightmap, massive level entities computing to save 3D artist lives, then may be something like 3D collaborative editing enviroment…
____

Initial Ideas:

*  Get to the cloud with ease, Spring-like but not just Spring
*  Framework for games and apps(3D) 
*  Nextgen techs

But technically, is something like this possible at all????

*Yes*, with helps of creative design of tools and frameworks, workflows and lastest technologies!!!

link:http://en.wikipedia.org/wiki/Model-driven_architecture[http://en.wikipedia.org/wiki/Model-driven_architecture]

link:http://en.wikipedia.org/wiki/Data-driven_architecture[http://en.wikipedia.org/wiki/Data-driven_architecture]

.  The first thing that most important to make this idea possible: *Everything are data*, including source code. 
.  How can it be? Yes, it can if source code are very *generative* , means it can be generated in this way or others. In fact, *generative* is also a key. 
.  Every aspect of this software development framework involving different kinds of auto-generating. Once again, *automatic* instead of manual is a key
.  Keep in mind *this is not magic but the lastest technologies* , means it's new, and some people also can not believe it real :p That's easy to understand. 

In fact, current implementation of AtomEx only cover a very small part of the automatic distributed game development but its potential is large. 
[quote]
____
As examples for distributed computing, I made a 3d rendering farm and a lightmap baker for demostration that show well the power of its theory and also helpful but not show much the automatic aspect. [quote]
____
In constrast, the example 1000MMORPG show only 1000 LOC (lines of code) of Groovy without the AtomEx's code base can make an full-scale MMORPG with Networking, Multi-nodes Database, servers, monitors, clients, SDKs , much more… which show the power of automatic code generation and model centric architecture. 
____

____


[TIP]
====
Go try JMERenderFarmLite link:http://github.com/sgmedia/jme-renderfarm-lite[http://github.com/sgmedia/jme-renderfarm-lite] and 1000MMORPG link:http://github.com/sgmedia/jme-1000loc-mmorpg[http://github.com/sgmedia/jme-1000loc-mmorpg] on github
====


The most attractive and impressive part is this is not a “config hell framework, somehow Spring-like mechaism, but Convention over configuration…

[to be continued]


=== Features


=== Architecture and components

Here are its architecture and components.
Atom Ex Core highlights:

*  Beans: Java at its finesse
*  Generative | Automative as its insistent characteristic
*  Dependency | Component injection: For modular enterprise software
*  Utilize the best open-source projects on earths
*  Meta widget: for a flexible presentation solution
*  Polymorphing via interfacing software architecture.
*  Event base, messaging non block 
*  Paralel ,utilize even GPU

Atom DB : Generate all DAO, configs for persitent. One code, run anywhere.

*  Bridge to ORMs : Cayneene , Hibernate
*  Bridge to NoSQL : Casabranda , Neo4j
*  Leverage all with “useful EJB3,Spring ideas and model driven architecture

Atom WebScale : play with only the best in Web world, generate game's website front|admin in few clicks

*  Bridge to Wicket
*  Bridge to Grails
*  Bridge to Play
*  Bridge to SpringMVC
*  Experiment with HTML5 and JavaScript almighty: Node.js , lot more… <<WebScale,WebScale>>

Atom Cloud : Modulize the game | application project and deploy structure

*  Bridge to Osgi
*  Ultimate Maven Gradle automatic deployment
*  Toward Collabrative enviroment

Atom Storm : Distributed computing at its finesse

*  Storm: as its best corporator
*  Hadoop and folks as the runner-up
*  Come with ready to use tools help 3D rendering and game creating pipeline

Atom Universal : Bring it all to common open infrastructure

*  Full distributed packages of the Atom framework online
*  Dynamic flexiable linkage that can suite almost teamwork game developing projects
*  Simple but powerful Pipeline | Workflow designer
*  A lot of examples , architype , free stuffs
*  Code link to OpenShift, Heroku, GoogleAppEngine, AppFrog,… via Git, SVN , Mecury
*  Utilites to use standard deploy solutions …

Atom Star Dust:

*  Smallscale version of those mentioned components, toward mobile devices and web-base, HTML5 games for ex.
*  Every where, small tiny, fastest, embed inside others, stick together well. 
*  This is specific component of Atom framework really show up as “Atom


=== Vision

Without trying to bloat, this is a most attractive point of the whole framework - Atom. 

You have open computing power, open infrastructure, open storage and everything under your hand and work as you wish!

Toward “cloud for game development and gaming, even better than that! 

Metaphorically, it's the sweestest result you can milk from the open source cows :p (Sorry if the idiom offense anyone) 

Yeah, money somehow..? But Open spirit in its heart! 


=== Other open-source dependencies


[WARNING]
====
Hundred of opensource projects…Nail it
====


<<jme3/atomixtuts#, Atomix Series of game making>>

GOTO <<jme3/advanced/atom_framework#,This Part of Atom framework >>
