= facial
:author:
:revnumber:
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../
:imagesdir: ../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== Facial Techs Introduction

Eh… What 's so fancy about those AAA games, like MassEffect, Drake and those from UDKs…?

It's all about the face!

....
  Yeah, indeed. Facial animation play an important role in game industry today. I won't tell you much about how much money are spent to get that character's face talk and lively... From an artist point of view, facial and emotional behavior of human character is the point to make a game's state of art!
....

Let see how can we do it in JME3, shall we?


=== Ideas

*  Customize the face with animations, emotions: ( eyes, nose, mouth ) with (smile, angry …)
*  User friendly.
**  For newbies
**  but also for professinal. especially with those who use FaceFx and UDK

*  Rooms for extends and usecases ( changing art-style, more specialize for simulations…)


[IMPORTANT]
====

Go to <<Researches & Papers,alternatives and researches>> if you want to go further than Atom!
====



== AtomFacial framework

image:jme3/advanced/atom_framework/youtube_fcf6grenolg[youtube_fcf6grenolg,width="",height=""]


=== Architecture


=== Components


=== Features


== Manuals


== Researches & Papers


== Alternatives


=== Opensource


=== Commercial
