= mmorpgtools
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../
:imagesdir: ../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== MMORPG Tools Introduction

This is the introduction of Atoms framework's MMORPG Tools.


=== Ideas

A lot of MMORPG game are published but how many in java you can count?

Do you feel so strange about it, even if we have the most powerful programming languages, techniques and toolset?


==== Problems

Let's talk a little bit about the problems:

.  Too much technical problems
.  Too much framework to use, which one is right?
.  Too much data to make
.  Too much people in teams, company involve the process
.  Too much time, competitors, requirements, money, efforts, …[over 9000 probs more!]

More about the MMORPG dream for small team, even invidual <<jme3/atomixtuts/mmorpg#,mmorpg>>


==== Solution?

Only one word (or 2): Open-source!

So in short, what I telling you is at least it provide you a framework and a rich toolset to build up your dream game and also a production enviroment to make MMORPG!

.  Stand in the shoulders of best open-source projects and also open-source spirit in its heart. 
.  Also born form the most innovative ideas of game production and deployment.


=== Buzz

It's coming with:

.  Ease of use - even your grandma can do, less code, smart tools in every single step
.  Effiecient - increase your productivity at least 10x
.  Scale to massive! - distributed computing, multi node , graph base database, non block event messaging, social network … much more!
.  Trick of the trade! - Yeah, money making tricks…


=== Current Tool?

Read the full article in researches about the open-source and commercial tool for MMORPG we have currently (well, the most popular) <<jme3/atomixtuts/mmorpg/researches/toolset#,toolset>>


=== Features


=== Techniques


[WARNING]
====
Warning: hundreds of open-source project. Nail it…
====


[IMPORTANT]
====
Go to alternatives and researches if you want to go further than Atom!
====



== Architecture


== Documentation


== Use case & Example

<<jme3/atomixtuts/mmorpg#,mmorpg>>
