= Emoji and Icons
:author: mitm
:revnumber: 2.0

== How to use icons in the wiki

[IMPORTANT]
====
Icons are currently not supported by the Antora backend. They will be available in the near future so the Icon section will remain for now.
====


You can use any font awesome icon listed at link:https://fontawesome.com/v4.7.0/icons/[https://fontawesome.com/v4.7.0/icons/] in your wiki documents by use of the icon macro.

.Syntax for inserting icons
```
icon:thumbs-up[]
icon:database[role=green] // change color by use of the role syntax
icon:heart[2x] // icons can be sized
icon:shield[rotate=90, flip=vertical] // rotate and flip
```

[TIP]
====
When setting the icons name, you do not have to preface it with `fa-`, asciidoctor will accept the font name.
====

The icon macro has three attributes you can set, they are size, rotate, and flip.

* size +
** The first positional attribute found, scales the icon; values are: `1x` (default), `2x`, `3x`, `4x`, `5x`, `lg`, `fw`
** You can fix the width of the icon by use of the `fw` attribute. This helps when trying to align with other elements by giving the icon a fixed width.
* rotate
** Rotates the icon; values are: `90`, `180`, `270`
* flip
** Flips the icon; values are: `horizontal`, `vertical`

The first unnamed attribute is assumed to be the size. For instance, to make the icon twice the size as the default, simply add 2x inside the square brackets.

```
icon:heart[2x]
```
Results:

icon:heart[] 2x icon:heart[2x]

To rotate and flip the icon:
```
icon:shield[rotate=270, flip=vertical]
```
Results:

icon:shield[] rotated 90, and flipped vertical icon:shield[rotate=90, flip=vertical]

You can also link to icons.
```
icon:download[link="https://rubygems.org/downloads/asciidoctor-1.5.2.gem"]
```
Results:

icon:download[link="https://rubygems.org/downloads/asciidoctor-1.5.2.gem"]

Lastly, you can color your icons using the role syntax.
```
icon:database[role=red]
```
Results:

database icon:database[] colored red icon:database[role=red]

== How to use emoji in the wiki


You add emoji by using the following syntax anywhere in your document.

```
emoji:heart[2x] // the "[2x]" is a size modifier
emoji:rage[]
```

[NOTE]
====
You can change the icon size with the size modifier `[2x]`.

`+emoji:heart[]+` emoji:heart[] `+emoji:heart[2x]+` emoji:heart[2x]
====

== Emoji and Name Cheet Sheet

=== People

[cols="2"]
|===

a| emoji:white_frowning_face[2x] [small]#`white_frowning_face`# +
emoji:relaxed[2x] [small]#`relaxed`# +
emoji:zipper_mouth_face[2x] [small]#`zipper_mouth_face`# +
emoji:money_mouth_face[2x] [small]#`money_mouth_face`# +
emoji:face_with_thermometer[2x] [small]#`face_with_thermometer`# +
emoji:nerd_face[2x] [small]#`nerd_face`# +
emoji:thinking_face[2x] [small]#`thinking_face`# +
emoji:face_with_head_bandage[2x] [small]#`face_with_head_bandage`# +
emoji:robot_face[2x] [small]#`robot_face`# +
emoji:hugging_face[2x] [small]#`hugging_face`# +
emoji:grinning[2x] [small]#`grinning`# +
emoji:grin[2x] [small]#`grin`# +
emoji:joy[2x] [small]#`joy`# +
emoji:smiley[2x] [small]#`smiley`# +
emoji:smile[2x] [small]#`smile`# +
emoji:sweat_smile[2x] [small]#`sweat_smile`# +
emoji:laughing[2x] [small]#`laughing`# +
emoji:innocent[2x] [small]#`innocent`# +
emoji:smiling_imp[2x] [small]#`smiling_imp`# +
emoji:wink[2x] [small]#`wink`# +
emoji:blush[2x] [small]#`blush`# +
emoji:yum[2x] [small]#`yum`# +
emoji:relieved[2x] [small]#`relieved`# +
emoji:heart_eyes[2x] [small]#`heart_eyes`# +
emoji:sunglasses[2x] [small]#`sunglasses`# +
emoji:smirk[2x] [small]#`smirk`# +
emoji:neutral_face[2x] [small]#`neutral_face`# +
emoji:expressionless[2x] [small]#`expressionless`# +
emoji:unamused[2x] [small]#`unamused`# +
emoji:sweat[2x] [small]#`sweat`# +
emoji:pensive[2x] [small]#`pensive`# +
emoji:confused[2x] [small]#`confused`# +
emoji:confounded[2x] [small]#`confounded`# +
emoji:kissing[2x] [small]#`kissing`# +
emoji:kissing_heart[2x] [small]#`kissing_heart`# +
emoji:kissing_smiling_eyes[2x] [small]#`kissing_smiling_eyes`# +
emoji:kissing_closed_eyes[2x] [small]#`kissing_closed_eyes`# +
emoji:stuck_out_tongue[2x] [small]#`stuck_out_tongue`# +
emoji:stuck_out_tongue_winking_eye[2x] [small]#`stuck_out_tongue_winking_eye`# +
emoji:stuck_out_tongue_closed_eyes[2x] [small]#`stuck_out_tongue_closed_eyes`# +
emoji:disappointed[2x] [small]#`disappointed`# +
emoji:worried[2x] [small]#`worried`# +
emoji:angry[2x] [small]#`angry`# +
emoji:rage[2x] [small]#`rage`# +
emoji:cry[2x] [small]#`cry`# +
emoji:persevere[2x] [small]#`persevere`# +
emoji:triumph[2x] [small]#`triumph`# +
emoji:disappointed_relieved[2x] [small]#`disappointed_relieved`# +
emoji:frowning[2x] [small]#`frowning`# +
emoji:anguished[2x] [small]#`anguished`# +
emoji:fearful[2x] [small]#`fearful`# +
emoji:weary[2x] [small]#`weary`# +
emoji:sleepy[2x] [small]#`sleepy`# +
emoji:tired_face[2x] [small]#`tired_face`# +
emoji:grimacing[2x] [small]#`grimacing`# +
emoji:sob[2x] [small]#`sob`# +
emoji:open_mouth[2x] [small]#`open_mouth`# +
emoji:hushed[2x] [small]#`hushed`# +
emoji:cold_sweat[2x] [small]#`cold_sweat`# +
emoji:scream[2x] [small]#`scream`# +
emoji:astonished[2x] [small]#`astonished`# +
emoji:flushed[2x] [small]#`flushed`# +
emoji:sleeping[2x] [small]#`sleeping`# +
emoji:dizzy_face[2x] [small]#`dizzy_face`# +
emoji:no_mouth[2x] [small]#`no_mouth`# +
emoji:mask[2x] [small]#`mask`# +
emoji:smile_cat[2x] [small]#`smile_cat`# +
emoji:joy_cat[2x] [small]#`joy_cat`# +
emoji:smiley_cat[2x] [small]#`smiley_cat`# +
emoji:heart_eyes_cat[2x] [small]#`heart_eyes_cat`# +
emoji:smirk_cat[2x] [small]#`smirk_cat`# +
emoji:kissing_cat[2x] [small]#`kissing_cat`# +
emoji:pouting_cat[2x] [small]#`pouting_cat`# +
emoji:crying_cat_face[2x] [small]#`crying_cat_face`# +
emoji:scream_cat[2x] [small]#`scream_cat`# +
emoji:slightly_frowning_face[2x] [small]#`slightly_frowning_face`# +
emoji:slightly_smiling_face[2x] [small]#`slightly_smiling_face`# +
emoji:upside_down_face[2x] [small]#`upside_down_face`# +
emoji:face_with_rolling_eyes[2x] [small]#`face_with_rolling_eyes`# +
emoji:see_no_evil[2x] [small]#`see_no_evil`# +
emoji:hear_no_evil[2x] [small]#`hear_no_evil`# +
emoji:speak_no_evil[2x] [small]#`speak_no_evil`# +
emoji:no_good-skin-tone-2[2x] [small]#`no_good-skin-tone-2`# +
emoji:no_good-skin-tone-3[2x] [small]#`no_good-skin-tone-3`# +
emoji:no_good-skin-tone-4[2x] [small]#`no_good-skin-tone-4`# +
emoji:no_good-skin-tone-5[2x] [small]#`no_good-skin-tone-5`# +
emoji:no_good-skin-tone-6[2x] [small]#`no_good-skin-tone-6`# +
emoji:no_good[2x] [small]#`no_good`# +
emoji:ok_woman-skin-tone-2[2x] [small]#`ok_woman-skin-tone-2`# +
emoji:ok_woman-skin-tone-3[2x] [small]#`ok_woman-skin-tone-3`# +
emoji:ok_woman-skin-tone-4[2x] [small]#`ok_woman-skin-tone-4`# +
emoji:ok_woman-skin-tone-5[2x] [small]#`ok_woman-skin-tone-5`# +
emoji:ok_woman-skin-tone-6[2x] [small]#`ok_woman-skin-tone-6`# +
emoji:ok_woman[2x] [small]#`ok_woman`# +
emoji:bow-skin-tone-2[2x] [small]#`bow-skin-tone-2`# +
emoji:bow-skin-tone-3[2x] [small]#`bow-skin-tone-3`# +
emoji:bow-skin-tone-4[2x] [small]#`bow-skin-tone-4`# +
emoji:bow-skin-tone-5[2x] [small]#`bow-skin-tone-5`# +
emoji:bow-skin-tone-6[2x] [small]#`bow-skin-tone-6`# +
emoji:bow[2x] [small]#`bow`# +
emoji:raising_hand-skin-tone-2[2x] [small]#`raising_hand-skin-tone-2`# +
emoji:raising_hand-skin-tone-3[2x] [small]#`raising_hand-skin-tone-3`# +
emoji:raising_hand-skin-tone-4[2x] [small]#`raising_hand-skin-tone-4`# +
emoji:raising_hand-skin-tone-5[2x] [small]#`raising_hand-skin-tone-5`# +
emoji:raising_hand-skin-tone-6[2x] [small]#`raising_hand-skin-tone-6`# +
emoji:raising_hand[2x] [small]#`raising_hand`# +
emoji:person_frowning-skin-tone-2[2x] [small]#`person_frowning-skin-tone-2`# +
emoji:person_frowning-skin-tone-3[2x] [small]#`person_frowning-skin-tone-3`# +
emoji:person_frowning-skin-tone-4[2x] [small]#`person_frowning-skin-tone-4`# +
emoji:person_frowning-skin-tone-5[2x] [small]#`person_frowning-skin-tone-5`# +
emoji:person_frowning-skin-tone-6[2x] [small]#`person_frowning-skin-tone-6`# +
emoji:person_frowning[2x] [small]#`person_frowning`# +
emoji:person_with_pouting_face-skin-tone-2[2x] [small]#`person_with_pouting_face-skin-tone-2`# +
emoji:person_with_pouting_face-skin-tone-3[2x] [small]#`person_with_pouting_face-skin-tone-3`# +
emoji:person_with_pouting_face-skin-tone-4[2x] [small]#`person_with_pouting_face-skin-tone-4`# +
emoji:person_with_pouting_face-skin-tone-5[2x] [small]#`person_with_pouting_face-skin-tone-5`# +
emoji:person_with_pouting_face-skin-tone-6[2x] [small]#`person_with_pouting_face-skin-tone-6`# +
emoji:person_with_pouting_face[2x] [small]#`person_with_pouting_face`# +
emoji:sleuth_or_spy-skin-tone-2[2x] [small]#`sleuth_or_spy-skin-tone-2`# +
emoji:sleuth_or_spy-skin-tone-3[2x] [small]#`sleuth_or_spy-skin-tone-3`# +
emoji:sleuth_or_spy-skin-tone-4[2x] [small]#`sleuth_or_spy-skin-tone-4`# +
emoji:sleuth_or_spy-skin-tone-5[2x] [small]#`sleuth_or_spy-skin-tone-5`# +
emoji:sleuth_or_spy-skin-tone-6[2x] [small]#`sleuth_or_spy-skin-tone-6`# +
emoji:sleuth_or_spy[2x] [small]#`sleuth_or_spy`# +
emoji:muscle-skin-tone-2[2x] [small]#`muscle-skin-tone-2`# +
emoji:muscle-skin-tone-3[2x] [small]#`muscle-skin-tone-3`# +
emoji:muscle-skin-tone-4[2x] [small]#`muscle-skin-tone-4`# +
emoji:muscle-skin-tone-5[2x] [small]#`muscle-skin-tone-5`# +
emoji:muscle-skin-tone-6[2x] [small]#`muscle-skin-tone-6`# +
emoji:muscle[2x] [small]#`muscle`# +
emoji:boy-skin-tone-2[2x] [small]#`boy-skin-tone-2`# +
emoji:boy-skin-tone-3[2x] [small]#`boy-skin-tone-3`# +
emoji:boy-skin-tone-4[2x] [small]#`boy-skin-tone-4`# +
emoji:boy-skin-tone-5[2x] [small]#`boy-skin-tone-5`# +
emoji:boy-skin-tone-6[2x] [small]#`boy-skin-tone-6`# +
emoji:boy[2x] [small]#`boy`# +
emoji:girl-skin-tone-2[2x] [small]#`girl-skin-tone-2`# +
emoji:girl-skin-tone-3[2x] [small]#`girl-skin-tone-3`# +
emoji:girl-skin-tone-4[2x] [small]#`girl-skin-tone-4`# +
emoji:girl-skin-tone-5[2x] [small]#`girl-skin-tone-5`# +
emoji:girl-skin-tone-6[2x] [small]#`girl-skin-tone-6`# +
emoji:girl[2x] [small]#`girl`# +
emoji:man-skin-tone-2[2x] [small]#`man-skin-tone-2`# +
emoji:man-skin-tone-3[2x] [small]#`man-skin-tone-3`# +
emoji:man-skin-tone-4[2x] [small]#`man-skin-tone-4`# +
emoji:man-skin-tone-5[2x] [small]#`man-skin-tone-5`# +
emoji:man-skin-tone-6[2x] [small]#`man-skin-tone-6`# +
emoji:man[2x] [small]#`man`# +
emoji:woman-skin-tone-2[2x] [small]#`woman-skin-tone-2`# +
emoji:woman-skin-tone-3[2x] [small]#`woman-skin-tone-3`# +
emoji:woman-skin-tone-4[2x] [small]#`woman-skin-tone-4`# +
emoji:woman-skin-tone-5[2x] [small]#`woman-skin-tone-5`# +
emoji:woman-skin-tone-6[2x] [small]#`woman-skin-tone-6`# +
emoji:woman[2x] [small]#`woman`# +
emoji:cop-skin-tone-2[2x] [small]#`cop-skin-tone-2`# +
emoji:cop-skin-tone-3[2x] [small]#`cop-skin-tone-3`# +
emoji:cop-skin-tone-4[2x] [small]#`cop-skin-tone-4`# +
emoji:cop-skin-tone-5[2x] [small]#`cop-skin-tone-5`# +
emoji:cop-skin-tone-6[2x] [small]#`cop-skin-tone-6`# +
emoji:cop[2x] [small]#`cop`# +
emoji:bride_with_veil-skin-tone-2[2x] [small]#`bride_with_veil-skin-tone-2`# +
emoji:bride_with_veil-skin-tone-3[2x] [small]#`bride_with_veil-skin-tone-3`# +
emoji:bride_with_veil-skin-tone-4[2x] [small]#`bride_with_veil-skin-tone-4`# +
emoji:bride_with_veil-skin-tone-5[2x] [small]#`bride_with_veil-skin-tone-5`# +
emoji:bride_with_veil-skin-tone-6[2x] [small]#`bride_with_veil-skin-tone-6`# +
emoji:bride_with_veil[2x] [small]#`bride_with_veil`# +
emoji:person_with_blond_hair-skin-tone-2[2x] [small]#`person_with_blond_hair-skin-tone-2`# +
emoji:person_with_blond_hair-skin-tone-3[2x] [small]#`person_with_blond_hair-skin-tone-3`# +
emoji:person_with_blond_hair-skin-tone-4[2x] [small]#`person_with_blond_hair-skin-tone-4`# +
emoji:person_with_blond_hair-skin-tone-5[2x] [small]#`person_with_blond_hair-skin-tone-5`# +
emoji:person_with_blond_hair-skin-tone-6[2x] [small]#`person_with_blond_hair-skin-tone-6`# +
emoji:person_with_blond_hair[2x] [small]#`person_with_blond_hair`# +
emoji:man_with_gua_pi_mao-skin-tone-2[2x] [small]#`man_with_gua_pi_mao-skin-tone-2`# +
emoji:man_with_gua_pi_mao-skin-tone-3[2x] [small]#`man_with_gua_pi_mao-skin-tone-3`# +
emoji:man_with_gua_pi_mao-skin-tone-4[2x] [small]#`man_with_gua_pi_mao-skin-tone-4`# +
emoji:man_with_gua_pi_mao-skin-tone-5[2x] [small]#`man_with_gua_pi_mao-skin-tone-5`# +
emoji:man_with_gua_pi_mao-skin-tone-6[2x] [small]#`man_with_gua_pi_mao-skin-tone-6`# +
emoji:man_with_gua_pi_mao[2x] [small]#`man_with_gua_pi_mao`# +
emoji:man_with_turban-skin-tone-2[2x] [small]#`man_with_turban-skin-tone-2`# +
emoji:man_with_turban-skin-tone-3[2x] [small]#`man_with_turban-skin-tone-3`# +
emoji:man_with_turban-skin-tone-4[2x] [small]#`man_with_turban-skin-tone-4`# +
emoji:man_with_turban-skin-tone-5[2x] [small]#`man_with_turban-skin-tone-5`# +
emoji:man_with_turban-skin-tone-6[2x] [small]#`man_with_turban-skin-tone-6`# +
emoji:man_with_turban[2x] [small]#`man_with_turban`# +
emoji:older_man-skin-tone-2[2x] [small]#`older_man-skin-tone-2`# +
emoji:older_man-skin-tone-3[2x] [small]#`older_man-skin-tone-3`# +
emoji:older_man-skin-tone-4[2x] [small]#`older_man-skin-tone-4`# +
emoji:older_man-skin-tone-5[2x] [small]#`older_man-skin-tone-5`# +
emoji:older_man-skin-tone-6[2x] [small]#`older_man-skin-tone-6`# +
emoji:older_man[2x] [small]#`older_man`# +
emoji:older_woman-skin-tone-2[2x] [small]#`older_woman-skin-tone-2`# +
emoji:older_woman-skin-tone-3[2x] [small]#`older_woman-skin-tone-3`# +
emoji:older_woman-skin-tone-4[2x] [small]#`older_woman-skin-tone-4`# +
emoji:older_woman-skin-tone-5[2x] [small]#`older_woman-skin-tone-5`# +
emoji:older_woman-skin-tone-6[2x] [small]#`older_woman-skin-tone-6`# +
emoji:older_woman[2x] [small]#`older_woman`# +
emoji:baby-skin-tone-2[2x] [small]#`baby-skin-tone-2`# +
emoji:baby-skin-tone-3[2x] [small]#`baby-skin-tone-3`# +
emoji:baby-skin-tone-4[2x] [small]#`baby-skin-tone-4`# +
emoji:baby-skin-tone-5[2x] [small]#`baby-skin-tone-5`# +
emoji:baby-skin-tone-6[2x] [small]#`baby-skin-tone-6`# +
emoji:baby[2x] [small]#`baby`# +
emoji:construction_worker-skin-tone-2[2x] [small]#`construction_worker-skin-tone-2`# +
emoji:construction_worker-skin-tone-3[2x] [small]#`construction_worker-skin-tone-3`# +
emoji:construction_worker-skin-tone-4[2x] [small]#`construction_worker-skin-tone-4`# +
emoji:construction_worker-skin-tone-5[2x] [small]#`construction_worker-skin-tone-5`# +
emoji:construction_worker-skin-tone-6[2x] [small]#`construction_worker-skin-tone-6`# +
emoji:construction_worker[2x] [small]#`construction_worker`# +
emoji:princess-skin-tone-2[2x] [small]#`princess-skin-tone-2`# +
emoji:princess-skin-tone-3[2x] [small]#`princess-skin-tone-3`# +
emoji:princess-skin-tone-4[2x] [small]#`princess-skin-tone-4`# +
emoji:princess-skin-tone-5[2x] [small]#`princess-skin-tone-5`# +
emoji:princess-skin-tone-6[2x] [small]#`princess-skin-tone-6`# +
emoji:princess[2x] [small]#`princess`# +
emoji:angel-skin-tone-2[2x] [small]#`angel-skin-tone-2`# +
emoji:angel-skin-tone-3[2x] [small]#`angel-skin-tone-3`# +
emoji:angel-skin-tone-4[2x] [small]#`angel-skin-tone-4`# +
emoji:angel-skin-tone-5[2x] [small]#`angel-skin-tone-5`# +
emoji:angel-skin-tone-6[2x] [small]#`angel-skin-tone-6`# +

a| emoji:angel[2x] [small]#`angel`# +
emoji:information_desk_person-skin-tone-2[2x] [small]#`information_desk_person-skin-tone-2`# +
emoji:information_desk_person-skin-tone-3[2x] [small]#`information_desk_person-skin-tone-3`# +
emoji:information_desk_person-skin-tone-4[2x] [small]#`information_desk_person-skin-tone-4`# +
emoji:information_desk_person-skin-tone-5[2x] [small]#`information_desk_person-skin-tone-5`# +
emoji:information_desk_person-skin-tone-6[2x] [small]#`information_desk_person-skin-tone-6`# +
emoji:information_desk_person[2x] [small]#`information_desk_person`# +
emoji:guardsman-skin-tone-2[2x] [small]#`guardsman-skin-tone-2`# +
emoji:guardsman-skin-tone-3[2x] [small]#`guardsman-skin-tone-3`# +
emoji:guardsman-skin-tone-4[2x] [small]#`guardsman-skin-tone-4`# +
emoji:guardsman-skin-tone-5[2x] [small]#`guardsman-skin-tone-5`# +
emoji:guardsman-skin-tone-6[2x] [small]#`guardsman-skin-tone-6`# +
emoji:guardsman[2x] [small]#`guardsman`# +
emoji:dancer-skin-tone-2[2x] [small]#`dancer-skin-tone-2`# +
emoji:dancer-skin-tone-3[2x] [small]#`dancer-skin-tone-3`# +
emoji:dancer-skin-tone-4[2x] [small]#`dancer-skin-tone-4`# +
emoji:dancer-skin-tone-5[2x] [small]#`dancer-skin-tone-5`# +
emoji:dancer-skin-tone-6[2x] [small]#`dancer-skin-tone-6`# +
emoji:dancer[2x] [small]#`dancer`# +
emoji:nail_care-skin-tone-2[2x] [small]#`nail_care-skin-tone-2`# +
emoji:nail_care-skin-tone-3[2x] [small]#`nail_care-skin-tone-3`# +
emoji:nail_care-skin-tone-4[2x] [small]#`nail_care-skin-tone-4`# +
emoji:nail_care-skin-tone-5[2x] [small]#`nail_care-skin-tone-5`# +
emoji:nail_care-skin-tone-6[2x] [small]#`nail_care-skin-tone-6`# +
emoji:nail_care[2x] [small]#`nail_care`# +
emoji:massage-skin-tone-2[2x] [small]#`massage-skin-tone-2`# +
emoji:massage-skin-tone-3[2x] [small]#`massage-skin-tone-3`# +
emoji:massage-skin-tone-4[2x] [small]#`massage-skin-tone-4`# +
emoji:massage-skin-tone-5[2x] [small]#`massage-skin-tone-5`# +
emoji:massage-skin-tone-6[2x] [small]#`massage-skin-tone-6`# +
emoji:massage[2x] [small]#`massage`# +
emoji:haircut-skin-tone-2[2x] [small]#`haircut-skin-tone-2`# +
emoji:haircut-skin-tone-3[2x] [small]#`haircut-skin-tone-3`# +
emoji:haircut-skin-tone-4[2x] [small]#`haircut-skin-tone-4`# +
emoji:haircut-skin-tone-5[2x] [small]#`haircut-skin-tone-5`# +
emoji:haircut-skin-tone-6[2x] [small]#`haircut-skin-tone-6`# +
emoji:haircut[2x] [small]#`haircut`# +
emoji:santa-skin-tone-2[2x] [small]#`santa-skin-tone-2`# +
emoji:santa-skin-tone-3[2x] [small]#`santa-skin-tone-3`# +
emoji:santa-skin-tone-4[2x] [small]#`santa-skin-tone-4`# +
emoji:santa-skin-tone-5[2x] [small]#`santa-skin-tone-5`# +
emoji:santa-skin-tone-6[2x] [small]#`santa-skin-tone-6`# +
emoji:santa[2x] [small]#`santa`# +
emoji:ear-skin-tone-2[2x] [small]#`ear-skin-tone-2`# +
emoji:ear-skin-tone-3[2x] [small]#`ear-skin-tone-3`# +
emoji:ear-skin-tone-4[2x] [small]#`ear-skin-tone-4`# +
emoji:ear-skin-tone-5[2x] [small]#`ear-skin-tone-5`# +
emoji:ear-skin-tone-6[2x] [small]#`ear-skin-tone-6`# +
emoji:ear[2x] [small]#`ear`# +
emoji:nose-skin-tone-2[2x] [small]#`nose-skin-tone-2`# +
emoji:nose-skin-tone-3[2x] [small]#`nose-skin-tone-3`# +
emoji:nose-skin-tone-4[2x] [small]#`nose-skin-tone-4`# +
emoji:nose-skin-tone-5[2x] [small]#`nose-skin-tone-5`# +
emoji:nose-skin-tone-6[2x] [small]#`nose-skin-tone-6`# +
emoji:nose[2x] [small]#`nose`# +
emoji:raised_hands-skin-tone-2[2x] [small]#`raised_hands-skin-tone-2`# +
emoji:raised_hands-skin-tone-3[2x] [small]#`raised_hands-skin-tone-3`# +
emoji:raised_hands-skin-tone-4[2x] [small]#`raised_hands-skin-tone-4`# +
emoji:raised_hands-skin-tone-5[2x] [small]#`raised_hands-skin-tone-5`# +
emoji:raised_hands-skin-tone-6[2x] [small]#`raised_hands-skin-tone-6`# +
emoji:raised_hands[2x] [small]#`raised_hands`# +
emoji:pray-skin-tone-2[2x] [small]#`pray-skin-tone-2`# +
emoji:pray-skin-tone-3[2x] [small]#`pray-skin-tone-3`# +
emoji:pray-skin-tone-4[2x] [small]#`pray-skin-tone-4`# +
emoji:pray-skin-tone-5[2x] [small]#`pray-skin-tone-5`# +
emoji:pray-skin-tone-6[2x] [small]#`pray-skin-tone-6`# +
emoji:pray[2x] [small]#`pray`# +
emoji:the_horns-skin-tone-2[2x] [small]#`the_horns-skin-tone-2`# +
emoji:the_horns-skin-tone-3[2x] [small]#`the_horns-skin-tone-3`# +
emoji:the_horns-skin-tone-4[2x] [small]#`the_horns-skin-tone-4`# +
emoji:the_horns-skin-tone-5[2x] [small]#`the_horns-skin-tone-5`# +
emoji:the_horns-skin-tone-6[2x] [small]#`the_horns-skin-tone-6`# +
emoji:the_horns[2x] [small]#`the_horns`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-2[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-2`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-3[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-3`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-4[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-4`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-5[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-5`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-6[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-6`# +
emoji:raised_hand_with_fingers_splayed[2x] [small]#`raised_hand_with_fingers_splayed`# +
emoji:middle_finger-skin-tone-2[2x] [small]#`middle_finger-skin-tone-2`# +
emoji:middle_finger-skin-tone-3[2x] [small]#`middle_finger-skin-tone-3`# +
emoji:middle_finger-skin-tone-4[2x] [small]#`middle_finger-skin-tone-4`# +
emoji:middle_finger-skin-tone-5[2x] [small]#`middle_finger-skin-tone-5`# +
emoji:middle_finger-skin-tone-6[2x] [small]#`middle_finger-skin-tone-6`# +
emoji:middle_finger[2x] [small]#`middle_finger`# +
emoji:spock-hand-skin-tone-2[2x] [small]#`spock-hand-skin-tone-2`# +
emoji:spock-hand-skin-tone-3[2x] [small]#`spock-hand-skin-tone-3`# +
emoji:spock-hand-skin-tone-4[2x] [small]#`spock-hand-skin-tone-4`# +
emoji:spock-hand-skin-tone-5[2x] [small]#`spock-hand-skin-tone-5`# +
emoji:spock-hand-skin-tone-6[2x] [small]#`spock-hand-skin-tone-6`# +
emoji:spock-hand[2x] [small]#`spock-hand`# +
emoji:point_up_2-skin-tone-2[2x] [small]#`point_up_2-skin-tone-2`# +
emoji:point_up_2-skin-tone-3[2x] [small]#`point_up_2-skin-tone-3`# +
emoji:point_up_2-skin-tone-4[2x] [small]#`point_up_2-skin-tone-4`# +
emoji:point_up_2-skin-tone-5[2x] [small]#`point_up_2-skin-tone-5`# +
emoji:point_up_2-skin-tone-6[2x] [small]#`point_up_2-skin-tone-6`# +
emoji:point_up_2[2x] [small]#`point_up_2`# +
emoji:point_down-skin-tone-2[2x] [small]#`point_down-skin-tone-2`# +
emoji:point_down-skin-tone-3[2x] [small]#`point_down-skin-tone-3`# +
emoji:point_down-skin-tone-4[2x] [small]#`point_down-skin-tone-4`# +
emoji:point_down-skin-tone-5[2x] [small]#`point_down-skin-tone-5`# +
emoji:point_down-skin-tone-6[2x] [small]#`point_down-skin-tone-6`# +
emoji:point_down[2x] [small]#`point_down`# +
emoji:point_left-skin-tone-2[2x] [small]#`point_left-skin-tone-2`# +
emoji:point_left-skin-tone-3[2x] [small]#`point_left-skin-tone-3`# +
emoji:point_left-skin-tone-4[2x] [small]#`point_left-skin-tone-4`# +
emoji:point_left-skin-tone-5[2x] [small]#`point_left-skin-tone-5`# +
emoji:point_left-skin-tone-6[2x] [small]#`point_left-skin-tone-6`# +
emoji:point_left[2x] [small]#`point_left`# +
emoji:point_right-skin-tone-2[2x] [small]#`point_right-skin-tone-2`# +
emoji:point_right-skin-tone-3[2x] [small]#`point_right-skin-tone-3`# +
emoji:point_right-skin-tone-4[2x] [small]#`point_right-skin-tone-4`# +
emoji:point_right-skin-tone-5[2x] [small]#`point_right-skin-tone-5`# +
emoji:point_right-skin-tone-6[2x] [small]#`point_right-skin-tone-6`# +
emoji:point_right[2x] [small]#`point_right`# +
emoji:facepunch-skin-tone-2[2x] [small]#`facepunch-skin-tone-2`# +
emoji:facepunch-skin-tone-3[2x] [small]#`facepunch-skin-tone-3`# +
emoji:facepunch-skin-tone-4[2x] [small]#`facepunch-skin-tone-4`# +
emoji:facepunch-skin-tone-5[2x] [small]#`facepunch-skin-tone-5`# +
emoji:facepunch-skin-tone-6[2x] [small]#`facepunch-skin-tone-6`# +
emoji:facepunch[2x] [small]#`facepunch`# +
emoji:wave-skin-tone-2[2x] [small]#`wave-skin-tone-2`# +
emoji:wave-skin-tone-3[2x] [small]#`wave-skin-tone-3`# +
emoji:wave-skin-tone-4[2x] [small]#`wave-skin-tone-4`# +
emoji:wave-skin-tone-5[2x] [small]#`wave-skin-tone-5`# +
emoji:wave-skin-tone-6[2x] [small]#`wave-skin-tone-6`# +
emoji:wave[2x] [small]#`wave`# +
emoji:ok_hand-skin-tone-2[2x] [small]#`ok_hand-skin-tone-2`# +
emoji:ok_hand-skin-tone-3[2x] [small]#`ok_hand-skin-tone-3`# +
emoji:ok_hand-skin-tone-4[2x] [small]#`ok_hand-skin-tone-4`# +
emoji:ok_hand-skin-tone-5[2x] [small]#`ok_hand-skin-tone-5`# +
emoji:ok_hand-skin-tone-6[2x] [small]#`ok_hand-skin-tone-6`# +
emoji:ok_hand[2x] [small]#`ok_hand`# +
emoji:+1-skin-tone-2[2x] [small]#`+1-skin-tone-2`# +
emoji:+1-skin-tone-3[2x] [small]#`+1-skin-tone-3`# +
emoji:+1-skin-tone-4[2x] [small]#`+1-skin-tone-4`# +
emoji:+1-skin-tone-5[2x] [small]#`+1-skin-tone-5`# +
emoji:+1-skin-tone-6[2x] [small]#`+1-skin-tone-6`# +
emoji:+1[2x] [small]#`+1`# +
emoji:-1-skin-tone-2[2x] [small]#`-1-skin-tone-2`# +
emoji:-1-skin-tone-3[2x] [small]#`-1-skin-tone-3`# +
emoji:-1-skin-tone-4[2x] [small]#`-1-skin-tone-4`# +
emoji:-1-skin-tone-5[2x] [small]#`-1-skin-tone-5`# +
emoji:-1-skin-tone-6[2x] [small]#`-1-skin-tone-6`# +
emoji:-1[2x] [small]#`-1`# +
emoji:clap-skin-tone-2[2x] [small]#`clap-skin-tone-2`# +
emoji:clap-skin-tone-3[2x] [small]#`clap-skin-tone-3`# +
emoji:clap-skin-tone-4[2x] [small]#`clap-skin-tone-4`# +
emoji:clap-skin-tone-5[2x] [small]#`clap-skin-tone-5`# +
emoji:clap-skin-tone-6[2x] [small]#`clap-skin-tone-6`# +
emoji:clap[2x] [small]#`clap`# +
emoji:open_hands-skin-tone-2[2x] [small]#`open_hands-skin-tone-2`# +
emoji:open_hands-skin-tone-3[2x] [small]#`open_hands-skin-tone-3`# +
emoji:open_hands-skin-tone-4[2x] [small]#`open_hands-skin-tone-4`# +
emoji:open_hands-skin-tone-5[2x] [small]#`open_hands-skin-tone-5`# +
emoji:open_hands-skin-tone-6[2x] [small]#`open_hands-skin-tone-6`# +
emoji:open_hands[2x] [small]#`open_hands`# +
emoji:point_up-skin-tone-2[2x] [small]#`point_up-skin-tone-2`# +
emoji:point_up-skin-tone-3[2x] [small]#`point_up-skin-tone-3`# +
emoji:point_up-skin-tone-4[2x] [small]#`point_up-skin-tone-4`# +
emoji:point_up-skin-tone-5[2x] [small]#`point_up-skin-tone-5`# +
emoji:point_up-skin-tone-6[2x] [small]#`point_up-skin-tone-6`# +
emoji:point_up[2x] [small]#`point_up`# +
emoji:fist-skin-tone-2[2x] [small]#`fist-skin-tone-2`# +
emoji:fist-skin-tone-3[2x] [small]#`fist-skin-tone-3`# +
emoji:fist-skin-tone-4[2x] [small]#`fist-skin-tone-4`# +
emoji:fist-skin-tone-5[2x] [small]#`fist-skin-tone-5`# +
emoji:fist-skin-tone-6[2x] [small]#`fist-skin-tone-6`# +
emoji:fist[2x] [small]#`fist`# +
emoji:hand-skin-tone-2[2x] [small]#`hand-skin-tone-2`# +
emoji:hand-skin-tone-3[2x] [small]#`hand-skin-tone-3`# +
emoji:hand-skin-tone-4[2x] [small]#`hand-skin-tone-4`# +
emoji:hand-skin-tone-5[2x] [small]#`hand-skin-tone-5`# +
emoji:hand-skin-tone-6[2x] [small]#`hand-skin-tone-6`# +
emoji:hand[2x] [small]#`hand`# +
emoji:victory_hand-skin-tone-2[2x] [small]#`victory_hand-skin-tone-2`# +
emoji:victory_hand-skin-tone-3[2x] [small]#`victory_hand-skin-tone-3`# +
emoji:victory_hand-skin-tone-4[2x] [small]#`victory_hand-skin-tone-4`# +
emoji:victory_hand-skin-tone-5[2x] [small]#`victory_hand-skin-tone-5`# +
emoji:victory_hand-skin-tone-6[2x] [small]#`victory_hand-skin-tone-6`# +
emoji:victory_hand[2x] [small]#`victory_hand`# +
emoji:writing_hand-skin-tone-2[2x] [small]#`writing_hand-skin-tone-2`# +
emoji:writing_hand-skin-tone-3[2x] [small]#`writing_hand-skin-tone-3`# +
emoji:writing_hand-skin-tone-4[2x] [small]#`writing_hand-skin-tone-4`# +
emoji:writing_hand-skin-tone-5[2x] [small]#`writing_hand-skin-tone-5`# +
emoji:writing_hand-skin-tone-6[2x] [small]#`writing_hand-skin-tone-6`# +
emoji:writing_hand[2x] [small]#`writing_hand`# +
emoji:bust_in_silhouette[2x] [small]#`bust_in_silhouette`# +
emoji:busts_in_silhouette[2x] [small]#`busts_in_silhouette`# +
emoji:dancers[2x] [small]#`dancers`# +
emoji:man_in_business_suit_levitating[2x] [small]#`man_in_business_suit_levitating`# +
emoji:man-woman-boy[2x] [small]#`man-woman-boy`# +
emoji:man-woman-boy-boy[2x] [small]#`man-woman-boy-boy`# +
emoji:man-woman-girl[2x] [small]#`man-woman-girl`# +
emoji:man-woman-girl-boy[2x] [small]#`man-woman-girl-boy`# +
emoji:man-woman-girl-girl[2x] [small]#`man-woman-girl-girl`# +
emoji:woman-heart-man[2x] [small]#`woman-heart-man`# +
emoji:woman-kiss-man[2x] [small]#`woman-kiss-man`# +
emoji:family[2x] [small]#`family`# +
emoji:couple[2x] [small]#`couple`# +
emoji:japanese_ogre[2x] [small]#`japanese_ogre`# +
emoji:japanese_goblin[2x] [small]#`japanese_goblin`# +
emoji:ghost[2x] [small]#`ghost`# +
emoji:alien[2x] [small]#`alien`# +
emoji:space_invader[2x] [small]#`space_invader`# +
emoji:imp[2x] [small]#`imp`# +
emoji:skull[2x] [small]#`skull`# +
emoji:eyes[2x] [small]#`eyes`# +
emoji:eye[2x] [small]#`eye`# +
emoji:lips[2x] [small]#`lips`# +
emoji:tongue[2x] [small]#`tongue`# +
emoji:skin-tone-2[2x] [small]#`skin-tone-2`# +
emoji:skin-tone-3[2x] [small]#`skin-tone-3`# +
emoji:skin-tone-4[2x] [small]#`skin-tone-4`# +
emoji:skin-tone-5[2x] [small]#`skin-tone-5`# +
emoji:skin-tone-6[2x] [small]#`skin-tone-6`# +

|===

=== Animals & Nature

[cols="2"]
|===

a| emoji:partly_sunny[2x] [small]#`partly_sunny`# +
emoji:thunder_cloud_and_rain[2x] [small]#`thunder_cloud_and_rain`# +
emoji:sunny[2x] [small]#`sunny`# +
emoji:cloud[2x] [small]#`cloud`# +
emoji:cyclone[2x] [small]#`cyclone`# +
emoji:foggy[2x] [small]#`foggy`# +
emoji:closed_umbrella[2x] [small]#`closed_umbrella`# +
emoji:night_with_stars[2x] [small]#`night_with_stars`# +
emoji:sunrise_over_mountains[2x] [small]#`sunrise_over_mountains`# +
emoji:sunrise[2x] [small]#`sunrise`# +
emoji:city_sunset[2x] [small]#`city_sunset`# +
emoji:city_sunrise[2x] [small]#`city_sunrise`# +
emoji:rainbow[2x] [small]#`rainbow`# +
emoji:bridge_at_night[2x] [small]#`bridge_at_night`# +
emoji:ocean[2x] [small]#`ocean`# +
emoji:volcano[2x] [small]#`volcano`# +
emoji:milky_way[2x] [small]#`milky_way`# +
emoji:earth_africa[2x] [small]#`earth_africa`# +
emoji:earth_americas[2x] [small]#`earth_americas`# +
emoji:earth_asia[2x] [small]#`earth_asia`# +
emoji:globe_with_meridians[2x] [small]#`globe_with_meridians`# +
emoji:new_moon[2x] [small]#`new_moon`# +
emoji:waxing_crescent_moon[2x] [small]#`waxing_crescent_moon`# +
emoji:first_quarter_moon[2x] [small]#`first_quarter_moon`# +
emoji:waxing_gibbous_moon[2x] [small]#`waxing_gibbous_moon`# +
emoji:full_moon[2x] [small]#`full_moon`# +
emoji:waning_gibbous_moon[2x] [small]#`waning_gibbous_moon`# +
emoji:last_quarter_moon[2x] [small]#`last_quarter_moon`# +
emoji:waning_crescent_moon[2x] [small]#`waning_crescent_moon`# +
emoji:crescent_moon[2x] [small]#`crescent_moon`# +
emoji:new_moon_with_face[2x] [small]#`new_moon_with_face`# +
emoji:first_quarter_moon_with_face[2x] [small]#`first_quarter_moon_with_face`# +
emoji:last_quarter_moon_with_face[2x] [small]#`last_quarter_moon_with_face`# +
emoji:full_moon_with_face[2x] [small]#`full_moon_with_face`# +
emoji:sun_with_face[2x] [small]#`sun_with_face`# +
emoji:star2[2x] [small]#`star2`# +
emoji:stars[2x] [small]#`stars`# +
emoji:thermometer[2x] [small]#`thermometer`# +
emoji:mostly_sunny[2x] [small]#`mostly_sunny`# +
emoji:barely_sunny[2x] [small]#`barely_sunny`# +
emoji:partly_sunny_rain[2x] [small]#`partly_sunny_rain`# +
emoji:rain_cloud[2x] [small]#`rain_cloud`# +
emoji:snow_cloud[2x] [small]#`snow_cloud`# +
emoji:lightning[2x] [small]#`lightning`# +
emoji:tornado[2x] [small]#`tornado`# +
emoji:fog[2x] [small]#`fog`# +
emoji:wind_blowing_face[2x] [small]#`wind_blowing_face`# +
emoji:seedling[2x] [small]#`seedling`# +
emoji:evergreen_tree[2x] [small]#`evergreen_tree`# +
emoji:deciduous_tree[2x] [small]#`deciduous_tree`# +
emoji:palm_tree[2x] [small]#`palm_tree`# +
emoji:cactus[2x] [small]#`cactus`# +
emoji:hot_pepper[2x] [small]#`hot_pepper`# +
emoji:tulip[2x] [small]#`tulip`# +
emoji:cherry_blossom[2x] [small]#`cherry_blossom`# +
emoji:rose[2x] [small]#`rose`# +
emoji:hibiscus[2x] [small]#`hibiscus`# +
emoji:sunflower[2x] [small]#`sunflower`# +
emoji:blossom[2x] [small]#`blossom`# +
emoji:corn[2x] [small]#`corn`# +
emoji:ear_of_rice[2x] [small]#`ear_of_rice`# +
emoji:herb[2x] [small]#`herb`# +
emoji:four_leaf_clover[2x] [small]#`four_leaf_clover`# +
emoji:maple_leaf[2x] [small]#`maple_leaf`# +
emoji:fallen_leaf[2x] [small]#`fallen_leaf`# +
emoji:leaves[2x] [small]#`leaves`# +
emoji:mushroom[2x] [small]#`mushroom`# +
emoji:tomato[2x] [small]#`tomato`# +
emoji:eggplant[2x] [small]#`eggplant`# +
emoji:grapes[2x] [small]#`grapes`# +
emoji:melon[2x] [small]#`melon`# +
emoji:watermelon[2x] [small]#`watermelon`# +
emoji:tangerine[2x] [small]#`tangerine`# +
emoji:lemon[2x] [small]#`lemon`# +
emoji:banana[2x] [small]#`banana`# +
emoji:pineapple[2x] [small]#`pineapple`# +
emoji:apple[2x] [small]#`apple`# +
emoji:green_apple[2x] [small]#`green_apple`# +
emoji:pear[2x] [small]#`pear`# +
emoji:peach[2x] [small]#`peach`# +
emoji:cherries[2x] [small]#`cherries`# +
emoji:strawberry[2x] [small]#`strawberry`# +

a| emoji:rat[2x] [small]#`rat`# +
emoji:mouse2[2x] [small]#`mouse2`# +
emoji:ox[2x] [small]#`ox`# +
emoji:water_buffalo[2x] [small]#`water_buffalo`# +
emoji:cow2[2x] [small]#`cow2`# +
emoji:tiger2[2x] [small]#`tiger2`# +
emoji:leopard[2x] [small]#`leopard`# +
emoji:rabbit2[2x] [small]#`rabbit2`# +
emoji:cat2[2x] [small]#`cat2`# +
emoji:dragon[2x] [small]#`dragon`# +
emoji:crocodile[2x] [small]#`crocodile`# +
emoji:whale2[2x] [small]#`whale2`# +
emoji:snail[2x] [small]#`snail`# +
emoji:snake[2x] [small]#`snake`# +
emoji:racehorse[2x] [small]#`racehorse`# +
emoji:ram[2x] [small]#`ram`# +
emoji:goat[2x] [small]#`goat`# +
emoji:sheep[2x] [small]#`sheep`# +
emoji:monkey[2x] [small]#`monkey`# +
emoji:rooster[2x] [small]#`rooster`# +
emoji:chicken[2x] [small]#`chicken`# +
emoji:dog2[2x] [small]#`dog2`# +
emoji:pig2[2x] [small]#`pig2`# +
emoji:boar[2x] [small]#`boar`# +
emoji:elephant[2x] [small]#`elephant`# +
emoji:octopus[2x] [small]#`octopus`# +
emoji:shell[2x] [small]#`shell`# +
emoji:bug[2x] [small]#`bug`# +
emoji:ant[2x] [small]#`ant`# +
emoji:bee[2x] [small]#`bee`# +
emoji:beetle[2x] [small]#`beetle`# +
emoji:fish[2x] [small]#`fish`# +
emoji:tropical_fish[2x] [small]#`tropical_fish`# +
emoji:blowfish[2x] [small]#`blowfish`# +
emoji:turtle[2x] [small]#`turtle`# +
emoji:hatching_chick[2x] [small]#`hatching_chick`# +
emoji:baby_chick[2x] [small]#`baby_chick`# +
emoji:hatched_chick[2x] [small]#`hatched_chick`# +
emoji:bird[2x] [small]#`bird`# +
emoji:penguin[2x] [small]#`penguin`# +
emoji:koala[2x] [small]#`koala`# +
emoji:poodle[2x] [small]#`poodle`# +
emoji:dromedary_camel[2x] [small]#`dromedary_camel`# +
emoji:camel[2x] [small]#`camel`# +
emoji:dolphin[2x] [small]#`dolphin`# +
emoji:mouse[2x] [small]#`mouse`# +
emoji:cow[2x] [small]#`cow`# +
emoji:tiger[2x] [small]#`tiger`# +
emoji:rabbit[2x] [small]#`rabbit`# +
emoji:cat[2x] [small]#`cat`# +
emoji:dragon_face[2x] [small]#`dragon_face`# +
emoji:whale[2x] [small]#`whale`# +
emoji:horse[2x] [small]#`horse`# +
emoji:monkey_face[2x] [small]#`monkey_face`# +
emoji:dog[2x] [small]#`dog`# +
emoji:pig[2x] [small]#`pig`# +
emoji:frog[2x] [small]#`frog`# +
emoji:hamster[2x] [small]#`hamster`# +
emoji:wolf[2x] [small]#`wolf`# +
emoji:bear[2x] [small]#`bear`# +
emoji:panda_face[2x] [small]#`panda_face`# +
emoji:pig_nose[2x] [small]#`pig_nose`# +
emoji:feet[2x] [small]#`feet`# +
emoji:chipmunk[2x] [small]#`chipmunk`# +
emoji:crab[2x] [small]#`crab`# +
emoji:lion_face[2x] [small]#`lion_face`# +
emoji:scorpion[2x] [small]#`scorpion`# +
emoji:turkey[2x] [small]#`turkey`# +
emoji:unicorn_face[2x] [small]#`unicorn_face`# +

|===


=== Food & Drink

[cols="2"]
|===

a| emoji:coffee[2x] [small]#`coffee`# +
emoji:cheese_wedge[2x] [small]#`cheese_wedge`# +
emoji:hotdog[2x] [small]#`hotdog`# +
emoji:taco[2x] [small]#`taco`# +
emoji:burrito[2x] [small]#`burrito`# +
emoji:chestnut[2x] [small]#`chestnut`# +
emoji:hamburger[2x] [small]#`hamburger`# +
emoji:pizza[2x] [small]#`pizza`# +
emoji:meat_on_bone[2x] [small]#`meat_on_bone`# +
emoji:poultry_leg[2x] [small]#`poultry_leg`# +
emoji:rice_cracker[2x] [small]#`rice_cracker`# +
emoji:rice_ball[2x] [small]#`rice_ball`# +
emoji:rice[2x] [small]#`rice`# +
emoji:curry[2x] [small]#`curry`# +
emoji:ramen[2x] [small]#`ramen`# +
emoji:spaghetti[2x] [small]#`spaghetti`# +
emoji:bread[2x] [small]#`bread`# +
emoji:fries[2x] [small]#`fries`# +
emoji:sweet_potato[2x] [small]#`sweet_potato`# +
emoji:dango[2x] [small]#`dango`# +
emoji:oden[2x] [small]#`oden`# +
emoji:sushi[2x] [small]#`sushi`# +
emoji:fried_shrimp[2x] [small]#`fried_shrimp`# +
emoji:fish_cake[2x] [small]#`fish_cake`# +

a| emoji:icecream[2x] [small]#`icecream`# +
emoji:shaved_ice[2x] [small]#`shaved_ice`# +
emoji:ice_cream[2x] [small]#`ice_cream`# +
emoji:doughnut[2x] [small]#`doughnut`# +
emoji:cookie[2x] [small]#`cookie`# +
emoji:chocolate_bar[2x] [small]#`chocolate_bar`# +
emoji:candy[2x] [small]#`candy`# +
emoji:lollipop[2x] [small]#`lollipop`# +
emoji:custard[2x] [small]#`custard`# +
emoji:honey_pot[2x] [small]#`honey_pot`# +
emoji:cake[2x] [small]#`cake`# +
emoji:bento[2x] [small]#`bento`# +
emoji:stew[2x] [small]#`stew`# +
emoji:egg[2x] [small]#`egg`# +
emoji:fork_and_knife[2x] [small]#`fork_and_knife`# +
emoji:tea[2x] [small]#`tea`# +
emoji:sake[2x] [small]#`sake`# +
emoji:wine_glass[2x] [small]#`wine_glass`# +
emoji:cocktail[2x] [small]#`cocktail`# +
emoji:tropical_drink[2x] [small]#`tropical_drink`# +
emoji:beer[2x] [small]#`beer`# +
emoji:beers[2x] [small]#`beers`# +
emoji:baby_bottle[2x] [small]#`baby_bottle`# +
emoji:knife_fork_plate[2x] [small]#`knife_fork_plate`# +
emoji:champagne[2x] [small]#`champagne`# +
emoji:popcorn[2x] [small]#`popcorn`# +

|===

=== Objects

[cols="2"]
|===

a| emoji:lipstick[2x] [small]#`lipstick`# +
emoji:pencil2[2x] [small]#`pencil2`# +
emoji:black_nib[2x] [small]#`black_nib`# +
emoji:tent[2x] [small]#`tent`# +
emoji:fuelpump[2x] [small]#`fuelpump`# +
emoji:scissors[2x] [small]#`scissors`# +
emoji:umbrella_on_ground[2x] [small]#`umbrella_on_ground`# +
emoji:fountain[2x] [small]#`fountain`# +
emoji:pick[2x] [small]#`pick`# +
emoji:helmet_with_white_cross[2x] [small]#`helmet_with_white_cross`# +
emoji:chains[2x] [small]#`chains`# +
emoji:coffin[2x] [small]#`coffin`# +
emoji:funeral_urn[2x] [small]#`funeral_urn`# +
emoji:soccer[2x] [small]#`soccer`# +
emoji:baseball[2x] [small]#`baseball`# +
emoji:shamrock[2x] [small]#`shamrock`# +
emoji:umbrella[2x] [small]#`umbrella`# +
emoji:snowman[2x] [small]#`snowman`# +
emoji:showman[2x] [small]#`showman`# +
emoji:comet[2x] [small]#`comet`# +
emoji:phone[2x] [small]#`phone`# +
emoji:ballot_box_with_check[2x] [small]#`ballot_box_with_check`# +
emoji:ballot_box_with_ballot[2x] [small]#`ballot_box_with_ballot`# +
emoji:umbrella_with_rain_drops[2x] [small]#`umbrella_with_rain_drops`# +
emoji:wastebasket[2x] [small]#`wastebasket`# +
emoji:spiral_note_pad[2x] [small]#`spiral_note_pad`# +
emoji:spiral_calendar_pad[2x] [small]#`spiral_calendar_pad`# +
emoji:compression[2x] [small]#`compression`# +
emoji:old_key[2x] [small]#`old_key`# +
emoji:rolled_up_newspaper[2x] [small]#`rolled_up_newspaper`# +
emoji:dagger_knife[2x] [small]#`dagger_knife`# +
emoji:dark_sunglasses[2x] [small]#`dark_sunglasses`# +
emoji:spider[2x] [small]#`spider`# +
emoji:spider_web[2x] [small]#`spider_web`# +
emoji:joystick[2x] [small]#`joystick`# +
emoji:linked_paperclips[2x] [small]#`linked_paperclips`# +
emoji:lower_left_ballpoint_pen[2x] [small]#`lower_left_ballpoint_pen`# +
emoji:lower_left_fountain_pen[2x] [small]#`lower_left_fountain_pen`# +
emoji:lower_left_paintbrush[2x] [small]#`lower_left_paintbrush`# +
emoji:lower_left_crayon[2x] [small]#`lower_left_crayon`# +
emoji:candle[2x] [small]#`candle`# +
emoji:mantelpiece_clock[2x] [small]#`mantelpiece_clock`# +
emoji:hole[2x] [small]#`hole`# +
emoji:ribbon[2x] [small]#`ribbon`# +
emoji:gift[2x] [small]#`gift`# +
emoji:birthday[2x] [small]#`birthday`# +
emoji:jack_o_lantern[2x] [small]#`jack_o_lantern`# +
emoji:christmas_tree[2x] [small]#`christmas_tree`# +
emoji:fireworks[2x] [small]#`fireworks`# +
emoji:sparkler[2x] [small]#`sparkler`# +
emoji:balloon[2x] [small]#`balloon`# +
emoji:tada[2x] [small]#`tada`# +
emoji:confetti_ball[2x] [small]#`confetti_ball`# +
emoji:tanabata_tree[2x] [small]#`tanabata_tree`# +
emoji:crossed_flags[2x] [small]#`crossed_flags`# +
emoji:bamboo[2x] [small]#`bamboo`# +
emoji:dolls[2x] [small]#`dolls`# +
emoji:flags[2x] [small]#`flags`# +
emoji:wind_chime[2x] [small]#`wind_chime`# +
emoji:rice_scene[2x] [small]#`rice_scene`# +
emoji:school_satchel[2x] [small]#`school_satchel`# +
emoji:mortar_board[2x] [small]#`mortar_board`# +
emoji:medal[2x] [small]#`medal`# +
emoji:reminder_ribbon[2x] [small]#`reminder_ribbon`# +
emoji:studio_microphone[2x] [small]#`studio_microphone`# +
emoji:level_slider[2x] [small]#`level_slider`# +
emoji:control_knobs[2x] [small]#`control_knobs`# +
emoji:film_frames[2x] [small]#`film_frames`# +
emoji:admission_tickets[2x] [small]#`admission_tickets`# +
emoji:carousel_horse[2x] [small]#`carousel_horse`# +
emoji:ferris_wheel[2x] [small]#`ferris_wheel`# +
emoji:roller_coaster[2x] [small]#`roller_coaster`# +
emoji:fishing_pole_and_fish[2x] [small]#`fishing_pole_and_fish`# +
emoji:microphone[2x] [small]#`microphone`# +
emoji:movie_camera[2x] [small]#`movie_camera`# +
emoji:cinema[2x] [small]#`cinema`# +
emoji:headphones[2x] [small]#`headphones`# +
emoji:art[2x] [small]#`art`# +

a| emoji:tophat[2x] [small]#`tophat`# +
emoji:circus_tent[2x] [small]#`circus_tent`# +
emoji:ticket[2x] [small]#`ticket`# +
emoji:clapper[2x] [small]#`clapper`# +
emoji:performing_arts[2x] [small]#`performing_arts`# +
emoji:video_game[2x] [small]#`video_game`# +
emoji:dart[2x] [small]#`dart`# +
emoji:slot_machine[2x] [small]#`slot_machine`# +
emoji:8ball[2x] [small]#`8ball`# +
emoji:game_die[2x] [small]#`game_die`# +
emoji:bowling[2x] [small]#`bowling`# +
emoji:flower_playing_cards[2x] [small]#`flower_playing_cards`# +
emoji:musical_note[2x] [small]#`musical_note`# +
emoji:notes[2x] [small]#`notes`# +
emoji:saxophone[2x] [small]#`saxophone`# +
emoji:guitar[2x] [small]#`guitar`# +
emoji:musical_keyboard[2x] [small]#`musical_keyboard`# +
emoji:trumpet[2x] [small]#`trumpet`# +
emoji:violin[2x] [small]#`violin`# +
emoji:musical_score[2x] [small]#`musical_score`# +
emoji:running_shirt_with_sash[2x] [small]#`running_shirt_with_sash`# +
emoji:waving_white_flag[2x] [small]#`waving_white_flag`# +
emoji:waving_black_flag[2x] [small]#`waving_black_flag`# +
emoji:rosette[2x] [small]#`rosette`# +
emoji:label[2x] [small]#`label`# +
emoji:badminton_racquet_and_shuttlecock[2x] [small]#`badminton_racquet_and_shuttlecock`# +
emoji:bow_and_arrow[2x] [small]#`bow_and_arrow`# +
emoji:amphora[2x] [small]#`amphora`# +
emoji:crown[2x] [small]#`crown`# +
emoji:womans_hat[2x] [small]#`womans_hat`# +
emoji:eyeglasses[2x] [small]#`eyeglasses`# +
emoji:necktie[2x] [small]#`necktie`# +
emoji:shirt[2x] [small]#`shirt`# +
emoji:jeans[2x] [small]#`jeans`# +
emoji:dress[2x] [small]#`dress`# +
emoji:kimono[2x] [small]#`kimono`# +
emoji:bikini[2x] [small]#`bikini`# +
emoji:womans_clothes[2x] [small]#`womans_clothes`# +
emoji:purse[2x] [small]#`purse`# +
emoji:handbag[2x] [small]#`handbag`# +
emoji:pouch[2x] [small]#`pouch`# +
emoji:mans_shoe[2x] [small]#`mans_shoe`# +
emoji:athletic_shoe[2x] [small]#`athletic_shoe`# +
emoji:high_heel[2x] [small]#`high_heel`# +
emoji:sandal[2x] [small]#`sandal`# +
emoji:boot[2x] [small]#`boot`# +
emoji:footprints[2x] [small]#`footprints`# +
emoji:barber[2x] [small]#`barber`# +
emoji:syringe[2x] [small]#`syringe`# +
emoji:pill[2x] [small]#`pill`# +
emoji:kiss[2x] [small]#`kiss`# +
emoji:love_letter[2x] [small]#`love_letter`# +
emoji:ring[2x] [small]#`ring`# +
emoji:gem[2x] [small]#`gem`# +
emoji:couplekiss[2x] [small]#`couplekiss`# +
emoji:bouquet[2x] [small]#`bouquet`# +
emoji:couple_with_heart[2x] [small]#`couple_with_heart`# +
emoji:wedding[2x] [small]#`wedding`# +
emoji:heartbeat[2x] [small]#`heartbeat`# +
emoji:broken_heart[2x] [small]#`broken_heart`# +
emoji:two_hearts[2x] [small]#`two_hearts`# +
emoji:sparkling_heart[2x] [small]#`sparkling_heart`# +
emoji:heartpulse[2x] [small]#`heartpulse`# +
emoji:cupid[2x] [small]#`cupid`# +
emoji:blue_heart[2x] [small]#`blue_heart`# +
emoji:green_heart[2x] [small]#`green_heart`# +
emoji:yellow_heart[2x] [small]#`yellow_heart`# +
emoji:purple_heart[2x] [small]#`purple_heart`# +
emoji:gift_heart[2x] [small]#`gift_heart`# +
emoji:revolving_hearts[2x] [small]#`revolving_hearts`# +
emoji:heart_decoration[2x] [small]#`heart_decoration`# +
emoji:diamond_shape_with_a_dot_inside[2x] [small]#`diamond_shape_with_a_dot_inside`# +
emoji:bulb[2x] [small]#`bulb`# +
emoji:anger[2x] [small]#`anger`# +
emoji:bomb[2x] [small]#`bomb`# +
emoji:zzz[2x] [small]#`zzz`# +
emoji:boom[2x] [small]#`boom`# +
emoji:sweat_drops[2x] [small]#`sweat_drops`# +
emoji:droplet[2x] [small]#`droplet`# +
emoji:dash[2x] [small]#`dash`# +
emoji:hankey[2x] [small]#`hankey`# +

|===

=== Activity

[cols="2"]
|===

a| emoji:bicyclist-skin-tone-2[2x] [small]#`bicyclist-skin-tone-2`# +
emoji:bicyclist-skin-tone-3[2x] [small]#`bicyclist-skin-tone-3`# +
emoji:bicyclist-skin-tone-4[2x] [small]#`bicyclist-skin-tone-4`# +
emoji:bicyclist-skin-tone-5[2x] [small]#`bicyclist-skin-tone-5`# +
emoji:bicyclist-skin-tone-6[2x] [small]#`bicyclist-skin-tone-6`# +
emoji:bicyclist[2x] [small]#`bicyclist`# +
emoji:mountain_bicyclist-skin-tone-2[2x] [small]#`mountain_bicyclist-skin-tone-2`# +
emoji:mountain_bicyclist-skin-tone-3[2x] [small]#`mountain_bicyclist-skin-tone-3`# +
emoji:mountain_bicyclist-skin-tone-4[2x] [small]#`mountain_bicyclist-skin-tone-4`# +
emoji:mountain_bicyclist-skin-tone-5[2x] [small]#`mountain_bicyclist-skin-tone-5`# +
emoji:mountain_bicyclist-skin-tone-6[2x] [small]#`mountain_bicyclist-skin-tone-6`# +
emoji:mountain_bicyclist[2x] [small]#`mountain_bicyclist`# +
emoji:walking-skin-tone-2[2x] [small]#`walking-skin-tone-2`# +
emoji:walking-skin-tone-3[2x] [small]#`walking-skin-tone-3`# +
emoji:walking-skin-tone-4[2x] [small]#`walking-skin-tone-4`# +
emoji:walking-skin-tone-5[2x] [small]#`walking-skin-tone-5`# +
emoji:walking-skin-tone-6[2x] [small]#`walking-skin-tone-6`# +
emoji:walking[2x] [small]#`walking`# +
emoji:skier[2x] [small]#`skier`# +
emoji:ice_skate[2x] [small]#`ice_skate`# +
emoji:person_with_ball-skin-tone-2[2x] [small]#`person_with_ball-skin-tone-2`# +
emoji:person_with_ball-skin-tone-3[2x] [small]#`person_with_ball-skin-tone-3`# +
emoji:person_with_ball-skin-tone-4[2x] [small]#`person_with_ball-skin-tone-4`# +
emoji:person_with_ball-skin-tone-5[2x] [small]#`person_with_ball-skin-tone-5`# +
emoji:person_with_ball-skin-tone-6[2x] [small]#`person_with_ball-skin-tone-6`# +
emoji:person_with_ball[2x] [small]#`person_with_ball`# +
emoji:golf[2x] [small]#`golf`# +
emoji:tennis[2x] [small]#`tennis`# +
emoji:ski[2x] [small]#`ski`# +
emoji:basketball[2x] [small]#`basketball`# +
emoji:checkered_flag[2x] [small]#`checkered_flag`# +
emoji:snowboarder-skin-tone-2[2x] [small]#`snowboarder-skin-tone-2`# +
emoji:snowboarder-skin-tone-3[2x] [small]#`snowboarder-skin-tone-3`# +
emoji:snowboarder-skin-tone-4[2x] [small]#`snowboarder-skin-tone-4`# +
emoji:snowboarder-skin-tone-5[2x] [small]#`snowboarder-skin-tone-5`# +
emoji:snowboarder-skin-tone-6[2x] [small]#`snowboarder-skin-tone-6`# +
emoji:snowboarder[2x] [small]#`snowboarder`# +

a| emoji:runner-skin-tone-2[2x] [small]#`runner-skin-tone-2`# +
emoji:runner-skin-tone-3[2x] [small]#`runner-skin-tone-3`# +
emoji:runner-skin-tone-4[2x] [small]#`runner-skin-tone-4`# +
emoji:runner-skin-tone-5[2x] [small]#`runner-skin-tone-5`# +
emoji:runner-skin-tone-6[2x] [small]#`runner-skin-tone-6`# +
emoji:runner[2x] [small]#`runner`# +
emoji:surfer-skin-tone-2[2x] [small]#`surfer-skin-tone-2`# +
emoji:surfer-skin-tone-3[2x] [small]#`surfer-skin-tone-3`# +
emoji:surfer-skin-tone-4[2x] [small]#`surfer-skin-tone-4`# +
emoji:surfer-skin-tone-5[2x] [small]#`surfer-skin-tone-5`# +
emoji:surfer-skin-tone-6[2x] [small]#`surfer-skin-tone-6`# +
emoji:surfer[2x] [small]#`surfer`# +
emoji:sports_medal[2x] [small]#`sports_medal`# +
emoji:trophy[2x] [small]#`trophy`# +
emoji:horse_racing-skin-tone-2[2x] [small]#`horse_racing-skin-tone-2`# +
emoji:horse_racing-skin-tone-3[2x] [small]#`horse_racing-skin-tone-3`# +
emoji:horse_racing-skin-tone-4[2x] [small]#`horse_racing-skin-tone-4`# +
emoji:horse_racing-skin-tone-5[2x] [small]#`horse_racing-skin-tone-5`# +
emoji:horse_racing-skin-tone-6[2x] [small]#`horse_racing-skin-tone-6`# +
emoji:horse_racing[2x] [small]#`horse_racing`# +
emoji:football[2x] [small]#`football`# +
emoji:rugby_football[2x] [small]#`rugby_football`# +
emoji:swimmer-skin-tone-2[2x] [small]#`swimmer-skin-tone-2`# +
emoji:swimmer-skin-tone-3[2x] [small]#`swimmer-skin-tone-2`# +
emoji:swimmer-skin-tone-4[2x] [small]#`swimmer-skin-tone-4`# +
emoji:swimmer-skin-tone-5[2x] [small]#`swimmer-skin-tone-5`# +
emoji:swimmer-skin-tone-6[2x] [small]#`swimmer-skin-tone-6`# +
emoji:swimmer[2x] [small]#`swimmer`# +
emoji:weight_lifter-skin-tone-2[2x] [small]#`weight_lifter-skin-tone-2`# +
emoji:weight_lifter-skin-tone-3[2x] [small]#`weight_lifter-skin-tone-3`# +
emoji:weight_lifter-skin-tone-4[2x] [small]#`weight_lifter-skin-tone-4`# +
emoji:weight_lifter-skin-tone-5[2x] [small]#`weight_lifter-skin-tone-5`# +
emoji:weight_lifter-skin-tone-6[2x] [small]#`weight_lifter-skin-tone-6`# +
emoji:weight_lifter[2x] [small]#`weight_lifter`# +
emoji:golfer[2x] [small]#`golfer`# +
emoji:racing_motorcycle[2x] [small]#`racing_motorcycle`# +
emoji:racing_car[2x] [small]#`racing_car`# +
emoji:cricket_bat_and_ball[2x] [small]#`cricket_bat_and_ball`# +
emoji:volleyball[2x] [small]#`volleyball`# +
emoji:field_hockey_stick_and_ball[2x] [small]#`field_hockey_stick_and_ball`# +
emoji:ice_hockey_stick_and_puck[2x] [small]#`ice_hockey_stick_and_puck`# +
emoji:table_tennis_paddle_and_ball[2x] [small]#`table_tennis_paddle_and_ball`# +

|===

=== Travel & Places

[cols="2"]
|===

a| emoji:airplane[2x] [small]#`airplane`# +
emoji:ferry[2x] [small]#`ferry`# +
emoji:boat[2x] [small]#`boat`# +
emoji:shinto_shrine[2x] [small]#`shinto_shrine`# +
emoji:church[2x] [small]#`church`# +
emoji:mountain[2x] [small]#`mountain`# +
emoji:rowboat-skin-tone-2[2x] [small]#`rowboat-skin-tone-2`# +
emoji:rowboat-skin-tone-3[2x] [small]#`rowboat-skin-tone-3`# +
emoji:rowboat-skin-tone-4[2x] [small]#`rowboat-skin-tone-4`# +
emoji:rowboat-skin-tone-5[2x] [small]#`rowboat-skin-tone-5`# +
emoji:rowboat-skin-tone-6[2x] [small]#`rowboat-skin-tone-6`# +
emoji:rowboat[2x] [small]#`rowboat`# +
emoji:speedboat[2x] [small]#`speedboat`# +
emoji:rocket[2x] [small]#`rocket`# +
emoji:helicopter[2x] [small]#`helicopter`# +
emoji:steam_locomotive[2x] [small]#`steam_locomotive`# +
emoji:railway_car[2x] [small]#`railway_car`# +
emoji:bullettrain_side[2x] [small]#`bullettrain_side`# +
emoji:bullettrain_front[2x] [small]#`bullettrain_front`# +
emoji:train2[2x] [small]#`train2`# +
emoji:metro[2x] [small]#`metro`# +
emoji:light_rail[2x] [small]#`light_rail`# +
emoji:station[2x] [small]#`station`# +
emoji:tram[2x] [small]#`tram`# +
emoji:train[2x] [small]#`train`# +
emoji:bus[2x] [small]#`bus`# +
emoji:oncoming_bus[2x] [small]#`oncoming_bus`# +
emoji:trolleybus[2x] [small]#`trolleybus`# +
emoji:busstop[2x] [small]#`busstop`# +
emoji:minibus[2x] [small]#`minibus`# +
emoji:ambulance[2x] [small]#`ambulance`# +
emoji:fire_engine[2x] [small]#`fire_engine`# +
emoji:police_car[2x] [small]#`police_car`# +
emoji:oncoming_police_car[2x] [small]#`oncoming_police_car`# +
emoji:taxi[2x] [small]#`taxi`# +
emoji:oncoming_taxi[2x] [small]#`oncoming_taxi`# +
emoji:car[2x] [small]#`car`# +
emoji:oncoming_automobile[2x] [small]#`oncoming_automobile`# +
emoji:blue_car[2x] [small]#`blue_car`# +
emoji:truck[2x] [small]#`truck`# +
emoji:articulated_lorry[2x] [small]#`articulated_lorry`# +
emoji:tractor[2x] [small]#`tractor`# +

a| emoji:monorail[2x] [small]#`monorail`# +
emoji:mountain_railway[2x] [small]#`mountain_railway`# +
emoji:suspension_railway[2x] [small]#`suspension_railway`# +
emoji:mountain_cableway[2x] [small]#`mountain_cableway`# +
emoji:aerial_tramway[2x] [small]#`aerial_tramway`# +
emoji:ship[2x] [small]#`ship`# +
emoji:world_map[2x] [small]#`world_map`# +
emoji:mount_fuji[2x] [small]#`mount_fuji`# +
emoji:tokyo_tower[2x] [small]#`tokyo_tower`# +
emoji:statue_of_liberty[2x] [small]#`statue_of_liberty`# +
emoji:japan[2x] [small]#`japan`# +
emoji:moyai[2x] [small]#`moyai`# +
emoji:snow_capped_mountain[2x] [small]#`snow_capped_mountain`# +
emoji:camping[2x] [small]#`camping`# +
emoji:beach_with_umbrella[2x] [small]#`beach_with_umbrella`# +
emoji:building_construction[2x] [small]#`building_construction`# +
emoji:house_buildings[2x] [small]#`house_buildings`# +
emoji:cityscape[2x] [small]#`cityscape`# +
emoji:derelict_house_building[2x] [small]#`derelict_house_building`# +
emoji:classical_building[2x] [small]#`classical_building`# +
emoji:desert[2x] [small]#`desert`# +
emoji:desert_island[2x] [small]#`desert_island`# +
emoji:national_park[2x] [small]#`national_park`# +
emoji:stadium[2x] [small]#`stadium`# +
emoji:house[2x] [small]#`house`# +
emoji:house_with_garden[2x] [small]#`house_with_garden`# +
emoji:office[2x] [small]#`office`# +
emoji:post_office[2x] [small]#`post_office`# +
emoji:european_post_office[2x] [small]#`european_post_office`# +
emoji:hospital[2x] [small]#`hospital`# +
emoji:bank[2x] [small]#`bank`# +
emoji:atm[2x] [small]#`atm`# +
emoji:hotel[2x] [small]#`hotel`# +
emoji:love_hotel[2x] [small]#`love_hotel`# +
emoji:convenience_store[2x] [small]#`convenience_store`# +
emoji:school[2x] [small]#`school`# +
emoji:department_store[2x] [small]#`department_store`# +
emoji:factory[2x] [small]#`factory`# +
emoji:izakaya_lantern[2x] [small]#`izakaya_lantern`# +
emoji:japanese_castle[2x] [small]#`japanese_castle`# +
emoji:european_castle[2x] [small]#`european_castle`# +

|===

=== Symbols

[cols="2"]
|===

a| emoji:latin_cross[2x] [small]#`latin_cross`# +
emoji:star_of_david[2x] [small]#`star_of_david`# +
emoji:sparkles[2x] [small]#`sparkles`# +
emoji:eight_spoked_asterisk[2x] [small]#`eight_spoked_asterisk`# +
emoji:eight_pointed_black_star[2x] [small]#`eight_pointed_black_star`# +
emoji:snowflake[2x] [small]#`snowflake`# +
emoji:sparkle[2x] [small]#`sparkle`# +
emoji:cross_mark[2x] [small]#`cross_mark`# +
emoji:negative_squared_cross_mark[2x] [small]#`negative_squared_cross_mark`# +
emoji:question[2x] [small]#`question`# +
emoji:grey_question[2x] [small]#`grey_question`# +
emoji:grey_exclamation[2x] [small]#`grey_exclamation`# +
emoji:exclamation[2x] [small]#`exclamation`# +
emoji:heavy_heart_exclamation_mark_ornament[2x] [small]#`heavy_heart_exclamation_mark_ornament`# +
emoji:shibuya[2x] [small]#`shibuya`# +
emoji:heart[2x] [small]#`heart`# +
emoji:heavy_plus_sign[2x] [small]#`heavy_plus_sign`# +
emoji:heavy_minus_sign[2x] [small]#`heavy_minus_sign`# +
emoji:heavy_division_sign[2x] [small]#`heavy_division_sign`# +
emoji:curly_loop[2x] [small]#`curly_loop`# +
emoji:loop[2x] [small]#`loop`# +
emoji:arrow_right[2x] [small]#`arrow_right`# +
emoji:arrow_heading_up[2x] [small]#`arrow_heading_up`# +
emoji:arrow_heading_down[2x] [small]#`arrow_heading_down`# +
emoji:asterisk[2x] [small]#`asterisk`# +
emoji:arrow_left[2x] [small]#`arrow_left`# +
emoji:arrow_up[2x] [small]#`arrow_up`# +
emoji:arrow_down[2x] [small]#`arrow_down`# +
emoji:zero[2x] [small]#`zero`# +
emoji:one[2x] [small]#`one`# +
emoji:two[2x] [small]#`two`# +
emoji:three[2x] [small]#`three`# +
emoji:four[2x] [small]#`four`# +
emoji:five[2x] [small]#`five`# +
emoji:six[2x] [small]#`six`# +
emoji:seven[2x] [small]#`seven`# +
emoji:eight[2x] [small]#`eight`# +
emoji:nine[2x] [small]#`nine`# +
emoji:copyright[2x] [small]#`copyright`# +
emoji:registered_sign[2x] [small]#`registered_sign`# +
emoji:black_large_square[2x] [small]#`black_large_square`# +
emoji:white_large_square[2x] [small]#`white_large_square`# +
emoji:star[2x] [small]#`star`# +
emoji:large_circle[2x] [small]#`large_circle`# +
emoji:wavy_dash[2x] [small]#`wavy_dash`# +
emoji:part_alternation_mark[2x] [small]#`part_alternation_mark`# +
emoji:heavy_check_mark[2x] [small]#`heavy_check_mark`# +
emoji:heavy_multiplication_x[2x] [small]#`heavy_multiplication_x`# +
emoji:email[2x] [small]#`email`# +
emoji:white_check_mark[2x] [small]#`white_check_mark`# +
emoji:no_entry[2x] [small]#`no_entry`# +
emoji:ophiuchus[2x] [small]#`ophiuchus`# +
emoji:bike[2x] [small]#`bike`# +
emoji:no_bicycles[2x] [small]#`no_bicycles`# +
emoji:no_pedestrians[2x] [small]#`no_pedestrians`# +
emoji:children_crossing[2x] [small]#`children_crossing`# +
emoji:mens[2x] [small]#`mens`# +
emoji:womens[2x] [small]#`womens`# +
emoji:restroom[2x] [small]#`restroom`# +
emoji:baby_symbol[2x] [small]#`baby_symbol`# +
emoji:toilet[2x] [small]#`toilet`# +
emoji:wc[2x] [small]#`wc`# +
emoji:shower[2x] [small]#`shower`# +
emoji:bath-skin-tone-2[2x] [small]#`bath-skin-tone-2`# +
emoji:bath-skin-tone-3[2x] [small]#`bath-skin-tone-3`# +
emoji:bath-skin-tone-4[2x] [small]#`bath-skin-tone-4`# +
emoji:bath-skin-tone-5[2x] [small]#`bath-skin-tone-5`# +
emoji:bath-skin-tone-6[2x] [small]#`bath-skin-tone-6`# +
emoji:bath[2x] [small]#`bath`# +
emoji:bathtub[2x] [small]#`bathtub`# +
emoji:passport_control[2x] [small]#`passport_control`# +
emoji:customs[2x] [small]#`customs`# +
emoji:baggage_claim[2x] [small]#`baggage_claim`# +
emoji:left_luggage[2x] [small]#`left_luggage`# +
emoji:couch_and_lamp[2x] [small]#`couch_and_lamp`# +
emoji:sleeping_accommodation[2x] [small]#`sleeping_accommodation`# +
emoji:shopping_bags[2x] [small]#`shopping_bags`# +
emoji:bellhop_bell[2x] [small]#`bellhop_bell`# +
emoji:bed[2x] [small]#`bed`# +
emoji:place_of_worship[2x] [small]#`place_of_worship`# +
emoji:hammer_and_wrench[2x] [small]#`hammer_and_wrench`# +
emoji:shield[2x] [small]#`shield`# +
emoji:oil_drum[2x] [small]#`oil_drum`# +
emoji:motorway[2x] [small]#`motorway`# +
emoji:railway_track[2x] [small]#`railway_track`# +
emoji:motor_boat[2x] [small]#`motor_boat`# +
emoji:small_airplane[2x] [small]#`small_airplane`# +
emoji:airplane_departure[2x] [small]#`airplane_departure`# +
emoji:airplane_arriving[2x] [small]#`airplane_arriving`# +
emoji:satellite[2x] [small]#`satellite`# +
emoji:passenger_ship[2x] [small]#`passenger_ship`# +
emoji:door[2x] [small]#`door`# +
emoji:no_entry_sign[2x] [small]#`no_entry_sign`# +
emoji:smoking[2x] [small]#`smoking`# +
emoji:no_smoking[2x] [small]#`no_smoking`# +
emoji:put_litter_in_its_place[2x] [small]#`put_litter_in_its_place`# +
emoji:do_not_litter[2x] [small]#`do_not_litter`# +
emoji:potable_water[2x] [small]#`potable_water`# +
emoji:non-potable_water[2x] [small]#`non-potable_water`# +
emoji:traffic_light[2x] [small]#`traffic_light`# +
emoji:vertical_traffic_light[2x] [small]#`vertical_traffic_light`# +
emoji:construction[2x] [small]#`construction`# +
emoji:rotating_light[2x] [small]#`rotating_light`# +
emoji:triangular_flag_on_post[2x] [small]#`triangular_flag_on_post`# +
emoji:speaking_head_in_silhouette[2x] [small]#`speaking_head_in_silhouette`# +
emoji:left_speech_bubble[2x] [small]#`left_speech_bubble`# +
emoji:right_anger_bubble[2x] [small]#`right_anger_bubble`# +
emoji:eye_left_speech_bubble[2x] [small]#`eye_left_speech_bubble`# +
emoji:desktop_computer[2x] [small]#`desktop_computer`# +
emoji:printer[2x] [small]#`printer`# +
emoji:three_button_mouse[2x] [small]#`three_button_mouse`# +
emoji:trackball[2x] [small]#`trackball`# +
emoji:frame_with_picture[2x] [small]#`frame_with_picture`# +
emoji:card_index_dividers[2x] [small]#`card_index_dividers`# +
emoji:card_file_box[2x] [small]#`card_file_box`# +
emoji:file_cabinet[2x] [small]#`file_cabinet`# +
emoji:dizzy[2x] [small]#`dizzy`# +
emoji:speech_balloon[2x] [small]#`speech_balloon`# +
emoji:thought_balloon[2x] [small]#`thought_balloon`# +
emoji:white_flower[2x] [small]#`white_flower`# +
emoji:100[2x] [small]#`100`# +
emoji:moneybag[2x] [small]#`moneybag`# +
emoji:currency_exchange[2x] [small]#`currency_exchange`# +
emoji:heavy_dollar_sign[2x] [small]#`heavy_dollar_sign`# +
emoji:credit_card[2x] [small]#`credit_card`# +
emoji:yen[2x] [small]#`yen`# +
emoji:dollar[2x] [small]#`dollar`# +
emoji:euro[2x] [small]#`euro`# +
emoji:pound[2x] [small]#`pound`# +
emoji:money_with_wings[2x] [small]#`money_with_wings`# +
emoji:chart[2x] [small]#`chart`# +
emoji:seat[2x] [small]#`seat`# +
emoji:computer[2x] [small]#`computer`# +
emoji:briefcase[2x] [small]#`briefcase`# +
emoji:minidisc[2x] [small]#`minidisc`# +
emoji:floppy_disk[2x] [small]#`floppy_disk`# +
emoji:cd[2x] [small]#`cd`# +
emoji:dvd[2x] [small]#`dvd`# +
emoji:file_folder[2x] [small]#`file_folder`# +
emoji:open_file_folder[2x] [small]#`open_file_folder`# +
emoji:page_with_curl[2x] [small]#`page_with_curl`# +
emoji:page_facing_up[2x] [small]#`page_facing_up`# +
emoji:date[2x] [small]#`date`# +
emoji:calendar[2x] [small]#`calendar`# +
emoji:card_index[2x] [small]#`card_index`# +
emoji:chart_with_upwards_trend[2x] [small]#`chart_with_upwards_trend`# +
emoji:chart_with_downwards_trend[2x] [small]#`chart_with_downwards_trend`# +
emoji:bar_chart[2x] [small]#`bar_chart`# +
emoji:clipboard[2x] [small]#`clipboard`# +
emoji:pushpin[2x] [small]#`pushpin`# +
emoji:round_pushpin[2x] [small]#`round_pushpin`# +
emoji:paperclip[2x] [small]#`paperclip`# +
emoji:straight_ruler[2x] [small]#`straight_ruler`# +
emoji:triangular_ruler[2x] [small]#`triangular_ruler`# +
emoji:bookmark_tabs[2x] [small]#`bookmark_tabs`# +
emoji:ledger[2x] [small]#`ledger`# +
emoji:notebook[2x] [small]#`notebook`# +
emoji:notebook_with_decorative_cover[2x] [small]#`notebook_with_decorative_cover`# +
emoji:closed_book[2x] [small]#`closed_book`# +
emoji:book[2x] [small]#`book`# +
emoji:green_book[2x] [small]#`green_book`# +
emoji:blue_book[2x] [small]#`blue_book`# +
emoji:orange_book[2x] [small]#`orange_book`# +
emoji:books[2x] [small]#`books`# +
emoji:name_badge[2x] [small]#`name_badge`# +
emoji:scroll[2x] [small]#`scroll`# +
emoji:memo[2x] [small]#`memo`# +
emoji:telephone_receiver[2x] [small]#`telephone_receiver`# +
emoji:pager[2x] [small]#`pager`# +
emoji:fax[2x] [small]#`fax`# +
emoji:satellite_antenna[2x] [small]#`satellite_antenna`# +
emoji:loudspeaker[2x] [small]#`loudspeaker`# +
emoji:mega[2x] [small]#`mega`# +
emoji:outbox_tray[2x] [small]#`outbox_tray`# +
emoji:inbox_tray[2x] [small]#`inbox_tray`# +
emoji:package[2x] [small]#`package`# +
emoji:e-mail[2x] [small]#`e-mail`# +
emoji:incoming_envelope[2x] [small]#`incoming_envelope`# +
emoji:envelope_with_arrow[2x] [small]#`envelope_with_arrow`# +
emoji:mailbox_closed[2x] [small]#`mailbox_closed`# +
emoji:mailbox[2x] [small]#`mailbox`# +
emoji:mailbox_with_mail[2x] [small]#`mailbox_with_mail`# +
emoji:mailbox_with_no_mail[2x] [small]#`mailbox_with_no_mail`# +
emoji:postbox[2x] [small]#`postbox`# +
emoji:postal_horn[2x] [small]#`postal_horn`# +
emoji:newspaper[2x] [small]#`newspaper`# +
emoji:iphone[2x] [small]#`iphone`# +
emoji:calling[2x] [small]#`calling`# +
emoji:vibration_mode[2x] [small]#`vibration_mode`# +
emoji:mobile_phone_off[2x] [small]#`mobile_phone_off`# +
emoji:no_mobile_phones[2x] [small]#`no_mobile_phones`# +
emoji:signal_strength[2x] [small]#`signal_strength`# +
emoji:camera[2x] [small]#`camera`# +
emoji:camera_with_flash[2x] [small]#`camera_with_flash`# +
emoji:video_camera[2x] [small]#`video_camera`# +

a| emoji:tv[2x] [small]#`tv`# +
emoji:radio[2x] [small]#`radio`# +
emoji:vhs[2x] [small]#`vhs`# +
emoji:film_projector[2x] [small]#`film_projector`# +
emoji:prayer_beads[2x] [small]#`prayer_beads`# +
emoji:twisted_rightwards_arrows[2x] [small]#`twisted_rightwards_arrows`# +
emoji:repeat[2x] [small]#`repeat`# +
emoji:repeat_one[2x] [small]#`repeat_one`# +
emoji:arrows_clockwise[2x] [small]#`arrows_clockwise`# +
emoji:arrows_counterclockwise[2x] [small]#`arrows_counterclockwise`# +
emoji:low_brightness[2x] [small]#`low_brightness`# +
emoji:high_brightness[2x] [small]#`high_brightness`# +
emoji:mute[2x] [small]#`mute`# +
emoji:speaker[2x] [small]#`speaker`# +
emoji:sound[2x] [small]#`sound`# +
emoji:loud_sound[2x] [small]#`loud_sound`# +
emoji:battery[2x] [small]#`battery`# +
emoji:electric_plug[2x] [small]#`electric_plug`# +
emoji:mag[2x] [small]#`mag`# +
emoji:mag_right[2x] [small]#`mag_right`# +
emoji:lock_with_ink_pen[2x] [small]#`lock_with_ink_pen`# +
emoji:closed_lock_with_key[2x] [small]#`closed_lock_with_key`# +
emoji:key[2x] [small]#`key`# +
emoji:lock[2x] [small]#`lock`# +
emoji:unlock[2x] [small]#`unlock`# +
emoji:bell[2x] [small]#`bell`# +
emoji:no_bell[2x] [small]#`no_bell`# +
emoji:bookmark[2x] [small]#`bookmark`# +
emoji:link[2x] [small]#`link`# +
emoji:radio_button[2x] [small]#`radio_button`# +
emoji:back[2x] [small]#`back`# +
emoji:end[2x] [small]#`end`# +
emoji:on[2x] [small]#`on`# +
emoji:soon[2x] [small]#`soon`# +
emoji:top[2x] [small]#`top`# +
emoji:underage[2x] [small]#`underage`# +
emoji:keycap_ten[2x] [small]#`keycap_ten`# +
emoji:capital_abcd[2x] [small]#`capital_abcd`# +
emoji:abcd[2x] [small]#`abcd`# +
emoji:1234[2x] [small]#`1234`# +
emoji:symbols[2x] [small]#`symbols`# +
emoji:abc[2x] [small]#`abc`# +
emoji:fire[2x] [small]#`fire`# +
emoji:flashlight[2x] [small]#`flashlight`# +
emoji:wrench[2x] [small]#`wrench`# +
emoji:hammer[2x] [small]#`hammer`# +
emoji:nut_and_bolt[2x] [small]#`nut_and_bolt`# +
emoji:hocho[2x] [small]#`hocho`# +
emoji:gun[2x] [small]#`gun`# +
emoji:microscope[2x] [small]#`microscope`# +
emoji:telescope[2x] [small]#`telescope`# +
emoji:crystal_ball[2x] [small]#`crystal_ball`# +
emoji:six_pointed_star[2x] [small]#`six_pointed_star`# +
emoji:beginner[2x] [small]#`beginner`# +
emoji:trident[2x] [small]#`trident`# +
emoji:black_square_button[2x] [small]#`black_square_button`# +
emoji:white_square_button[2x] [small]#`white_square_button`# +
emoji:red_circle[2x] [small]#`red_circle`# +
emoji:large_blue_circle[2x] [small]#`large_blue_circle`# +
emoji:large_orange_diamond[2x] [small]#`large_orange_diamond`# +
emoji:large_blue_diamond[2x] [small]#`large_blue_diamond`# +
emoji:small_orange_diamond[2x] [small]#`small_orange_diamond`# +
emoji:small_blue_diamond[2x] [small]#`small_blue_diamond`# +
emoji:small_red_triangle[2x] [small]#`small_red_triangle`# +
emoji:small_red_triangle_down[2x] [small]#`small_red_triangle_down`# +
emoji:arrow_up_small[2x] [small]#`arrow_up_small`# +
emoji:arrow_down_small[2x] [small]#`arrow_down_small`# +
emoji:om_symbol[2x] [small]#`om_symbol`# +
emoji:dove_of_peace[2x] [small]#`dove_of_peace`# +
emoji:kaaba[2x] [small]#`kaaba`# +
emoji:mosque[2x] [small]#`mosque`# +
emoji:synagogue[2x] [small]#`synagogue`# +
emoji:menorah_with_nine_branches[2x] [small]#`menorah_with_nine_branches`# +
emoji:clock1[2x] [small]#`clock1`# +
emoji:clock2[2x] [small]#`clock2`# +
emoji:clock3[2x] [small]#`clock3`# +
emoji:clock4[2x] [small]#`clock4`# +
emoji:clock5[2x] [small]#`clock5`# +
emoji:clock6[2x] [small]#`clock6`# +
emoji:clock7[2x] [small]#`clock7`# +
emoji:clock8[2x] [small]#`clock8`# +
emoji:clock9[2x] [small]#`clock9`# +
emoji:clock10[2x] [small]#`clock10`# +
emoji:clock11[2x] [small]#`clock11`# +
emoji:clock12[2x] [small]#`clock12`# +
emoji:clock130[2x] [small]#`clock130`# +
emoji:clock230[2x] [small]#`clock230`# +
emoji:clock330[2x] [small]#`clock330`# +
emoji:clock430[2x] [small]#`clock430`# +
emoji:clock530[2x] [small]#`clock530`# +
emoji:clock630[2x] [small]#`clock630`# +
emoji:clock730[2x] [small]#`clock730`# +
emoji:clock830[2x] [small]#`clock830`# +
emoji:clock930[2x] [small]#`clock930`# +
emoji:clock1030[2x] [small]#`clock1030`# +
emoji:clock1130[2x] [small]#`clock1130`# +
emoji:clock1230[2x] [small]#`clock1230`# +
emoji:mahjong[2x] [small]#``mahjong``# +
emoji:black_joker[2x] [small]#``black_joker``# +
emoji:a_negative[2x] [small]#``a_negative``# +
emoji:b_negative[2x] [small]#`b_negative`# +
emoji:o_negative[2x] [small]#`o_negative`# +
emoji:parking[2x] [small]#`parking`# +
emoji:double_exclamation_mark[2x] [small]#`double_exclamation_mark`# +
emoji:interrobang[2x] [small]#`interrobang`# +
emoji:trade_mark[2x] [small]#`trade_mark`# +
emoji:information_source[2x] [small]#`information_source`# +
emoji:left_right_arrow[2x] [small]#`left_right_arrow`# +
emoji:arrow_up_down[2x] [small]#`arrow_up_down`# +
emoji:arrow_upper_left[2x] [small]#`arrow_upper_left`# +
emoji:arrow_upper_right[2x] [small]#`arrow_upper_right`# +
emoji:arrow_lower_right[2x] [small]#`arrow_lower_right`# +
emoji:arrow_lower_left[2x] [small]#`arrow_lower_left`# +
emoji:leftwards_arrow_with_hook[2x] [small]#`leftwards_arrow_with_hook`# +
emoji:arrow_right_hook[2x] [small]#`arrow_right_hook`# +
emoji:hash[2x] [small]#`hash`# +
emoji:watch[2x] [small]#`watch`# +
emoji:hourglass[2x] [small]#`hourglass`# +
emoji:keyboard[2x] [small]#`keyboard`# +
emoji:eject[2x] [small]#`eject`# +
emoji:fast_forward[2x] [small]#`fast_forward`# +
emoji:rewind[2x] [small]#`rewind`# +
emoji:arrow_double_up[2x] [small]#`arrow_double_up`# +
emoji:arrow_double_down[2x] [small]#`arrow_double_down`# +
emoji:black_right_pointing_double_triangle_with_vertical_bar[2x] [small]#`black_right_pointing_double_triangle_with_vertical_bar`# +
emoji:black_left_pointing_double_triangle_with_vertical_bar[2x] [small]#`black_left_pointing_double_triangle_with_vertical_bar`# +
emoji:black_right_pointing_triangle_with_double_vertical_bar[2x] [small]#`black_right_pointing_triangle_with_double_vertical_bar`# +
emoji:alarm_clock[2x] [small]#`alarm_clock`# +
emoji:stopwatch[2x] [small]#`stopwatch`# +
emoji:timer_clock[2x] [small]#`timer_clock`# +
emoji:hourglass_flowing_sand[2x] [small]#`hourglass_flowing_sand`# +
emoji:double_vertical_bar[2x] [small]#`double_vertical_bar`# +
emoji:black_square_for_stop[2x] [small]#`black_square_for_stop`# +
emoji:black_circle_for_record[2x] [small]#`black_circle_for_record`# +
emoji:m_circled[2x] [small]#`m_circled`# +
emoji:black_small_square[2x] [small]#`black_small_square`# +
emoji:white_small_square[2x] [small]#`white_small_square`# +
emoji:arrow_forward[2x] [small]#`arrow_forward`# +
emoji:arrow_backward[2x] [small]#`arrow_backward`# +
emoji:white_medium_square[2x] [small]#`white_medium_square`# +
emoji:black_medium_square[2x] [small]#`black_medium_square`# +
emoji:white_medium_small_square[2x] [small]#`white_medium_small_square`# +
emoji:black_medium_small_square[2x] [small]#`black_medium_small_square`# +
emoji:ab[2x] [small]#`ab`# +
emoji:cl[2x] [small]#`cl`# +
emoji:cool[2x] [small]#`cool`# +
emoji:free[2x] [small]#`free`# +
emoji:id[2x] [small]#`id`# +
emoji:new[2x] [small]#`new`# +
emoji:ng[2x] [small]#`ng`# +
emoji:ok[2x] [small]#`ok`# +
emoji:sos[2x] [small]#`sos`# +
emoji:up[2x] [small]#`up`# +
emoji:vs[2x] [small]#`vs`# +
emoji:skull_and_crossbones[2x] [small]#`skull_and_crossbones`# +
emoji:radioactive_sign[2x] [small]#`radioactive_sign`# +
emoji:biohazard_sign[2x] [small]#`biohazard_sign`# +
emoji:orthodox_cross[2x] [small]#`orthodox_cross`# +
emoji:star_and_crescent[2x] [small]#`star_and_crescent`# +
emoji:peace_symbol[2x] [small]#`peace_symbol`# +
emoji:yin_yang[2x] [small]#`yin_yang`# +
emoji:wheel_of_dharma[2x] [small]#`wheel_of_dharma`# +
emoji:aries[2x] [small]#`aries`# +
emoji:taurus[2x] [small]#`taurus`# +
emoji:gemini[2x] [small]#`gemini`# +
emoji:cancer[2x] [small]#`cancer`# +
emoji:leo[2x] [small]#`leo`# +
emoji:virgo[2x] [small]#`virgo`# +
emoji:libra[2x] [small]#`libra`# +
emoji:scorpius[2x] [small]#`scorpius`# +
emoji:sagittarius[2x] [small]#`sagittarius`# +
emoji:capricorn[2x] [small]#`capricorn`# +
emoji:aquarius[2x] [small]#`aquarius`# +
emoji:pisces[2x] [small]#`pisces`# +
emoji:spades[2x] [small]#`spades`# +
emoji:clubs[2x] [small]#`clubs`# +
emoji:hearts[2x] [small]#`hearts`# +
emoji:diamonds[2x] [small]#`diamonds`# +
emoji:hotsprings[2x] [small]#`hotsprings`# +
emoji:recycle[2x] [small]#`recycle`# +
emoji:wheelchair[2x] [small]#`wheelchair`# +
emoji:hammer_and_pick[2x] [small]#`hammer_and_pick`# +
emoji:anchor[2x] [small]#`anchor`# +
emoji:crossed_swords[2x] [small]#`crossed_swords`# +
emoji:scales[2x] [small]#`scales`# +
emoji:alembic[2x] [small]#`alembic`# +
emoji:gear[2x] [small]#`gear`# +
emoji:atom_symbol[2x] [small]#`atom_symbol`# +
emoji:fleur_de_lis[2x] [small]#`fleur_de_lis`# +
emoji:warning[2x] [small]#`warning`# +
emoji:zap[2x] [small]#`zap`# +
emoji:white_circle[2x] [small]#`white_circle`# +
emoji:black_circle[2x] [small]#`black_circle`# +

|===

=== Flags

[cols="4"]
|===

a| emoji:a[2x] [small]#`a`# +
emoji:flag-ac[2x] [small]#`flag-ac`# +
emoji:flag-ad[2x] [small]#`flag-ad`# +
emoji:flag-ae[2x] [small]#`flag-ae`# +
emoji:flag-af[2x] [small]#`flag-af`# +
emoji:flag-ag[2x] [small]#`flag-ag`# +
emoji:flag-ai[2x] [small]#`flag-ai`# +
emoji:flag-al[2x] [small]#`flag-al`# +
emoji:flag-am[2x] [small]#`flag-am`# +
emoji:flag-ao[2x] [small]#`flag-ao`# +
emoji:flag-aq[2x] [small]#`flag-aq`# +
emoji:flag-ar[2x] [small]#`flag-ar`# +
emoji:flag-as[2x] [small]#`flag-as`# +
emoji:flag-at[2x] [small]#`flag-at`# +
emoji:flag-au[2x] [small]#`flag-au`# +
emoji:flag-aw[2x] [small]#`flag-aw`# +
emoji:flag-ax[2x] [small]#`flag-ax`# +
emoji:flag-az[2x] [small]#`flag-az`# +
emoji:b[2x] [small]#`b`# +
emoji:flag-ba[2x] [small]#`flag-ba`# +
emoji:flag-bb[2x] [small]#`flag-bb`# +
emoji:flag-bd[2x] [small]#`flag-bd`# +
emoji:flag-be[2x] [small]#`flag-be`# +
emoji:flag-bf[2x] [small]#`flag-bf`# +
emoji:flag-bg[2x] [small]#`flag-bg`# +
emoji:flag-bh[2x] [small]#`flag-bh`# +
emoji:flag-bi[2x] [small]#`flag-bi`# +
emoji:flag-bj[2x] [small]#`flag-bj`# +
emoji:flag-bl[2x] [small]#`flag-bl`# +
emoji:flag-bm[2x] [small]#`flag-bm`# +
emoji:flag-bn[2x] [small]#`flag-bn`# +
emoji:flag-bo[2x] [small]#`flag-bo`# +
emoji:flag-bq[2x] [small]#`flag-bq`# +
emoji:flag-br[2x] [small]#`flag-br`# +
emoji:flag-bs[2x] [small]#`flag-bs`# +
emoji:flag-bt[2x] [small]#`flag-bt`# +
emoji:flag-bv[2x] [small]#`flag-bv`# +
emoji:flag-bw[2x] [small]#`flag-bw`# +
emoji:flag-by[2x] [small]#`flag-by`# +
emoji:flag-bz[2x] [small]#`flag-bz`# +
emoji:c[2x] [small]#`c`# +
emoji:flag-ca[2x] [small]#`flag-ca`# +
emoji:flag-cc[2x] [small]#`flag-cc`# +
emoji:flag-cd[2x] [small]#`flag-cd`# +
emoji:flag-cf[2x] [small]#`flag-cf`# +
emoji:flag-cg[2x] [small]#`flag-cg`# +
emoji:flag-ch[2x] [small]#`flag-ch`# +
emoji:flag-ci[2x] [small]#`flag-ci`# +
emoji:flag-ck[2x] [small]#`flag-ck`# +
emoji:flag-cl[2x] [small]#`flag-cl`# +
emoji:flag-cm[2x] [small]#`flag-cm`# +
emoji:flag-cn[2x] [small]#`flag-cn`# +
emoji:flag-co[2x] [small]#`flag-co`# +
emoji:flag-cp[2x] [small]#`flag-cp`# +
emoji:flag-cr[2x] [small]#`flag-cr`# +
emoji:flag-cu[2x] [small]#`flag-cu`# +
emoji:flag-cv[2x] [small]#`flag-cv`# +
emoji:flag-cw[2x] [small]#`flag-cw`# +
emoji:flag-cx[2x] [small]#`flag-cx`# +
emoji:flag-cy[2x] [small]#`flag-cy`# +
emoji:flag-cz[2x] [small]#`flag-cz`# +
emoji:d[2x] [small]#`d`# +
emoji:flag-de[2x] [small]#`flag-de`# +
emoji:flag-dg[2x] [small]#`flag-dg`# +
emoji:flag-dj[2x] [small]#`flag-dj`# +
emoji:flag-dk[2x] [small]#`flag-dk`# +
emoji:flag-dm[2x] [small]#`flag-dm`# +
emoji:flag-do[2x] [small]#`flag-do`# +
emoji:flag-dz[2x] [small]#`flag-dz`# +

a| emoji:e[2x] [small]#`e`# +
emoji:flag-ea[2x] [small]#`flag-ea`# +
emoji:flag-ec[2x] [small]#`flag-ec`# +
emoji:flag-ee[2x] [small]#`flag-ee`# +
emoji:flag-eg[2x] [small]#`flag-eg`# +
emoji:flag-eh[2x] [small]#`flag-eh`# +
emoji:flag-er[2x] [small]#`flag-er`# +
emoji:flag-es[2x] [small]#`flag-es`# +
emoji:flag-et[2x] [small]#`flag-et`# +
emoji:flag-eu[2x] [small]#`flag-eu`# +
emoji:f[2x] [small]#`f`# +
emoji:flag-fi[2x] [small]#`flag-fi`# +
emoji:flag-fj[2x] [small]#`flag-fj`# +
emoji:flag-fk[2x] [small]#`flag-fk`# +
emoji:flag-fm[2x] [small]#`flag-fm`# +
emoji:flag-fo[2x] [small]#`flag-fo`# +
emoji:flag-fr[2x] [small]#`flag-fr`# +
emoji:g[2x] [small]#`g`# +
emoji:flag-ga[2x] [small]#`flag-ga`# +
emoji:flag-gb[2x] [small]#`flag-gb`# +
emoji:flag-gd[2x] [small]#`flag-gd`# +
emoji:flag-ge[2x] [small]#`flag-ge`# +
emoji:flag-gf[2x] [small]#`flag-gf`# +
emoji:flag-gg[2x] [small]#`flag-gg`# +
emoji:flag-gh[2x] [small]#`flag-gh`# +
emoji:flag-gi[2x] [small]#`flag-gi`# +
emoji:flag-gl[2x] [small]#`flag-gl`# +
emoji:flag-gm[2x] [small]#`flag-gm`# +
emoji:flag-gn[2x] [small]#`flag-gn`# +
emoji:flag-gp[2x] [small]#`flag-gp`# +
emoji:flag-gq[2x] [small]#`flag-gq`# +
emoji:flag-gr[2x] [small]#`flag-gr`# +
emoji:flag-gs[2x] [small]#`flag-gs`# +
emoji:flag-gt[2x] [small]#`flag-gt`# +
emoji:flag-gu[2x] [small]#`flag-gu`# +
emoji:flag-gw[2x] [small]#`flag-gw`# +
emoji:flag-gy[2x] [small]#`flag-gy`# +
emoji:h[2x] [small]#`h`# +
emoji:flag-hk[2x] [small]#`flag-hk`# +
emoji:flag-hm[2x] [small]#`flag-hm`# +
emoji:flag-hn[2x] [small]#`flag-hn`# +
emoji:flag-hr[2x] [small]#`flag-hr`# +
emoji:flag-ht[2x] [small]#`flag-ht`# +
emoji:flag-hu[2x] [small]#`flag-hu`# +
emoji:i[2x] [small]#`i`# +
emoji:flag-ic[2x] [small]#`flag-ic`# +
emoji:flag-id[2x] [small]#`flag-id`# +
emoji:flag-ie[2x] [small]#`flag-ie`# +
emoji:flag-il[2x] [small]#`flag-il`# +
emoji:flag-im[2x] [small]#`flag-im`# +
emoji:flag-in[2x] [small]#`flag-in`# +
emoji:flag-io[2x] [small]#`flag-io`# +
emoji:flag-iq[2x] [small]#`flag-iq`# +
emoji:flag-ir[2x] [small]#`flag-ir`# +
emoji:flag-is[2x] [small]#`flag-is`# +
emoji:flag-it[2x] [small]#`flag-it`# +
emoji:j[2x] [small]#`j`# +
emoji:flag-je[2x] [small]#`flag-je`# +
emoji:flag-jm[2x] [small]#`flag-jm`# +
emoji:flag-jo[2x] [small]#`flag-jo`# +
emoji:flag-jp[2x] [small]#`flag-jp`# +
emoji:k[2x] [small]#`k`# +
emoji:flag-ke[2x] [small]#`flag-ke`# +
emoji:flag-kg[2x] [small]#`flag-kg`# +
emoji:flag-kh[2x] [small]#`flag-kh`# +
emoji:flag-ki[2x] [small]#`flag-ki`# +
emoji:flag-km[2x] [small]#`flag-km`# +
emoji:flag-kn[2x] [small]#`flag-kn`# +
emoji:flag-kp[2x] [small]#`flag-kp`# +
emoji:flag-kr[2x] [small]#`flag-kr`# +
emoji:flag-kw[2x] [small]#`flag-kw`# +
emoji:flag-ky[2x] [small]#`flag-ky`# +
emoji:flag-kz[2x] [small]#`flag-kz`# +

a| emoji:l[2x] [small]#`l`# +
emoji:flag-la[2x] [small]#`flag-la`# +
emoji:flag-lb[2x] [small]#`flag-lb`# +
emoji:flag-lc[2x] [small]#`flag-lc`# +
emoji:flag-li[2x] [small]#`flag-li`# +
emoji:flag-lk[2x] [small]#`flag-lk`# +
emoji:flag-lr[2x] [small]#`flag-lr`# +
emoji:flag-ls[2x] [small]#`flag-ls`# +
emoji:flag-lt[2x] [small]#`flag-lt`# +
emoji:flag-lu[2x] [small]#`flag-lu`# +
emoji:flag-lv[2x] [small]#`flag-lv`# +
emoji:flag-ly[2x] [small]#`flag-ly`# +
emoji:m[2x] [small]#`m`# +
emoji:flag-ma[2x] [small]#`flag-ma`# +
emoji:flag-mc[2x] [small]#`flag-mc`# +
emoji:flag-md[2x] [small]#`flag-md`# +
emoji:flag-me[2x] [small]#`flag-me`# +
emoji:flag-mf[2x] [small]#`flag-mf`# +
emoji:flag-mg[2x] [small]#`flag-mg`# +
emoji:flag-mh[2x] [small]#`flag-mh`# +
emoji:flag-mk[2x] [small]#`flag-mk`# +
emoji:flag-ml[2x] [small]#`flag-ml`# +
emoji:flag-mm[2x] [small]#`flag-mm`# +
emoji:flag-mn[2x] [small]#`flag-mn`# +
emoji:flag-mo[2x] [small]#`flag-mo`# +
emoji:flag-mp[2x] [small]#`flag-mp`# +
emoji:flag-mq[2x] [small]#`flag-mq`# +
emoji:flag-mr[2x] [small]#`flag-mr`# +
emoji:flag-ms[2x] [small]#`flag-ms`# +
emoji:flag-mt[2x] [small]#`flag-mt`# +
emoji:flag-mu[2x] [small]#`flag-mu`# +
emoji:flag-mv[2x] [small]#`flag-mv`# +
emoji:flag-mw[2x] [small]#`flag-mw`# +
emoji:flag-mx[2x] [small]#`flag-mx`# +
emoji:flag-my[2x] [small]#`flag-my`# +
emoji:flag-mz[2x] [small]#`flag-mz`# +
emoji:n[2x] [small]#`n`# +
emoji:flag-na[2x] [small]#`flag-na`# +
emoji:flag-nc[2x] [small]#`flag-nc`# +
emoji:flag-ne[2x] [small]#`flag-ne`# +
emoji:flag-nf[2x] [small]#`flag-nf`# +
emoji:flag-ng[2x] [small]#`flag-ng`# +
emoji:flag-ni[2x] [small]#`flag-ni`# +
emoji:flag-nl[2x] [small]#`flag-nl`# +
emoji:flag-no[2x] [small]#`flag-no`# +
emoji:flag-np[2x] [small]#`flag-np`# +
emoji:flag-nr[2x] [small]#`flag-nr`# +
emoji:flag-nu[2x] [small]#`flag-nu`# +
emoji:flag-nz[2x] [small]#`flag-nz`# +
emoji:o[2x] [small]#`o`# +
emoji:flag-om[2x] [small]#`flag-om`# +
emoji:p[2x] [small]#`p`# +
emoji:flag-pa[2x] [small]#`flag-pa`# +
emoji:flag-pe[2x] [small]#`flag-pe`# +
emoji:flag-pf[2x] [small]#`flag-pf`# +
emoji:flag-pg[2x] [small]#`flag-pg`# +
emoji:flag-ph[2x] [small]#`flag-ph`# +
emoji:flag-pk[2x] [small]#`flag-pk`# +
emoji:flag-pl[2x] [small]#`flag-pl`# +
emoji:flag-pm[2x] [small]#`flag-pm`# +
emoji:flag-pn[2x] [small]#`flag-pn`# +
emoji:flag-pr[2x] [small]#`flag-pr`# +
emoji:flag-ps[2x] [small]#`flag-ps`# +
emoji:flag-pt[2x] [small]#`flag-pt`# +
emoji:flag-pw[2x] [small]#`flag-pw`# +
emoji:flag-py[2x] [small]#`flag-py`# +
emoji:q[2x] [small]#`q`# +
emoji:flag-qa[2x] [small]#`flag-qa`# +

a| emoji:r[2x] [small]#`r`# +
emoji:flag-re[2x] [small]#`flag-re`# +
emoji:flag-ro[2x] [small]#`flag-ro`# +
emoji:flag-rs[2x] [small]#`flag-rs`# +
emoji:flag-ru[2x] [small]#`flag-ru`# +
emoji:flag-rw[2x] [small]#`flag-rw`# +
emoji:s[2x] [small]#`s`# +
emoji:flag-sa[2x] [small]#`flag-sa`# +
emoji:flag-sb[2x] [small]#`flag-sb`# +
emoji:flag-sc[2x] [small]#`flag-sc`# +
emoji:flag-sd[2x] [small]#`flag-sd`# +
emoji:flag-se[2x] [small]#`flag-se`# +
emoji:flag-sg[2x] [small]#`flag-sg`# +
emoji:flag-sh[2x] [small]#`flag-sh`# +
emoji:flag-si[2x] [small]#`flag-si`# +
emoji:flag-sj[2x] [small]#`flag-sj`# +
emoji:flag-sk[2x] [small]#`flag-sk`# +
emoji:flag-sl[2x] [small]#`flag-sl`# +
emoji:flag-sm[2x] [small]#`flag-sm`# +
emoji:flag-sn[2x] [small]#`flag-sn`# +
emoji:flag-so[2x] [small]#`flag-so`# +
emoji:flag-sr[2x] [small]#`flag-sr`# +
emoji:flag-ss[2x] [small]#`flag-ss`# +
emoji:flag-st[2x] [small]#`flag-st`# +
emoji:flag-sv[2x] [small]#`flag-sv`# +
emoji:flag-sx[2x] [small]#`flag-sx`# +
emoji:flag-sy[2x] [small]#`flag-sy`# +
emoji:flag-sz[2x] [small]#`flag-sz`# +
emoji:t[2x] [small]#`t`# +
emoji:flag-ta[2x] [small]#`flag-ta`# +
emoji:flag-tc[2x] [small]#`flag-tc`# +
emoji:flag-td[2x] [small]#`flag-td`# +
emoji:flag-tf[2x] [small]#`flag-tf`# +
emoji:flag-tg[2x] [small]#`flag-tg`# +
emoji:flag-th[2x] [small]#`flag-th`# +
emoji:flag-tj[2x] [small]#`flag-tj`# +
emoji:flag-tk[2x] [small]#`flag-tk`# +
emoji:flag-tl[2x] [small]#`flag-tl`# +
emoji:flag-tm[2x] [small]#`flag-tm`# +
emoji:flag-tn[2x] [small]#`flag-tn`# +
emoji:flag-to[2x] [small]#`flag-to`# +
emoji:flag-tr[2x] [small]#`flag-tr`# +
emoji:flag-tt[2x] [small]#`flag-tt`# +
emoji:flag-tv[2x] [small]#`flag-tv`# +
emoji:flag-tw[2x] [small]#`flag-tw`# +
emoji:flag-tz[2x] [small]#`flag-tz`# +
emoji:u[2x] [small]#`u`# +
emoji:flag-ua[2x] [small]#`flag-ua`# +
emoji:flag-ug[2x] [small]#`flag-ug`# +
emoji:flag-um[2x] [small]#`flag-um`# +
emoji:flag-us[2x] [small]#`flag-us`# +
emoji:flag-uy[2x] [small]#`flag-uy`# +
emoji:flag-uz[2x] [small]#`flag-uz`# +
emoji:v[2x] [small]#`v`# +
emoji:flag-va[2x] [small]#`flag-va`# +
emoji:flag-vc[2x] [small]#`flag-vc`# +
emoji:flag-ve[2x] [small]#`flag-ve`# +
emoji:flag-vg[2x] [small]#`flag-vg`# +
emoji:flag-vi[2x] [small]#`flag-vi`# +
emoji:flag-vn[2x] [small]#`flag-vn`# +
emoji:flag-vu[2x] [small]#`flag-vu`# +
emoji:w[2x] [small]#`w`# +
emoji:flag-wf[2x] [small]#`flag-wf`# +
emoji:flag-ws[2x] [small]#`flag-ws`# +
emoji:x[2x] [small]#`x`# +
emoji:flag-xk[2x] [small]#`flag-xk`# +
emoji:y[2x] [small]#`y`# +
emoji:flag-ye[2x] [small]#`flag-ye`# +
emoji:flag-yt[2x] [small]#`flag-yt`# +
emoji:z[2x] [small]#`z`# +
emoji:flag-za[2x] [small]#`flag-za`# +
emoji:flag-zm[2x] [small]#`flag-zm`# +
emoji:flag-zw[2x] [small]#`flag-zw`# +

|===

== Credits

Emoji support by link:https://github.com/twitter/twemoji[twemoji].

Emoji graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/
