= Anatomy of a Wiki Header
:author: mitm
:revnumber:
:revdate: 2017-09-08T23:24:11.262Z
:relfileprefix: ../
:imagesdir: ..
:experimental:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

All wiki documents use these header attributes. Optional attributes can be left blank following the kbd:[:] colon symbol.

[source,subs="+macros"]
----
= Enter Document Title Here
:author:
:revnumber:
:revdate:
:relfileprefix: ../../
:imagesdir: ../..
:experimental:
:link-javadoc: pass:[https://javadoc.jmonkeyengine.org]
:stylesheet: twemoji-awesome.css
ifdef++::++env-github,env-browser[:outfilesuffix: .adoc]
----

== =

Mandatory. Title of your document.

== :author:

Optional. Document author.

[IMPORTANT]
====
Optional Author and Revision information immediately follows the header title.
====

== :revnumber:

Optional. Revision number.

== :revdate:

Optional. Revision Date

== :relfileprefix:

Optional. Enter a path to the "`asciidoc`" folder if using cross reference links.

TIP: Use `Tree View` (kbd:[ctrl]+kbd:[\ ] or `menu:View[Toggle Tree View]`) to locate the "`asciidoc`" folder if using the link:https://atom.io/[Atom editor].

In the example below, "`asciidoc`" is two folders above the folder this file is located in.

```
:relfileprefix: ../../
```

== :imagesdir:

Optional. Enter a path to the "images" folder if using image links.

TIP: Use `Tree View` (kbd:[ctrl]+kbd:[\ ] or `menu:View[Toggle Tree View]`) to locate the "`images`" folder if using the link:https://atom.io/[Atom editor].

In the example below, "`images`" is two folders above the folder this file is located in. Note the missing kbd:[/] forward slash.

```
:imagesdir: ../..
```

[TIP]
====
A simple way to determine the location of the "asciidoc" and "images" folder in the Atom editor is first save the file to its new location, then in `Tree View` (kbd:[ctrl]+kbd:[\ ] or `menu:View[Toggle Tree View]`), btn:[RMB] select the saved file and select btn:[Copy Project Path].

Temporarily paste this into your document to see where the "`asciidoc`" folder is located.

For example: `src\docs\asciidoc\jme3\advanced\3d_models.adoc`

In this example, "asciidoc" is located two folders above the "advanced" folder `3d_models.adoc` resides in.

You can find this same folder information using link:https://github.com/jMonkeyEngine/wiki/blob/master/docs/modules/ROOT/pages/jme3/advanced/3d_models.adoc[GitHub].
====

The "`images`" folder resides in the same folder as the "`asciidoc`" folder so it has the same setting minus the kbd:[/ ] forward slash.

== :experimental:

Optional. Leave this blank, i.e do not set a value for this attribute if using it. This is the experimental attribute that allows the use of link:http://asciidoctor.org/docs/user-manual/#user-interface-macros[User Interface Macros]. You use these macros for creating keyboard shortcuts, displaying menu selections and UI buttons.

== :link-javadoc:

Optional. This is the global attribute for the jME javadocs. You set this if you are *overriding* the default setting from the link:https://github.com/jMonkeyEngine/wiki/blob/9d0e4fd07d019c3d41c6b9e64b2a1a5b7e0ed774/build.gradle#L39[build.gradle] file. You can use the default `pass:[{link-javadoc}]` attribute directly in any document you write, as is shown in the following example, without adding anything to the header.

```
link:{link-javadoc}/com/jme3/app/state/BaseAppState.html[BaseAppState]
```

If you override the variable in the header of the document, that value will be used instead.

== :stylesheet: twemoji-awesome.css

Optional. Adding this attribute will allow the use of emoji in the document.

See: <<wiki/emoji#,Emoji Cheat Sheet>>

== ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Mandatory. See link:http://asciidoctor.org/docs/user-manual/#navigating-between-source-files[Navigating Between Source Files] in the AsciiDoctor user manual. Leave this as written.
