= Setting up JME3 in Netbeans 6+
:author:
:revnumber:
:revdate: 2016/03/17 20:48
:keywords: documentation, install
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


You are welcome to try out the new jME3, and contribute patches and features! This document shows how to download, set up, build, and run the latest development version from the sources. These instructions work in NetBeans IDE 6 or better.

Note: In the following, always replace “~ with the path to your home directory.


== Downloading the Sources

Check out the sources from the repository. (The following NetBeans instructions are equivalent to executing `cd ~/NetBeansProjects; svn checkout link:http://jmonkeyengine.googlecode.com/svn/branches/3.0final/engine[http://jmonkeyengine.googlecode.com/svn/branches/3.0final/engine] jme3` on the commandline.)

.  In NetBeans go to Team &gt; Subversion &gt; Checkout
..  Repository +++<abbr title="Uniform Resource Locator">URL</abbr>+++: `link:https://jmonkeyengine.googlecode.com/svn[https://jmonkeyengine.googlecode.com/svn]`
..  You can leave user/pw blank for anonymous access.

.  Click Next
..  Repository Folders: `branches/3.0final/engine`
..  Enable the checkbox to Skip “engine and only checkout its contents.
..  Local Folder: `~/NetBeansProjects/jme3`

.  Click Finish and wait.

The jme3 project opens in the Project window. It already includes a working ANT build script for building and running.

Look into the Libraries node and confirm that the project depends on the following libraries in the classpath:

*  j-ogg-oggd.jar
*  j-ogg-vorbisd.jar
*  jbullet.jar
*  stack-alloc.jar
*  vecmath.jar
*  lwjgl.jar
*  jME3-lwjgl-natives.jar
*  jinput.jar
*  eventbus.jar
*  nifty-default-controls.jar
*  nifty-examples.jar
*  nifty-style-black.jar
*  nifty.jar
*  jglfont-core.jar
*  xmlpull-xpp3.jar
*  android.jar
*  jME3-bullet-natives.jar
*  gluegen-rt.jar
*  joal.jar
*  jogl-all.jar
*  jME3-natives-joal.jar
*  jME3-openal-soft-natives-android.jar

For a detailed description of the separate jar files see <<jme3/jme3_source_structure#structure_of_jmonkeyengine3_jars,this list>>.


== Build the Project and Run a Sample App

.  Right-click the jme3 project node and “Clean and Build the project.
.  In the Projects window, open the `Test` folder which contains the sample apps.
.  Every file with a Main class (for example `jme3test.model/TestHoverTank.java` or `jme3test.game/CubeField.java`) is an app.
.  Right-click a sample app and choose “Run File (Shift-F6).
.  Generally in sample apps:
..  the mouse and the WASD keys control movement
..  the Esc key exits the application



== Optional: Javadoc Popups and Source Navigation in NetBeans

If you are working on the jme3 sources:

.  In the Projects window, right-click the jme3 project and choose Generate Javadoc. Wait.
.  Confirm in the Files window that the javadoc has been created in `~/NetBeansProjects/jme3/dist/javadoc`
.  In the editor, place the caret in a jme class and press ctrl-space to view javadoc.

If you are working on a game project that depends on jme3:

.  First follow the previous tip. (In the future, we may offer jme javadoc as download instead.)
.  In your game project, right-click the Libraries node and choose “Properties.
.  In the Library properties, select jme3.jar and click the Edit button.
..  For the Javadoc field, browse to `~/NetBeansProjects/jme3/dist/javadoc`. Check “as relative path and click select.
..  For the Sources field, browse to `~/NetBeansProjects/jme3/src`. Check “as relative path and click select.
..  Click OK.

.  In the editor, place the caret in a jme class and press ctrl-space to view javadoc. Ctrl-click any jme3 method to jump to its definition in the sources.

This tip works for any third-party JAR library that you use. (You may have to download the javadoc/sources from their home page separately).
'''

Sources used: link:http://code.google.com/p/jmonkeyengine/wiki/BuildJme3[BuildJme3], link:http://www.jmonkeyengine.com/forum/index.php?topic=13108.0[NetBeans tutorial from forum]
