= This is just notes at the moment
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../
:imagesdir: ../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Noting down Ouya stuff, will be turned into a proper doc later.

Installing Ouya drivers etc: 
link:https://devs.ouya.tv/developers/docs/setup[https://devs.ouya.tv/developers/docs/setup]

Note that you need to connect the USB to the micro USB port, not the full sized one!

Be aware that because the driver is unsigned it can be a real pain for windows to find it. You need to really persist until you get an android ADB Interface or similar. Windows tends to try and install it as an MTP USB Device instead - which will allow you to transfer files but not actually debug or run anything!

ADB Interface didn't work, had to use USB Composite. Google gives conflicting advice on this though so no idea if different people will find different. Key thing is to make sure the Ouya appears in adb devices.

Some helpful advice: link:http://ouyaforum.com/showthread.php?1425-Tutorial-Jmonkey-and-OUYA[http://ouyaforum.com/showthread.php?1425-Tutorial-Jmonkey-and-OUYA]

Need to download Ouya Dev Kit (ODK) from link:https://devs.ouya.tv/developers/odk[https://devs.ouya.tv/developers/odk]

Add the libraries from the download into the project.
