= "Which should I choose? jME2 or jME3?"
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:keywords: about
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


It is is one of the most common questions on the jME board, hence this wiki page is dedicated to answering it in full. For further insight on features, please refer to this <<compare-jme2-jme3#, comparison between jME2 and jME3>>.

If you are still not sure about your choice, we'll be happy to answer your questions on the forum. Many have asked before though, so please start out with a couple search terms like 'jme2 and jme3' and you might find that your question has been answered already.


== Why choose jME3?


=== Current- & next-generation graphics

From the beginning, jME3 was designed with modern principles and hardware in mind. Being shader based and only supporting OpenGL 2 or higher, jME3 is meant for the higher end of today's computers, and what's yet to come. OpenGL 1 support is limited to the basics of displaying textured models.


=== Actively developed

As opposed to it's legacy counterpart, jME3 is very actively developed by a team of core developers and a huge community of contributors. Any aspect of jME3 can be brought up for debate at any time.
P.S. The earlier you get involved the greater the chance you can have a changing impact on the project.


=== Ever-improving documentation

The majority of new docs created today are documentation for jMonkeyEngine3. While naturally part of a grand community effort, these docs benefit greatly from the added support and continued iteration by core team members.


=== jMonkeyEngine SDK

With jMonkeyEngine <<sdk#,SDK>>, jME3 is the first jME version with a dedicated IDE for application development, deployment, asset management and composition tools.


=== Broad Featureset

A major design goal for jME3 is “no game-dev essential left behind. Straight out of the box we aim to deliver all the basics you need to practically prototype any type of game: Physics, networking, terrain and so on, all bundled, but not forced. You can always replace any feature that doesn't match your game's requirement with a custom solution of your own making.


=== We'll be so happy to have you!

Naturally we are thrilled every time someone has decided to adopt jME3 for their [game-] development needs. Prospectively speaking, this means more testing, more commits, more buzz, more projects, more innovation; better community.


== Why choose jME2?


=== Stability right now

jME2 has been deemed stable since 2009, with no major feature additions or reworks since 2008. Although there are plans for a final point version release (2.1), jME2 is practically in complete feature freeze.


=== Support for low-end computers

jME2 fully supports OpenGL 1, while jME3 does not. Coupled with careful programming this means you can achieve very low hardware requirements for your project.


=== Community Tools

Well written utilities like SceneMonitor and SceneWorker greatly enrich the engine's toolset.


=== Thoroughly documented

There are literally hundreds of pages of documentation for jMonkeyEngine 2.0, detailing development practices with the engine from beginners' levels through intermediate to advanced. Do note however that as jME3 grows more popular this documentation will be maintained by the community alone (see 'Ever-improving documentation' in the jME3 section below).
