= jMonkeyEngine Documentation
:author:
:revnumber:
:revdate: 2016/03/17 20:48
:experimental:
:keywords: documentation, sdk, install
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


This documentation wiki contains installation and configuration guides, jME coding tutorials and other information that will help you get your game project going. You can search the contents of this wiki using the search box in the upper right.

You are also very welcome to fix mistakes or spelling as well as unclear paragraphs using the "`Wiki`" menu on top or the "`Edit`" buttons after each paragraph. You have to be logged in to edit the wiki.

TIP: This is an Admonition. You will see many of these scattered throughout the Wiki. See the <<wiki/admonitions#,Admonition Definitions>> for the meaning of this and all the other Admonitions.

== Install

*Before installing, check the <<bsd_license#,license>>, <<jme3/features#,features>>, and <<jme3/requirements#,requirements>>.* Then choose one of these options:
[cols="4", options="header"]
|===

a|
<a| Recommended
<a| Optional
<a| Optional

a| You want to…
a| Get started with jMonkeyEngine
a| Use jMonkeyEngine in another IDE
a| Build custom engine from sources

a| Then download…
a| link:https://github.com/jMonkeyEngine/sdk/releases[jMonkeyEngine SDK]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine/releases[Binaries]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine[Engine Sources]

a| You receive…
a| SDK, binaries, javadoc, sources
a| Binaries, javadoc, sources
a| Sources

a| Learn more here…
a|
* <<sdk#,Using the SDK>>
* <<sdk/project_creation#,Project Creation>>
a|
* <<jme3/maven#,Setting up jME3 with maven compatible IDEs>>
* <<jme3/setting_up_netbeans_and_jme3#,Setting up JME3 in the NetBeans IDE>>
* <<jme3/setting_up_jme3_in_eclipse#,Setting up JME3 in the Eclipse IDE>>
* <<jme3/eclipse_jme3_android_jnindk#,Setting up JME3 in the Eclipse IDE (with Android and/or JNI/NDK)>>
a|
* <<jme3/build_from_sources#,Building JME3 from the Sources>>
* <<jme3/build_jme3_sources_with_netbeans#,Building JME3 from the sources with NetBeans>>
* <<jme3/simpleapplication_from_the_commandline#,Setting up JME3 on the commandline>>
|===

pass:[*] The SDK creates Ant-based projects that any Java IDE can import. We recommend users of other IDEs to also download the jMonkeyEngine SDK and choose `menu:File[Import Project > External Project Assets]` to create a codeless project for managing assets only. This way you can code in the IDE of your choice, and use the SDK to convert your models to .j3o format.


== Create

After downloading and installing, <<jme3#,bookmark the jME Documentation page>> and start writing your first game!
[cols="3", options="header"]
|===

a| Tutorials
a| jMonkeyEngine SDK
a| Other Documentation

a| <<jme3#tutorials-for-beginners,jME3 beginner tutorials>>
a| <<sdk#,jMonkeyEngine SDK Documentation and Video Tutorials>>
a| link:http://javadoc.jmonkeyengine.org/[Full API JavaDoc]

a| <<jme3#documentation-for-intermediate-users,jME3 intermediate articles>>
a| <<sdk/comic#,jMonkeyEngine SDK - the Comic :-)>>
a| <<jme3/external/blender#,Blender Modeling Guide>>

a| <<jme3#documentation-for-advanced-users,jME3 advanced documentation>>
<a|
a| <<jme3/faq#,Answers to Frequently Asked Questions>>

|===


== Contribute

Are you an experienced Java developer who wants to add new features or contribute patches to the jME3 project?

*  Get inspired by existing <<jme3/contributions#,contributions>>
*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md[How to contribute to jMonkeyEngine]
*  link:https://github.com/jMonkeyEngine/wiki[Become a Wiki Editor]
*  link:http://hub.jmonkeyengine.org/c/contribution-depot-jme3[Chime in on the Contributors Forum]
*  <<jme3/jme3_source_structure#,Learn about the source structure>>
*  <<sdk#development,Write jMonkeyEngine SDK plugins and visual editors>>
*  <<report_bugs#,Report bugs and submit patches>>


== Contact

You are welcome to contribute and inquire about the project: Please contact the link:https://hub.jmonkeyengine.org/badges/103/core-developer[developers] or ask on the link:http://hub.jmonkeyengine.org/[forums].

*  link:https://hub.jmonkeyengine.org/badges/103/core-developer[Contact the jME team]
**  <<team#,[Core team - Who are we?]>>

*  <<report_bugs#,Report a bug>>
*  link:http://hub.jmonkeyengine.org/c/documentation-jme3[Report unclear or missing documentation]


== Languages

<<documentacao#,Documentação em Português>> +
<<documentation_zh#,中文版>>
