= jMonkeyEngine說明文件
:author:
:revnumber:
:revdate: 2016/03/17 20:48
:experimental:
:keywords: 說明文件，sdk，安裝
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


這個說明文件包含安裝及設定導引, jME 程式撰寫 教學 以及其他可以幫助你的遊戲專案繼續進行的資訊. 你可以在右上角的搜尋匡搜尋這個說明文件的內容

也非常歡迎你來修正錯誤或是拼字跟不清楚的文章一樣. 你需要登入來編輯.


== 安裝

*Before installing, check the <<bsd_license#,license>>, <<jme3/features#,features>>, and <<jme3/requirements#,requirements>>.* Then choose one of these options:
[cols="4", options="header"]
|===

a|
<a| 推薦
<a| 選項
<a| Optional

a| 你想要...
a| 直接開始使用 jMonkeyEngine
a| 在別的IDE中使用jMonkeyEngine
a| 由原始碼客製化引擎

a| 那要下載...
a| link:https://github.com/jMonkeyEngine/sdk/releases[jMonkeyEngine SDK]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine/releases[Binaries檔]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine[引擎原始碼]

a| 你會得到...
a| SDK, binaries, Java說明文件, 原始碼
a| Binaries,Java說明文件,原始碼
a| 原始碼 

a| 在這裡了解更多...
a|
* <<sdk#,使用SDK>>
* <<sdk/project_creation#,創建專案>>
a|
* <<jme3/maven#,在許多知名IDE設定JME3>>
* <<jme3/setting_up_netbeans_and_jme3#,在NetBeans IDE中設定JME3>>
* <<jme3/setting_up_jme3_in_eclipse#,在Eclipse IDE中設定JME3>>
* <<jme3/eclipse_jme3_android_jnindk#,在Eclipse IDE (與 Android 以及/或是 JNI/NDK) 中設定JME3>>
a|
* <<jme3/build_from_sources#,由原始碼建置JME3>>
* <<jme3/build_jme3_sources_with_netbeans#,用NetBeans由原始碼建置JME3>>
* <<jme3/simpleapplication_from_the_commandline#,在命令列設定JME3>>
|===

pass:[*] The SDK creates Ant-based projects that any Java IDE can import. We recommend users of other IDEs to also download the jMonkeyEngine SDK and choose `menu:File[Import Project > External Project Assets]` to create a codeless project for managing assets only. This way you can code in the IDE of your choice, and use the SDK to convert your models to .j3o format.


== 創造

After downloading and installing, <<jme3#,bookmark the jME Documentation page>> and start writing your first game!
[cols="3", options="header"]
|===

a| 教學
a| jMonkeyEngine SDK
a| 其他說明文件

a| <<jme3#tutorials-for-beginners,jME3 新手教學>>
a| <<sdk#,jMonkeyEngine SDK 說明文件以及教學影片>>
a| link:http://javadoc.jmonkeyengine.org/[完整API Java說明文件]

a| <<jme3#documentation-for-intermediate-users,jME3 中等 文章>>
a| <<sdk/comic#,jMonkeyEngine SDK - 漫畫 :-)>>
a| <<jme3/external/blender#,Blender建模指導>>

a| <<jme3#documentation-for-advanced-users,jME3 進階說明文件>>
<a|
a| <<jme3/faq#,常見問題的答案>>

|===


== 貢獻

請問你是資深的Java開發人員並且想要增加新功能或是貢獻到jME3計畫嗎?

*  Get inspired by existing <<jme3/contributions#,contributions>>
*  link:http://hub.jmonkeyengine.org/introduction/contributors-handbook/[閱讀 貢獻者手冊]
*  link:http://hub.jmonkeyengine.org/c/contribution-depot-jme3[在貢獻者論壇中的到幫助]
*  <<jme3/jme3_source_structure#,學習原始碼結構>>
*  <<sdk#development,撰寫 jMonkeyEngine SDK 外掛 and 視覺編輯器>>
*  <<report_bugs#,回報問題以及提交補丁>>


== 聯絡

You are welcome to contribute and inquire about the project: Please contact the link:https://hub.jmonkeyengine.org/badges/103/core-developer[developers] or ask on the link:http://hub.jmonkeyengine.org/[forums].

*  link:https://hub.jmonkeyengine.org/badges/103/core-developer[聯絡jME團隊]
**  <<team#,[主要團隊 - 我們是誰?]>>

*  <<report_bugs#,回報錯誤>>
*  link:http://hub.jmonkeyengine.org/c/documentation-jme3[回報不清楚以及失蹤的說明文件]


== 語言

<<документация#,Документация на Русском>> +
<<documentacao#,Documentação em Português>> +
<<documentation_zh#,中文版>>
