= How to report bugs against the jMonkeyEngine
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:keywords: contributor
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



[WARNING]
====
New issues should be reported against the link:https://github.com/jMonkeyEngine/jmonkeyengine/issues[GitHub issue tracker].  The entire jMonkeyEngine repository on link:https://code.google.com/p/jmonkeyengine/[Google Code] is deprecated as of March 2014.
====



Even if you cannot contribute patches and plugins, you can still help a lot by reporting bugs and helping us improve existing features.


To file a bug report, you must have a link:https://www.google.com/accounts/[google account]. If that’s something you are strongly opposed to, you may file a report by posting in our  link:http://www.jmonkeyengine.com/forum/index.php?board=30.0[ contribution depot for jME3], or link:http://www.jmonkeyengine.com/forum/index.php?board=28.0[ here for jME2]. We do highly prefer the GoogleCode issue tracker though.



== Filing a new issue to GoogleCode

.  Navigate to link:http://code.google.com/p/jmonkeyengine/issues/list[jMonkeyEngine’s issues list].
.  Carefully search through existing jME3 issues. Is your issue not listed? Please continue.
.  Press the `new issue` button in the top left corner, or use this direct link to link:http://code.google.com/p/jmonkeyengine/issues/entry[file a new issue].
.  Simply follow the instructions. Do not apply any new labels unless you know what you’re doing.

For more information, see: link:http://code.google.com/p/support/wiki/IssueTracker[http://code.google.com/p/support/wiki/IssueTracker]



== Filing a new issue in the ‘contribution depot’

You need a registered account on our forum to post a new thread.


*  link:http://hub.jmonkeyengine.org/c/contribution-depot-jme3[ jME3 Contribution Depot]
*  link:http://jmonkeyengine.org/groups/contribution-depot-jme2/forum/[ jME2 Contribution Depot] (currently broken link)

Please make a descriptive title for your post, and use the template below.



= Bug Report Template

*  What did you intend to do, what was the expected outcome?
*  What outcome do you experience instead?
*  What steps will reproduce the problem?
..  …
..  …
..  …

*  What version of the product(s) are you using? *Please copy build details from jMonkeyEngine's About Screen!*
*  On what operating system?
*  Please provide any additional information. (e.g. your hardware specs and Java version).
