= How to report bugs against the jMonkeyEngine
:author:
:revnumber:
:revdate: 2016/09/29 08:30
:keywords: contributor
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

Even if you cannot contribute patches and plugins, you can still help a lot by reporting bugs and helping us improve existing features.

To file a bug report, you must have a link:https://github.com/[github account]. If that’s something you are strongly opposed to, you may file a report by posting in our  link:https://hub.jmonkeyengine.org/[ forum for jME3]. We do highly prefer the Github issue tracker though.
Note that for troubleshooting, the forum is the preferred way.


== Filing a new issue to github

.  Navigate to link:https://github.com/jMonkeyEngine/jmonkeyengine/issues[jMonkeyEngine’s issues list].
.  Carefully search through existing jME3 issues. Is your issue not listed? Please continue.
.  Press the `new issue` button in the top right corner, or use this direct link to link:https://github.com/jMonkeyEngine/jmonkeyengine/issues/new[file a new issue].
.  Fill in the form using the bug report template bellow, and click on "Submit new issue" when you're done.


== Filing a new issue in the ‘contribution depot’

You need a registered account on link:https://hub.jmonkeyengine.org[our forum] to post a new thread.

*  Then go to link:https://hub.jmonkeyengine.org/c/contribution-depot-jme3[ jME3 Contribution Depot]

Please make a descriptive title for your post, and use the template below.


=== Bug Report Template

*  What did you intend to do, what was the expected outcome?
*  What outcome do you experience instead?
*  What steps will reproduce the problem?
..  …
..  …
..  …

*  What version of the product(s) are you using? *Please copy build details from jMonkeyEngine's About Screen!*
*  On what operating system?
*  Please provide any additional information. (e.g. your hardware specs and Java version).
