= managers
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../../
:imagesdir: ../../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== Atom framework's Managers

Read about the Manager idea here <<jme3/advanced/atom_framework/atomcore#,atomcore>>

Atom also have a lot of Managers. *Here suggestion for implemented one!*, you can call it a convention because it's not forced on you to gain more flexibility.

Manager can has SubManagers, as a List or a Map (Hierarchy or not is not forced)

Manager can be extended or Singleton or DefaultInstance (can be getDefault() but not a singleton) here and there. Manager all “attend” in a “cycle” but not “obey”. They can implement ICycle to mark they executor as Obey stricly to the Cycle.

you can do Main.getManager(Class) if your Main support it, or doing the long reference getManager().getSubManager().

You can see it as a hybrid or “no contract yet” – “not stricted to” way of implementing to get “best of both world” out of:

.  singleton vs default vs linked instance
.  hierarchy vs flatten component base
.  cycle attend vs a random routine.

In this implementation, I also try to have a good balance between flexibility and usefulness, clearance and performance. In the near future, when my framework is proved to be statable and useful, I will release it fully.
