= jMonkeyEngine 说明文档
:author: yanmaoyuan
:revnumber: 1.0
:revdate: 2018/01/15 16:41
:imagesdir: ../
:keywords: documentation, sdk, install
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


本wiki页面包含jME3的安装和配置指南、jME3编程教程以及其他一些能够帮助你开发游戏项目的资料，请善用本页右上方的搜索框来检索整个wiki中的内容。

TIP: This is an Admonition. You will see many of these scattered throughout the Wiki. See the <<wiki/admonitions#,Admonition Definitions>> for the meaning of this and all the other Admonitions.

== 下载和安装

*在安装之前，请查阅<<bsd_license#,许可证>>、<<jme3/features#,jME3功能说明>>和<<install/requirements#,开发需求>>，* 然后选择其中一个选项：
[cols="4", options="header"]
|===

a|
<a| 推荐
<a| 可选
<a| 可选

a| 你打算…
a| 使用jMonkeyEngine SDK开发
a| 在其他的IDE中使用jMonkeyEngine
a| 利用源码来编译自定义引擎

a| 请下载…
a| link:https://github.com/jMonkeyEngine/sdk/releases/tag/stable[jMonkeyEngine SDK]
a| link:https://github.com/jMonkeyEngine/sdk/releases[Binaries]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine[Sources]

a| 你会得到…
a| Sources, binaries, javadoc, SDK
a| Latest stable binary build, sources, javadoc.
a| Sources

a| 更多学习内容…
a| * <<sdk/index#,学习使用SDK>> +
* <<sdk/create_project#,使用SDK创建工程>> +

a| 在下列环境中集成JME3： +

* <<getting-start/gradle#,Gradle>> +
* <<getting-start/maven#,Maven>> +
* <<getting-start/netbeans#,NetBeans>> +
* <<getting-start/eclipse#, Eclipse>> +
* <<getting-start/android_studio#,Android Studio>> +
* <<getting-start/intellij_idea#,Intellij IDEA>>
a| * <<install/build_from_sources#,编译JME3源码>> +
* <<jme3/build_jme3_sources_with_netbeans#,在NetBeans中编译JME3源码>> +
* <<jme3/simpleapplication_from_the_commandline#,在(Linux)命令行下开发JME3>>

|===

(*) jME SDK创建的是基于Ant的项目，任何Java IDE都可以导入。我们建议其他IDE的用户也下载jME SDK，并选择 “File→Import Project→External Project Assets 来创建一个不包含任何代码的资源项目，用以管理项目中的资源文件(如模型、材质、贴图等)。这样您就可以在自己选择的IDE中编码，并利用jME SDK来将您的模型转换成.j3o格式。


== 创建jME工程

下载安装jME之后，请把这个<<jme3,jME教程>>加入您的书签，然后动手开发您的第一个游戏吧！
[cols="3", options="header"]
|===

a| 教程
a| jMonkeyEngine SDK
a| 其他文档

a| <<jme3/beginners/index#,jME3初级教程>>
a| <<sdk/index#,jMonkeyEngine SDK 文档和视频教程>>
a| link:http://javadoc.jmonkeyengine.org/[Full API JavaDoc]

a| <<jme3/advanced/index#,jME3中级教程>>
a| <<sdk/comic#,jMonkeyEngine SDK - 漫画 :-)>>
a| <<jme3/external/blender#,Blender建模指南>>

a| <<jme3/senior/index#,jME3进阶教程>>
<a|
a| <<jme3/faq#,FAQ>>

|===


== 贡献代码

想给jME3贡献新的特性和功能吗？如果你是一名熟练的Java开发者，请看下列页面：

*  了解已有的<<jme3/contributions#,贡献>>
*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md[阅读贡献者手册]
*  link:https://github.com/jMonkeyEngine/wiki[成为维基编辑者]
*  link:http://hub.jmonkeyengine.org/c/contribution-depot-jme3[加入官方社区的讨论]
*  <<jme3/jme3_source_structure#,学习jME3源码架构>>
*  <<sdk#development,开发jME SDK插件以及可视化编辑器>>
*  <<report_bugs#,报告bug &amp; 提交补丁>>

== 联系我们

欢迎您的贡献和咨询：请联系 link:https://hub.jmonkeyengine.org/badges/103/core-developer[开发者]，或者在 link:http://hub.jmonkeyengine.org/[官方论坛]发帖提问。

* link:https://hub.jmonkeyengine.org/badges/103/core-developer[联系JME3开发团队]
**  <<team#,[核心团队 - 我们是谁？]>>

*  <<report_bugs#,报告BUG>>
*  link:http://hub.jmonkeyengine.org/c/documentation-jme3[发现文档内容含糊或文档不存在]

== 中文开发者讨论群

本群不是jME的官方QQ群，而是由一群国内的jME爱好者聚集的讨论群，欢迎加入讨论，群号：423979787。

中文网站： http://www.jmecn.net/
