= jMonkeyEngine Documentation
:revnumber: 2.0
:revdate: 2020/07/12
:keywords: documentation, sdk, install


This documentation wiki contains installation and configuration guides, jME coding tutorials and other information that will help you get your game project going. You can search the contents of this wiki using the "`Wiki`" menu search box at the top of each page.

You are also very welcome to fix mistakes or spelling as well as unclear paragraphs using the "`Edit this Page`" link. You have to be logged into GitHub to edit the wiki. You can learn more about editing and contributing under the <<Contribute,Contribute>> heading.

TIP: This is an Admonition. You will see many of these scattered throughout the Wiki. See the xref:wiki:admonitions.adoc[Admonition Definitions] for the meaning of this and all the other Admonitions.

== Forum

The link:http://hub.jmonkeyengine.org/[forum] is your first stop when reporting bugs, making contributions, discussing wiki content, or anything else that you can't get the answer for by reading the wiki or searching the forum archives. You will find it to be a friendly and inviting place to have discussions, but before posting, there are two minor rules you will need to observe.

.  For questions that include code, learn link:https://hub.jmonkeyengine.org/t/how-to-type-code-blocks/31155[how to use code blocks]. If you fail to do so, you will at best be reminded of your lapse in judgment and may not receive an answer to your question at all otherwise. See the <<github_tips#,Github Tips>> page for info on how to insert links into your posts.
.  link:https://hub.jmonkeyengine.org/t/uploading-pictures-and-changing-avatars-is-disabled/39520[Uploading pictures is disabled] with the exception of a 50k disk space allowance for a forum avatar.


== Install

Before installing, check the xref:bsd_license.adoc[license], xref:jme3/features.adoc[features], and xref:jme3/requirements.adoc[requirements]. Then choose one of these options:
[cols="4", options="header"]
|===

a|
<a| Recommended
<a| Optional
<a| Optional

a| You want to…
a| Get started with jMonkeyEngine
a| Use jMonkeyEngine in another IDE
a| Build custom engine from sources

a| Then download…
a| link:https://github.com/jMonkeyEngine/sdk/releases[jMonkeyEngine SDK]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine/releases[Binaries]
a| link:https://github.com/jMonkeyEngine/jmonkeyengine[Engine Sources]

a| You receive…
a| SDK, binaries, javadoc, sources
a| Binaries, javadoc, sources
a| Sources

a| Learn more here…
a|
* xref:sdk:sdk.adoc[Using the SDK]
* xref:sdk:project_creation.adoc[Project Creation]
a|
* xref:jme3/maven.adoc[Setting up jME3 with Maven and Gradle compatible IDEs]
* xref:jme3/setting_up_netbeans_and_jme3.adoc[Setting up JME3 in the NetBeans IDE]
* xref:jme3/setting_up_jme3_in_eclipse.adoc[Setting up JME3 in the Eclipse IDE]
a|
* xref:jme3/build_from_sources.adoc[Building JME3 from the Sources]
* xref:jme3/build_jme3_sources_with_netbeans.adoc[Building JME3 from the sources with NetBeans]
* xref:jme3/simpleapplication_from_the_commandline.adoc[Setting up JME3 on the commandline]

4+^a| xref:jme3/jme3_source_structure.adoc[Learn about the source structure]

|===

pass:[*] The SDK creates Ant-based projects that any Java IDE can import. We recommend users of other IDEs to also download the jMonkeyEngine SDK and choose `menu:File[Import Project > External Project Assets]` to create a codeless project for managing assets only. This way you can code in the IDE of your choice, and use the SDK to convert your models to .j3o format.


== Create

After downloading and installing, xref:documentation.adoc[bookmark this page], and start writing your first game!
[cols="3", options="header"]
|===

a| Tutorials
a| jMonkeyEngine SDK
a| Other Documentation

a| xref:tutorials:beginner/beginner.adoc[jME3 beginner tutorials]
a| xref:sdk:sdk.adoc[jMonkeyEngine SDK Documentation and Video Tutorials]
a| link:{link-javadoc}[Full API JavaDoc]

a| <<jme3.adoc#documentation-for-intermediate-users,jME3 intermediate articles>>
a| xref:sdk:comic.adoc[jMonkeyEngine SDK - the Comic :-)]
a| xref:jme3/external/blender.adoc[Blender Modeling Guide]

a| <<jme3.adoc#documentation-for-advanced-users,jME3 advanced documentation>>
<a|
a| xref:jme3/faq.adoc[Answers to Frequently Asked Questions]

|===


== Contribute

Are you an experienced Java developer who wants to add new features or contribute patches to the jME3 project?

*  Get inspired by existing xref:jme3/contributions.adoc[contributions]
*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/CONTRIBUTING.md[How to contribute to jMonkeyEngine]
*  link:https://github.com/jMonkeyEngine/wiki#jmonkeyengine-documentation[Become a Wiki Editor]
*  link:http://hub.jmonkeyengine.org/c/contribution-depot-jme3[Chime in on the Contributors Forum]
*  xref:sdk:development.adoc[Write jMonkeyEngine SDK plugins and visual editors]
*  xref:report_bugs.adoc[Report bugs and submit patches]
* link:https://jmonkeystore.com/[Find assets on the community supported jMonkeyStore]
* link:https://hub.jmonkeyengine.org/c/documentation-jme3/24[Report unclear or missing documentation]

== Contact

You are welcome to contribute and inquire about the project: Please contact the link:https://hub.jmonkeyengine.org/badges/103/core-developer[developers] or ask on the link:https://hub.jmonkeyengine.org[forums].

*  link:https://hub.jmonkeyengine.org/badges/103/core-developer[Contact the jME team]
**  xref:team.adoc[Core team - Who are we?]

== Languages

The team is looking for other monkeys that would be interested in a wiki translation of [insert your favorite language here]. If you're interested in hosting translations see xref:wiki:wiki_translation.adoc[Wiki Translation Repositories].

link:http://www.jmecn.net/wiki/[简体中文]
