= 安装 jMonkeyEngine3
:author: yanmaoyuan
:revnumber: 1.0
:revdate: 2018/01/15 16:29
:keywords:
ifdef::env-github,env-browser[:outfilesuffix: .adoc]

jMonkeyEngine3(简称jME3) 是一款纯Java开发的开源3D游戏引擎。它的核心是一套模块化的Java类库，同时还为提供了名为 `jMonkenEngine3 SDK` 的集成开发环境。

本文将介绍如何下载、安装 jMonkeyEngine3。

== 开发需求

jME3 是一个3D游戏引擎，这意味着开发者和用户都需要性能足够好的CPU和GPU。

详细： link:requirements.html[jMonkeyEngine开发需求]

== jMonkeyEngine3

jME3 本质上是一个第三方Java类库，它的本体是一套 jar 文件。只需要在Java/Android项目中引用这些 jar文件，就可以开发3D游戏。jME3 基于模块法开发，用户可以根据需要来使用这些 jar 文件的一个子集。也就是说，你不需要全部的 jar 文件，就可以用 jME3 来开发3D程序。

jME3 下载地址： https://github.com/jMonkeyEngine/jmonkeyengine/releases

更多内容，请查阅：link:engine.html[jME3 简介]

== jMonkeyEngine3 SDK

jMonkeyEngine3 SDK(简称SDK) 是基于 NetBeans 平台开发的 jME3 集成开发环境(IDE)。SDK 包含地形制作、预览3D模型、材质编辑器、粒子编辑器等诸多可视化开发功能。

SDK 下载地址： https://github.com/jMonkeyEngine/sdk/releases

更多内容，请查阅： link:sdk.html[SDK 简介]

== 源代码

jMonkeyEngine3 的源代码托管于 github.com，你可以通过下面的链接找到它的全部源代码。

https://github.com/jMonkeyEngine/jmonkeyengine

jMonkeyEngine3 还有大量用户贡献源代码，可以通过下面的连接找到他们。

https://github.com/jMonkeyEngine-Contributions/

更多内容，请查阅： link:source_code.html[jME3 源代码]

== 许可证

jMonkeyEngine3 遵循 BSD 许可证，这意味着你几乎可以用它做任何事情，包括开发商业游戏。

许可证： link:../../bsd_license.html[BSD_LICENSE]