= Introduction
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


The current front page needs replacing, due to its jME2-oriented layout. At this point, considering jME3's maturity, the opening page of the wiki should achieve the following:

*  Explain briefly, but in more exact detail than the home index, what jME (jME2, jME3 &amp; jMP + project) is, and provide links for further reading.
*  Expose the key differences between jME2 and jME3; links for further reading.
*  jMP in a nutshell
*  jME3 in a nutshell
*  jME2 in a nutshell

The jMonkey Engine framework (jME) is a high-performance, 3D scenegraph based graphics +++<abbr title="Application Programming Interface">API</abbr>+++, written in Java. It supports both LWJGL and JOGL OpenGL rendering systems. jME is completely open-source under the BSD license and you are free to use it in anyway you see fit, be it hobby or commercial. The current stable version is jME2. However thanks to high development standards, jME3 Alpha is on the brink of being stable enough for production use, and is already experiencing wide adoption.


== Choosing the right branch

*  Choosing between jME2 and jME3
*  Comparing jME2 and jME3
*  jME2 Exhaustive Features
*  jME3 Exhaustive Features

&lt;box 45% left round #fc9&gt;jMonkeyEngine 2.0&lt;/box&gt;&lt;box 45% right round #fc9&gt;jMonkeyEngine 3.0&lt;/box&gt;
