= detailed
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../../
:imagesdir: ../../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== Detailed


=== General


==== GamePlayer

....
  Name
  Avatar
  Infos
....

Ex: 


=== League


==== Football League

....
  Country
  Champion ship
  History
  List of rounds and matches
....

Ex:


==== Football Club

....
  Name
  Owner (GamePlayer)
  Stadium
  Team ( of Football Players)
  Logo
  Shirt
....

Ex:


==== Football Player

....
  Name, Infos
  Career path, history
  SkillInfos
  Training statistics
....

Ex:


=== FootballMatch gameplay


==== Football Match

....
  TwoTeams
  Refere
  Stadium
  TwoCoachs
  Time and Leage
  Commentor
  Result
  Game actions (for replay)
....


==== FootballPlayer Control

....
  Like ProEvolution Soccer
....


=== Coach gameplay


==== Football Coach

....
  Positions
  Stragegies
  Team start position for a Match
  Training schedule
....


==== Traning course

....
  List of exercices
  Traning Result
....


=== Manager gameplay


==== Football player transactions

....
  Buy
  Sell
  Loan
  Search
....


==== Staffs management

....
  Recruit
  Dismiss
....


==== Construction

....
  Build
  Destruct
....


==== Shop

....
  Products
....


==== Media

....
  Advertisments
  Newspaper
  Stadium ads
....


==== Business

....
  Contract
  Emails
  Reports
....


==== Statistics

....
  Review numbers
  History
....


=== Other gameplay


==== Character Customization

....
  Head
  Body
  Clothes design
  
....


==== Construction

....
  Place building
  Build stuffs
....

<<jme3/atomixtuts/kickgame/gameplay#,gameplay>>
