= Entity System Zay-ES
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../
:imagesdir: ../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


Entity Systems are a new way of organising your game data.

The basic idea comes from the famous t-machine article about entity systems as a possibility for mmorpg development.
Zay-ES is pspeed's Entity System which he uses for his game Mythruna.
Entity Systems aim to make your project more clear and dynamic.


== Entity System Introduction

If you are new to this topic you should read:

<<jme3/contributions/entitysystem/introduction#,Entity System Introduction>>

*Read this if you want to look carefully at the design of a general ES and compare between different projects.*

<<jme3/contributions/entitysystem/detailed#,Entity System Detailed>>

<<jme3/contributions/entitysystem/interviews#,Entity System Approaches and Interviews>>


== Zay-ES Tutorials

*  link:https://github.com/jMonkeyEngine-Contributions/zay-es/wiki[Official Zay ES Wiki]
*  <<jme3/contributions/entitysystem/beginner#,Zay-ES Beginner>>
*  <<jme3/contributions/entitysystem/entityset#,The EntitySet>>
*  AppStates/Filter
*  Zay-ES and SQL


== Zay-ES Examples

In the future, more examples will be added to help with solving problems the Entity System way.

*  <<jme3/contributions/entitysystem/examples/damagesystem#,Making a Damage System>>
*  <<jme3/contributions/entitysystem/examples/own_logic_thread#,Your Own Logic Thread>>


== Zay-ES Forum

A lot of very up-to-date information on the Zay-ES entity system can be found on the jME3 Forum.  There are example projects, example code, and a lot of general help.

*  link:http://hub.jmonkeyengine.org/c/user-code-projects/zay-es[ Zay-ES forum]


== Zay-ES Download

Zay-ES can be downloaded via SVN from link:https://github.com/jMonkeyEngine-Contributions/zay-es[https://github.com/jMonkeyEngine-Contributions/zay-es]

It also now available as a jMonkey SDK plugin.
