

= jMonkeyEngine3 Поддерживаемые Типы Файлов


== jMonkeyEngine3 Форматы Файлов
[cols="3", options="header"]
|===

a|Расширение
a|Использование
a|Узнать больше

a|.j3o
a|Бинарные 3D модели или сцены. На последние бета-версии вашей игры, вы должны преобразовать все модели .j3o формат. +
Во время альфа-и более ранних этапов разработки (когда в модели вы планируете еще многое изменить), в качестве альтернативы можно загружать OgreXML/OBJ модели прямо в папку.
a|<<sdk/model_loader_and_viewer#,Модель Загрузка и Просмотр>> 

a|.j3m
a|Пользовательский Материал. Вы можете создать .j3m-файла для сохранения конфигурации материала для геометрии (например, 3D-модели).
a|<<jme3/advanced/materials_overview#,Materials Overview>> +
<<sdk/material_editing#,Material Editing>> 

a|.j3md
a|Описание Материала. Это предопределенно описанные шаблоны для шейдеров на основе материалов. +
Каждый пользовательский .j3m Материал основан на описании материала. Продвинутые пользователи могут создавать свои собственные описания материала. 
a| <<jme3/advanced/materials_overview#,Materials Overview>> 

a|.j3f
a|Пользовательские post-processor конфигурации фильтра. Вы можете создавать .j3f файл для сохранения FilterPostProcessor с набором предварительно настроенных фильтров 
a| <<sdk/filters#,Filters>> +
<<jme3/advanced/effects_overview#,Effects Overview>> 

|===


== Поддерживаемые Внешние Типы Файлов
[cols="3", options="header"]
|===

a|Расширение файла
a|Тип
a|Описание

a|.mesh.xml, .meshxml
a|3D model
a|Ogre Mesh XML 

a|.scene
a|3D scene
a|Ogre DotScene 

a|.OBJ, .MTL
a|3D model
a|Wavefront

a|.blend
a|3D model
a|Blender версии 2.49 и далее (протестировано до 2.65)

a|COLLADA
a| 3D model
a|Импортированные из Blender в комплекте с SDK

a|3DS
a|3D model
a|Импортированные из Blender в комплекте с SDK

|===
[cols="3", options="header"]
|===

a|.JPG, .PNG, .GIF
a|image
a|Textures, icons

a|.DDS
a|image
a|Direct Draw Surface texture

a|.HDR
a|image
a|High Dynamic Range texture

a|.TGA
a|image
a|Targa Image File texture

a|.PFM
a|image
a|Portable Float Map texture

a|.fnt
a|bitmap font
a|AngelCode шрифт для +++<abbr title="Graphical User Interface">GUI</abbr>+++ и HUD

a|.WAV
a|audio
a|Wave музыка и звуки

a|.OGG
a|audio
a|OGG Vorbis музыка и звуки

|===
