= jMonkeyEngine SDK: Assetbrowser
:revnumber: 1.0
:revdate: 2023/09/16
:keywords: documentation, sdk, assets, assetbrowser

The assetbrowser is a part of WYSIWYG. It aims to show a miniature of all assets in a project, and supports drag and drop to many of the components and editors in the SDk.

== How to use it

When it's first loaded, you will see a box that says "No project selected". This is because Netbeans, as opposed to many other IDE's can have many projects open at once.
The Assetbrowser doesn't know which you will be working on, so you need to choose it.
Once done, it will be populated with the assets inside the /assets folder.

* Double clicking a Texture will open the Texture Editor
* Double clicking a Material will open the Material Editor
* Double clicking a Spatial will open the Scene Composer

* You can drag and drop a Texture from the Assetbrowser to a Texture slot in the Material Editor
* You can drag and drop a Material from the Assetbrowser to a Spatial in the SceneComposer to set that Material.
* You can drag and drop a Spatial from the Assetbrowser to the SceneComposer to place it. It will ray cast and place it roughly where it hits something.


== Clearing cache

If you for some reason want to remove all the thumbnails, you can find them in a folder called .assetbrowser in the root of the project. It is safe to delete the folder.

