= build_platform
:revnumber: 2.0
:revdate: 2020/07/10
:keywords: documentation, sdk, builds, project


== Building jMonkeyEngine SDK Yourself


=== In the jMonkeyEngine SDK or NetBeans


==== Plugins

Make sure all necessary plugins are installed and active:

*  From the menu bar, select `Tools` → `Plugins` to open a `Plugins` dialog.
*  Select the `Available Plugins` tab.
*  Sort the plugin list by category.
*  Check the `Install` checkbox for any plugins in the `Developing NetBeans` category.
*  Click on the `Install` button and complete the wizard.
*  Select the `Installed` tab.
*  Activate any inactive plugins in the `Developing NetBeans` category.
*  Close the `Plugins` dialog.


==== Checkout

*  From the menu bar, select `Team` → `Git` → `Clone` to open a `Clone Repository` dialog.
*  In the `Repository +++<abbr title="Uniform Resource Locator">URL</abbr>+++:` textbox, type `link:https://github.com/jMonkeyEngine/jmonkeyengine[https://github.com/jMonkeyEngine/jmonkeyengine]`.
*  Clear the `User:` and `Password:` textboxes.
*  Click on the `Next` button.
*  Choose the remote branch, typically "`master`", and click the Next button.
*  Click on the `Browse…` button to the right of the `Parent directory:` textbox to open a `Browse Local Folder` dialog.
*  Select an empty or non-existent directory (folder) where you want to save the jMonkeyEngine sources on your hard drive.
*  Click the `Finish` button.

Project checkout may take awhile.  Do not proceed before the task is complete.


==== Build

On the commandline:

.  `cd jmonkeyengine`
.  `./gradlew build`

From the SDK:

*  From the menu bar, select `File` → `Open project…` to open an `Open Project` dialog.
*  Highlight the free-form project folder you used for checkout and click on the `Open Project` button.
**  A new free-form project named `jME3-SDK` should appear in the SDK's `Projects` window.

*  Build the free-form project by right-clicking on it and selecting `Build`.
*  Wait until the `jME3-SDK (build)` task is complete.  At one point, a web browser window may open.
*  From the menu bar, select `File` → `Open project…` to open an `Open Project` dialog.
*  Browse into the free-form project folder, highlight the `sdk` node, and click on the `Open Project` button.
**  A number of new projects should appear in the SDK's `Projects` window.


Building the main freeform project copies the jME3 libraries to the sdk, so you should run its build script each time jME3 changes.


==== Run

*  In the SDK's `Projects` window, right-click on the `jMonkeyEngine SDK` project and select `Run`.
**  The SDK you just built will start executing in a new window.
