= update_center
:revnumber:2.0
:revdate: 2020/07/09
:keywords: documentation, sdk, builds, update



== Automatically Updating jMonkeyEngine SDK


=== Getting stable updates

The jMonkeyEngine SDK includes an automatic web update feature. To run an update, simply go to Help→Check for Updates and you will get the most current stable update of the SDK and the engine. By default the IDE will check every week for new updates and inform you about them with a symbol in the lower right.


=== Testing the nightly version

You can test the nightly version with all the latest untested features to give feedback to the developers. Be warned however, the changes in the nightly versions might break your current game project if heavy changes have been committed. To make sure that you do not break your current development environment it is recommended to use a separate application and settings directory for the nightly version.

*  Copy the whole application (folder) to a new name like jmonkeyplatform_nightly.
*  Edit the file jmonkeyplatform.conf in the etc directory of the folder. Mac users have to right-click the application and select "`Show`" package contents and then navigate to Contents/Resources/jmonkeyplatform.
*  Change the default_userdir or default_mac_userdir from "`$pass:[{]HOME}/.$pass:[{]APPNAME}/version`" to something like "`$pass:[{]HOME}/.$pass:[{]APPNAME}/nightly`".

Then start the new application and have your SDK being updated to the most current nightly version:

*  Go to Tools→Plugins
*  Select the "`Settings`" tab
  *  Select the checkbox for "`jMonkeyEngine SDK`" nightly svn
*  Make sure the "`force install to shared directories`" checkbox is selected
*  Select the "`Updates`" tab
*  Press "`Reload Catalog`"
*  Press "`Update`"
