= Why not Eclipse?
:revnumber:2.0
:revdate: 2020/07/09


The jMonkeyEngine's default IDE (xref:sdk/what_s_an_ide.adoc[Integrated Development Environment]) bases on the link:http://platform.netbeans.org[NetBeans RCP (Rich Client Platform)]. There is a RCP for Eclipse too, so why don't we use Eclipse as IDE for jMonkey? Well, there's several reasons:

.  Eclipse uses a proprietary +++<abbr title="Graphical User Interface">GUI</abbr>+++ system (SWT), NetBeans uses the Java-default AWT implementation for which a high-performance canvas display exists in LWJGL/jME3. AWT compatibility allowed e.g. integration of plugins like NeoTexture.
.  Eclipse projects are proprietary and they can not be opened without Eclipse. The NetBeans Platform uses the ANT standard which works outside the IDE as well, and can be extended by other build processes that use ANT (e.g. Android deployment). Furthermore, Eclipse can open projects generated by the NetBeans-based jMonkeyEngine SDK if needed.
.  There is no way to extend Eclipse projects properly as there is no global concept of a “Project in the RCP.
.  Eclipse RCP does not offer a Nodes +++<abbr title="Application Programming Interface">API</abbr>+++ that allows easy wrapping of the SceneGraph into a visual representation.
.  Eclipse RCP only has commercial +++<abbr title="Graphical User Interface">GUI</abbr>+++ editors, NetBeans comes with a free AWT +++<abbr title="Graphical User Interface">GUI</abbr>+++ editor for designing plugins.
.  The two Platforms are the same feature-wise.
.  The core jME3 developers use NetBeans IDE.


[TIP]
====
If you come from another IDE and want to try jMonkeyEngine SDK, you can easily set up the keyboard shortcut mappings to resemble the configuration you are used to. Profiles exist for Eclipse, IntelliJ and others. Just go to `Settings → Keymap` and select one of the existing profiles.
====
