= beans
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../../
:imagesdir: ../../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== Atom framework's Beans


=== Technologies

Bean is nothing new in Java, actually is … (a long story) plain old :)
What Atom'sBeans try to do is similar to EJB without its complexility. Because we have to use it in real-time enviroment, we have to make its fast and have high through put performance.

*  Bean binding : reactive binding with generated functions like 2-way mapping below
*  Bean mapping / morphing : bytecode generation (or reflection) for mapping and interpolating, remote syncing 
*  Bean modelling : code generation directly from java-java, java-xml, java-html
*  Bean generation : bytecode generation with conventions, specifications, configurations to make Java's Object's bytecode cross platform as data
*  Distributed bean: distributed bean with RPC and syncing

The most different between this bean frameworks and others is it stand in J2SE specification and make bean related job really easy as it should! See to believe.


=== Components


=== AtomBean


=== Bean binding


=== Bean mapping / morphing


=== Bean modeling


=== Bean generation


=== Distributed Bean
