= Application Template
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:keywords: gsoc
:relfileprefix: ../
:imagesdir: ..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


(Courtesy of Blender.org; link:http://wiki.blender.org/index.php/Dev:Ref/GSoC/2010/Application_Template[http://wiki.blender.org/index.php/Dev:Ref/GSoC/2010/Application_Template])


== Name

Please provide your full name.


== Email / IRC / WWW

Where can we contact you? If you frequent our +++<abbr title="Internet Relay Chat">IRC</abbr>+++ channel (#jme on irc.freenode.net) please let us know what your nick is. If you have a web page you'd like us to know about, please include it.


== Synopsis

A short description of your planned SoC project


== Benefits to jME

Describe how your project will benefit jME. Will it enhance some graphics functionality? Lower the entry barrier? Simplify a common procedure?


== Deliverables

Provide a user-level summary of the final output or results of your project. How does it integrate in jME, and how does it cooperate with the rest of jME's features? Note that end-user documentation should be one of the deliverables as well.


== Project Details

A more detailed description.


== Project Schedule

How long will the project take? When can you begin work?
Include an estimated timeline of the project with mini-milestones
Please also note any vacation time you expect to take during the project period.
Do you have any possible school or work conflicts with your schedule?


== Bio

Who are you, what are you studying (and where), and what activities do you enjoy? What is your experience using jME or other computer graphics programs? What (3D) code development projects have you realized? What makes you the best person to work on this project? If you have any history contributing to jME or otherwise advocating the project, please describe your efforts.
+
+
Send your application to mailto:&#x63;&#x6f;&#x6e;&#x74;&#x61;&#x63;&#x74;&#x40;&#x6a;&#x6d;&#x6f;&#x6e;&#x6b;&#x65;&#x79;&#x65;&#x6e;&#x67;&#x69;&#x6e;&#x65;&#x2e;&#x63;&#x6f;&#x6d;[]
+
+
_Thank you for applying!_
