

= Модели и сцены

Английская версия: <<jme3/advanced/3d_models#,3D Models>>


Так же как и <<фигура#,фигура>>, 3D-модели тоже состоит из <<сетки#,Сетки>>, но модели являются более сложными, чем фигуры. В то время как фигуры встроены в jME3, модели вы, как правило, создаете во внешнем редакторе 3D-сетки.



== Использование моделей и сцен с jME3

Использование 3D-моделей в jME3 приложения:


.  Экспортировать 3D-модели в формате Ogre XML или Wavefront OBJ. Экспорт сцен, в формате Ogre DotScene.
.  Сохраните файлы в подкаталог вашего jME3 проекта в папке `assets`.
.  В вашем коде вы используете <<asset_manager#,Asset Manager>> для загрузки моделей в качестве<<spatial#,Spatial>>s в приложения jME. 
[source,java]

----
Spatial model = assetManager.loadModel(
    "Models/MonkeyHead/MonkeyHead.mesh.xml" );
----

.  (Для сборки релиза:) используйте jMonkeyEngine SDK для преобразования моделей в формат .j3o . Вам не нужен этот шаг, пока вам предстоит еще долго разрабатывать и тестировать приложения в jMonkeyEngine SDK.


== Создание Моделей и сцен

Для создания 3D-моделей и сцен, вам нужен 3D Mesh Editor например link:http://www.blender.org/[Blender], с OgreXML Exporter plugin. 


*Совет:* Узнайте, как создать link:http://en.wikibooks.org/wiki/Blender_3D:_Noob_to_Pro/UV_Map_Basics[UV textures] для более сложных моделей, это выглядит более профессионально.


Редакторы 3D моделей сторонние продукты, поэтому, пожалуйста, просмотрите их документацию и инструкции, как использовать их. Вот пример рабочего процесса для пользователей Blender:


*  <<jme3/external/blender#,Создание jME3 совместимой 3D модели в Blender>>

Для экспорта моделей, как Ogre XML сеток с материалами:


.  Open the menu File &gt; Export &gt; OgreXML Exporter to open the exporter dialog.
.  In the Export Materials field: Give the material the same name as the model. For example, the model `something.mesh.xml` goes with `something.material`, plus (optionally) `something.skeleton.xml`, and some JPG files.
.  In the Export Meshes field: Select a target subdirectory of your `assets/Models/` directory. E.g. `assets/Models/something/`.
.  Activate the following exporter settings: 
**  Copy Textures: YES
**  Rendering Materials: YES
**  Flip Axis: YES
**  Require Materials: YES
**  Skeleton name follows mesh: YES

.  Click export.

Теперь вы можете использовать <<sdk#,jMonkeyEngine SDK>> <<sdk/model_loader_and_viewer#,загрузку и просмотр моделей>>. Вы можете <<sdk/scene_composer#,создать сцену>> от них и написать код, который загружает их в ваше приложение.

