= Emoji and Icons
:author: mitm
:revnumber: 2.0

== How to use icons in the wiki

[IMPORTANT]
====
Icons are currently not supported by the Antora backend. They will be available in the near future so the Icon  section will remain.
====


You can use any font awesome icon listed at link:https://fontawesome.com/v4.7.0/icons/[https://fontawesome.com/v4.7.0/icons/] in your wiki documents by use of the icon macro.

.Syntax for inserting icons
```
icon:thumbs-up[]
icon:database[role=green] // change color by use of the role syntax
icon:heart[2x] // icons can be sized
icon:shield[rotate=90, flip=vertical] // rotate and flip
```

[TIP]
====
When setting the icons name, you do not have to preface it with `fa-`, asciidoctor will accept the font name.
====

The icon macro has three attributes you can set, they are size, rotate, and flip.

* size +
** The first positional attribute found, scales the icon; values are: `1x` (default), `2x`, `3x`, `4x`, `5x`, `lg`, `fw`
** You can fix the width of the icon by use of the `fw` attribute. This helps when trying to align with other elements by giving the icon a fixed width.
* rotate
** Rotates the icon; values are: `90`, `180`, `270`
* flip
** Flips the icon; values are: `horizontal`, `vertical`

The first unnamed attribute is assumed to be the size. For instance, to make the icon twice the size as the default, simply add 2x inside the square brackets.

```
icon:heart[2x]
```
Results:

icon:heart[] 2x icon:heart[2x]

To rotate and flip the icon:
```
icon:shield[rotate=270, flip=vertical]
```
Results:

icon:shield[] rotated 90, and flipped vertical icon:shield[rotate=90, flip=vertical]

You can also link to icons.
```
icon:download[link="https://rubygems.org/downloads/asciidoctor-1.5.2.gem"]
```
Results:

icon:download[link="https://rubygems.org/downloads/asciidoctor-1.5.2.gem"]

Lastly, you can color your icons using the role syntax.
```
icon:database[role=red]
```
Results:

database icon:database[] colored red icon:database[role=red]

== How to use emoji in the wiki


You add emoji by using the following syntax anywhere in your document.

```
emoji:heart[2x] // the "[2x]" is a size modifier
emoji:rage[]
```

[NOTE]
====
You can change the icon size with the size modifier `[2x]`.

`+emoji:heart[]+` emoji:heart[] `+emoji:heart[2x]+` emoji:heart[2x]
====

== Emoji and Name Cheet Sheet

=== People

[cols="50,50"]
|===

a| emoji:white_frowning_face[2x] [small]#`white_frowning_face`# +
emoji:relaxed[2x] [small]#`relaxed`# +
emoji:zipper_mouth_face[2x] [small]#`zipper_mouth_face`# +
emoji:money_mouth_face[2x] [small]#`money_mouth_face`# +
emoji:face_with_thermometer[2x] [small]#`face_with_thermometer`# +
emoji:nerd_face[2x] [small]#`nerd_face`# +
emoji:thinking_face[2x] [small]#`thinking_face`# +
emoji:face_with_head_bandage[2x] [small]#`face_with_head_bandage`# +
emoji:robot_face[2x] [small]#`robot_face`# +
emoji:hugging_face[2x] [small]#`hugging_face`# +
emoji:grinning[2x] [small]#`grinning`# +
emoji:grin[2x] [small]#`grin`# +
emoji:joy[2x] [small]#`joy`# +
emoji:smiley[2x] [small]#`smiley`# +
emoji:smile[2x] [small]#`smile`# +
emoji:sweat_smile[2x] [small]#`sweat_smile`# +
emoji:laughing[2x] [small]#`laughing`# +
emoji:innocent[2x] [small]#`innocent`# +
emoji:smiling_imp[2x] [small]#`smiling_imp`# +
emoji:wink[2x] [small]#`wink`# +
emoji:blush[2x] [small]#`blush`# +
emoji:yum[2x] [small]#`yum`# +
emoji:relieved[2x] [small]#`relieved`# +
emoji:heart_eyes[2x] [small]#`heart_eyes`# +
emoji:sunglasses[2x] [small]#`sunglasses`# +
emoji:smirk[2x] [small]#`smirk`# +
emoji:neutral_face[2x] [small]#`neutral_face`# +
emoji:expressionless[2x] [small]#`expressionless`# +
emoji:unamused[2x] [small]#`unamused`# +
emoji:sweat[2x] [small]#`sweat`# +
emoji:pensive[2x] [small]#`pensive`# +
emoji:confused[2x] [small]#`confused`# +
emoji:confounded[2x] [small]#`confounded`# +
emoji:kissing[2x] [small]#`kissing`# +
emoji:kissing_heart[2x] [small]#`kissing_heart`# +
emoji:kissing_smiling_eyes[2x] [small]#`kissing_smiling_eyes`# +
emoji:kissing_closed_eyes[2x] [small]#`kissing_closed_eyes`# +
emoji:stuck_out_tongue[2x] [small]#`stuck_out_tongue`# +
emoji:stuck_out_tongue_winking_eye[2x] [small]#`stuck_out_tongue_winking_eye`# +
emoji:stuck_out_tongue_closed_eyes[2x] [small]#`stuck_out_tongue_closed_eyes`# +
emoji:disappointed[2x] [small]#`disappointed`# +
emoji:worried[2x] [small]#`worried`# +
emoji:angry[2x] [small]#`angry`# +
emoji:rage[2x] [small]#`rage`# +
emoji:cry[2x] [small]#`cry`# +
emoji:persevere[2x] [small]#`persevere`# +
emoji:triumph[2x] [small]#`triumph`# +
emoji:disappointed_relieved[2x] [small]#`disappointed_relieved`# +
emoji:frowning[2x] [small]#`frowning`# +
emoji:anguished[2x] [small]#`anguished`# +
emoji:fearful[2x] [small]#`fearful`# +
emoji:weary[2x] [small]#`weary`# +
emoji:sleepy[2x] [small]#`sleepy`# +
emoji:tired_face[2x] [small]#`tired_face`# +
emoji:grimacing[2x] [small]#`grimacing`# +
emoji:sob[2x] [small]#`sob`# +
emoji:open_mouth[2x] [small]#`open_mouth`# +
emoji:hushed[2x] [small]#`hushed`# +
emoji:cold_sweat[2x] [small]#`cold_sweat`# +
emoji:scream[2x] [small]#`scream`# +
emoji:astonished[2x] [small]#`astonished`# +
emoji:flushed[2x] [small]#`flushed`# +
emoji:sleeping[2x] [small]#`sleeping`# +
emoji:dizzy_face[2x] [small]#`dizzy_face`# +
emoji:no_mouth[2x] [small]#`no_mouth`# +
emoji:mask[2x] [small]#`mask`# +
emoji:smile_cat[2x] [small]#`smile_cat`# +
emoji:joy_cat[2x] [small]#`joy_cat`# +
emoji:smiley_cat[2x] [small]#`smiley_cat`# +
emoji:heart_eyes_cat[2x] [small]#`heart_eyes_cat`# +
emoji:smirk_cat[2x] [small]#`smirk_cat`# +
emoji:kissing_cat[2x] [small]#`kissing_cat`# +
emoji:pouting_cat[2x] [small]#`pouting_cat`# +
emoji:crying_cat_face[2x] [small]#`crying_cat_face`# +
emoji:scream_cat[2x] [small]#`scream_cat`# +
emoji:slightly_frowning_face[2x] [small]#`slightly_frowning_face`# +
emoji:slightly_smiling_face[2x] [small]#`slightly_smiling_face`# +
emoji:upside_down_face[2x] [small]#`upside_down_face`# +
emoji:face_with_rolling_eyes[2x] [small]#`face_with_rolling_eyes`# +
emoji:see_no_evil[2x] [small]#`see_no_evil`# +
emoji:hear_no_evil[2x] [small]#`hear_no_evil`# +
emoji:speak_no_evil[2x] [small]#`speak_no_evil`# +
emoji:no_good-skin-tone-2[2x] [small]#`no_good-skin-tone-2`# +
emoji:no_good-skin-tone-3[2x] [small]#`no_good-skin-tone-3`# +
emoji:no_good-skin-tone-4[2x] [small]#`no_good-skin-tone-4`# +
emoji:no_good-skin-tone-5[2x] [small]#`no_good-skin-tone-5`# +
emoji:no_good-skin-tone-6[2x] [small]#`no_good-skin-tone-6`# +
emoji:no_good[2x] [small]#`no_good`# +
emoji:ok_woman-skin-tone-2[2x] [small]#`ok_woman-skin-tone-2`# +
emoji:ok_woman-skin-tone-3[2x] [small]#`ok_woman-skin-tone-3`# +
emoji:ok_woman-skin-tone-4[2x] [small]#`ok_woman-skin-tone-4`# +
emoji:ok_woman-skin-tone-5[2x] [small]#`ok_woman-skin-tone-5`# +
emoji:ok_woman-skin-tone-6[2x] [small]#`ok_woman-skin-tone-6`# +
emoji:ok_woman[2x] [small]#`ok_woman`# +
emoji:bow-skin-tone-2[2x] [small]#`bow-skin-tone-2`# +
emoji:bow-skin-tone-3[2x] [small]#`bow-skin-tone-3`# +
emoji:bow-skin-tone-4[2x] [small]#`bow-skin-tone-4`# +
emoji:bow-skin-tone-5[2x] [small]#`bow-skin-tone-5`# +
emoji:bow-skin-tone-6[2x] [small]#`bow-skin-tone-6`# +
emoji:bow[2x] [small]#`bow`# +
emoji:raising_hand-skin-tone-2[2x] [small]#`raising_hand-skin-tone-2`# +
emoji:raising_hand-skin-tone-3[2x] [small]#`raising_hand-skin-tone-3`# +
emoji:raising_hand-skin-tone-4[2x] [small]#`raising_hand-skin-tone-4`# +
emoji:raising_hand-skin-tone-5[2x] [small]#`raising_hand-skin-tone-5`# +
emoji:raising_hand-skin-tone-6[2x] [small]#`raising_hand-skin-tone-6`# +
emoji:raising_hand[2x] [small]#`raising_hand`# +
emoji:person_frowning-skin-tone-2[2x] [small]#`person_frowning-skin-tone-2`# +
emoji:person_frowning-skin-tone-3[2x] [small]#`person_frowning-skin-tone-3`# +
emoji:person_frowning-skin-tone-4[2x] [small]#`person_frowning-skin-tone-4`# +
emoji:person_frowning-skin-tone-5[2x] [small]#`person_frowning-skin-tone-5`# +
emoji:person_frowning-skin-tone-6[2x] [small]#`person_frowning-skin-tone-6`# +
emoji:person_frowning[2x] [small]#`person_frowning`# +
emoji:person_with_pouting_face-skin-tone-2[2x] [small]#`person_with_pouting_face-skin-tone-2`# +
emoji:person_with_pouting_face-skin-tone-3[2x] [small]#`person_with_pouting_face-skin-tone-3`# +
emoji:person_with_pouting_face-skin-tone-4[2x] [small]#`person_with_pouting_face-skin-tone-4`# +
emoji:person_with_pouting_face-skin-tone-5[2x] [small]#`person_with_pouting_face-skin-tone-5`# +
emoji:person_with_pouting_face-skin-tone-6[2x] [small]#`person_with_pouting_face-skin-tone-6`# +
emoji:person_with_pouting_face[2x] [small]#`person_with_pouting_face`# +
emoji:sleuth_or_spy-skin-tone-2[2x] [small]#`sleuth_or_spy-skin-tone-2`# +
emoji:sleuth_or_spy-skin-tone-3[2x] [small]#`sleuth_or_spy-skin-tone-3`# +
emoji:sleuth_or_spy-skin-tone-4[2x] [small]#`sleuth_or_spy-skin-tone-4`# +
emoji:sleuth_or_spy-skin-tone-5[2x] [small]#`sleuth_or_spy-skin-tone-5`# +
emoji:sleuth_or_spy-skin-tone-6[2x] [small]#`sleuth_or_spy-skin-tone-6`# +
emoji:sleuth_or_spy[2x] [small]#`sleuth_or_spy`# +
emoji:muscle-skin-tone-2[2x] [small]#`muscle-skin-tone-2`# +
emoji:muscle-skin-tone-3[2x] [small]#`muscle-skin-tone-3`# +
emoji:muscle-skin-tone-4[2x] [small]#`muscle-skin-tone-4`# +
emoji:muscle-skin-tone-5[2x] [small]#`muscle-skin-tone-5`# +
emoji:muscle-skin-tone-6[2x] [small]#`muscle-skin-tone-6`# +
emoji:muscle[2x] [small]#`muscle`# +
emoji:boy-skin-tone-2[2x] [small]#`boy-skin-tone-2`# +
emoji:boy-skin-tone-3[2x] [small]#`boy-skin-tone-3`# +
emoji:boy-skin-tone-4[2x] [small]#`boy-skin-tone-4`# +
emoji:boy-skin-tone-5[2x] [small]#`boy-skin-tone-5`# +
emoji:boy-skin-tone-6[2x] [small]#`boy-skin-tone-6`# +
emoji:boy[2x] [small]#`boy`# +
emoji:girl-skin-tone-2[2x] [small]#`girl-skin-tone-2`# +
emoji:girl-skin-tone-3[2x] [small]#`girl-skin-tone-3`# +
emoji:girl-skin-tone-4[2x] [small]#`girl-skin-tone-4`# +
emoji:girl-skin-tone-5[2x] [small]#`girl-skin-tone-5`# +
emoji:girl-skin-tone-6[2x] [small]#`girl-skin-tone-6`# +
emoji:girl[2x] [small]#`girl`# +
emoji:man-skin-tone-2[2x] [small]#`man-skin-tone-2`# +
emoji:man-skin-tone-3[2x] [small]#`man-skin-tone-3`# +
emoji:man-skin-tone-4[2x] [small]#`man-skin-tone-4`# +
emoji:man-skin-tone-5[2x] [small]#`man-skin-tone-5`# +
emoji:man-skin-tone-6[2x] [small]#`man-skin-tone-6`# +
emoji:man[2x] [small]#`man`# +
emoji:woman-skin-tone-2[2x] [small]#`woman-skin-tone-2`# +
emoji:woman-skin-tone-3[2x] [small]#`woman-skin-tone-3`# +
emoji:woman-skin-tone-4[2x] [small]#`woman-skin-tone-4`# +
emoji:woman-skin-tone-5[2x] [small]#`woman-skin-tone-5`# +
emoji:woman-skin-tone-6[2x] [small]#`woman-skin-tone-6`# +
emoji:woman[2x] [small]#`woman`# +
emoji:cop-skin-tone-2[2x] [small]#`cop-skin-tone-2`# +
emoji:cop-skin-tone-3[2x] [small]#`cop-skin-tone-3`# +
emoji:cop-skin-tone-4[2x] [small]#`cop-skin-tone-4`# +
emoji:cop-skin-tone-5[2x] [small]#`cop-skin-tone-5`# +
emoji:cop-skin-tone-6[2x] [small]#`cop-skin-tone-6`# +
emoji:cop[2x] [small]#`cop`# +
emoji:bride_with_veil-skin-tone-2[2x] [small]#`bride_with_veil-skin-tone-2`# +
emoji:bride_with_veil-skin-tone-3[2x] [small]#`bride_with_veil-skin-tone-3`# +
emoji:bride_with_veil-skin-tone-4[2x] [small]#`bride_with_veil-skin-tone-4`# +
emoji:bride_with_veil-skin-tone-5[2x] [small]#`bride_with_veil-skin-tone-5`# +
emoji:bride_with_veil-skin-tone-6[2x] [small]#`bride_with_veil-skin-tone-6`# +
emoji:bride_with_veil[2x] [small]#`bride_with_veil`# +
emoji:person_with_blond_hair-skin-tone-2[2x] [small]#`person_with_blond_hair-skin-tone-2`# +
emoji:person_with_blond_hair-skin-tone-3[2x] [small]#`person_with_blond_hair-skin-tone-3`# +
emoji:person_with_blond_hair-skin-tone-4[2x] [small]#`person_with_blond_hair-skin-tone-4`# +
emoji:person_with_blond_hair-skin-tone-5[2x] [small]#`person_with_blond_hair-skin-tone-5`# +
emoji:person_with_blond_hair-skin-tone-6[2x] [small]#`person_with_blond_hair-skin-tone-6`# +
emoji:person_with_blond_hair[2x] [small]#`person_with_blond_hair`# +
emoji:man_with_gua_pi_mao-skin-tone-2[2x] [small]#`man_with_gua_pi_mao-skin-tone-2`# +
emoji:man_with_gua_pi_mao-skin-tone-3[2x] [small]#`man_with_gua_pi_mao-skin-tone-3`# +
emoji:man_with_gua_pi_mao-skin-tone-4[2x] [small]#`man_with_gua_pi_mao-skin-tone-4`# +
emoji:man_with_gua_pi_mao-skin-tone-5[2x] [small]#`man_with_gua_pi_mao-skin-tone-5`# +
emoji:man_with_gua_pi_mao-skin-tone-6[2x] [small]#`man_with_gua_pi_mao-skin-tone-6`# +
emoji:man_with_gua_pi_mao[2x] [small]#`man_with_gua_pi_mao`# +
emoji:man_with_turban-skin-tone-2[2x] [small]#`man_with_turban-skin-tone-2`# +
emoji:man_with_turban-skin-tone-3[2x] [small]#`man_with_turban-skin-tone-3`# +
emoji:man_with_turban-skin-tone-4[2x] [small]#`man_with_turban-skin-tone-4`# +
emoji:man_with_turban-skin-tone-5[2x] [small]#`man_with_turban-skin-tone-5`# +
emoji:man_with_turban-skin-tone-6[2x] [small]#`man_with_turban-skin-tone-6`# +
emoji:man_with_turban[2x] [small]#`man_with_turban`# +
emoji:older_man-skin-tone-2[2x] [small]#`older_man-skin-tone-2`# +
emoji:older_man-skin-tone-3[2x] [small]#`older_man-skin-tone-3`# +
emoji:older_man-skin-tone-4[2x] [small]#`older_man-skin-tone-4`# +
emoji:older_man-skin-tone-5[2x] [small]#`older_man-skin-tone-5`# +
emoji:older_man-skin-tone-6[2x] [small]#`older_man-skin-tone-6`# +
emoji:older_man[2x] [small]#`older_man`# +
emoji:older_woman-skin-tone-2[2x] [small]#`older_woman-skin-tone-2`# +
emoji:older_woman-skin-tone-3[2x] [small]#`older_woman-skin-tone-3`# +
emoji:older_woman-skin-tone-4[2x] [small]#`older_woman-skin-tone-4`# +
emoji:older_woman-skin-tone-5[2x] [small]#`older_woman-skin-tone-5`# +
emoji:older_woman-skin-tone-6[2x] [small]#`older_woman-skin-tone-6`# +
emoji:older_woman[2x] [small]#`older_woman`# +
emoji:baby-skin-tone-2[2x] [small]#`baby-skin-tone-2`# +
emoji:baby-skin-tone-3[2x] [small]#`baby-skin-tone-3`# +
emoji:baby-skin-tone-4[2x] [small]#`baby-skin-tone-4`# +
emoji:baby-skin-tone-5[2x] [small]#`baby-skin-tone-5`# +
emoji:baby-skin-tone-6[2x] [small]#`baby-skin-tone-6`# +
emoji:baby[2x] [small]#`baby`# +
emoji:construction_worker-skin-tone-2[2x] [small]#`construction_worker-skin-tone-2`# +
emoji:construction_worker-skin-tone-3[2x] [small]#`construction_worker-skin-tone-3`# +
emoji:construction_worker-skin-tone-4[2x] [small]#`construction_worker-skin-tone-4`# +
emoji:construction_worker-skin-tone-5[2x] [small]#`construction_worker-skin-tone-5`# +
emoji:construction_worker-skin-tone-6[2x] [small]#`construction_worker-skin-tone-6`# +
emoji:construction_worker[2x] [small]#`construction_worker`# +
emoji:princess-skin-tone-2[2x] [small]#`princess-skin-tone-2`# +
emoji:princess-skin-tone-3[2x] [small]#`princess-skin-tone-3`# +
emoji:princess-skin-tone-4[2x] [small]#`princess-skin-tone-4`# +
emoji:princess-skin-tone-5[2x] [small]#`princess-skin-tone-5`# +
emoji:princess-skin-tone-6[2x] [small]#`princess-skin-tone-6`# +
emoji:princess[2x] [small]#`princess`# +
emoji:angel-skin-tone-2[2x] [small]#`angel-skin-tone-2`# +
emoji:angel-skin-tone-3[2x] [small]#`angel-skin-tone-3`# +
emoji:angel-skin-tone-4[2x] [small]#`angel-skin-tone-4`# +
emoji:angel-skin-tone-5[2x] [small]#`angel-skin-tone-5`# +
emoji:angel-skin-tone-6[2x] [small]#`angel-skin-tone-6`# +

a| emoji:angel[2x] [small]#`angel`# +
emoji:information_desk_person-skin-tone-2[2x] [small]#`information_desk_person-skin-tone-2`# +
emoji:information_desk_person-skin-tone-3[2x] [small]#`information_desk_person-skin-tone-3`# +
emoji:information_desk_person-skin-tone-4[2x] [small]#`information_desk_person-skin-tone-4`# +
emoji:information_desk_person-skin-tone-5[2x] [small]#`information_desk_person-skin-tone-5`# +
emoji:information_desk_person-skin-tone-6[2x] [small]#`information_desk_person-skin-tone-6`# +
emoji:information_desk_person[2x] [small]#`information_desk_person`# +
emoji:guardsman-skin-tone-2[2x] [small]#`guardsman-skin-tone-2`# +
emoji:guardsman-skin-tone-3[2x] [small]#`guardsman-skin-tone-3`# +
emoji:guardsman-skin-tone-4[2x] [small]#`guardsman-skin-tone-4`# +
emoji:guardsman-skin-tone-5[2x] [small]#`guardsman-skin-tone-5`# +
emoji:guardsman-skin-tone-6[2x] [small]#`guardsman-skin-tone-6`# +
emoji:guardsman[2x] [small]#`guardsman`# +
emoji:dancer-skin-tone-2[2x] [small]#`dancer-skin-tone-2`# +
emoji:dancer-skin-tone-3[2x] [small]#`dancer-skin-tone-3`# +
emoji:dancer-skin-tone-4[2x] [small]#`dancer-skin-tone-4`# +
emoji:dancer-skin-tone-5[2x] [small]#`dancer-skin-tone-5`# +
emoji:dancer-skin-tone-6[2x] [small]#`dancer-skin-tone-6`# +
emoji:dancer[2x] [small]#`dancer`# +
emoji:nail_care-skin-tone-2[2x] [small]#`nail_care-skin-tone-2`# +
emoji:nail_care-skin-tone-3[2x] [small]#`nail_care-skin-tone-3`# +
emoji:nail_care-skin-tone-4[2x] [small]#`nail_care-skin-tone-4`# +
emoji:nail_care-skin-tone-5[2x] [small]#`nail_care-skin-tone-5`# +
emoji:nail_care-skin-tone-6[2x] [small]#`nail_care-skin-tone-6`# +
emoji:nail_care[2x] [small]#`nail_care`# +
emoji:massage-skin-tone-2[2x] [small]#`massage-skin-tone-2`# +
emoji:massage-skin-tone-3[2x] [small]#`massage-skin-tone-3`# +
emoji:massage-skin-tone-4[2x] [small]#`massage-skin-tone-4`# +
emoji:massage-skin-tone-5[2x] [small]#`massage-skin-tone-5`# +
emoji:massage-skin-tone-6[2x] [small]#`massage-skin-tone-6`# +
emoji:massage[2x] [small]#`massage`# +
emoji:haircut-skin-tone-2[2x] [small]#`haircut-skin-tone-2`# +
emoji:haircut-skin-tone-3[2x] [small]#`haircut-skin-tone-3`# +
emoji:haircut-skin-tone-4[2x] [small]#`haircut-skin-tone-4`# +
emoji:haircut-skin-tone-5[2x] [small]#`haircut-skin-tone-5`# +
emoji:haircut-skin-tone-6[2x] [small]#`haircut-skin-tone-6`# +
emoji:haircut[2x] [small]#`haircut`# +
emoji:santa-skin-tone-2[2x] [small]#`santa-skin-tone-2`# +
emoji:santa-skin-tone-3[2x] [small]#`santa-skin-tone-3`# +
emoji:santa-skin-tone-4[2x] [small]#`santa-skin-tone-4`# +
emoji:santa-skin-tone-5[2x] [small]#`santa-skin-tone-5`# +
emoji:santa-skin-tone-6[2x] [small]#`santa-skin-tone-6`# +
emoji:santa[2x] [small]#`santa`# +
emoji:ear-skin-tone-2[2x] [small]#`ear-skin-tone-2`# +
emoji:ear-skin-tone-3[2x] [small]#`ear-skin-tone-3`# +
emoji:ear-skin-tone-4[2x] [small]#`ear-skin-tone-4`# +
emoji:ear-skin-tone-5[2x] [small]#`ear-skin-tone-5`# +
emoji:ear-skin-tone-6[2x] [small]#`ear-skin-tone-6`# +
emoji:ear[2x] [small]#`ear`# +
emoji:nose-skin-tone-2[2x] [small]#`nose-skin-tone-2`# +
emoji:nose-skin-tone-3[2x] [small]#`nose-skin-tone-3`# +
emoji:nose-skin-tone-4[2x] [small]#`nose-skin-tone-4`# +
emoji:nose-skin-tone-5[2x] [small]#`nose-skin-tone-5`# +
emoji:nose-skin-tone-6[2x] [small]#`nose-skin-tone-6`# +
emoji:nose[2x] [small]#`nose`# +
emoji:raised_hands-skin-tone-2[2x] [small]#`raised_hands-skin-tone-2`# +
emoji:raised_hands-skin-tone-3[2x] [small]#`raised_hands-skin-tone-3`# +
emoji:raised_hands-skin-tone-4[2x] [small]#`raised_hands-skin-tone-4`# +
emoji:raised_hands-skin-tone-5[2x] [small]#`raised_hands-skin-tone-5`# +
emoji:raised_hands-skin-tone-6[2x] [small]#`raised_hands-skin-tone-6`# +
emoji:raised_hands[2x] [small]#`raised_hands`# +
emoji:pray-skin-tone-2[2x] [small]#`pray-skin-tone-2`# +
emoji:pray-skin-tone-3[2x] [small]#`pray-skin-tone-3`# +
emoji:pray-skin-tone-4[2x] [small]#`pray-skin-tone-4`# +
emoji:pray-skin-tone-5[2x] [small]#`pray-skin-tone-5`# +
emoji:pray-skin-tone-6[2x] [small]#`pray-skin-tone-6`# +
emoji:pray[2x] [small]#`pray`# +
emoji:the_horns-skin-tone-2[2x] [small]#`the_horns-skin-tone-2`# +
emoji:the_horns-skin-tone-3[2x] [small]#`the_horns-skin-tone-3`# +
emoji:the_horns-skin-tone-4[2x] [small]#`the_horns-skin-tone-4`# +
emoji:the_horns-skin-tone-5[2x] [small]#`the_horns-skin-tone-5`# +
emoji:the_horns-skin-tone-6[2x] [small]#`the_horns-skin-tone-6`# +
emoji:the_horns[2x] [small]#`the_horns`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-2[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-2`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-3[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-3`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-4[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-4`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-5[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-5`# +
emoji:raised_hand_with_fingers_splayed-skin-tone-6[2x] [small]#`raised_hand_with_fingers_splayed-skin-tone-6`# +
emoji:raised_hand_with_fingers_splayed[2x] [small]#`raised_hand_with_fingers_splayed`# +
emoji:middle_finger-skin-tone-2[2x] [small]#`middle_finger-skin-tone-2`# +
emoji:middle_finger-skin-tone-3[2x] [small]#`middle_finger-skin-tone-3`# +
emoji:middle_finger-skin-tone-4[2x] [small]#`middle_finger-skin-tone-4`# +
emoji:middle_finger-skin-tone-5[2x] [small]#`middle_finger-skin-tone-5`# +
emoji:middle_finger-skin-tone-6[2x] [small]#`middle_finger-skin-tone-6`# +
emoji:middle_finger[2x] [small]#`middle_finger`# +
emoji:spock-hand-skin-tone-2[2x] [small]#`spock-hand-skin-tone-2`# +
emoji:spock-hand-skin-tone-3[2x] [small]#`spock-hand-skin-tone-3`# +
emoji:spock-hand-skin-tone-4[2x] [small]#`spock-hand-skin-tone-4`# +
emoji:spock-hand-skin-tone-5[2x] [small]#`spock-hand-skin-tone-5`# +
emoji:spock-hand-skin-tone-6[2x] [small]#`spock-hand-skin-tone-6`# +
emoji:spock-hand[2x] [small]#`spock-hand`# +
emoji:point_up_2-skin-tone-2[2x] [small]#`point_up_2-skin-tone-2`# +
emoji:point_up_2-skin-tone-3[2x] [small]#`point_up_2-skin-tone-3`# +
emoji:point_up_2-skin-tone-4[2x] [small]#`point_up_2-skin-tone-4`# +
emoji:point_up_2-skin-tone-5[2x] [small]#`point_up_2-skin-tone-5`# +
emoji:point_up_2-skin-tone-6[2x] [small]#`point_up_2-skin-tone-6`# +
emoji:point_up_2[2x] [small]#`point_up_2`# +
emoji:point_down-skin-tone-2[2x] [small]#`point_down-skin-tone-2`# +
emoji:point_down-skin-tone-3[2x] [small]#`point_down-skin-tone-3`# +
emoji:point_down-skin-tone-4[2x] [small]#`point_down-skin-tone-4`# +
emoji:point_down-skin-tone-5[2x] [small]#`point_down-skin-tone-5`# +
emoji:point_down-skin-tone-6[2x] [small]#`point_down-skin-tone-6`# +
emoji:point_down[2x] [small]#`point_down`# +
emoji:point_left-skin-tone-2[2x] [small]#`point_left-skin-tone-2`# +
emoji:point_left-skin-tone-3[2x] [small]#`point_left-skin-tone-3`# +
emoji:point_left-skin-tone-4[2x] [small]#`point_left-skin-tone-4`# +
emoji:point_left-skin-tone-5[2x] [small]#`point_left-skin-tone-5`# +
emoji:point_left-skin-tone-6[2x] [small]#`point_left-skin-tone-6`# +
emoji:point_left[2x] [small]#`point_left`# +
emoji:point_right-skin-tone-2[2x] [small]#`point_right-skin-tone-2`# +
emoji:point_right-skin-tone-3[2x] [small]#`point_right-skin-tone-3`# +
emoji:point_right-skin-tone-4[2x] [small]#`point_right-skin-tone-4`# +
emoji:point_right-skin-tone-5[2x] [small]#`point_right-skin-tone-5`# +
emoji:point_right-skin-tone-6[2x] [small]#`point_right-skin-tone-6`# +
emoji:point_right[2x] [small]#`point_right`# +
emoji:facepunch-skin-tone-2[2x] [small]#`facepunch-skin-tone-2`# +
emoji:facepunch-skin-tone-3[2x] [small]#`facepunch-skin-tone-3`# +
emoji:facepunch-skin-tone-4[2x] [small]#`facepunch-skin-tone-4`# +
emoji:facepunch-skin-tone-5[2x] [small]#`facepunch-skin-tone-5`# +
emoji:facepunch-skin-tone-6[2x] [small]#`facepunch-skin-tone-6`# +
emoji:facepunch[2x] [small]#`facepunch`# +
emoji:wave-skin-tone-2[2x] [small]#`wave-skin-tone-2`# +
emoji:wave-skin-tone-3[2x] [small]#`wave-skin-tone-3`# +
emoji:wave-skin-tone-4[2x] [small]#`wave-skin-tone-4`# +
emoji:wave-skin-tone-5[2x] [small]#`wave-skin-tone-5`# +
emoji:wave-skin-tone-6[2x] [small]#`wave-skin-tone-6`# +
emoji:wave[2x] [small]#`wave`# +
emoji:ok_hand-skin-tone-2[2x] [small]#`ok_hand-skin-tone-2`# +
emoji:ok_hand-skin-tone-3[2x] [small]#`ok_hand-skin-tone-3`# +
emoji:ok_hand-skin-tone-4[2x] [small]#`ok_hand-skin-tone-4`# +
emoji:ok_hand-skin-tone-5[2x] [small]#`ok_hand-skin-tone-5`# +
emoji:ok_hand-skin-tone-6[2x] [small]#`ok_hand-skin-tone-6`# +
emoji:ok_hand[2x] [small]#`ok_hand`# +
emoji:+1-skin-tone-2[2x] [small]#`+1-skin-tone-2`# +
emoji:+1-skin-tone-3[2x] [small]#`+1-skin-tone-3`# +
emoji:+1-skin-tone-4[2x] [small]#`+1-skin-tone-4`# +
emoji:+1-skin-tone-5[2x] [small]#`+1-skin-tone-5`# +
emoji:+1-skin-tone-6[2x] [small]#`+1-skin-tone-6`# +
emoji:+1[2x] [small]#`+1`# +
emoji:-1-skin-tone-2[2x] [small]#`-1-skin-tone-2`# +
emoji:-1-skin-tone-3[2x] [small]#`-1-skin-tone-3`# +
emoji:-1-skin-tone-4[2x] [small]#`-1-skin-tone-4`# +
emoji:-1-skin-tone-5[2x] [small]#`-1-skin-tone-5`# +
emoji:-1-skin-tone-6[2x] [small]#`-1-skin-tone-6`# +
emoji:-1[2x] [small]#`-1`# +
emoji:clap-skin-tone-2[2x] [small]#`clap-skin-tone-2`# +
emoji:clap-skin-tone-3[2x] [small]#`clap-skin-tone-3`# +
emoji:clap-skin-tone-4[2x] [small]#`clap-skin-tone-4`# +
emoji:clap-skin-tone-5[2x] [small]#`clap-skin-tone-5`# +
emoji:clap-skin-tone-6[2x] [small]#`clap-skin-tone-6`# +
emoji:clap[2x] [small]#`clap`# +
emoji:open_hands-skin-tone-2[2x] [small]#`open_hands-skin-tone-2`# +
emoji:open_hands-skin-tone-3[2x] [small]#`open_hands-skin-tone-3`# +
emoji:open_hands-skin-tone-4[2x] [small]#`open_hands-skin-tone-4`# +
emoji:open_hands-skin-tone-5[2x] [small]#`open_hands-skin-tone-5`# +
emoji:open_hands-skin-tone-6[2x] [small]#`open_hands-skin-tone-6`# +
emoji:open_hands[2x] [small]#`open_hands`# +
emoji:point_up-skin-tone-2[2x] [small]#`point_up-skin-tone-2`# +
emoji:point_up-skin-tone-3[2x] [small]#`point_up-skin-tone-3`# +
emoji:point_up-skin-tone-4[2x] [small]#`point_up-skin-tone-4`# +
emoji:point_up-skin-tone-5[2x] [small]#`point_up-skin-tone-5`# +
emoji:point_up-skin-tone-6[2x] [small]#`point_up-skin-tone-6`# +
emoji:point_up[2x] [small]#`point_up`# +
emoji:fist-skin-tone-2[2x] [small]#`fist-skin-tone-2`# +
emoji:fist-skin-tone-3[2x] [small]#`fist-skin-tone-3`# +
emoji:fist-skin-tone-4[2x] [small]#`fist-skin-tone-4`# +
emoji:fist-skin-tone-5[2x] [small]#`fist-skin-tone-5`# +
emoji:fist-skin-tone-6[2x] [small]#`fist-skin-tone-6`# +
emoji:fist[2x] [small]#`fist`# +
emoji:hand-skin-tone-2[2x] [small]#`hand-skin-tone-2`# +
emoji:hand-skin-tone-3[2x] [small]#`hand-skin-tone-3`# +
emoji:hand-skin-tone-4[2x] [small]#`hand-skin-tone-4`# +
emoji:hand-skin-tone-5[2x] [small]#`hand-skin-tone-5`# +
emoji:hand-skin-tone-6[2x] [small]#`hand-skin-tone-6`# +
emoji:hand[2x] [small]#`hand`# +
emoji:victory_hand-skin-tone-2[2x] [small]#`victory_hand-skin-tone-2`# +
emoji:victory_hand-skin-tone-3[2x] [small]#`victory_hand-skin-tone-3`# +
emoji:victory_hand-skin-tone-4[2x] [small]#`victory_hand-skin-tone-4`# +
emoji:victory_hand-skin-tone-5[2x] [small]#`victory_hand-skin-tone-5`# +
emoji:victory_hand-skin-tone-6[2x] [small]#`victory_hand-skin-tone-6`# +
emoji:victory_hand[2x] [small]#`victory_hand`# +
emoji:writing_hand-skin-tone-2[2x] [small]#`writing_hand-skin-tone-2`# +
emoji:writing_hand-skin-tone-3[2x] [small]#`writing_hand-skin-tone-3`# +
emoji:writing_hand-skin-tone-4[2x] [small]#`writing_hand-skin-tone-4`# +
emoji:writing_hand-skin-tone-5[2x] [small]#`writing_hand-skin-tone-5`# +
emoji:writing_hand-skin-tone-6[2x] [small]#`writing_hand-skin-tone-6`# +
emoji:writing_hand[2x] [small]#`writing_hand`# +
emoji:bust_in_silhouette[2x] [small]#`bust_in_silhouette`# +
emoji:busts_in_silhouette[2x] [small]#`busts_in_silhouette`# +
emoji:dancers[2x] [small]#`dancers`# +
emoji:man_in_business_suit_levitating[2x] [small]#`man_in_business_suit_levitating`# +
emoji:man-woman-boy[2x] [small]#`man-woman-boy`# +
emoji:man-woman-boy-boy[2x] [small]#`man-woman-boy-boy`# +
emoji:man-woman-girl[2x] [small]#`man-woman-girl`# +
emoji:man-woman-girl-boy[2x] [small]#`man-woman-girl-boy`# +
emoji:man-woman-girl-girl[2x] [small]#`man-woman-girl-girl`# +
emoji:woman-heart-man[2x] [small]#`woman-heart-man`# +
emoji:woman-kiss-man[2x] [small]#`woman-kiss-man`# +
emoji:family[2x] [small]#`family`# +
emoji:couple[2x] [small]#`couple`# +
emoji:japanese_ogre[2x] [small]#`japanese_ogre`# +
emoji:japanese_goblin[2x] [small]#`japanese_goblin`# +
emoji:ghost[2x] [small]#`ghost`# +
emoji:alien[2x] [small]#`alien`# +
emoji:space_invader[2x] [small]#`space_invader`# +
emoji:imp[2x] [small]#`imp`# +
emoji:skull[2x] [small]#`skull`# +
emoji:eyes[2x] [small]#`eyes`# +
emoji:eye[2x] [small]#`eye`# +
emoji:lips[2x] [small]#`lips`# +
emoji:tongue[2x] [small]#`tongue`# +
emoji:skin-tone-2[2x] [small]#`skin-tone-2`# +
emoji:skin-tone-3[2x] [small]#`skin-tone-3`# +
emoji:skin-tone-4[2x] [small]#`skin-tone-4`# +
emoji:skin-tone-5[2x] [small]#`skin-tone-5`# +
emoji:skin-tone-6[2x] [small]#`skin-tone-6`# +

|===

=== Animals & Nature

[cols="10,40,10,40", header=true]
|===

a| Emoji
a| Code
a| Emoji
a| Code

a| emoji:partly_sunny[2x] a| [small]#`partly_sunny`#
a| emoji:thunder_cloud_and_rain[2x] a| [small]#`thunder_cloud_and_rain`#

a| emoji:sunny[2x] a| [small]#`sunny`#
a| emoji:cloud[2x] a| [small]#`cloud`#

a| emoji:cyclone[2x] a| [small]#`cyclone`#
a| emoji:foggy[2x] a| [small]#`foggy`#

a| emoji:closed_umbrella[2x] a| [small]#`closed_umbrella`#
a| emoji:night_with_stars[2x] a| [small]#`night_with_stars`#

a| emoji:sunrise_over_mountains[2x] a| [small]#`sunrise_over_mountains`#
a| emoji:sunrise[2x] a| [small]#`sunrise`#

a| emoji:city_sunset[2x] a| [small]#`city_sunset`#
a| emoji:city_sunrise[2x] a| [small]#`city_sunrise`#

a| emoji:rainbow[2x] a| [small]#`rainbow`#
a| emoji:bridge_at_night[2x] a| [small]#`bridge_at_night`#

a| emoji:ocean[2x] a| [small]#`ocean`#
a| emoji:volcano[2x] a| [small]#`volcano`#

a| emoji:milky_way[2x] a| [small]#`milky_way`#
a| emoji:earth_africa[2x] a| [small]#`earth_africa`#

a| emoji:earth_americas[2x] a| [small]#`earth_americas`#
a| emoji:earth_asia[2x] a| [small]#`earth_asia`#

a| emoji:globe_with_meridians[2x] a| [small]#`globe_with_meridians`#
a| emoji:new_moon[2x] a| [small]#`new_moon`#

a| emoji:waxing_crescent_moon[2x] a| [small]#`waxing_crescent_moon`#
a| emoji:first_quarter_moon[2x] a| [small]#`first_quarter_moon`#

a| emoji:waxing_gibbous_moon[2x] a| [small]#`waxing_gibbous_moon`#
a| emoji:full_moon[2x] a| [small]#`full_moon`#

a| emoji:waning_gibbous_moon[2x] a| [small]#`waning_gibbous_moon`#
a| emoji:last_quarter_moon[2x] a| [small]#`last_quarter_moon`#

a| emoji:waning_crescent_moon[2x] a| [small]#`waning_crescent_moon`#
a| emoji:crescent_moon[2x] a| [small]#`crescent_moon`#

a| emoji:new_moon_with_face[2x] a| [small]#`new_moon_with_face`#
a| emoji:first_quarter_moon_with_face[2x] a| [small]#`first_quarter_moon_with_face`#

a| emoji:last_quarter_moon_with_face[2x] a| [small]#`last_quarter_moon_with_face`#
a| emoji:full_moon_with_face[2x] a| [small]#`full_moon_with_face`#

a| emoji:sun_with_face[2x] a| [small]#`sun_with_face`#
a| emoji:star2[2x] a| [small]#`star2`#

a| emoji:stars[2x] a| [small]#`stars`#
a| emoji:thermometer[2x] a| [small]#`thermometer`#

a| emoji:mostly_sunny[2x] a| [small]#`mostly_sunny`#
a| emoji:barely_sunny[2x] a| [small]#`barely_sunny`#

a| emoji:partly_sunny_rain[2x] a| [small]#`partly_sunny_rain`#
a| emoji:rain_cloud[2x] a| [small]#`rain_cloud`#

a| emoji:snow_cloud[2x] a| [small]#`snow_cloud`#
a| emoji:lightning[2x] a| [small]#`lightning`#

a| emoji:tornado[2x] a| [small]#`tornado`#
a| emoji:fog[2x] a| [small]#`fog`#

a| emoji:wind_blowing_face[2x] a| [small]#`wind_blowing_face`#
a| emoji:seedling[2x] a| [small]#`seedling`#

a| emoji:evergreen_tree[2x] a| [small]#`evergreen_tree`#
a| emoji:deciduous_tree[2x] a| [small]#`deciduous_tree`#

a| emoji:palm_tree[2x] a| [small]#`palm_tree`#
a| emoji:cactus[2x] a| [small]#`cactus`#

a| emoji:hot_pepper[2x] a| [small]#`hot_pepper`#
a| emoji:tulip[2x] a| [small]#`tulip`#

a| emoji:cherry_blossom[2x] a| [small]#`cherry_blossom`#
a| emoji:rose[2x] a| [small]#`rose`#

a| emoji:hibiscus[2x] a| [small]#`hibiscus`#
a| emoji:sunflower[2x] a| [small]#`sunflower`#

a| emoji:blossom[2x] a| [small]#`blossom`#
a| emoji:corn[2x] a| [small]#`corn`#

a| emoji:ear_of_rice[2x] a| [small]#`ear_of_rice`#
a| emoji:herb[2x] a| [small]#`herb`#

a| emoji:four_leaf_clover[2x] a| [small]#`four_leaf_clover`#
a| emoji:maple_leaf[2x] a| [small]#`maple_leaf`#

a| emoji:fallen_leaf[2x] a| [small]#`fallen_leaf`#
a| emoji:leaves[2x] a| [small]#`leaves`#

a| emoji:mushroom[2x] a| [small]#`mushroom`#
a| emoji:tomato[2x] a| [small]#`tomato`#

a| emoji:eggplant[2x] a| [small]#`eggplant`#
a| emoji:grapes[2x] a| [small]#`grapes`#

a| emoji:melon[2x] a| [small]#`melon`#
a| emoji:watermelon[2x] a| [small]#`watermelon`#

a| emoji:tangerine[2x] a| [small]#`tangerine`#
a| emoji:lemon[2x] a| [small]#`lemon`#

a| emoji:banana[2x] a| [small]#`banana`#
a| emoji:pineapple[2x] a| [small]#`pineapple`#

a| emoji:apple[2x] a| [small]#`apple`#
a| emoji:green_apple[2x] a| [small]#`green_apple`#

a| emoji:pear[2x] a| [small]#`pear`#
a| emoji:peach[2x] a| [small]#`peach`#

a| emoji:cherries[2x] a| [small]#`cherries`#
a| emoji:strawberry[2x] a| [small]#`strawberry`#

a| emoji:rat[2x] a| [small]#`rat`#
a| emoji:mouse2[2x] a| [small]#`mouse2`#

a| emoji:ox[2x] a| [small]#`ox`#
a| emoji:water_buffalo[2x] a| [small]#`water_buffalo`#

a| emoji:cow2[2x] a| [small]#`cow2`#
a| emoji:tiger2[2x] a| [small]#`tiger2`#

a| emoji:leopard[2x] a| [small]#`leopard`#
a| emoji:rabbit2[2x] a| [small]#`rabbit2`#

a| emoji:cat2[2x] a| [small]#`cat2`#
a| emoji:dragon[2x] a| [small]#`dragon`#

a| emoji:crocodile[2x] a| [small]#`crocodile`#
a| emoji:whale2[2x] a| [small]#`whale2`#

a| emoji:snail[2x] a| [small]#`snail`#
a| emoji:snake[2x] a| [small]#`snake`#

a| emoji:racehorse[2x] a| [small]#`racehorse`#
a| emoji:ram[2x] a| [small]#`ram`#

a| emoji:goat[2x] a| [small]#`goat`#
a| emoji:sheep[2x] a| [small]#`sheep`#

a| emoji:monkey[2x] a| [small]#`monkey`#
a| emoji:rooster[2x] a| [small]#`rooster`#

a| emoji:chicken[2x] a| [small]#`chicken`#
a| emoji:dog2[2x] a| [small]#`dog2`#

a| emoji:pig2[2x] a| [small]#`pig2`#
a| emoji:boar[2x] a| [small]#`boar`#

a| emoji:elephant[2x] a| [small]#`elephant`#
a| emoji:octopus[2x] a| [small]#`octopus`#

a| emoji:shell[2x] a| [small]#`shell`#
a| emoji:bug[2x] a| [small]#`bug`#

a| emoji:ant[2x] a| [small]#`ant`#
a| emoji:bee[2x] a| [small]#`bee`#

a| emoji:beetle[2x] a| [small]#`beetle`#
a| emoji:fish[2x] a| [small]#`fish`#

a| emoji:tropical_fish[2x] a| [small]#`tropical_fish`#
a| emoji:blowfish[2x] a| [small]#`blowfish`#

a| emoji:turtle[2x] a| [small]#`turtle`#
a| emoji:hatching_chick[2x] a| [small]#`hatching_chick`#

a| emoji:baby_chick[2x] a| [small]#`baby_chick`#
a| emoji:hatched_chick[2x] a| [small]#`hatched_chick`#

a| emoji:bird[2x] a| [small]#`bird`#
a| emoji:penguin[2x] a| [small]#`penguin`#

a| emoji:koala[2x] a| [small]#`koala`#
a| emoji:poodle[2x] a| [small]#`poodle`#

a| emoji:dromedary_camel[2x] a| [small]#`dromedary_camel`#
a| emoji:camel[2x] a| [small]#`camel`#

a| emoji:dolphin[2x] a| [small]#`dolphin`#
a| emoji:mouse[2x] a| [small]#`mouse`#

a| emoji:cow[2x] a| [small]#`cow`#
a| emoji:tiger[2x] a| [small]#`tiger`#

a| emoji:rabbit[2x] a| [small]#`rabbit`#
a| emoji:cat[2x] a| [small]#`cat`#

a| emoji:dragon_face[2x] a| [small]#`dragon_face`#
a| emoji:whale[2x] a| [small]#`whale`#

a| emoji:horse[2x] a| [small]#`horse`#
a| emoji:monkey_face[2x] a| [small]#`monkey_face`#

a| emoji:dog[2x] a| [small]#`dog`#
a| emoji:pig[2x] a| [small]#`pig`#

a| emoji:frog[2x] a| [small]#`frog`#
a| emoji:hamster[2x] a| [small]#`hamster`#

a| emoji:wolf[2x] a| [small]#`wolf`#
a| emoji:bear[2x] a| [small]#`bear`#

a| emoji:panda_face[2x] a| [small]#`panda_face`#
a| emoji:pig_nose[2x] a| [small]#`pig_nose`#

a| emoji:feet[2x] a| [small]#`feet`#
a| emoji:chipmunk[2x] a| [small]#`chipmunk`#

a| emoji:crab[2x] a| [small]#`crab`#
a| emoji:lion_face[2x] a| [small]#`lion_face`#

a| emoji:scorpion[2x] a| [small]#`scorpion`#
a| emoji:turkey[2x] a| [small]#`turkey`#

a| emoji:unicorn_face[2x] a| [small]#`unicorn_face`#
a| a|

|===


=== Food & Drink

[cols="10,40,10,40", header=true]
|===

a| Emoji
a| Code
a| Emoji
a| Code

a| emoji:coffee[2x] a| [small]#`coffee`#
a| emoji:cheese_wedge[2x] a| [small]#`cheese_wedge`#

a| emoji:hotdog[2x] a| [small]#`hotdog`#
a| emoji:taco[2x] a| [small]#`taco`#

a| emoji:burrito[2x] a| [small]#`burrito`#
a| emoji:chestnut[2x] a| [small]#`chestnut`#

a| emoji:hamburger[2x] a| [small]#`hamburger`#
a| emoji:pizza[2x] a| [small]#`pizza`#

a| emoji:meat_on_bone[2x] a| [small]#`meat_on_bone`#
a| emoji:poultry_leg[2x] a| [small]#`poultry_leg`#

a| emoji:rice_cracker[2x] a| [small]#`rice_cracker`#
a| emoji:rice_ball[2x] a| [small]#`rice_ball`#

a| emoji:rice[2x] a| [small]#`rice`#
a| emoji:curry[2x] a| [small]#`curry`#

a| emoji:ramen[2x] a| [small]#`ramen`#
a| emoji:spaghetti[2x] a| [small]#`spaghetti`#

a| emoji:bread[2x] a| [small]#`bread`#
a| emoji:fries[2x] a| [small]#`fries`#

a| emoji:sweet_potato[2x] a| [small]#`sweet_potato`#
a| emoji:dango[2x] a| [small]#`dango`#

a| emoji:oden[2x] a| [small]#`oden`#
a| emoji:sushi[2x] a| [small]#`sushi`#

a| emoji:fried_shrimp[2x] a| [small]#`fried_shrimp`#
a| emoji:fish_cake[2x] a| [small]#`fish_cake`#

a| emoji:icecream[2x] a| [small]#`icecream`#
a| emoji:shaved_ice[2x] a| [small]#`shaved_ice`#

a| emoji:ice_cream[2x] a| [small]#`ice_cream`#
a| emoji:doughnut[2x] a| [small]#`doughnut`#

a| emoji:cookie[2x] a| [small]#`cookie`#
a| emoji:chocolate_bar[2x] a| [small]#`chocolate_bar`#

a| emoji:candy[2x] a| [small]#`candy`#
a| emoji:lollipop[2x] a| [small]#`lollipop`#

a| emoji:custard[2x] a| [small]#`custard`#
a| emoji:honey_pot[2x] a| [small]#`honey_pot`#

a| emoji:cake[2x] a| [small]#`cake`#
a| emoji:bento[2x] a| [small]#`bento`#

a| emoji:stew[2x] a| [small]#`stew`#
a| emoji:egg[2x] a| [small]#`egg`#

a| emoji:fork_and_knife[2x] a| [small]#`fork_and_knife`#
a| emoji:tea[2x] a| [small]#`tea`#

a| emoji:sake[2x] a| [small]#`sake`#
a| emoji:wine_glass[2x] a| [small]#`wine_glass`#

a| emoji:cocktail[2x] a| [small]#`cocktail`#
a| emoji:tropical_drink[2x] a| [small]#`tropical_drink`#

a| emoji:beer[2x] a| [small]#`beer`#
a| emoji:beers[2x] a| [small]#`beers`#

a| emoji:baby_bottle[2x] a| [small]#`baby_bottle`#
a| emoji:knife_fork_plate[2x] a| [small]#`knife_fork_plate`#

a| emoji:champagne[2x] a| [small]#`champagne`#
a| emoji:popcorn[2x] a| [small]#`popcorn`#

|===

=== Objects

[cols="10,40,10,40", header=true]
|===

a| Emoji
a| Code
a| Emoji
a| Code

a| emoji:lipstick[2x] a| [small]#`lipstick`#
a| emoji:pencil2[2x] a| [small]#`pencil2`#

a| emoji:black_nib[2x] a| [small]#`black_nib`#
a| emoji:tent[2x] a| [small]#`tent`#

a| emoji:fuelpump[2x] a| [small]#`fuelpump`#
a| emoji:scissors[2x] a| [small]#`scissors`#

a| emoji:umbrella_on_ground[2x] a| [small]#`umbrella_on_ground`#
a| emoji:fountain[2x] a| [small]#`fountain`#

a| emoji:pick[2x] a| [small]#`pick`#
a| emoji:helmet_with_white_cross[2x] a| [small]#`helmet_with_white_cross`#

a| emoji:chains[2x] a| [small]#`chains`#
a| emoji:coffin[2x] a| [small]#`coffin`#

a| emoji:funeral_urn[2x] a| [small]#`funeral_urn`#
a| emoji:soccer[2x] a| [small]#`soccer`#

a| emoji:baseball[2x] a| [small]#`baseball`#
a| emoji:shamrock[2x] a| [small]#`shamrock`#

a| emoji:umbrella[2x] a| [small]#`umbrella`#
a| emoji:snowman[2x] a| [small]#`snowman`#

a| emoji:showman[2x] a| [small]#`showman`#
a| emoji:comet[2x] a| [small]#`comet`#

a| emoji:phone[2x] a| [small]#`phone`#
a| emoji:ballot_box_with_check[2x] a| [small]#`ballot_box_with_check`#

a| emoji:ballot_box_with_ballot[2x] a| [small]#`ballot_box_with_ballot`#
a| emoji:umbrella_with_rain_drops[2x] a| [small]#`umbrella_with_rain_drops`#

a| emoji:wastebasket[2x] a| [small]#`wastebasket`#
a| emoji:spiral_note_pad[2x] a| [small]#`spiral_note_pad`#

a| emoji:spiral_calendar_pad[2x] a| [small]#`spiral_calendar_pad`#
a| emoji:compression[2x] a| [small]#`compression`#

a| emoji:old_key[2x] a| [small]#`old_key`#
a| emoji:rolled_up_newspaper[2x] a| [small]#`rolled_up_newspaper`#

a| emoji:dagger_knife[2x] a| [small]#`dagger_knife`#
a| emoji:dark_sunglasses[2x] a| [small]#`dark_sunglasses`#

a| emoji:spider[2x] a| [small]#`spider`#
a| emoji:spider_web[2x] a| [small]#`spider_web`#

a| emoji:joystick[2x] a| [small]#`joystick`#
a| emoji:linked_paperclips[2x] a| [small]#`linked_paperclips`#

a| emoji:lower_left_ballpoint_pen[2x] a| [small]#`lower_left_ballpoint_pen`#
a| emoji:lower_left_fountain_pen[2x] a| [small]#`lower_left_fountain_pen`#

a| emoji:lower_left_paintbrush[2x] a| [small]#`lower_left_paintbrush`#
a| emoji:lower_left_crayon[2x] a| [small]#`lower_left_crayon`#

a| emoji:candle[2x] a| [small]#`candle`#
a| emoji:mantelpiece_clock[2x] a| [small]#`mantelpiece_clock`#

a| emoji:hole[2x] a| [small]#`hole`#
a| emoji:ribbon[2x] a| [small]#`ribbon`#

a| emoji:gift[2x] a| [small]#`gift`#
a| emoji:birthday[2x] a| [small]#`birthday`#

a| emoji:jack_o_lantern[2x] a| [small]#`jack_o_lantern`#
a| emoji:christmas_tree[2x] a| [small]#`christmas_tree`#

a| emoji:fireworks[2x] a| [small]#`fireworks`#
a| emoji:sparkler[2x] a| [small]#`sparkler`#

a| emoji:balloon[2x] a| [small]#`balloon`#
a| emoji:tada[2x] a| [small]#`tada`#

a| emoji:confetti_ball[2x] a| [small]#`confetti_ball`#
a| emoji:tanabata_tree[2x] a| [small]#`tanabata_tree`#

a| emoji:crossed_flags[2x] a| [small]#`crossed_flags`#
a| emoji:bamboo[2x] a| [small]#`bamboo`#

a| emoji:dolls[2x] a| [small]#`dolls`#
a| emoji:flags[2x] a| [small]#`flags`#

a| emoji:wind_chime[2x] a| [small]#`wind_chime`#
a| emoji:rice_scene[2x] a| [small]#`rice_scene`#

a| emoji:school_satchel[2x] a| [small]#`school_satchel`#
a| emoji:mortar_board[2x] a| [small]#`mortar_board`#

a| emoji:medal[2x] a| [small]#`medal`#
a| emoji:reminder_ribbon[2x] a| [small]#`reminder_ribbon`#

a| emoji:studio_microphone[2x] a| [small]#`studio_microphone`#
a| emoji:level_slider[2x] a| [small]#`level_slider`#

a| emoji:control_knobs[2x] a| [small]#`control_knobs`#
a| emoji:film_frames[2x] a| [small]#`film_frames`#

a| emoji:admission_tickets[2x] a| [small]#`admission_tickets`#
a| emoji:carousel_horse[2x] a| [small]#`carousel_horse`#

a| emoji:ferris_wheel[2x] a| [small]#`ferris_wheel`#
a| emoji:roller_coaster[2x] a| [small]#`roller_coaster`#

a| emoji:fishing_pole_and_fish[2x] a| [small]#`fishing_pole_and_fish`#
a| emoji:microphone[2x] a| [small]#`microphone`#

a| emoji:movie_camera[2x] a| [small]#`movie_camera`#
a| emoji:cinema[2x] a| [small]#`cinema`#

a| emoji:headphones[2x] a| [small]#`headphones`#
a| emoji:art[2x] a| [small]#`art`#

a| emoji:tophat[2x] a| [small]#`tophat`#
a| emoji:circus_tent[2x] a| [small]#`circus_tent`#

a| emoji:ticket[2x] a| [small]#`ticket`#
a| emoji:clapper[2x] a| [small]#`clapper`#

a| emoji:performing_arts[2x] a| [small]#`performing_arts`#
a| emoji:video_game[2x] a| [small]#`video_game`#

a| emoji:dart[2x] a| [small]#`dart`#
a| emoji:slot_machine[2x] a| [small]#`slot_machine`#

a| emoji:8ball[2x] a| [small]#`8ball`#
a| emoji:game_die[2x] a| [small]#`game_die`#

a| emoji:bowling[2x] a| [small]#`bowling`#
a| emoji:flower_playing_cards[2x] a| [small]#`flower_playing_cards`#

a| emoji:musical_note[2x] a| [small]#`musical_note`#
a| emoji:notes[2x] a| [small]#`notes`#

a| emoji:saxophone[2x] a| [small]#`saxophone`#
a| emoji:guitar[2x] a| [small]#`guitar`#

a| emoji:musical_keyboard[2x] a| [small]#`musical_keyboard`#
a| emoji:trumpet[2x] a| [small]#`trumpet`#

a| emoji:violin[2x] a| [small]#`violin`#
a| emoji:musical_score[2x] a| [small]#`musical_score`#

a| emoji:running_shirt_with_sash[2x] a| [small]#`running_shirt_with_sash`#
a| emoji:waving_white_flag[2x] a| [small]#`waving_white_flag`#

a| emoji:waving_black_flag[2x] a| [small]#`waving_black_flag`#
a| emoji:rosette[2x] a| [small]#`rosette`#

a| emoji:label[2x] a| [small]#`label`#
a| emoji:badminton_racquet_and_shuttlecock[2x] a| [small]#`badminton_racquet_and_shuttlecock`#

a| emoji:bow_and_arrow[2x] a| [small]#`bow_and_arrow`#
a| emoji:amphora[2x] a| [small]#`amphora`#

a| emoji:crown[2x] a| [small]#`crown`#
a| emoji:womans_hat[2x] a| [small]#`womans_hat`#

a| emoji:eyeglasses[2x] a| [small]#`eyeglasses`#
a| emoji:necktie[2x] a| [small]#`necktie`#

a| emoji:shirt[2x] a| [small]#`shirt`#
a| emoji:jeans[2x] a| [small]#`jeans`#

a| emoji:dress[2x] a| [small]#`dress`#
a| emoji:kimono[2x] a| [small]#`kimono`#

a| emoji:bikini[2x] a| [small]#`bikini`#
a| emoji:womans_clothes[2x] a| [small]#`womans_clothes`#

a| emoji:purse[2x] a| [small]#`purse`#
a| emoji:handbag[2x] a| [small]#`handbag`#

a| emoji:pouch[2x] a| [small]#`pouch`#
a| emoji:mans_shoe[2x] a| [small]#`mans_shoe`#

a| emoji:athletic_shoe[2x] a| [small]#`athletic_shoe`#
a| emoji:high_heel[2x] a| [small]#`high_heel`#

a| emoji:sandal[2x] a| [small]#`sandal`#
a| emoji:boot[2x] a| [small]#`boot`#

a| emoji:footprints[2x] a| [small]#`footprints`#
a| emoji:barber[2x] a| [small]#`barber`#

a| emoji:syringe[2x] a| [small]#`syringe`#
a| emoji:pill[2x] a| [small]#`pill`#

a| emoji:kiss[2x] a| [small]#`kiss`#
a| emoji:love_letter[2x] a| [small]#`love_letter`#

a| emoji:ring[2x] a| [small]#`ring`#
a| emoji:gem[2x] a| [small]#`gem`#

a| emoji:couplekiss[2x] a| [small]#`couplekiss`#
a| emoji:bouquet[2x] a| [small]#`bouquet`#

a| emoji:couple_with_heart[2x] a| [small]#`couple_with_heart`#
a| emoji:wedding[2x] a| [small]#`wedding`#

a| emoji:heartbeat[2x] a| [small]#`heartbeat`#
a| emoji:broken_heart[2x] a| [small]#`broken_heart`#

a| emoji:two_hearts[2x] a| [small]#`two_hearts`#
a| emoji:sparkling_heart[2x] a| [small]#`sparkling_heart`#

a| emoji:heartpulse[2x] a| [small]#`heartpulse`#
a| emoji:cupid[2x] a| [small]#`cupid`#

a| emoji:blue_heart[2x] a| [small]#`blue_heart`#
a| emoji:green_heart[2x] a| [small]#`green_heart`#

a| emoji:yellow_heart[2x] a| [small]#`yellow_heart`#
a| emoji:purple_heart[2x] a| [small]#`purple_heart`#

a| emoji:gift_heart[2x] a| [small]#`gift_heart`#
a| emoji:revolving_hearts[2x] a| [small]#`revolving_hearts`#

a| emoji:heart_decoration[2x] a| [small]#`heart_decoration`#
a| emoji:diamond_shape_with_a_dot_inside[2x] a| [small]#`diamond_shape_with_a_dot_inside`#

a| emoji:bulb[2x] a| [small]#`bulb`#
a| emoji:anger[2x] a| [small]#`anger`#

a| emoji:bomb[2x] a| [small]#`bomb`#
a| emoji:zzz[2x] a| [small]#`zzz`#

a| emoji:boom[2x] a| [small]#`boom`#
a| emoji:sweat_drops[2x] a| [small]#`sweat_drops`#

a| emoji:droplet[2x] a| [small]#`droplet`#
a| emoji:dash[2x] a| [small]#`dash`#

a| emoji:hankey[2x] a| [small]#`hankey`#
a| a|

|===

=== Activity

[cols="10,40,10,40", header=true]
|===

a| Emoji
a| Code
a| Emoji
a| Code

a| emoji:bicyclist-skin-tone-2[2x] a| [small]#`bicyclist-skin-tone-2`#
a| emoji:bicyclist-skin-tone-3[2x] a| [small]#`bicyclist-skin-tone-3`#

a| emoji:bicyclist-skin-tone-4[2x] a| [small]#`bicyclist-skin-tone-4`#
a| emoji:bicyclist-skin-tone-5[2x] a| [small]#`bicyclist-skin-tone-5`#

a| emoji:bicyclist-skin-tone-6[2x] a| [small]#`bicyclist-skin-tone-6`#
a| emoji:bicyclist[2x] a| [small]#`bicyclist`#

a| emoji:mountain_bicyclist-skin-tone-2[2x] a| [small]#`mountain_bicyclist-skin-tone-2`#
a| emoji:mountain_bicyclist-skin-tone-3[2x] a| [small]#`mountain_bicyclist-skin-tone-3`#

a| emoji:mountain_bicyclist-skin-tone-4[2x] a| [small]#`mountain_bicyclist-skin-tone-4`#
a| emoji:mountain_bicyclist-skin-tone-5[2x] a| [small]#`mountain_bicyclist-skin-tone-5`#

a| emoji:mountain_bicyclist-skin-tone-6[2x] a| [small]#`mountain_bicyclist-skin-tone-6`#
a| emoji:mountain_bicyclist[2x] a| [small]#`mountain_bicyclist`#

a| emoji:walking-skin-tone-2[2x] a| [small]#`walking-skin-tone-2`#
a| emoji:walking-skin-tone-3[2x] a| [small]#`walking-skin-tone-3`#

a| emoji:walking-skin-tone-4[2x] a| [small]#`walking-skin-tone-4`#
a| emoji:walking-skin-tone-5[2x] a| [small]#`walking-skin-tone-5`#

a| emoji:walking-skin-tone-6[2x] a| [small]#`walking-skin-tone-6`#
a| emoji:walking[2x] a| [small]#`walking`#

a| emoji:skier[2x] a| [small]#`skier`#
a| emoji:ice_skate[2x] a| [small]#`ice_skate`#

a| emoji:person_with_ball-skin-tone-2[2x] a| [small]#`person_with_ball-skin-tone-2`#
a| emoji:person_with_ball-skin-tone-3[2x] a| [small]#`person_with_ball-skin-tone-3`#

a| emoji:person_with_ball-skin-tone-4[2x] a| [small]#`person_with_ball-skin-tone-4`#
a| emoji:person_with_ball-skin-tone-5[2x] a| [small]#`person_with_ball-skin-tone-5`#

a| emoji:person_with_ball-skin-tone-6[2x] a| [small]#`person_with_ball-skin-tone-6`#
a| emoji:person_with_ball[2x] a| [small]#`person_with_ball`#

a| emoji:golf[2x] a| [small]#`golf`#
a| emoji:tennis[2x] a| [small]#`tennis`#

a| emoji:ski[2x] a| [small]#`ski`#
a| emoji:basketball[2x] a| [small]#`basketball`#

a| emoji:checkered_flag[2x] a| [small]#`checkered_flag`#
a| emoji:snowboarder-skin-tone-2[2x] a| [small]#`snowboarder-skin-tone-2`#

a| emoji:snowboarder-skin-tone-3[2x] a| [small]#`snowboarder-skin-tone-3`#
a| emoji:snowboarder-skin-tone-4[2x] a| [small]#`snowboarder-skin-tone-4`#

a| emoji:snowboarder-skin-tone-5[2x] a| [small]#`snowboarder-skin-tone-5`#
a| emoji:snowboarder-skin-tone-6[2x] a| [small]#`snowboarder-skin-tone-6`#

a| emoji:snowboarder[2x] a| [small]#`snowboarder`#
a| emoji:runner-skin-tone-2[2x] a| [small]#`runner-skin-tone-2`#

a| emoji:runner-skin-tone-3[2x] a| [small]#`runner-skin-tone-3`#
a| emoji:runner-skin-tone-4[2x] a| [small]#`runner-skin-tone-4`#

a| emoji:runner-skin-tone-5[2x] a| [small]#`runner-skin-tone-5`#
a| emoji:runner-skin-tone-6[2x] a| [small]#`runner-skin-tone-6`#

a| emoji:runner[2x] a| [small]#`runner`#
a| emoji:surfer-skin-tone-2[2x] a| [small]#`surfer-skin-tone-2`#

a| emoji:surfer-skin-tone-3[2x] a| [small]#`surfer-skin-tone-3`#
a| emoji:surfer-skin-tone-4[2x] a| [small]#`surfer-skin-tone-4`#

a| emoji:surfer-skin-tone-5[2x] a| [small]#`surfer-skin-tone-5`#
a| emoji:surfer-skin-tone-6[2x] a| [small]#`surfer-skin-tone-6`#

a| emoji:surfer[2x] a| [small]#`surfer`#
a| emoji:sports_medal[2x] a| [small]#`sports_medal`#

a| emoji:trophy[2x] a| [small]#`trophy`#
a| emoji:horse_racing-skin-tone-2[2x] a| [small]#`horse_racing-skin-tone-2`#

a| emoji:horse_racing-skin-tone-3[2x] a| [small]#`horse_racing-skin-tone-3`#
a| emoji:horse_racing-skin-tone-4[2x] a| [small]#`horse_racing-skin-tone-4`#

a| emoji:horse_racing-skin-tone-5[2x] a| [small]#`horse_racing-skin-tone-5`#
a| emoji:horse_racing-skin-tone-6[2x] a| [small]#`horse_racing-skin-tone-6`#

a| emoji:horse_racing[2x] a| [small]#`horse_racing`#
a| emoji:football[2x] a| [small]#`football`#

a| emoji:rugby_football[2x] a| [small]#`rugby_football`#
a| emoji:swimmer-skin-tone-2[2x] a| [small]#`swimmer-skin-tone-2`#

a| emoji:swimmer-skin-tone-3[2x] a| [small]#`swimmer-skin-tone-2`#
a| emoji:swimmer-skin-tone-4[2x] a| [small]#`swimmer-skin-tone-4`#

a| emoji:swimmer-skin-tone-5[2x] a| [small]#`swimmer-skin-tone-5`#
a| emoji:swimmer-skin-tone-6[2x] a| [small]#`swimmer-skin-tone-6`#

a| emoji:swimmer[2x] a| [small]#`swimmer`#
a| emoji:weight_lifter-skin-tone-2[2x] a| [small]#`weight_lifter-skin-tone-2`#

a| emoji:weight_lifter-skin-tone-3[2x] a| [small]#`weight_lifter-skin-tone-3`#
a| emoji:weight_lifter-skin-tone-4[2x] a| [small]#`weight_lifter-skin-tone-4`#

a| emoji:weight_lifter-skin-tone-5[2x] a| [small]#`weight_lifter-skin-tone-5`#
a| emoji:weight_lifter-skin-tone-6[2x] a| [small]#`weight_lifter-skin-tone-6`#

a| emoji:weight_lifter[2x] a| [small]#`weight_lifter`#
a| emoji:golfer[2x] a| [small]#`golfer`#

a| emoji:racing_motorcycle[2x] a| [small]#`racing_motorcycle`#
a| emoji:racing_car[2x] a| [small]#`racing_car`#

a| emoji:cricket_bat_and_ball[2x] a| [small]#`cricket_bat_and_ball`#
a| emoji:volleyball[2x] a| [small]#`volleyball`#

a| emoji:field_hockey_stick_and_ball[2x] a| [small]#`field_hockey_stick_and_ball`#
a| emoji:ice_hockey_stick_and_puck[2x] a| [small]#`ice_hockey_stick_and_puck`#

a| emoji:table_tennis_paddle_and_ball[2x] a| [small]#`table_tennis_paddle_and_ball`#
a| a|

|===

=== Travel & Places

[cols="10,40,10,40", header=true]
|===

a| Emoji
a| Code
a| Emoji
a| Code

a| emoji:airplane[2x] a| [small]#`airplane`#
a| emoji:ferry[2x] a| [small]#`ferry`#

a| emoji:boat[2x] a| [small]#`boat`#
a| emoji:shinto_shrine[2x] a| [small]#`shinto_shrine`#

a| emoji:church[2x] a| [small]#`church`#
a| emoji:mountain[2x] a| [small]#`mountain`#

a| emoji:rowboat-skin-tone-2[2x] a| [small]#`rowboat-skin-tone-2`#
a| emoji:rowboat-skin-tone-3[2x] a| [small]#`rowboat-skin-tone-3`#

a| emoji:rowboat-skin-tone-4[2x] a| [small]#`rowboat-skin-tone-4`#
a| emoji:rowboat-skin-tone-5[2x] a| [small]#`rowboat-skin-tone-5`#

a| emoji:rowboat-skin-tone-6[2x] a| [small]#`rowboat-skin-tone-6`#
a| emoji:rowboat[2x] a| [small]#`rowboat`#

a| emoji:speedboat[2x] a| [small]#`speedboat`#
a| emoji:rocket[2x] a| [small]#`rocket`#

a| emoji:helicopter[2x] a| [small]#`helicopter`#
a| emoji:steam_locomotive[2x] a| [small]#`steam_locomotive`#

a| emoji:railway_car[2x] a| [small]#`railway_car`#
a| emoji:bullettrain_side[2x] a| [small]#`bullettrain_side`#

a| emoji:bullettrain_front[2x] a| [small]#`bullettrain_front`#
a| emoji:train2[2x] a| [small]#`train2`#

a| emoji:metro[2x] a| [small]#`metro`#
a| emoji:light_rail[2x] a| [small]#`light_rail`#

a| emoji:station[2x] a| [small]#`station`#
a| emoji:tram[2x] a| [small]#`tram`#

a| emoji:train[2x] a| [small]#`train`#
a| emoji:bus[2x] a| [small]#`bus`#

a| emoji:oncoming_bus[2x] a| [small]#`oncoming_bus`#
a| emoji:trolleybus[2x] a| [small]#`trolleybus`#

a| emoji:busstop[2x] a| [small]#`busstop`#
a| emoji:minibus[2x] a| [small]#`minibus`#

a| emoji:ambulance[2x] a| [small]#`ambulance`#
a| emoji:fire_engine[2x] a| [small]#`fire_engine`#

a| emoji:police_car[2x] a| [small]#`police_car`#
a| emoji:oncoming_police_car[2x] a| [small]#`oncoming_police_car`#

a| emoji:taxi[2x] a| [small]#`taxi`#
a| emoji:oncoming_taxi[2x] a| [small]#`oncoming_taxi`#

a| emoji:car[2x] a| [small]#`car`#
a| emoji:oncoming_automobile[2x] a| [small]#`oncoming_automobile`#

a| emoji:blue_car[2x] a| [small]#`blue_car`#
a| emoji:truck[2x] a| [small]#`truck`#

a| emoji:articulated_lorry[2x] a| [small]#`articulated_lorry`#
a| emoji:tractor[2x] a| [small]#`tractor`#

a| emoji:monorail[2x] a| [small]#`monorail`#
a| emoji:mountain_railway[2x] a| [small]#`mountain_railway`#

a| emoji:suspension_railway[2x] a| [small]#`suspension_railway`#
a| emoji:mountain_cableway[2x] a| [small]#`mountain_cableway`#

a| emoji:aerial_tramway[2x] a| [small]#`aerial_tramway`#
a| emoji:ship[2x] a| [small]#`ship`#

a| emoji:world_map[2x] a| [small]#`world_map`#
a| emoji:mount_fuji[2x] a| [small]#`mount_fuji`#

a| emoji:tokyo_tower[2x] a| [small]#`tokyo_tower`#
a| emoji:statue_of_liberty[2x] a| [small]#`statue_of_liberty`#

a| emoji:japan[2x] a| [small]#`japan`#
a| emoji:moyai[2x] a| [small]#`moyai`#

a| emoji:snow_capped_mountain[2x] a| [small]#`snow_capped_mountain`#
a| emoji:camping[2x] a| [small]#`camping`#

a| emoji:beach_with_umbrella[2x] a| [small]#`beach_with_umbrella`#
a| emoji:building_construction[2x] a| [small]#`building_construction`#

a| emoji:house_buildings[2x] a| [small]#`house_buildings`#
a| emoji:cityscape[2x] a| [small]#`cityscape`#

a| emoji:derelict_house_building[2x] a| [small]#`derelict_house_building`#
a| emoji:classical_building[2x] a| [small]#`classical_building`#

a| emoji:desert[2x] a| [small]#`desert`#
a| emoji:desert_island[2x] a| [small]#`desert_island`#

a| emoji:national_park[2x] a| [small]#`national_park`#
a| emoji:stadium[2x] a| [small]#`stadium`#

a| emoji:house[2x] a| [small]#`house`#
a| emoji:house_with_garden[2x] a| [small]#`house_with_garden`#

a| emoji:office[2x] a| [small]#`office`#
a| emoji:post_office[2x] a| [small]#`post_office`#

a| emoji:european_post_office[2x] a| [small]#`european_post_office`#
a| emoji:hospital[2x] a| [small]#`hospital`#

a| emoji:bank[2x] a| [small]#`bank`#
a| emoji:atm[2x] a| [small]#`atm`#

a| emoji:hotel[2x] a| [small]#`hotel`#
a| emoji:love_hotel[2x] a| [small]#`love_hotel`#

a| emoji:convenience_store[2x] a| [small]#`convenience_store`#
a| emoji:school[2x] a| [small]#`school`#

a| emoji:department_store[2x] a| [small]#`department_store`#
a| emoji:factory[2x] a| [small]#`factory`#

a| emoji:izakaya_lantern[2x] a| [small]#`izakaya_lantern`#
a| emoji:japanese_castle[2x] a| [small]#`japanese_castle`#

a| emoji:european_castle[2x] a| [small]#`european_castle`#
a| a|

|===

=== Symbols

[cols="10,40,10,40", header=true]
|===

a| Emoji
a| Code
a| Emoji
a| Code

a| emoji:latin_cross[2x] a| [small]#`latin_cross`#
a| emoji:star_of_david[2x] a| [small]#`star_of_david`#

a| emoji:sparkles[2x] a| [small]#`sparkles`#
a| emoji:eight_spoked_asterisk[2x] a| [small]#`eight_spoked_asterisk`#

a| emoji:eight_pointed_black_star[2x] a| [small]#`eight_pointed_black_star`#
a| emoji:snowflake[2x] a| [small]#`snowflake`#

a| emoji:sparkle[2x] a| [small]#`sparkle`#
a| emoji:cross_mark[2x] a| [small]#`cross_mark`#

a| emoji:negative_squared_cross_mark[2x] a| [small]#`negative_squared_cross_mark`#
a| emoji:question[2x] a| [small]#`question`#

a| emoji:grey_question[2x] a| [small]#`grey_question`#
a| emoji:grey_exclamation[2x] a| [small]#`grey_exclamation`#

a| emoji:exclamation[2x] a| [small]#`exclamation`#
a| emoji:heavy_heart_exclamation_mark_ornament[2x] a| [small]#`heavy_heart_exclamation_mark_ornament`#

a| emoji:shibuya[2x] a| [small]#`shibuya`#
a| emoji:heart[2x] a| [small]#`heart`#

a| emoji:heavy_plus_sign[2x] a| [small]#`heavy_plus_sign`#
a| emoji:heavy_minus_sign[2x] a| [small]#`heavy_minus_sign`#

a| emoji:heavy_division_sign[2x] a| [small]#`heavy_division_sign`#
a| emoji:curly_loop[2x] a| [small]#`curly_loop`#

a| emoji:loop[2x] a| [small]#`loop`#
a| emoji:arrow_right[2x] a| [small]#`arrow_right`#

a| emoji:arrow_heading_up[2x] a| [small]#`arrow_heading_up`#
a| emoji:arrow_heading_down[2x] a| [small]#`arrow_heading_down`#

a| emoji:asterisk[2x] a| [small]#`asterisk`#
a| emoji:arrow_left[2x] a| [small]#`arrow_left`#

a| emoji:arrow_up[2x] a| [small]#`arrow_up`#
a| emoji:arrow_down[2x] a| [small]#`arrow_down`#

a| emoji:zero[2x] a| [small]#`zero`#
a| emoji:one[2x] a| [small]#`one`#

a| emoji:two[2x] a| [small]#`two`#
a| emoji:three[2x] a| [small]#`three`#

a| emoji:four[2x] a| [small]#`four`#
a| emoji:five[2x] a| [small]#`five`#

a| emoji:six[2x] a| [small]#`six`#
a| emoji:seven[2x] a| [small]#`seven`#

a| emoji:eight[2x] a| [small]#`eight`#
a| emoji:nine[2x] a| [small]#`nine`#

a| emoji:copyright[2x] a| [small]#`copyright`#
a| emoji:registered_sign[2x] a| [small]#`registered_sign`#

a| emoji:black_large_square[2x] a| [small]#`black_large_square`#
a| emoji:white_large_square[2x] a| [small]#`white_large_square`#

a| emoji:star[2x] a| [small]#`star`#
a| emoji:large_circle[2x] a| [small]#`large_circle`#

a| emoji:wavy_dash[2x] a| [small]#`wavy_dash`#
a| emoji:part_alternation_mark[2x] a| [small]#`part_alternation_mark`#

a| emoji:heavy_check_mark[2x] a| [small]#`heavy_check_mark`#
a| emoji:heavy_multiplication_x[2x] a| [small]#`heavy_multiplication_x`#

a| emoji:email[2x] a| [small]#`email`#
a| emoji:white_check_mark[2x] a| [small]#`white_check_mark`#

a| emoji:no_entry[2x] a| [small]#`no_entry`#
a| emoji:ophiuchus[2x] a| [small]#`ophiuchus`#

a| emoji:bike[2x] a| [small]#`bike`#
a| emoji:no_bicycles[2x] a| [small]#`no_bicycles`#

a| emoji:no_pedestrians[2x] a| [small]#`no_pedestrians`#
a| emoji:children_crossing[2x] a| [small]#`children_crossing`#

a| emoji:mens[2x] a| [small]#`mens`#
a| emoji:womens[2x] a| [small]#`womens`#

a| emoji:restroom[2x] a| [small]#`restroom`#
a| emoji:baby_symbol[2x] a| [small]#`baby_symbol`#

a| emoji:toilet[2x] a| [small]#`toilet`#
a| emoji:wc[2x] a| [small]#`wc`#

a| emoji:shower[2x] a| [small]#`shower`#
a| emoji:bath-skin-tone-2[2x] a| [small]#`bath-skin-tone-2`#

a| emoji:bath-skin-tone-3[2x] a| [small]#`bath-skin-tone-3`#
a| emoji:bath-skin-tone-4[2x] a| [small]#`bath-skin-tone-4`#

a| emoji:bath-skin-tone-5[2x] a| [small]#`bath-skin-tone-5`#
a| emoji:bath-skin-tone-6[2x] a| [small]#`bath-skin-tone-6`#

a| emoji:bath[2x] a| [small]#`bath`#
a| emoji:bathtub[2x] a| [small]#`bathtub`#

a| emoji:passport_control[2x] a| [small]#`passport_control`#
a| emoji:customs[2x] a| [small]#`customs`#

a| emoji:baggage_claim[2x] a| [small]#`baggage_claim`#
a| emoji:left_luggage[2x] a| [small]#`left_luggage`#

a| emoji:couch_and_lamp[2x] a| [small]#`couch_and_lamp`#
a| emoji:sleeping_accommodation[2x] a| [small]#`sleeping_accommodation`#

a| emoji:shopping_bags[2x] a| [small]#`shopping_bags`#
a| emoji:bellhop_bell[2x] a| [small]#`bellhop_bell`#

a| emoji:bed[2x] a| [small]#`bed`#
a| emoji:place_of_worship[2x] a| [small]#`place_of_worship`#

a| emoji:hammer_and_wrench[2x] a| [small]#`hammer_and_wrench`#
a| emoji:shield[2x] a| [small]#`shield`#

a| emoji:oil_drum[2x] a| [small]#`oil_drum`#
a| emoji:motorway[2x] a| [small]#`motorway`#

a| emoji:railway_track[2x] a| [small]#`railway_track`#
a| emoji:motor_boat[2x] a| [small]#`motor_boat`#

a| emoji:small_airplane[2x] a| [small]#`small_airplane`#
a| emoji:airplane_departure[2x] a| [small]#`airplane_departure`#

a| emoji:airplane_arriving[2x] a| [small]#`airplane_arriving`#
a| emoji:satellite[2x] a| [small]#`satellite`#

a| emoji:passenger_ship[2x] a| [small]#`passenger_ship`#
a| emoji:door[2x] a| [small]#`door`#

a| emoji:no_entry_sign[2x] a| [small]#`no_entry_sign`#
a| emoji:smoking[2x] a| [small]#`smoking`#

a| emoji:no_smoking[2x] a| [small]#`no_smoking`#
a| emoji:put_litter_in_its_place[2x] a| [small]#`put_litter_in_its_place`#

a| emoji:do_not_litter[2x] a| [small]#`do_not_litter`#
a| emoji:potable_water[2x] a| [small]#`potable_water`#

a| emoji:non-potable_water[2x] a| [small]#`non-potable_water`#
a| emoji:traffic_light[2x] a| [small]#`traffic_light`#

a| emoji:vertical_traffic_light[2x] a| [small]#`vertical_traffic_light`#
a| emoji:construction[2x] a| [small]#`construction`#

a| emoji:rotating_light[2x] a| [small]#`rotating_light`#
a| emoji:triangular_flag_on_post[2x] a| [small]#`triangular_flag_on_post`#

a| emoji:speaking_head_in_silhouette[2x] a| [small]#`speaking_head_in_silhouette`#
a| emoji:left_speech_bubble[2x] a| [small]#`left_speech_bubble`#

a| emoji:right_anger_bubble[2x] a| [small]#`right_anger_bubble`#
a| emoji:eye_left_speech_bubble[2x] a| [small]#`eye_left_speech_bubble`#

a| emoji:desktop_computer[2x] a| [small]#`desktop_computer`#
a| emoji:printer[2x] a| [small]#`printer`#

a| emoji:three_button_mouse[2x] a| [small]#`three_button_mouse`#
a| emoji:trackball[2x] a| [small]#`trackball`#

a| emoji:frame_with_picture[2x] a| [small]#`frame_with_picture`#
a| emoji:card_index_dividers[2x] a| [small]#`card_index_dividers`#

a| emoji:card_file_box[2x] a| [small]#`card_file_box`#
a| emoji:file_cabinet[2x] a| [small]#`file_cabinet`#

a| emoji:dizzy[2x] a| [small]#`dizzy`#
a| emoji:speech_balloon[2x] a| [small]#`speech_balloon`#

a| emoji:thought_balloon[2x] a| [small]#`thought_balloon`#
a| emoji:white_flower[2x] a| [small]#`white_flower`#

a| emoji:100[2x] a| [small]#`100`#
a| emoji:moneybag[2x] a| [small]#`moneybag`#

a| emoji:currency_exchange[2x] a| [small]#`currency_exchange`#
a| emoji:heavy_dollar_sign[2x] a| [small]#`heavy_dollar_sign`#

a| emoji:credit_card[2x] a| [small]#`credit_card`#
a| emoji:yen[2x] a| [small]#`yen`#

a| emoji:dollar[2x] a| [small]#`dollar`#
a| emoji:euro[2x] a| [small]#`euro`#

a| emoji:pound[2x] a| [small]#`pound`#
a| emoji:money_with_wings[2x] a| [small]#`money_with_wings`#

a| emoji:chart[2x] a| [small]#`chart`#
a| emoji:seat[2x] a| [small]#`seat`#

a| emoji:computer[2x] a| [small]#`computer`#
a| emoji:briefcase[2x] a| [small]#`briefcase`#

a| emoji:minidisc[2x] a| [small]#`minidisc`#
a| emoji:floppy_disk[2x] a| [small]#`floppy_disk`#

a| emoji:cd[2x] a| [small]#`cd`#
a| emoji:dvd[2x] a| [small]#`dvd`#

a| emoji:file_folder[2x] a| [small]#`file_folder`#
a| emoji:open_file_folder[2x] a| [small]#`open_file_folder`#

a| emoji:page_with_curl[2x] a| [small]#`page_with_curl`#
a| emoji:page_facing_up[2x] a| [small]#`page_facing_up`#

a| emoji:date[2x] a| [small]#`date`#
a| emoji:calendar[2x] a| [small]#`calendar`#

a| emoji:card_index[2x] a| [small]#`card_index`#
a| emoji:chart_with_upwards_trend[2x] a| [small]#`chart_with_upwards_trend`#

a| emoji:chart_with_downwards_trend[2x] a| [small]#`chart_with_downwards_trend`#
a| emoji:bar_chart[2x] a| [small]#`bar_chart`#

a| emoji:clipboard[2x] a| [small]#`clipboard`#
a| emoji:pushpin[2x] a| [small]#`pushpin`#

a| emoji:round_pushpin[2x] a| [small]#`round_pushpin`#
a| emoji:paperclip[2x] a| [small]#`paperclip`#

a| emoji:straight_ruler[2x] a| [small]#`straight_ruler`#
a| emoji:triangular_ruler[2x] a| [small]#`triangular_ruler`#

a| emoji:bookmark_tabs[2x] a| [small]#`bookmark_tabs`#
a| emoji:ledger[2x] a| [small]#`ledger`#

a| emoji:notebook[2x] a| [small]#`notebook`#
a| emoji:notebook_with_decorative_cover[2x] a| [small]#`notebook_with_decorative_cover`#

a| emoji:closed_book[2x] a| [small]#`closed_book`#
a| emoji:book[2x] a| [small]#`book`#

a| emoji:green_book[2x] a| [small]#`green_book`#
a| emoji:blue_book[2x] a| [small]#`blue_book`#

a| emoji:orange_book[2x] a| [small]#`orange_book`#
a| emoji:books[2x] a| [small]#`books`#

a| emoji:name_badge[2x] a| [small]#`name_badge`#
a| emoji:scroll[2x] a| [small]#`scroll`#

a| emoji:memo[2x] a| [small]#`memo`#
a| emoji:telephone_receiver[2x] a| [small]#`telephone_receiver`#

a| emoji:pager[2x] a| [small]#`pager`#
a| emoji:fax[2x] a| [small]#`fax`#

a| emoji:satellite_antenna[2x] a| [small]#`satellite_antenna`#
a| emoji:loudspeaker[2x] a| [small]#`loudspeaker`#

a| emoji:mega[2x] a| [small]#`mega`#
a| emoji:outbox_tray[2x] a| [small]#`outbox_tray`#

a| emoji:inbox_tray[2x] a| [small]#`inbox_tray`#
a| emoji:package[2x] a| [small]#`package`#

a| emoji:e-mail[2x] a| [small]#`e-mail`#
a| emoji:incoming_envelope[2x] a| [small]#`incoming_envelope`#

a| emoji:envelope_with_arrow[2x] a| [small]#`envelope_with_arrow`#
a| emoji:mailbox_closed[2x] a| [small]#`mailbox_closed`#

a| emoji:mailbox[2x] a| [small]#`mailbox`#
a| emoji:mailbox_with_mail[2x] a| [small]#`mailbox_with_mail`#

a| emoji:mailbox_with_no_mail[2x] a| [small]#`mailbox_with_no_mail`#
a| emoji:postbox[2x] a| [small]#`postbox`#

a| emoji:postal_horn[2x] a| [small]#`postal_horn`#
a| emoji:newspaper[2x] a| [small]#`newspaper`#

a| emoji:iphone[2x] a| [small]#`iphone`#
a| emoji:calling[2x] a| [small]#`calling`#

a| emoji:vibration_mode[2x] a| [small]#`vibration_mode`#
a| emoji:mobile_phone_off[2x] a| [small]#`mobile_phone_off`#

a| emoji:no_mobile_phones[2x] a| [small]#`no_mobile_phones`#
a| emoji:signal_strength[2x] a| [small]#`signal_strength`#

a| emoji:camera[2x] a| [small]#`camera`#
a| emoji:camera_with_flash[2x] a| [small]#`camera_with_flash`#

a| emoji:video_camera[2x] a| [small]#`video_camera`#
a| emoji:tv[2x] a| [small]#`tv`#

a| emoji:radio[2x] a| [small]#`radio`#
a| emoji:vhs[2x] a| [small]#`vhs`#

a| emoji:film_projector[2x] a| [small]#`film_projector`#
a| emoji:prayer_beads[2x] a| [small]#`prayer_beads`#

a| emoji:twisted_rightwards_arrows[2x] a| [small]#`twisted_rightwards_arrows`#
a| emoji:repeat[2x] a| [small]#`repeat`#

a| emoji:repeat_one[2x] a| [small]#`repeat_one`#
a| emoji:arrows_clockwise[2x] a| [small]#`arrows_clockwise`#

a| emoji:arrows_counterclockwise[2x] a| [small]#`arrows_counterclockwise`#
a| emoji:low_brightness[2x] a| [small]#`low_brightness`#

a| emoji:high_brightness[2x] a| [small]#`high_brightness`#
a| emoji:mute[2x] a| [small]#`mute`#

a| emoji:speaker[2x] a| [small]#`speaker`#
a| emoji:sound[2x] a| [small]#`sound`#

a| emoji:loud_sound[2x] a| [small]#`loud_sound`#
a| emoji:battery[2x] a| [small]#`battery`#

a| emoji:electric_plug[2x] a| [small]#`electric_plug`#
a| emoji:mag[2x] a| [small]#`mag`#

a| emoji:mag_right[2x] a| [small]#`mag_right`#
a| emoji:lock_with_ink_pen[2x] a| [small]#`lock_with_ink_pen`#

a| emoji:closed_lock_with_key[2x] a| [small]#`closed_lock_with_key`#
a| emoji:key[2x] a| [small]#`key`#

a| emoji:lock[2x] a| [small]#`lock`#
a| emoji:unlock[2x] a| [small]#`unlock`#

a| emoji:bell[2x] a| [small]#`bell`#
a| emoji:no_bell[2x] a| [small]#`no_bell`#

a| emoji:bookmark[2x] a| [small]#`bookmark`#
a| emoji:link[2x] a| [small]#`link`#

a| emoji:radio_button[2x] a| [small]#`radio_button`#
a| emoji:back[2x] a| [small]#`back`#

a| emoji:end[2x] a| [small]#`end`#
a| emoji:on[2x] a| [small]#`on`#

a| emoji:soon[2x] a| [small]#`soon`#
a| emoji:top[2x] a| [small]#`top`#

a| emoji:underage[2x] a| [small]#`underage`#
a| emoji:keycap_ten[2x] a| [small]#`keycap_ten`#

a| emoji:capital_abcd[2x] a| [small]#`capital_abcd`#
a| emoji:abcd[2x] a| [small]#`abcd`#

a| emoji:1234[2x] a| [small]#`1234`#
a| emoji:symbols[2x] a| [small]#`symbols`#

a| emoji:abc[2x] a| [small]#`abc`#
a| emoji:fire[2x] a| [small]#`fire`#

a| emoji:flashlight[2x] a| [small]#`flashlight`#
a| emoji:wrench[2x] a| [small]#`wrench`#

a| emoji:hammer[2x] a| [small]#`hammer`#
a| emoji:nut_and_bolt[2x] a| [small]#`nut_and_bolt`#

a| emoji:hocho[2x] a| [small]#`hocho`#
a| emoji:gun[2x] a| [small]#`gun`#

a| emoji:microscope[2x] a| [small]#`microscope`#
a| emoji:telescope[2x] a| [small]#`telescope`#

a| emoji:crystal_ball[2x] a| [small]#`crystal_ball`#
a| emoji:six_pointed_star[2x] a| [small]#`six_pointed_star`#

a| emoji:beginner[2x] a| [small]#`beginner`#
a| emoji:trident[2x] a| [small]#`trident`#

a| emoji:black_square_button[2x] a| [small]#`black_square_button`#
a| emoji:white_square_button[2x] a| [small]#`white_square_button`#

a| emoji:red_circle[2x] a| [small]#`red_circle`#
a| emoji:large_blue_circle[2x] a| [small]#`large_blue_circle`#

a| emoji:large_orange_diamond[2x] a| [small]#`large_orange_diamond`#
a| emoji:large_blue_diamond[2x] a| [small]#`large_blue_diamond`#

a| emoji:small_orange_diamond[2x] a| [small]#`small_orange_diamond`#
a| emoji:small_blue_diamond[2x] a| [small]#`small_blue_diamond`#

a| emoji:small_red_triangle[2x] a| [small]#`small_red_triangle`#
a| emoji:small_red_triangle_down[2x] a| [small]#`small_red_triangle_down`#

a| emoji:arrow_up_small[2x] a| [small]#`arrow_up_small`#
a| emoji:arrow_down_small[2x] a| [small]#`arrow_down_small`#

a| emoji:om_symbol[2x] a| [small]#`om_symbol`#
a| emoji:dove_of_peace[2x] a| [small]#`dove_of_peace`#

a| emoji:kaaba[2x] a| [small]#`kaaba`#
a| emoji:mosque[2x] a| [small]#`mosque`#

a| emoji:synagogue[2x] a| [small]#`synagogue`#
a| emoji:menorah_with_nine_branches[2x] a| [small]#`menorah_with_nine_branches`#

a| emoji:clock1[2x] a| [small]#`clock1`#
a| emoji:clock2[2x] a| [small]#`clock2`#

a| emoji:clock3[2x] a| [small]#`clock3`#
a| emoji:clock4[2x] a| [small]#`clock4`#

a| emoji:clock5[2x] a| [small]#`clock5`#
a| emoji:clock6[2x] a| [small]#`clock6`#

a| emoji:clock7[2x] a| [small]#`clock7`#
a| emoji:clock8[2x] a| [small]#`clock8`#

a| emoji:clock9[2x] a| [small]#`clock9`#
a| emoji:clock10[2x] a| [small]#`clock10`#

a| emoji:clock11[2x] a| [small]#`clock11`#
a| emoji:clock12[2x] a| [small]#`clock12`#

a| emoji:clock130[2x] a| [small]#`clock130`#
a| emoji:clock230[2x] a| [small]#`clock230`#

a| emoji:clock330[2x] a| [small]#`clock330`#
a| emoji:clock430[2x] a| [small]#`clock430`#

a| emoji:clock530[2x] a| [small]#`clock530`#
a| emoji:clock630[2x] a| [small]#`clock630`#

a| emoji:clock730[2x] a| [small]#`clock730`#
a| emoji:clock830[2x] a| [small]#`clock830`#

a| emoji:clock930[2x] a| [small]#`clock930`#
a| emoji:clock1030[2x] a| [small]#`clock1030`#

a| emoji:clock1130[2x] a| [small]#`clock1130`#
a| emoji:clock1230[2x] a| [small]#`clock1230`#

a| emoji:mahjong[2x] a| [small]#``mahjong``#
a| emoji:black_joker[2x] a| [small]#``black_joker``#

a| emoji:a_negative[2x] a| [small]#``a_negative``#
a| emoji:b_negative[2x] a| [small]#`b_negative`#

a| emoji:o_negative[2x] a| [small]#`o_negative`#
a| emoji:parking[2x] a| [small]#`parking`#

a| emoji:double_exclamation_mark[2x] a| [small]#`double_exclamation_mark`#
a| emoji:interrobang[2x] a| [small]#`interrobang`#

a| emoji:trade_mark[2x] a| [small]#`trade_mark`#
a| emoji:information_source[2x] a| [small]#`information_source`#

a| emoji:left_right_arrow[2x] a| [small]#`left_right_arrow`#
a| emoji:arrow_up_down[2x] a| [small]#`arrow_up_down`#

a| emoji:arrow_upper_left[2x] a| [small]#`arrow_upper_left`#
a| emoji:arrow_upper_right[2x] a| [small]#`arrow_upper_right`#

a| emoji:arrow_lower_right[2x] a| [small]#`arrow_lower_right`#
a| emoji:arrow_lower_left[2x] a| [small]#`arrow_lower_left`#

a| emoji:leftwards_arrow_with_hook[2x] a| [small]#`leftwards_arrow_with_hook`#
a| emoji:arrow_right_hook[2x] a| [small]#`arrow_right_hook`#

a| emoji:hash[2x] a| [small]#`hash`#
a| emoji:watch[2x] a| [small]#`watch`#

a| emoji:hourglass[2x] a| [small]#`hourglass`#
a| emoji:keyboard[2x] a| [small]#`keyboard`#

a| emoji:eject[2x] a| [small]#`eject`#
a| emoji:fast_forward[2x] a| [small]#`fast_forward`#

a| emoji:rewind[2x] a| [small]#`rewind`#
a| emoji:arrow_double_up[2x] a| [small]#`arrow_double_up`#

a| emoji:arrow_double_down[2x] a| [small]#`arrow_double_down`#
a| emoji:black_right_pointing_double_triangle_with_vertical_bar[2x] a| [small]#`black_right_pointing_double_triangle_with_vertical_bar`#

a| emoji:black_left_pointing_double_triangle_with_vertical_bar[2x] a| [small]#`black_left_pointing_double_triangle_with_vertical_bar`#
a| emoji:black_right_pointing_triangle_with_double_vertical_bar[2x] a| [small]#`black_right_pointing_triangle_with_double_vertical_bar`#

a| emoji:alarm_clock[2x] a| [small]#`alarm_clock`#
a| emoji:stopwatch[2x] a| [small]#`stopwatch`#

a| emoji:timer_clock[2x] a| [small]#`timer_clock`#
a| emoji:hourglass_flowing_sand[2x] a| [small]#`hourglass_flowing_sand`#

a| emoji:double_vertical_bar[2x] a| [small]#`double_vertical_bar`#
a| emoji:black_square_for_stop[2x] a| [small]#`black_square_for_stop`#

a| emoji:black_circle_for_record[2x] a| [small]#`black_circle_for_record`#
a| emoji:m_circled[2x] a| [small]#`m_circled`#

a| emoji:black_small_square[2x] a| [small]#`black_small_square`#
a| emoji:white_small_square[2x] a| [small]#`white_small_square`#

a| emoji:arrow_forward[2x] a| [small]#`arrow_forward`#
a| emoji:arrow_backward[2x] a| [small]#`arrow_backward`#

a| emoji:white_medium_square[2x] a| [small]#`white_medium_square`#
a| emoji:black_medium_square[2x] a| [small]#`black_medium_square`#

a| emoji:white_medium_small_square[2x] a| [small]#`white_medium_small_square`#
a| emoji:black_medium_small_square[2x] a| [small]#`black_medium_small_square`#

a| emoji:ab[2x] a| [small]#`ab`#
a| emoji:cl[2x] a| [small]#`cl`#

a| emoji:cool[2x] a| [small]#`cool`#
a| emoji:free[2x] a| [small]#`free`#

a| emoji:id[2x] a| [small]#`id`#
a| emoji:new[2x] a| [small]#`new`#

a| emoji:ng[2x] a| [small]#`ng`#
a| emoji:ok[2x] a| [small]#`ok`#

a| emoji:sos[2x] a| [small]#`sos`#
a| emoji:up[2x] a| [small]#`up`#

a| emoji:vs[2x] a| [small]#`vs`#
a| emoji:skull_and_crossbones[2x] a| [small]#`skull_and_crossbones`#

a| emoji:radioactive_sign[2x] a| [small]#`radioactive_sign`#
a| emoji:biohazard_sign[2x] a| [small]#`biohazard_sign`#

a| emoji:orthodox_cross[2x] a| [small]#`orthodox_cross`#
a| emoji:star_and_crescent[2x] a| [small]#`star_and_crescent`#

a| emoji:peace_symbol[2x] a| [small]#`peace_symbol`#
a| emoji:yin_yang[2x] a| [small]#`yin_yang`#

a| emoji:wheel_of_dharma[2x] a| [small]#`wheel_of_dharma`#
a| emoji:aries[2x] a| [small]#`aries`#

a| emoji:taurus[2x] a| [small]#`taurus`#
a| emoji:gemini[2x] a| [small]#`gemini`#

a| emoji:cancer[2x] a| [small]#`cancer`#
a| emoji:leo[2x] a| [small]#`leo`#

a| emoji:virgo[2x] a| [small]#`virgo`#
a| emoji:libra[2x] a| [small]#`libra`#

a| emoji:scorpius[2x] a| [small]#`scorpius`#
a| emoji:sagittarius[2x] a| [small]#`sagittarius`#

a| emoji:capricorn[2x] a| [small]#`capricorn`#
a| emoji:aquarius[2x] a| [small]#`aquarius`#

a| emoji:pisces[2x] a| [small]#`pisces`#
a| emoji:spades[2x] a| [small]#`spades`#

a| emoji:clubs[2x] a| [small]#`clubs`#
a| emoji:hearts[2x] a| [small]#`hearts`#

a| emoji:diamonds[2x] a| [small]#`diamonds`#
a| emoji:hotsprings[2x] a| [small]#`hotsprings`#

a| emoji:recycle[2x] a| [small]#`recycle`#
a| emoji:wheelchair[2x] a| [small]#`wheelchair`#

a| emoji:hammer_and_pick[2x] a| [small]#`hammer_and_pick`#
a| emoji:anchor[2x] a| [small]#`anchor`#

a| emoji:crossed_swords[2x] a| [small]#`crossed_swords`#
a| emoji:scales[2x] a| [small]#`scales`#

a| emoji:alembic[2x] a| [small]#`alembic`#
a| emoji:gear[2x] a| [small]#`gear`#

a| emoji:atom_symbol[2x] a| [small]#`atom_symbol`#
a| emoji:fleur_de_lis[2x] a| [small]#`fleur_de_lis`#

a| emoji:warning[2x] a| [small]#`warning`#
a| emoji:zap[2x] a| [small]#`zap`#

a| emoji:white_circle[2x] a| [small]#`white_circle`#
a| emoji:black_circle[2x] a| [small]#`black_circle`#

|===

=== Flags

[cols="10,15,10,15,10,15,10,15", header=true]
|===

a| Emoji a| Code a| Emoji a| Code a| Emoji a| Code a| Emoji a| Code

a|emoji:a[2x] a| [small]#`a`#
6+a|

a| emoji:flag-ac[2x] a| [small]#`flag-ac`#
a| emoji:flag-ad[2x] a| [small]#`flag-ad`#
a| emoji:flag-ae[2x] a| [small]#`flag-ae`#
a| emoji:flag-af[2x] a| [small]#`flag-af`#

a| emoji:flag-ag[2x] a| [small]#`flag-ag`#
a| emoji:flag-ai[2x] a| [small]#`flag-ai`#
a| emoji:flag-al[2x] a| [small]#`flag-al`#
a| emoji:flag-am[2x] a| [small]#`flag-am`#

a| emoji:flag-ao[2x] a| [small]#`flag-ao`#
a| emoji:flag-aq[2x] a| [small]#`flag-aq`#
a| emoji:flag-ar[2x] a| [small]#`flag-ar`#
a| emoji:flag-as[2x] a| [small]#`flag-as`#

a| emoji:flag-at[2x] a| [small]#`flag-at`#
a| emoji:flag-au[2x] a| [small]#`flag-au`#
a| emoji:flag-aw[2x] a| [small]#`flag-aw`#
a| emoji:flag-ax[2x] a| [small]#`flag-ax`#

a| emoji:flag-az[2x] a| [small]#`flag-az`#
6+a|

a| emoji:b[2x] a| [small]#`b`#
6+a|

a| emoji:flag-ba[2x] a| [small]#`flag-ba`#
a| emoji:flag-bb[2x] a| [small]#`flag-bb`#
a| emoji:flag-bd[2x] a| [small]#`flag-bd`#
a| emoji:flag-be[2x] a| [small]#`flag-be`#

a| emoji:flag-bf[2x] a| [small]#`flag-bf`#
a| emoji:flag-bg[2x] a| [small]#`flag-bg`#
a| emoji:flag-bh[2x] a| [small]#`flag-bh`#
a| emoji:flag-bi[2x] a| [small]#`flag-bi`#

a| emoji:flag-bj[2x] a| [small]#`flag-bj`#
a| emoji:flag-bl[2x] a| [small]#`flag-bl`#
a| emoji:flag-bm[2x] a| [small]#`flag-bm`#
a| emoji:flag-bn[2x] a| [small]#`flag-bn`#

a| emoji:flag-bo[2x] a| [small]#`flag-bo`#
a| emoji:flag-bq[2x] a| [small]#`flag-bq`#
a| emoji:flag-br[2x] a| [small]#`flag-br`#
a| emoji:flag-bs[2x] a| [small]#`flag-bs`#

a| emoji:flag-bt[2x] a| [small]#`flag-bt`#
a| emoji:flag-bv[2x] a| [small]#`flag-bv`#
a| emoji:flag-bw[2x] a| [small]#`flag-bw`#
a| emoji:flag-by[2x] a| [small]#`flag-by`#

a| emoji:flag-bz[2x] a| [small]#`flag-bz`#
6+a|

a| emoji:c[2x] a| [small]#`c`#
6+a|

a| emoji:flag-ca[2x] a| [small]#`flag-ca`#
a| emoji:flag-cc[2x] a| [small]#`flag-cc`#
a| emoji:flag-cd[2x] a| [small]#`flag-cd`#
a| emoji:flag-cf[2x] a| [small]#`flag-cf`#

a| emoji:flag-cg[2x] a| [small]#`flag-cg`#
a| emoji:flag-ch[2x] a| [small]#`flag-ch`#
a| emoji:flag-ci[2x] a| [small]#`flag-ci`#
a| emoji:flag-ck[2x] a| [small]#`flag-ck`#

a| emoji:flag-cl[2x] a| [small]#`flag-cl`#
a| emoji:flag-cm[2x] a| [small]#`flag-cm`#
a| emoji:flag-cn[2x] a| [small]#`flag-cn`#
a| emoji:flag-co[2x] a| [small]#`flag-co`#

a| emoji:flag-cp[2x] a| [small]#`flag-cp`#
a| emoji:flag-cr[2x] a| [small]#`flag-cr`#
a| emoji:flag-cu[2x] a| [small]#`flag-cu`#
a| emoji:flag-cv[2x] a| [small]#`flag-cv`#

a| emoji:flag-cw[2x] a| [small]#`flag-cw`#
a| emoji:flag-cx[2x] a| [small]#`flag-cx`#
a| emoji:flag-cy[2x] a| [small]#`flag-cy`#
a| emoji:flag-cz[2x] a| [small]#`flag-cz`#

a| emoji:d[2x] a| [small]#`d`#
6+a|

a| emoji:flag-de[2x] a| [small]#`flag-de`#
a| emoji:flag-dg[2x] a| [small]#`flag-dg`#
a| emoji:flag-dj[2x] a| [small]#`flag-dj`#
a| emoji:flag-dk[2x] a| [small]#`flag-dk`#

a| emoji:flag-dm[2x] a| [small]#`flag-dm`#
a| emoji:flag-do[2x] a| [small]#`flag-do`#
a| emoji:flag-dz[2x] a| [small]#`flag-dz`#
2+a|

a| emoji:e[2x] a| [small]#`e`#
6+a|

a| emoji:flag-ea[2x] a| [small]#`flag-ea`#
a| emoji:flag-ec[2x] a| [small]#`flag-ec`#
a| emoji:flag-ee[2x] a| [small]#`flag-ee`#
a| emoji:flag-eg[2x] a| [small]#`flag-eg`#

a| emoji:flag-eh[2x] a| [small]#`flag-eh`#
a| emoji:flag-er[2x] a| [small]#`flag-er`#
a| emoji:flag-es[2x] a| [small]#`flag-es`#
a| emoji:flag-et[2x] a| [small]#`flag-et`#

a| emoji:flag-eu[2x] a| [small]#`flag-eu`#
6+a|

a| emoji:f[2x] a| [small]#`f`#
6+a|

a| emoji:flag-fi[2x] a| [small]#`flag-fi`#
a| emoji:flag-fj[2x] a| [small]#`flag-fj`#
a| emoji:flag-fk[2x] a| [small]#`flag-fk`#
a| emoji:flag-fm[2x] a| [small]#`flag-fm`#

a| emoji:flag-fo[2x] a| [small]#`flag-fo`#
a| emoji:flag-fr[2x] a| [small]#`flag-fr`#
4+a|

a| emoji:g[2x] a| [small]#`g`#
6+a|

a| emoji:flag-ga[2x] a| [small]#`flag-ga`#
a| emoji:flag-gb[2x] a| [small]#`flag-gb`#
a| emoji:flag-gd[2x] a| [small]#`flag-gd`#
a| emoji:flag-ge[2x] a| [small]#`flag-ge`#

a| emoji:flag-gf[2x] a| [small]#`flag-gf`#
a| emoji:flag-gg[2x] a| [small]#`flag-gg`#
a| emoji:flag-gh[2x] a| [small]#`flag-gh`#
a| emoji:flag-gi[2x] a| [small]#`flag-gi`#

a| emoji:flag-gl[2x] a| [small]#`flag-gl`#
a| emoji:flag-gm[2x] a| [small]#`flag-gm`#
a| emoji:flag-gn[2x] a| [small]#`flag-gn`#
a| emoji:flag-gp[2x] a| [small]#`flag-gp`#

a| emoji:flag-gq[2x] a| [small]#`flag-gq`#
a| emoji:flag-gr[2x] a| [small]#`flag-gr`#
a| emoji:flag-gs[2x] a| [small]#`flag-gs`#
a| emoji:flag-gt[2x] a| [small]#`flag-gt`#

a| emoji:flag-gu[2x] a| [small]#`flag-gu`#
a| emoji:flag-gw[2x] a| [small]#`flag-gw`#
a| emoji:flag-gy[2x] a| [small]#`flag-gy`#
2+a|

a| emoji:h[2x] a| [small]#`h`#
6+a|

a| emoji:flag-hk[2x] a| [small]#`flag-hk`#
a| emoji:flag-hm[2x] a| [small]#`flag-hm`#
a| emoji:flag-hn[2x] a| [small]#`flag-hn`#
a| emoji:flag-hr[2x] a| [small]#`flag-hr`#

a| emoji:flag-ht[2x] a| [small]#`flag-ht`#
a| emoji:flag-hu[2x] a| [small]#`flag-hu`#
4+a|

a| emoji:i[2x] a| [small]#`i`#
6+a|

a| emoji:flag-ic[2x] a| [small]#`flag-ic`#
a| emoji:flag-id[2x] a| [small]#`flag-id`#
a| emoji:flag-ie[2x] a| [small]#`flag-ie`#
a| emoji:flag-il[2x] a| [small]#`flag-il`#

a| emoji:flag-im[2x] a| [small]#`flag-im`#
a| emoji:flag-in[2x] a| [small]#`flag-in`#
a| emoji:flag-io[2x] a| [small]#`flag-io`#
a| emoji:flag-iq[2x] a| [small]#`flag-iq`#

a| emoji:flag-ir[2x] a| [small]#`flag-ir`#
a| emoji:flag-is[2x] a| [small]#`flag-is`#
a| emoji:flag-it[2x] a| [small]#`flag-it`#
2+a|

a| emoji:j[2x] a| [small]#`j`#
6+a|

a| emoji:flag-je[2x] a| [small]#`flag-je`#
a| emoji:flag-jm[2x] a| [small]#`flag-jm`#
a| emoji:flag-jo[2x] a| [small]#`flag-jo`#
a| emoji:flag-jp[2x] a| [small]#`flag-jp`#

a| emoji:k[2x] a| [small]#`k`#
6+a|

a| emoji:flag-ke[2x] a| [small]#`flag-ke`#
a| emoji:flag-kg[2x] a| [small]#`flag-kg`#
a| emoji:flag-kh[2x] a| [small]#`flag-kh`#
a| emoji:flag-ki[2x] a| [small]#`flag-ki`#

a| emoji:flag-km[2x] a| [small]#`flag-km`#
a| emoji:flag-kn[2x] a| [small]#`flag-kn`#
a| emoji:flag-kp[2x] a| [small]#`flag-kp`#
a| emoji:flag-kr[2x] a| [small]#`flag-kr`#

a| emoji:flag-kw[2x] a| [small]#`flag-kw`#
a| emoji:flag-ky[2x] a| [small]#`flag-ky`#
a| emoji:flag-kz[2x] a| [small]#`flag-kz`#
2+a|

a| emoji:l[2x] a| [small]#`l`#
6+a|

a| emoji:flag-la[2x] a| [small]#`flag-la`#
a| emoji:flag-lb[2x] a| [small]#`flag-lb`#
a| emoji:flag-lc[2x] a| [small]#`flag-lc`#
a| emoji:flag-li[2x] a| [small]#`flag-li`#

a| emoji:flag-lk[2x] a| [small]#`flag-lk`#
a| emoji:flag-lr[2x] a| [small]#`flag-lr`#
a| emoji:flag-ls[2x] a| [small]#`flag-ls`#
a| emoji:flag-lt[2x] a| [small]#`flag-lt`#

a| emoji:flag-lu[2x] a| [small]#`flag-lu`#
a| emoji:flag-lv[2x] a| [small]#`flag-lv`#
a| emoji:flag-ly[2x] a| [small]#`flag-ly`#
2+a|

a| emoji:m[2x] a| [small]#`m`#
6+a|

a| emoji:flag-ma[2x] a| [small]#`flag-ma`#
a| emoji:flag-mc[2x] a| [small]#`flag-mc`#
a| emoji:flag-md[2x] a| [small]#`flag-md`#
a| emoji:flag-me[2x] a| [small]#`flag-me`#

a| emoji:flag-mf[2x] a| [small]#`flag-mf`#
a| emoji:flag-mg[2x] a| [small]#`flag-mg`#
a| emoji:flag-mh[2x] a| [small]#`flag-mh`#
a| emoji:flag-mk[2x] a| [small]#`flag-mk`#

a| emoji:flag-ml[2x] a| [small]#`flag-ml`#
a| emoji:flag-mm[2x] a| [small]#`flag-mm`#
a| emoji:flag-mn[2x] a| [small]#`flag-mn`#
a| emoji:flag-mo[2x] a| [small]#`flag-mo`#

a| emoji:flag-mp[2x] a| [small]#`flag-mp`#
a| emoji:flag-mq[2x] a| [small]#`flag-mq`#
a| emoji:flag-mr[2x] a| [small]#`flag-mr`#
a| emoji:flag-ms[2x] a| [small]#`flag-ms`#

a| emoji:flag-mt[2x] a| [small]#`flag-mt`#
a| emoji:flag-mu[2x] a| [small]#`flag-mu`#
a| emoji:flag-mv[2x] a| [small]#`flag-mv`#
a| emoji:flag-mw[2x] a| [small]#`flag-mw`#

a| emoji:flag-mx[2x] a| [small]#`flag-mx`#
a| emoji:flag-my[2x] a| [small]#`flag-my`#
a| emoji:flag-mz[2x] a| [small]#`flag-mz`#
2+a|

a| emoji:n[2x] a| [small]#`n`#
6+a|

a| emoji:flag-na[2x] a| [small]#`flag-na`#
a| emoji:flag-nc[2x] a| [small]#`flag-nc`#
a| emoji:flag-ne[2x] a| [small]#`flag-ne`#
a| emoji:flag-nf[2x] a| [small]#`flag-nf`#

a| emoji:flag-ng[2x] a| [small]#`flag-ng`#
a| emoji:flag-ni[2x] a| [small]#`flag-ni`#
a| emoji:flag-nl[2x] a| [small]#`flag-nl`#
a| emoji:flag-no[2x] a| [small]#`flag-no`#

a| emoji:flag-np[2x] a| [small]#`flag-np`#
a| emoji:flag-nr[2x] a| [small]#`flag-nr`#
a| emoji:flag-nu[2x] a| [small]#`flag-nu`#
a| emoji:flag-nz[2x] a| [small]#`flag-nz`#

a| emoji:o[2x] a| [small]#`o`#
6+a|

a| emoji:flag-om[2x] a| [small]#`flag-om`#
6+a|

a| emoji:p[2x] a| [small]#`p`#
6+a|

a| emoji:flag-pa[2x] a| [small]#`flag-pa`#
a| emoji:flag-pe[2x] a| [small]#`flag-pe`#
a| emoji:flag-pf[2x] a| [small]#`flag-pf`#
a| emoji:flag-pg[2x] a| [small]#`flag-pg`#

a| emoji:flag-ph[2x] a| [small]#`flag-ph`#
a| emoji:flag-pk[2x] a| [small]#`flag-pk`#
a| emoji:flag-pl[2x] a| [small]#`flag-pl`#
a| emoji:flag-pm[2x] a| [small]#`flag-pm`#

a| emoji:flag-pn[2x] a| [small]#`flag-pn`#
a| emoji:flag-pr[2x] a| [small]#`flag-pr`#
a| emoji:flag-ps[2x] a| [small]#`flag-ps`#
a| emoji:flag-pt[2x] a| [small]#`flag-pt`#

a| emoji:flag-pw[2x] a| [small]#`flag-pw`#
a| emoji:flag-py[2x] a| [small]#`flag-py`#
4+a|

a| emoji:q[2x] a| [small]#`q`#
6+a|

a| emoji:flag-qa[2x] a| [small]#`flag-qa`#
6+a|

a| emoji:r[2x] a| [small]#`r`#
6+a|

a| emoji:flag-re[2x] a| [small]#`flag-re`#
a| emoji:flag-ro[2x] a| [small]#`flag-ro`#
a| emoji:flag-rs[2x] a| [small]#`flag-rs`#
a| emoji:flag-ru[2x] a| [small]#`flag-ru`#

a| emoji:flag-rw[2x] a| [small]#`flag-rw`#
6+a|

a| emoji:s[2x] a| [small]#`s`#
6+a|

a| emoji:flag-sa[2x] a| [small]#`flag-sa`#
a| emoji:flag-sb[2x] a| [small]#`flag-sb`#
a| emoji:flag-sc[2x] a| [small]#`flag-sc`#
a| emoji:flag-sd[2x] a| [small]#`flag-sd`#

a| emoji:flag-se[2x] a| [small]#`flag-se`#
a| emoji:flag-sg[2x] a| [small]#`flag-sg`#
a| emoji:flag-sh[2x] a| [small]#`flag-sh`#
a| emoji:flag-si[2x] a| [small]#`flag-si`#

a| emoji:flag-sj[2x] a| [small]#`flag-sj`#
a| emoji:flag-sk[2x] a| [small]#`flag-sk`#
a| emoji:flag-sl[2x] a| [small]#`flag-sl`#
a| emoji:flag-sm[2x] a| [small]#`flag-sm`#

a| emoji:flag-sn[2x] a| [small]#`flag-sn`#
a| emoji:flag-so[2x] a| [small]#`flag-so`#
a| emoji:flag-sr[2x] a| [small]#`flag-sr`#
a| emoji:flag-ss[2x] a| [small]#`flag-ss`#

a| emoji:flag-st[2x] a| [small]#`flag-st`#
a| emoji:flag-sv[2x] a| [small]#`flag-sv`#
a| emoji:flag-sx[2x] a| [small]#`flag-sx`#
a| emoji:flag-sy[2x] a| [small]#`flag-sy`#

a| emoji:flag-sz[2x] a| [small]#`flag-sz`#
6+a|

a| emoji:t[2x] a| [small]#`t`#
6+a|

a| emoji:flag-ta[2x] a| [small]#`flag-ta`#
a| emoji:flag-tc[2x] a| [small]#`flag-tc`#
a| emoji:flag-td[2x] a| [small]#`flag-td`#
a| emoji:flag-tf[2x] a| [small]#`flag-tf`#

a| emoji:flag-tg[2x] a| [small]#`flag-tg`#
a| emoji:flag-th[2x] a| [small]#`flag-th`#
a| emoji:flag-tj[2x] a| [small]#`flag-tj`#
a| emoji:flag-tk[2x] a| [small]#`flag-tk`#

a| emoji:flag-tl[2x] a| [small]#`flag-tl`#
a| emoji:flag-tm[2x] a| [small]#`flag-tm`#
a| emoji:flag-tn[2x] a| [small]#`flag-tn`#
a| emoji:flag-to[2x] a| [small]#`flag-to`#

a| emoji:flag-tr[2x] a| [small]#`flag-tr`#
a| emoji:flag-tt[2x] a| [small]#`flag-tt`#
a| emoji:flag-tv[2x] a| [small]#`flag-tv`#
a| emoji:flag-tw[2x] a| [small]#`flag-tw`#

a| emoji:flag-tz[2x] a| [small]#`flag-tz`#
6+a|

a| emoji:u[2x] a| [small]#`u`#
6+a|

a| emoji:flag-ua[2x] a| [small]#`flag-ua`#
a| emoji:flag-ug[2x] a| [small]#`flag-ug`#
a| emoji:flag-um[2x] a| [small]#`flag-um`#
a| emoji:flag-us[2x] a| [small]#`flag-us`#

a| emoji:flag-uy[2x] a| [small]#`flag-uy`#
a| emoji:flag-uz[2x] a| [small]#`flag-uz`#
4+a|

a| emoji:v[2x] a| [small]#`v`#
6+a|

a| emoji:flag-va[2x] a| [small]#`flag-va`#
a| emoji:flag-vc[2x] a| [small]#`flag-vc`#
a| emoji:flag-ve[2x] a| [small]#`flag-ve`#
a| emoji:flag-vg[2x] a| [small]#`flag-vg`#

a| emoji:flag-vi[2x] a| [small]#`flag-vi`#
a| emoji:flag-vn[2x] a| [small]#`flag-vn`#
a| emoji:flag-vu[2x] a| [small]#`flag-vu`#
2+a|

a| emoji:w[2x] a| [small]#`w`#
6+a|

a| emoji:flag-wf[2x] a| [small]#`flag-wf`#
a| emoji:flag-ws[2x] a| [small]#`flag-ws`#
4+a|

a| emoji:x[2x] a| [small]#`x`#
6+a|

a| emoji:flag-xk[2x] a| [small]#`flag-xk`#
6+a|

a| emoji:y[2x] a| [small]#`y`#
6+a|

a| emoji:flag-ye[2x] a| [small]#`flag-ye`#
a| emoji:flag-yt[2x] a| [small]#`flag-yt`#
4+a|

a| emoji:z[2x] a| [small]#`z`#
6+a|

a| emoji:flag-za[2x] a| [small]#`flag-za`#
a| emoji:flag-zm[2x] a| [small]#`flag-zm`#
a| emoji:flag-zw[2x] a| [small]#`flag-zw`#
2+a|

|===

== Credits

Emoji support by link:https://github.com/twitter/twemoji[twemoji].

Emoji graphics licensed under CC-BY 4.0: https://creativecommons.org/licenses/by/4.0/
