= Making the Camera Follow a 3rd-Person Character
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../
:imagesdir: ../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


When players steer a game character with 1st-person view, they directly steer the camera (`flyCam.setEnabled(true);`), and they never see the walking character itself. In a game with 3rd-person view, however, the players see the character walk, and you (the game developer) want to make the camera follow the character around when it walks.

There are two ways how the camera can do that:

*  Registering a chase camera to the player and the input manager.
*  Attaching the camera to the character using a camera node.

*Important:* Using third-person view requires you to deactivate the default flyCam (first-person view). This means that you have to configure your own navigation (<<jme3/advanced/input_handling#,key inputs and analogListener>>) that make your player character walk. For moving a physical player character, use `player.setWalkDirection()`, for a non-physical character you can use `player.move()`.


== Code Samples

Press the WASD or arrow keys to move. Drag with the left mouse button to rotate.

*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-examples/src/main/java/jme3test/input/TestChaseCamera.java[TestChaseCamera.java]
*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-examples/src/main/java/jme3test/input/TestCameraNode.java[TestCameraNode.java]


== Camera Node

To make the camera follow a target node, add this camera node code to your init method (e.g. `simpleInitApp()`). The `target` spatial is typically the player node.

[source,java]
----

// Disable the default flyby cam
flyCam.setEnabled(false);
//create the camera Node
camNode = new CameraNode("Camera Node", cam);
//This mode means that camera copies the movements of the target:
camNode.setControlDir(ControlDirection.SpatialToCamera);
//Attach the camNode to the target:
target.attachChild(camNode);
//Move camNode, e.g. behind and above the target:
camNode.setLocalTranslation(new Vector3f(0, 5, -5));
//Rotate the camNode to look at the target:
camNode.lookAt(target.getLocalTranslation(), Vector3f.UNIT_Y);

----

[IMPORTANT]
====
Where the example says `camNode.setLocalTranslation(new Vector3f(0, 5, -5));`, you have to supply your own start position for the camera. This depends on the size of your target (the player character) and its position in your particular scene. Optimally, you set this to a spot a bit behind and above the target.
====

[cols="2", options="header"]
|===

a|Methods
a|Description

a|setControlDir(ControlDirection.SpatialToCamera)
a|User input steers the target spatial, and the camera follows the spatial. +
The spatial's transformation is copied over the camera's transformation. +
Example: Use with <<jme3/advanced/physics#,CharacterControl>>led spatial.

a|setControlDir(ControlDirection.CameraToSpatial)
a|User input steers the camera, and the target spatial follows the camera. +
The camera's transformation is copied over the spatial's transformation. Use with first-person flyCam.

|===

*Code sample:*

*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-examples/src/main/java/jme3test/input/TestCameraNode.java[TestCameraNode.java] – Press the WASD or arrow keys to move. Drag with the left mouse button to rotate.


== Chase Camera

To activate the chase camera, add the following code to your init method (e.g. `simpleInitApp()`). The `target` spatial is typically the player node. You will be able to rotate the target by dragging (keeping the left mouse button pressed and moving the mouse).

[source,java]
----

// Disable the default flyby cam
flyCam.setEnabled(false);
// Enable a chase cam for this target (typically the player).
ChaseCamera chaseCam = new ChaseCamera(cam, target, inputManager);
chaseCam.setSmoothMotion(true);

----
[cols="2", options="header"]
|===

a|Method
a|Description

a|setInvertVerticalAxis(true)
a|Invert the camera's vertical rotation Axis 

a|setInvertHorizontalAxis(true)
a|Invert the camera's horizontal rotation Axis

a|setTrailingEnabled(true)
a|Camera follows the target and flies around and behind when the target moves towards the camera. Trailing only works with smooth motion enabled. (Default)

a|setTrailingEnabled(false)
a|Camera follows the target, but does not rotate around the target when the target changes direction.

a|setSmoothMotion(true)
a|Activate SmoothMotion when trailing. This means the camera seems to accelerate and fly after the character, when it has caught up, it slows down again.

a|setSmoothMotion(false)
a|Disable smooth camera motion. Disabling SmoothMotion also disables trailing.

a|setLookAtOffset(Vector3f.UNIT_Y.mult(3))
a|Camera looks at a point 3 world units above the target.

a|setToggleRotationTrigger(new MouseButtonTrigger(MouseInput.BUTTON_MIDDLE))
a|Enable rotation by keeping the middle mouse button pressed (like in Blender). This disables the rotation on right and left mouse button click.

a|setToggleRotationTrigger(new MouseButtonTrigger( +
MouseInput.BUTTON_MIDDLE), +
new KeyTrigger(KeyInput.KEY_SPACE))
a|Activate mutiple triggers for the rotation of the camera, e.g. spacebar and middle mouse button, etc.

a|setRotationSensitivity(5f)
a|How fast the camera rotates. Use values around &lt;1.0f (all bigger values are ignored).

|===

*Code sample:*

*  link:https://github.com/jMonkeyEngine/jmonkeyengine/blob/master/jme3-examples/src/main/java/jme3test/input/TestChaseCamera.java[TestChaseCamera.java] – Press the WASD or arrow keys to move. Drag with the left mouse button to rotate.


== Which to Choose?

What is the difference of the two code samples above?
[cols="2", options="header"]
|===

a|CameraNode
a|ChaseCam

a|Camera follows immediately, flies at same speed as target.
a|Camera moves smoothly and accelerates and decelerates, flies more slowly than the target and catches up.

a|Camera stays attached to the target at a constant distance.
a|Camera orbits the target and approaches slowly.

a|Drag-to-Rotate rotates the target and the camera. You always see the target from behind.
a|Drag-to-Rotate rotates only the camera. You can see the target from various sides.

|===
