= Settings
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../
:imagesdir: ../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]


This framework is intended to run every kind of block world the user wants - This includes different chunk sizes, block sizes, materials and a lot more.

Those attributes are handled by an instance of the class *CubesSettings*. You will have to specify such an object when creating your block world:

[source,java]
----
//You have to specify a valid application, the framework will use e.g. its assetManager
CubesSettings settings = new CubesSettings(application);
----

Now, you can set all needed options via `get`/`set`-methods:
[cols="20,15,65", options="header"]
|===

a| Setting 
a| Default Value 
<a| Usage  

a| `Block Size` 
a| 3 
a| The side length of a block in world units. 

a| `Chunk Size X/Y/Z` 
a| 16/256/15 
a| The amount of blocks, that are contained in one chunk in the given direction. 

a| `Block Material` 
a| null 
a| The material that will be used by the chunks' geometries. You can load also load a default blockworld-fitting material by calling `setDefaultBlockMaterial(String textureFilePath)`. 

a| `Textures Count X/Y` 
a| 16 
a| The amount of textures in your image file, on the given axis. 

|===


[TIP]
====
You can generate valid test settings by calling `CubesTestAssets.getSettings(application)`.
====



[WARNING]
====
At the moment, changes to the settings won't affect the block world at "`runtime`", i.e. *after* it's created.
====

