= cc
:author: 
:revnumber: 
:revdate: 2016/03/17 20:48
:relfileprefix: ../../../
:imagesdir: ../../..
ifdef::env-github,env-browser[:outfilesuffix: .adoc]



== Character customization

This is an interesting topic in game development and industry


[WARNING]
====
This is a very loooong story… 
====

[quote]
____
 I started my game develop career with some basic DirectX examples and pirated 3DSMax 13 years ago, when I was 13. :p Yes, I'm just 26 in 2013. Then I went to 3D Game Studio version A5 to do some fancy drag and drop stuff… From that point I've already got the idea of doing a character customization system in my mind. 
____
[quote]
____
[quote]
____
So, that's why this story will be quite loong, even f$#4king much more than I imagine. Bear with me
____

____


=== Ideas

The initial idea of Character customization is: We (human) are soooo *similiar*!! 

The second idea: *resuable* and *composable*!

.  Cloths, skins, 3dmodels, animation.. are components of a whole, which made up character
.  The same ideas with component oriented architecture

So to reduce a very big workload of data and assets need for a game with vast data of character (football players, etc…) More over we can support and encourage gamer to “build their own character! This is how we handle the situations, similiar scenario can happen in a MMOs.


[TIP]
====
Read full solution in Atom framework CC page <<jme3/advanced/atom_framework/cc#,cc>>
====



=== References


=== Video Preview


=== Articles & Papers

Forum:


=== My JME Character customization approach
